### ISSUE TITLE
Escape placeholder syntax to show parentheses in an example

### ISSUE THREAD

**Issue by MrNossiom** [tldr-pages/tldr#10040]
Hi 👋🏻,

I would like to be able to escape the placeholder syntax, in this case we want to be able to show these parentheses to the end user.
https://github.com/tldr-pages/tldr/blob/fb7c5c3eaea335dbc681a72b6177c4c92188f676/pages/linux/playerctl.md?plain=1#L32

I found a case where someone tried...
https://github.com/tldr-pages/tldr/blob/16d7f93aeaecce3be3ec5e11136278ca3ab640ad/pages/common/fakedata.md?plain=1#L24
...but it does not work
![image](https://user-images.githubusercontent.com/43814157/230793438-35d6e9c1-5027-4660-b29f-6a49f2dbe1c8.png)

Is there a way to escape this syntax ? I can submit 2 PRs to fix these examples

**Comment by SethFalco** [comment]
Closing this in favor of https://github.com/tldr-pages/tldr/issues/10125
