### ISSUE TITLE
MAINTAINERS: add @kbdharun as org owner

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#10057]
Hi, @kbdharun! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by kbdharun** [comment]
Sure, I would love to contribute and maintain more in future, so I am up for it. Thanks for the issue.

**Comment by blueskyson** [comment]
We need an active owner to add us to owners. c.c. @CleanMachine1 @navarroaxel @marchersimon @sbrl

**Comment by CleanMachine1** [comment]
Just a quick note, "members of the tldr-pages organization who remain active __for at least 6 months__" Hasn't reached that milestone yet.

**Comment by pixelcmtd** [comment]
[If my math's right](https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md#organization-members), you, @kbdharun, have now spent 6 months as a very active organization member. So, would you still like to become an owner?

**Comment by kbdharun** [comment]
Sure
