### ISSUE TITLE
MAINTAINERS: add @blueskyson as org owner

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#10054]
Hi, @blueskyson! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by blueskyson** [comment]
Yes, it's really cool!

**Comment by CleanMachine1** [comment]
Just a quick note, "members of the tldr-pages organization who remain active __for at least 6 months__". It hasn't reached that milestone yet.

**Comment by kbdharun** [comment]
> Just a quick note, "members of the tldr-pages organization who remain active **for at least 6 months**". It hasn't reached that milestone yet.

WDYM, @blueskyson seem to be very active for more than 6 months.

![image](https://user-images.githubusercontent.com/26346867/231470131-1b756937-0c3d-42c1-b2dc-0e75299cecb8.png)
![image](https://user-images.githubusercontent.com/26346867/231470237-5384b0b9-c42f-4fce-925e-61b600eaa30b.png)
![image](https://user-images.githubusercontent.com/26346867/231470288-b5fc8121-395a-41a1-be01-ef826b636dde.png)

You can checkout his GitHub profile for yourself.

**Comment by kbdharun** [comment]
Does it to be 6 months after they have been added to Organization?

**Comment by kbdharun** [comment]
So we have this issue open for a while IG till the time.

**Comment by CleanMachine1** [comment]
Sure

**Comment by blueskyson** [comment]
We can reopen this a few months later.

**Comment by kbdharun** [comment]
@blueskyson Updated your role to Owner, please open a PR to update the same in MAINTAINERS.md
