### ISSUE TITLE
MAINTAINERS: add @pixelcmtd as org owner

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#10056]
Hi, @pixelcmtd! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by pixelcmtd** [comment]
I'm [beyond](https://twitter.com/pixelcmtd/status/1649542552066850816) honored and hope I will be able to live up to that role.

**Comment by kbdharun** [comment]
> I'm [beyond](https://twitter.com/pixelcmtd/status/1649542552066850816) honored and hope I will be able to live up to that role.

cc @CleanMachine1

**Comment by CleanMachine1** [comment]
Done, if you could make a PR @pixelcmtd amending your self to MAINTAINERS.md
