### ISSUE TITLE
MAINTAINERS: add @SethFalco as org owner

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#10052]
Hi, @SethFalco ! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by SethFalco** [comment]
Hey hey!

Unfortunately, I'm going actually going to decline this! It's very unlikely I'll be taking actions that will utilize the permissions offered by becoming an owner. By accepting this, I would just increase any damage that can be done in the scenario my account in compromised.

If in future we find the project is dangerously low on active owners, or if I find myself doing anything that warrants having those permissions, I'd be happy to raise the topic with existing organization owners at the time to discuss this!

Thanks for considering me, though. :+1:  
I'll continue to do what I can as an org member.
