### ISSUE TITLE
Curly braces not properly escaped on pages (e.g. docker, playerctl, fakedata)

### ISSUE THREAD

**Issue by mrnossiom** [tldr-pages/tldr#10125]
# 👋🏻 Hi

## Problem
On some pages, we actually need to show parenthesis `{{ ... }}` like the ones of `docker inspect` and `playerctl` for templating.

Docker example
![image](https://user-images.githubusercontent.com/43814157/235321780-d7981733-f4d5-4977-b604-3eadb330437e.png)
where it should be in fact
https://github.com/tldr-pages/tldr/blob/e9995a8249a19c3bfb2e20a0f91c52b177578cc4/pages/common/docker-inspect.md?plain=1#L16

## Research
I tried to find a way to escape these, but after some research, I only found someone that tried to escape for `fakedata`
https://github.com/tldr-pages/tldr/blob/e9995a8249a19c3bfb2e20a0f91c52b177578cc4/pages/common/fakedata.md?plain=1#L24
but it does not actually work
![image](https://user-images.githubusercontent.com/43814157/235321756-0f3457b1-56f4-4752-aee6-e7fa8f40a504.png)

I asked on the Matrix chat, but one told me to open an issue here...

## Solution
I'll create a PR as soon as I know how to escape the parentheses to fix most of the pages. I think I can find more example of this issue.

PS: I use `tldr` every day, and it is a great piece of information. Thanks

**Comment by MrNossiom** [comment]
Wait, I actually forgot I already opened an issue for this : #10040

**Comment by principis** [comment]
I think backslash for escaping would be easy to implement in clients.

**Comment by mrnossiom** [comment]
@kbdharun Does that mean that the cases mentioned here were fixed in the process ?

**Comment by kbdharun** [comment]
> @kbdharun Does that mean that the cases mentioned here were fixed in the process ?

Yes, Once a new client specification release is made. Clients will be able to update their code and fix escaping (by referring to the examples, in client spec).

**Comment by mrnossiom** [comment]
Yeah, I know, but does the docker tldr page has been fixed ?
I don't remember which other one, but I know there was another case that didn't match the spec as it is now.

**Comment by kbdharun** [comment]
> Yeah, I know, but does the docker tldr page has been fixed ? I don't remember which other one, but I know there was another case that didn't match the spec as it is now.

The docker tldr page indeed hasn't been fixed yet (I will open a PR to update it now), I believe the other case would be `playerctl` which we updated recently at #11616. Feel free to let us know if any other page needs to be fixed. Btw, [`tlrc`](https://github.com/tldr-pages/tlrc) has implemented the change in the recent release and it is live to use.

An escaped page now will look something like this:

![image](https://github.com/tldr-pages/tldr/assets/26346867/79e661d7-1916-4df8-bbf6-1277709a1f96)

**Comment by mrnossiom** [comment]
Great news! Thanks

I didn't encounter any other glitched page during my investigation.
