### ISSUE TITLE
add install command

### ISSUE THREAD

**Issue by jasonkarns** [tldr-pages/tldr#1015]
http://linux.die.net/man/1/install

**Comment by waldyrious** [comment]
Can you add a link/reference?

**Comment by jasonkarns** [comment]
@waldyrious added link to linux man pages. Is there a specific man pages site you'd prefer?

**Comment by waldyrious** [comment]
No, that's fine :) I just asked because the name is a little generic and could be ambiguous. This way anyone, even if they are not familiar with `install`, can grab this issue, read about the command and submit a PR (even you! 😉)

**Comment by assemusr** [comment]
Working on this..
