### ISSUE TITLE
page request: zotero

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#10189]
### Command description

[Zotero](https://www.zotero.org/) is a bibliography manager. Even though it is a GUI application, it has several command-line options (eg for starting it in headless mode, for changing its behaviour etc.)

As I'm no expert on these options, I'd welcome if a knowledgable person could add a tldr page for Zotero.

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by dch82** [comment]
#10367

All good! :)
