### ISSUE TITLE
Add convention to indicate origin of option names to Contributing.md

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1018]
Generally, if the short option letter corresponds to a given word, that word must be present in the command description (even if within parenthesis as a synonym to a more common word); otherwise, if it corresponds to a letter within a word, that letter should be highlighted (see for example chmod and pwgen).

If the letter was arbitrarily chosen and doesn't correspond to a word or a letter within a word, the description should strive to include a word that _could_ be applied to the option and starts with that letter.

**Comment by ostera** [comment]
chmod page: https://tldr.ostera.io/chmod
pwgen: https://tldr.ostera.io/linux/pwgen

Note that the emphasis on both these pages is inconsistent (one is using `t(e)xt` and the other is using `t[e]xt`).

**Comment by waldyrious** [comment]
@ericbn has changed chmod to use brackets in #1024 ([congrats btw!](http://www.xkcd.com/1000/)), so I suppose we can standardize in them rather than parenthesis.

He also pointed out that the `grep` page also uses this system.

**Comment by marchersimon** [comment]
Can we close this?
