### ISSUE TITLE
tree: add "prune" functionality to linux version

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1022]
GNU's version of `tree` does not implement the `--prune` option (#990). An alternative for the use case of searching a hierarchy of directories to locate files using a pattern could be something like this: `tree -ifF -P tree.md | grep -E -v '/$|^\.$'``

Of course, since that gives out the exact same result as `find . -name tree.md`, the usefulness of this is quite questionable; still, it would provide parity between the BSD and GNU versions of tree.md.

**Comment by waldyrious** [comment]
@spageektti can you please explain why this was closed?

**Comment by kbdharun** [comment]
> can you please explain why this was closed?

Adding to this @spageektti, it is generally better to provide context on the reason why it's being closed when closing an issue.

---

Related to the initial issue, I can't find a GNU-specific reference manual (nor a POSIX page) for `tree` but in the distros I checked now the `--prune` flag is present as an option with `tree`.

**Comment by spageektti** [comment]
> @spageektti can you please explain why this was closed?

Sorry, I was browsing through old issues and accidentally clicked the close button.

**Comment by waldyrious** [comment]
No worries :) I'll reopen, then.

**Comment by spageektti** [comment]
Now we have only two pages for `tree`: one in `common` and one in `windows`. On the common page, the penultimate example uses the `--prune` option, which seems to work for me on Fedora 40. Could you let me know if this satisfies you or if you mean something else?

**Comment by waldyrious** [comment]
Thanks for the ping, @sebastiaanspeck. Indeed I can attest that the version of `tree` I have installed in my Linux machine (Ubuntu 24.04) does support the `--prune` option. The version is this:

```
tree --version
tree v2.1.1 © 1996 - 2023 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro
```

Unfortunately I didn't record what version I was testing against when I opened this issue and submitted #990. I'll assume the option was added in the meantime.

Therefore, I suppose we could do as @agnivade suggests, and keep only the `common` version of the `tree` page.

**Comment by waldyrious** [comment]
> Therefore, I suppose we could do as @agnivade suggests, and keep only the common version of the tree page.

Actually, that is already the case: the page got the `--prune` option added as part of #4332 (in particular, see the [discussion thread](https://github.com/tldr-pages/tldr/pull/4332#discussion_r488819297) about the option differences), and it was later moved to common as part of #6551.

So there's nothing to do here, and I'll close the issue. That said, I'm glad the three PRs are now connected with links, to allow tracing the history of the page for future reference.
