### ISSUE TITLE
du: add pattern matching example

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1032]
Get the total size of .jpg files at any depth within the current directory: `du -ch -- **/*.jpg | grep total$` ([source](http://unix.stackexchange.com/a/41635/30336)).

This [requires bash 4.0](http://unix.stackexchange.com/questions/34024/what-is-the-tool-that-allows-me-to-specify-arbitrary-directories-using#comment46158_34026), so I can't test it at the moment in OS X (`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)`) -- if I try this the `**` does the same as `*`, i.e. it only matches a single depth level.

If someone can confirm the multi-level `**` behavior for this example in a shell that supports it, please say so.

**Comment by agnivade** [comment]
Is this the reason why you added #1031 ? :stuck_out_tongue_winking_eye:

**Comment by waldyrious** [comment]
> Is this the reason why you added #1031 ? :stuck_out_tongue_winking_eye: 

For sure! Scratching my own itch as per good FOSS tradition :D

> I have bash 4.3, but I don't see any difference between * and **

I don't think that example should behave differently, since there's only one level of directories below `pages/`. Can you try with a deeper hierarchy?

**Comment by agnivade** [comment]
Works. But you have to do `shopt -s globstar` before it.

**Comment by waldyrious** [comment]
Cool, that's what I assumed. Ok, I'll make the PR then.

**Comment by agnivade** [comment]
Closing this as the PR as been merged.

**Comment by waldyrious** [comment]
@agnivade huh? It has not, as far as I can see... #1034

**Comment by agnivade** [comment]
@waldyrious - dang it. My apologies. I saw this - https://github.com/tldr-pages/tldr/commit/240b219dba8b32bcd0b609226cb9e52859cfa8b9 and thought it was merged. Didn't check the branch. :sweat:

**Comment by waldyrious** [comment]
Heheh no problem :)
