### ISSUE TITLE
page request: `dirbuster`

### ISSUE THREAD

**Issue by 0x69420f** [tldr-pages/tldr#10362]
### Command description

Hello there, Xander here :smile: 
I tried getting a hint on using `dirbuster` using the code below but got nothing :cry: :

```bash
tldr --update dirbuster
```

Fix this, will you? :smile_cat: 

Yours,
:cheese: 

### Command details

dirbuster 1.0-RC1

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by dch82** [comment]
#10364
Closed
