### ISSUE TITLE
page request: op

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#10415]
### Command description

[1Password's CLI](https://developer.1password.com/docs/cli/)
We could also consider making pages for all the different subcommands, but it's simple enough that one page should be enough.

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by wangme88** [comment]
https://github.com/tldr-pages/tldr/pull/10717
