### ISSUE TITLE
Support downloading & caching of a subset of languages by clients

### ISSUE THREAD

**Issue by adamazing** [tldr-pages/tldr#10545]
Re: dbrgn/tealdeer#335

Paraphrased user story: "As a user with limited/metered bandwidth and/or limited storage, I want my tldr client to only download the languages I care about."

I think this would be in line with the spirit of the caching section in the [client specification](https://github.com/tldr-pages/tldr/blob/412c3caa8de65871c5407f7f569f85bf93e50879/CLIENT-SPECIFICATION.md#caching):

> _Caching SHOULD be done according to the user's language configuration (if any), **as to not waste unneeded space for unused languages**. Additionally, clients MAY automatically update the cache on a regular basis._

I'm happy to have a go at a PR to enable this use case for clients if it's something the project would like to support?

**Comment by adamazing** [comment]
> Hi, I am pretty sure our official clients only cache the correct locales in your system. Is it missing from any of our official clients (in the org here)?

Apologies for the confusion, the key improvement would be the ability to be able to **download** only the pages required. 

Having checked the node cli -- quickly from my phone in the middle of my night, so I'm sorry if I've misunderstood something -- it looks like the method there (as with tealdeer) is to download the zip file containing _all_ languages.

Zipping and publishing languages' subdirectories in build.sh/deploy.sh might be one way to allow clients to avoid downloading all languages.

**Comment by kbdharun** [comment]
> Zipping and publishing languages' subdirectories in build.sh/deploy.sh might be one way to allow clients to avoid downloading all languages.

If possible, can you start a discussion regarding this in our [chatroom](https://matrix.to/#/#tldr-pages:matrix.org)?

As this is kinda a breaking change, so I want to hear what other maintainers think about this proposal.

**Comment by adamazing** [comment]
> As this is kinda a breaking change for our existing clients, so I want to hear what other maintainers think about this proposal.

I don't believe it would be. 

One approach, the one I had considered implementing, would be that the complete archive would _still_ be published for clients that chose to download the complete archive. They would see no change. The complete archive would still be available at the current location.

BUT separate lang-specific archives would also exist, e.g. pages.zip/tldr-pages.zip/pages.base.zip & pages.ar.zip/tldr-pages.ar.zip (TBD). 

> If possible, can you start a discussion regarding this in our [chatroom](https://matrix.to/#/#tldr-pages:matrix.org)?

I'll endeavour to do so later today.
