### ISSUE TITLE
debug report

### ISSUE THREAD

**Issue by yrmvgh** [tldr-pages/tldr#1054]
It failed at --update, but also it was the first time I installed and used npm, so I probably don't have npm set up right.

https://github.com/tldr-pages/tldr/blob/65636d12191b99456cd760a92145ca879a5e2043/debug

**Comment by agnivade** [comment]
Please follow the steps mentioned here - https://github.com/tldr-pages/tldr-node-client#installing. That should solve your issue.

**Comment by agnivade** [comment]
Hi @yrmvgh , did it solve your issue ?

**Comment by agnivade** [comment]
Hi @yrmvgh , I am closing this issue now. Please open an issue at this repo - https://github.com/tldr-pages/tldr-node-client if your issue persists.
