### ISSUE TITLE
page update request: yt-dlp

### ISSUE THREAD

**Issue by Managor** [tldr-pages/tldr#10585]
### Command description

The page for `yt-dlp` is sloppily written. The page for `youtube-dl` is much better written and `yt-dlp` is a basically just a fork of `youtube-dl` so the commands should be taken from that page, tested and copied over. 

`yt-dlp` page https://github.com/tldr-pages/tldr/blob/main/pages/common/yt-dlp.md
`youtube-dl` page https://github.com/tldr-pages/tldr/blob/main/pages/common/youtube-dl.md

### OS

- [X] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by thrila** [comment]
can i take this issue?

**Comment by kbdharun** [comment]
> can i take this issue?

Sure

**Comment by 4yu5h23** [comment]
hello

**Comment by thrila** [comment]
Did this a while back forgot to comment hopefully it has been taken care of

**Comment by kbdharun** [comment]
> Did this a while back forgot to comment hopefully it has been taken care of

This still is open for anyone to create a PR on as the page hasn't been updated yet.

**Comment by thrila** [comment]
Ok thanks I'll do it today unfailingly

**Comment by Managor** [comment]
This seems to be now fixed
