### ISSUE TITLE
page request: docker compose specifying a project name

### ISSUE THREAD

**Issue by imlucyd** [tldr-pages/tldr#10596]
### Command description

Currently we have a part of the docker compose command documented but almost all every project I've been are using a project name in their containers but this information is not available in the current docker compose page so that's the goal

### Command details

docker compose -p {{project_name}} up

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by luisnquin** [comment]
Actually I was working on it with @imlucyd so I'll upload my pull request
