### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by ASBaumgarten** [tldr-pages/tldr#1059]
![terminal](https://cloud.githubusercontent.com/assets/7777147/18483153/fcf6414a-79b0-11e6-8a26-c80c10a97c12.jpg)
Is there anyway to change the color of the output text? The blue color of some of the text is terribly difficult to read on a black terminal background without turning my screen brightness up.

 **OS**: 64bit Mac OS X 10.11.6 15G31
 **Kernel**: x86_64 Darwin 15.6.0
 **Uptime**: 12d 20h 47m
 **Packages**: 76
 **Shell**: bash 3.2.57
 **Resolution**: 2880x1800
 **DE**: Aqua
 **WM**: Quartz Compositor
 **WM Theme**: Blue
 **Font**: Monaco 12
 **CPU**: Intel Core i7-4850HQ CPU @ 2.30GHz
 **GPU**: Intel Iris Pro / NVIDIA GeForce GT 750M
 **RAM**: 5577MiB / 16384MiB

**Comment by waldyrious** [comment]
This is an issue with https://github.com/tldr-pages/tldr-cpp-client. I would ask you to report it there, but I think we have to handle this sort of confusion between the pages repo and the clients, so I'll leave it here as a reminder for us to clarify that.

@Leandros can you please take a look?

**Comment by Leandros** [comment]
We've had such issues before. And as a response we've changed a few of the colors.

However, we're using the default ANSI Colors, which are defined by your terminal theme. We can't account for every single theme out there, the best way to fix this is by fixing your terminal theme.

Here you can view the color escape codes we're using (the one in question, blue, is highlighted): https://github.com/tldr-pages/tldr-cpp-client/blob/master/src/tldr.h#L36

**Comment by ASBaumgarten** [comment]
I'll play around with different themes in iTerm2 to find one that works. Thanks for the help.

**Comment by Leandros** [comment]
For inspiration I can recommend [base16](http://chriskempson.com/projects/base16/). I've used that in the past.

**Comment by agnivade** [comment]
Hey @ASBaumgarten, I think there is nothing further to be done in this thread. Closing this one. Feel free to reopen if needed.

**Comment by HalisCz** [comment]
I would like to reopen this issue.

I am using (KDE Plasma 5) Konsole with included colorscheme "Solarized Light", and basic font is almost invisible (as you can see below). 

![obrazek](https://user-images.githubusercontent.com/1120890/34205724-d1d83866-e583-11e7-9d83-34aa5ed67e16.png)

I know that "background" color and "color8" are almost the same, but I think that Solarized is so popular, that this should be handled somehow.

What do you think?

**Comment by agnivade** [comment]
Please raise the issue in the tldr-cpp-client repo. This repo is only for the pages.

**Comment by HalisCz** [comment]
Ok, thank you for quick response ;-)
