### ISSUE TITLE
Let's Document: pkgctl

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#10590]
https://man.archlinux.org/man/pkgctl.1

## Commands

- [x] pkgctl → #10573
- [x] pkgctl auth → #10595
- [ ] pkgctl build → #10808
- [x] pkgctl diff → #10599
- [ ] pkgctl release → #10808
- [x] pkgctl repo → #10598
- [x] pkgctl version → #10600

**Comment by ohyahgit** [comment]
Can I help?

**Comment by kbdharun** [comment]
> Can I help?

Sure
