### ISSUE TITLE
add screenfetch command

### ISSUE THREAD

**Issue by ASBaumgarten** [tldr-pages/tldr#1060]
[https://github.com/KittyKatt/screenFetch](https://github.com/KittyKatt/screenFetch)

**Comment by assemusr** [comment]
I want to work on this, but I have a problem installing 'tldr' in the first place
![screenshot from 2016-10-31 10-07-39](https://cloud.githubusercontent.com/assets/16057969/19847793/f6c408f4-9f51-11e6-9214-025d0bfbf950.png)

**Comment by waldyrious** [comment]
@assemusr thanks for the initiative! The installation error is a known issue which I'm afraid has yet to be resolved in a satisfactory manner (cc @agnivade, @zdroid). For now, the workaround is as described in the [tldr-node-client readme](https://github.com/tldr-pages/tldr-node-client#installing):

> If you are installing with sudo, pass the `--user` parameter:

> ```bash
sudo npm install -g tldr --user=$(whoami)
```

> This is required because we populate the page cache after installation. And npm by default downgrades the post-install user permission level to `nobody` when run as root.

**Comment by assemusr** [comment]
Thanks :) Work in progress.

**Comment by assemusr** [comment]
This one is already there in /pages/linux
I even thought it's a '/pages/common' one according to KittyKatt's repo. Anyway, I consider this has been done.

**Comment by agnivade** [comment]
Wow .. we should have caught this. @waldyrious - what do you think ? Shall we close this one ?

**Comment by zdroid** [comment]
Feel free to close this, there's already [such page](https://github.com/tldr-pages/tldr/blob/master/pages/linux/screenfetch.md).

**Comment by waldyrious** [comment]
Weird. I wonder if @ASBaumgarten was looking for this page in another platform's folder? The tool does seem to be [pretty platform-agnostic](https://github.com/KittyKatt/screenFetch#how-do-i-get-screenfetch), so maybe we should just move the page?

**Comment by agnivade** [comment]
makes sense to me.

**Comment by waldyrious** [comment]
@assemusr wanna add this one to your belt? ;)

**Comment by assemusr** [comment]
@waldyrious How is that supposed to be?

**Comment by waldyrious** [comment]
@assemusr this one would have to be done in the command line. In your local clone of the repo, you would do `git mv pages/linux/screenfetch.md pages/common/screenfetch.md`, then commit the change and start a new PR from it. Let me know if anything isn't clear, or if you'd rather leave this for someone else to do.

**Comment by assemusr** [comment]
Definitely, I will do that, thanks ;)
