### ISSUE TITLE
Local Custom Pages

### ISSUE THREAD

**Issue by BrianEnigma** [tldr-pages/tldr#10602]
I work in an organization that has several internal CLI tools. Like many of the things documented in tldr, they can be complex but there are only a half-dozen common workflows. Since they're internal tools, they are 100% NOT useful as contributions to the public tldr git repo. If there's a way to add personal/local pages to tldr, I apologize but I don't see it documented anywhere. I think I found I could correctly format a Markdown file and place it in `~/.tldrc/tldr/pages/common/` and it sort of works for a while, but eventually gets clobbered by a database refresh. It would be great if there was a place such as `~/.tldrc/tldr/local` that maintains a local set of custom tldr pages that gets unioned with the public list of commands. Or if there's already a mechanism to do this, to add it to the documentation.

**Comment by kbdharun** [comment]
Hi, Thanks for the issue. Our official clients don't support this behaviour but Tealdeer (a popular `tldr` client supports it), feel free to check it out at https://dbrgn.github.io/tealdeer/installing.html and this is the page you are looking for https://dbrgn.github.io/tealdeer/usage_custom_pages.html.

Ref. https://github.com/orgs/tldr-pages/discussions/8237

**Comment by jasonkarns** [comment]
The links shared above are broken. I _think_ the tealdeer client being referenced above is: https://github.com/tealdeer-rs/tealdeer with the github pages site: https://tealdeer-rs.github.io/tealdeer/usage_custom_pages.html

**Comment by kbdharun** [comment]
> The links shared above are broken. I _think_ the tealdeer client being referenced above is: https://github.com/tealdeer-rs/tealdeer with the github pages site: https://tealdeer-rs.github.io/tealdeer/usage_custom_pages.html

Yep, will update them in my comment, the project has moved to an org from the original author's individual account last year.
