### ISSUE TITLE
how switch to Chinese prompt

### ISSUE THREAD

**Issue by JHXue** [tldr-pages/tldr#10655]
Hi, I am from China and my computer is mac mini m2.
 I use brew install tldr, how to switch to Chinese prompt.

![image](https://github.com/tldr-pages/tldr/assets/5742702/f88114ca-481a-45e4-9c7d-5d01dc70fe8d)

**Comment by pixelcmtd** [comment]
If you're using a spec-compliant client, you can configure the language through the means [outlined in the client specification](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#language) (mainly the `LANG` and `LANGUAGE` environment variables and the `-L`/`--language` command line option). However, the [`tldr-c-client`](https://github.com/tldr-pages/tldr-c-client) is currently under-maintained and doesn't support other languages. If you want to read `tldr` pages in a different language than English, you should consider switching to a different client like [`tldr-python-client`](https://github.com/tldr-pages/tldr-python-client) or [`tealdeer`](https://github.com/dbrgn/tealdeer).
