### ISSUE TITLE
Post and update a Checklist with the errors to be fixed on each PR

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#1066]
As per https://github.com/tldr-pages/tldr/issues/980

While most people are happy with checking travis logs, it's a step less for us to just look for a message like the one below when a Travis build has failed, and make sure it's been all checked.

> Hi! We found some errors in your pages. Please attend to them soon so we can take a look at your page!
> - [ ] pages/linux/strace.md:21: TLDR005 Example descriptions should end in a colon
> - [ ] pages/linux/strace.md:21: TLDR006 Command name and description should be separated by an empty line

**Comment by agnivade** [comment]
This might be a starting place to look - https://github.com/koddsson/travis-github-pr-bot

**Comment by waldyrious** [comment]
This has been reopened in #1207.

**Comment by agnivade** [comment]
Now that its merged, will run some tests to see if it actually works.

**Comment by waldyrious** [comment]
Woohoo!! 🎉 🌟
