### ISSUE TITLE
Define and Setup PR template

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#1067]

**Comment by waldyrious** [comment]
a draft to get the discussion started would be nice :)

**Comment by ostera** [comment]
Absolutely agree, I'm just splitting up the [bigger issue](https://github.com/tldr-pages/tldr/issues/980) into smaller, digestible chunks we can work on better, and track in a project.

Once I'm done with this I'll give the PR template a shot :)

**Comment by waldyrious** [comment]
No pressure regardless, I just meant to post what I thought should be the next step for this issue move forward :)

**Comment by waldyrious** [comment]
Jotting down some ideas so I don't forget them:

- lowercase command name, space after the `#`
- description following a common phrase structure format (e.g. no "this tool serves to" or variants, etc.)
- verbs conjugated in the infinity ("Create foo", not "Creates foo"), in both the main and example descriptions
- other commands mentioned within backtics (#784)
- uppercase first letter on each description, end in `.` or `:` for the main and example descriptions, respectively (the linter already checks this)
- max length of lines
- max length of page (number of lines)
- token formatting (snake_case, when to use real examples or generic placeholders, etc.)

**Comment by waldyrious** [comment]
:tada: @agnivade :D
