### ISSUE TITLE
Define and Setup Issue Template

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#1069]
As per https://github.com/tldr-pages/tldr/issues/980

**Comment by waldyrious** [comment]
@ostera, now that we have a nice [PR template](https://github.com/tldr-pages/tldr/blob/master/.github/PULL_REQUEST_TEMPLATE.md) (#1434 / #1067), I wonder if we still need an issue template. @agnivade and @sbrl, your thoughts would be appreciated as well.

**Comment by waldyrious** [comment]
Note that in #1073, @ostera commented:
> Submit an Command Request (Issue) [...] is fairly straightforward

which I tend to agree with. Does anyone feel we need to provide specific instructions for issues requesting new commands?

**Comment by agnivade** [comment]
Yes, I still still it would be nice to have the issue template too. Just for completeness' sake.

**Comment by waldyrious** [comment]
Ok, sure. I still think it's overkill, and that we must be careful with the contents of the template to avoid making participation in the project too bureaucratic or burdensome. With that in mind, feel free to suggest a wording you think would work well, at your leisure :)

**Comment by sbrl** [comment]
I think that the PR template serves a useful purpose for contributors, but while there is a clear category of issues requesting particular commands, there are also a bunch of other types of issues that wouldn't necessarily benefit from an issue template - such as this one, or #1410, or #1263. I suspect that there isn't a 'one size fits all' solution here, so I'd vote to not have an issue template.

**Comment by waldyrious** [comment]
That was my concern as well. We can always use the approach I mentioned [here](https://github.com/tldr-pages/tldr/issues/1073#issuecomment-253673426), which allows multiple templates, one per issue type, but to be honest I don't think the influx of issues is neither large enough, nor neatly separable into a few bins, to justify the apparatus.

**Comment by sbrl** [comment]
I agree.
