### ISSUE TITLE
page request: mkosi

### ISSUE THREAD

**Issue by fwilhe2** [tldr-pages/tldr#10692]
### Command description

Tool for building os images described as

> A fancy wrapper around `dnf --installroot`, `apt`, `pacman` and `zypper` that generates customized disk images with a number of bells and whistles.

Part of systemd

https://github.com/systemd/mkosi

### Command details

v16

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by Sourav-Kumar-Panda** [comment]
Can i work on this project?

**Comment by kbdharun** [comment]
> Can i work on this project?

Sure

**Comment by fwilhe2** [comment]
Hi @Sourav-Kumar-Panda, sure, please go ahead. I did not have time to prepare a draft so far. I'm happy to review any draft you might have.

**Comment by Sourav-Kumar-Panda** [comment]
Actually, I am new to open source, can you please suggest to me what resources I should follow in order to solve this issue?

**Comment by fwilhe2** [comment]
[The Contributing page should be a good place to start](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md)

For mkosi specifically it makes sense to get familiar with the tool and distill the most important commands, see the page I've linked above in the issue.
