### ISSUE TITLE
MAINTAINERS: add @isaacvicente as collaborator

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#10737]
Hi, @isaacvicente! You seem to be enjoying contributing to the tldr-pages project.
You now have had 13 distinct [pull requests](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+author%3A%22isaacvicente+%22) merged!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by isaacvicente** [comment]
Yes, absolutely! I'm very happy about this indication. As a volunteer, I can't contribute on a regular basis, but I will try to enhance the project whenever I can. Thank you very much!
Greetings.

**Comment by kbdharun** [comment]
Congratulations and welcome to tldr @isaacvicente, I have sent the invitation to add you as a collaborator. Feel free to close to issue with a PR.

**Comment by kbdharun** [comment]
Btw, if you are interested, can we add you alongside Waldyrus as Codeowner to automatically review pt_BR translation PRs?

**Comment by isaacvicente** [comment]
Sure.

**Comment by kbdharun** [comment]
> Sure

While creating a PR to update MAINTAINERS.md, add yourself to the CODEOWNERS file too.

**Comment by isaacvicente** [comment]
I've created a PR doing what you requested.
