### ISSUE TITLE
MAINTAINERS: add @kant as collaborator

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#10738]
Hi, @kant! You seem to be enjoying contributing to the tldr-pages project.
You now have had over 200 distinct [pull requests](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+is%3Aclosed+author%3Akant) merged!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by kant** [comment]
Thanks for the nomination. 
Of course, count with me as collaborator!

**Comment by kbdharun** [comment]
Congratulations and welcome to tldr @kant, I have sent the invitation to add you as a collaborator. Feel free to close this issue with a PR.
