### ISSUE TITLE
Add more fields to the commands

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1082]
e.g. URL (mentioned in [#934](https://github.com/tldr-pages/tldr/pull/934#issuecomment-229016985)), see also (tracked in #481), maybe platform (related to #190)?

We will need to decide details in dedicated issues, but overall discussion about a potential new page format (including markdown syntax, see #784 and #958) should happen in a coordinated way, hence this issue.

**Comment by waldyrious** [comment]
Another field proposal: original manpage (#1248)

**Comment by waldyrious** [comment]
The first one (URL) is now properly tracked in #2649.

**Comment by zdroid** [comment]
Isn't this all already implemented @waldyrious?

**Comment by waldyrious** [comment]
@zdroid how so? IIUC only `URL` and `see also`. Even then, neither is implemented in a structured way.

Since we're already using markdown, one possibility to make these fields consistent and extensible would be to use the frontmatter metadata format, like this:

```md
---
foo: bar
baz: qux
---

(rest of markdown content)
```

That would make our pages compatible with other markdown processing tools and in particular with other cheatsheet repositories, as described by @chrisallenlane in https://github.com/chubin/cheat.sheets/issues/101#issuecomment-632032627.

**Comment by chrisallenlane** [comment]
+1. Front-matter has worked really well for `cheat`. I think it would be the most painless approach to make the cheatsheet repositories portable, without imposing meaningful constraints on any of our individual projects.

Just shout if I can somehow be of service.

**Comment by sbrl** [comment]
Ah, thanks for opening this issue @waldyrious!

Indeed, taking a more structured approach would be great.

Front-matter does sound like a good idea. It bothers me a bit that it's above the main title of the page though - but that's not a big deal.

I'm not sure that it's part of the CommonMark spec though, so it would require a breaking change update to the client specification.

We'd also have to perform an automated update to existing pages, and potentially rename the .zip archive too (which might be a good opportunity to deal with that other issue that was talking about restructuring the .zip file by splitting it into multiple languages, but I can't remember the issue number).

**Comment by waldyrious** [comment]
Good point. @chrisallenlane do you know if these metadata blocks can be added to the bottom of the markdown file rather than the beginning? It would be great if we could keep our format `cat`/`less`-friendly.

**Comment by Managor** [comment]
I'm not seeing any unresolved proposals in this issue. If I missed any, please reopen the issue.
