### ISSUE TITLE
MAINTAINERS: add @gutjuri as collaborator

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#10874]
Hi, @gutjuri! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3Agutjuri+is%3Aclosed)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by gutjuri** [comment]
Thank you, I'd be glad to be a maintainer. However, I cannot promise that I can be very active in this repository, as I am maintaining others as well. Still, I think that I could help here and there.

**Comment by kbdharun** [comment]
Congratulations, I have sent an invitation to add you as a collaborator. Feel free to close this PR with an issue.
