### ISSUE TITLE
page request: a2ping

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#10884]
### Command description

a2ping is a script that can convert images into EPS or PDF files. See https://www.ctan.org/pkg/a2ping

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [X] Windows

**Comment by npv12** [comment]
I would like to contribute to it

**Comment by gutjuri** [comment]
Sure, I can assign you to this issue if you would like that. Thanks for your interest!
