### ISSUE TITLE
Let's document: Netpbm

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#10887]
### Command description

[Netpbm](https://en.wikipedia.org/wiki/Netpbm) is a software package for manipulating images. It contains many commands, none of which have tldr pages yet. 

I created this issue for tracking the progress of documenting netpbm. Documentation of these commands can be found here: https://netpbm.sourceforge.net/doc/directory.html

- [x] anytopnm → #10908
- [x] asciitopgm → #11050
- [x] atktopbm → #12236
- [x] bioradtopgm → #11071
- [x] bmptopnm → #11026
- [x] brushtopbm → #11308
- [x] cmuwmtopbm   → #12235
- [x] escp2topbm   → #12235
- [x] eyuvtoppm → #11380
- [x] fiascotopnm → #11752
- [x] fitstopnm → #12296
- [x] fstopgm → #12198
- [x] gemtopnm → 
- [x] giftopnm → #11307
- [x] gouldtoppm →
- [x] hipstopgm→#11197
- [x] ilbmtoppm →#11432
- [x] imgtoppm → #11329
- [x] jpegtopnm → #11084
- [x] leaftoppm → #11237
- [x] lispmtopgm → #12198
- [x] macptopbm → #11316
- [x] mdatopbm → #12225
- [x] mgrtopbm → #12225
- [x] mtvtoppm →
- [x] neotoppm → #10979
- [x] palmtopnm → #11057 #11751
- [x] pambackground → #12237
- [x] pamcut →  #12296
- [x] pamcomp → #12197 
- [x] pamdeinterlace →  #12296
- [x] pamdepth  → #11379
- [x] pamdice →  #12296
- [x] pamdither → #11379
- [x] pamenlarge  → #12236
- [x] pamfile  → #10893
- [x] pamflip → #11800
- [x] pamfunc → #11449
- [x] pamnoraw  → #11403
- [x] pamoil → #11433
- [x] pampop9 → #11756
- [x] pamscale → #11779
- [x] pamstack →
- [x] pamstretch → #12237
- [x] pamstretch-gen  → #12237
- [x] pamtopam → #11403
- [x] pamtopnm → #11403
- [x] pamtoqoi → #11401
- [x] pamtotiff → #11408
- [x] pamtowinicon → #11404
- [x] pamtoxvmini → #11406
- [x] pbmclean → #12237
- [x] pbmlife → #11240
- [x] pbmmake → #11435
- [x] pbmmask → #12237
- [x] pbmnoise → #12202
- [x] pbmpage → #12237
- [x] pbmpscale → #12237
- [x] pbmreduce → #12236
- [x] pbmtext → #12236
- [x] pbmtextps → #12236
- [x] pbmtoascii → #11289
- [x] pbmtoatk → #12236
- [x] pbmtobbnbg → #12236
- [x] pbmtocmuwm → #12235
- [x] pbmtoepsi → #12235
- [x] pbmtoepson → #12235
- [x] pbmtoescp2  → #12235
- [x] pbmtogem → #11343
- [x] pbmtogo → #12235
- [x] pbmtolj → #11409
- [x] pbmtomacp → #12225
- [x] pbmtomda → #12225
- [x] pbmtomgr → #12225
- [x] pbmtonokia → #12225
- [x] pbmtopgm → #12224 
- [x] pbmtoplot → #12224 
- [x] pbmtoppa → #12224 
- [x] pbmtoptx → #12224 
- [x] pbmtowbmp → #11408
- [x] pbmtox10bm → #11407
- [x] pbmtoxbm → #11407
- [x] pbmtoybm → #11406
- [x] pbmtozinc → #11401
- [x] pbmupc → #12224 
- [x] pcxtoppm →#11432
- [x] pgmbentley → #11433
- [x] pgmdeshadow → #11433
- [x] pgmenhance → #12224 
- [x] pgmhist → #12202
- [x] pgmkernel → #12202
- [x] pgmnoise → #12202
- [x] pgmmake → #11435
- [x] pgmoil → #11433
- [x] pgmramp → #12202
- [x] pgmtexture → #12202
- [x] pgmtofs → #12198
- [x] pgmtolispm → #12198
- [x] pgmtoppm → #12198
- [x] pgmtosbig → #11404
- [x] pgmtost4  → #11404
- [x] picttoppm → #11413
- [x] pjtoppm → #11409
- [x] pnmalias → #12198
- [x] pnmcolormap → #11800
- [x] pnmcomp → #12197 
- [x] pnmconvol → #12197 
- [x] pnmcrop → #12197 
- [x] pnmdepth  → #11379
- [x] pnmgamma → #12197 
- [x] pnmhisteq →  #12189
- [x] pnmhistmap →  #12189
- [x] pnmindex →  #12189
- [x] pnminvert → #12189
- [x] pnmmargin →  #12187
- [x] pnmmontage →  #12187
- [x] pnmnlfilt →  #12187
- [x] pnmnorm →  #12187
- [x] pnmpad →  #12187
- [x] pnmpaste → #12187
- [x] pnmpsnr → #12180
- [x] pnmquant → #11800
- [x] pnmremap → #11800
- [x] pnmrotate → #11800
- [x] pnmscale → #11779
- [x] pnmscalefixed → #11779
- [x] pnmshear →  #11758
- [x] pnmsmooth → #11757
- [x] pnmtile → #11755
- [x] pnmtoddif →  #11753
- [x] pnmtofiasco → #11752
- [x] pnmtojpeg → #11081
- [x] pnmtopalm →  #11751
- [x] pnmtopclxl → #11409
- [x] pnmtoplainpnm → #11403
- [x] pnmtopng → #11072
- [x] pnmtopnm → #11403
- [x] pnmtops → #11413
- [x] pnmtorast → #11410
- [x] pnmtorle → #11410
- [x] pnmtosgi → #11410
- [x] pnmtosir → #11410
- [x] pnmtotiffcmyk → #11408
- [x] pnmtotiff → #11408
- [x] pnmtoxwd → #11406
- [x] ppmchange → #11449
- [x] ppmcie → #11449
- [x] ppmcolormask → #11449
- [x] ppmdim → #11449
- [x] ppmdist → #11449
- [x] ppmdither →  #11379 
- [x] ppmfade → #11449
- [x] ppmflash → #11116
- [x] ppmforge → #11449
- [x] ppmhist → #10950
- [x] ppmlabel → #11435
- [x] ppmmake → #11435
- [x] ppmmix → #11435
- [x] ppmntsc → #11435
- [x] ppmpat → #11435
- [x] ppmquant → #11800
- [x] ppmrainbow → #11433
- [x] ppmrelief → #11433
- [x] ppmshadow → #11433
- [x] ppmshift → #11433
- [x] ppmspread → #11433
- [x] ppmtoacad → #11433
- [x] ppmtoarbtxt → #11401
- [x] ppmtobmp → #11433
- [x] ppmtoeyuv → #11380
- [x] ppmtoicr → #11433
- [x] ppmtoilbm →#11432
- [x] ppmtoleaf →#11432
- [x] ppmtolj → #11409
- [x] ppmtomitsu →#11432
- [x] ppmtompeg →#11432
- [x] ppmtoneo →#11432
- [x] ppmtopcx →#11432
- [x] ppmtopgm → #11094
- [x] ppmtopict → #11413
- [x] ppmtopj → #11409
- [x] ppmtoppm → #11403
- [x] ppmtopuzz → #11413
- [x] ppmtosixel → #11413
- [x] ppmtospu → #11409
- [x] ppmtowinicon → #11404
- [x] ppmtoxpm → #11407
- [x] ppmtoyuv → #11380
- [x] ppmtoyuvsplit → #11380
- [x] ppmtv → #11338
- [x] psidtopgm → #11413
- [x] pstopnm → #11413
- [x] qoitopam → #11401
- [x] qrttoppm → #11413
- [x] rasttopnm → #11410
- [x] rawtopgm → #11401
- [x] rawtoppm → #11401
- [x] rletopnm → #11410
- [x] sbigtopgm → #11404
- [x] sgitopnm → #11410
- [x] sirtopnm → #11410
- [x] sldtoppm → #11409
- [x] spctoppm → #11409
- [x] sputoppm → #11409
- [x] st4topgm → #11404
- [x] tgatoppm → #11402
- [x] thinkjettopbm → #11409
- [x] tifftopnm →  #11408
- [x] wbmptopbm → #11408
- [x] winicontopam → #11404
- [x] winicontoppm → #11404
- [x] xbmtopbm → #11407
- [x] ximtoppm → #11407
- [x] xpmtoppm → #11407
- [x] xvminitoppm → #11406
- [x] xwdtopnm → #11406
- [x] ybmtopbm → #11406
- [x] yuvsplittoppm → #11380
- [x] yuvtoppm → #11380
- [x] zeisstopnm → #10888

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by WillOfHeaven** [comment]
I have been learning linxu for a while and I really would like to contribute this issue, can you please assign this to me !

**Comment by gutjuri** [comment]
> I have been learning linxu for a while and I really would like to contribute this issue, can you please assign this to me !

Thanks for your interest. However, this issue is not meant to be assigned to individual developers, its purpose is rather to track progress on documenting Netpbm. 

If you would like to contribute to this issue, you could follow these steps:

- Choose a command that you would like to document from the list above.
- Create a fork of this project.
- In this fork, create a tldr page for the command you chose.
- Create a pull request that merges your changes into this project.

We also have a [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md) file, which will be of interest to you. If you have any other questions, feel free to ask :) 

Have fun!

**Comment by gutjuri** [comment]
done with #12296 🥳

to be continued in #12299
