### ISSUE TITLE
Add thefuck command

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1097]
This should address #241 which at the time was just an alias and wasn't merged because of it. The tool is now a [full-fledged command line utility](https://github.com/nvbn/thefuck), and a very useful one at that, so we definitely should cover it.

**Comment by assemusr** [comment]
Working on this..

**Comment by assemusr** [comment]
Working on this.. But I quite don't understand how to distinguish between 'common' commands and the system-specific' commands, there're commands listed under 'system-specific' which works as well on other systems while they're not listed under 'common'. for example this one here, where should I list it? I'd appreciate any explanation, thanks in advance.

**Comment by agnivade** [comment]
@assemusr - Yes, there might be discrepancies and we fix it from time to time. Typically, the logic is what you would expect, any platform agnostic command is placed under `common` and platform specific commands are placed under that folder.

However, there are several occasions, where the same command will have different variants of options on different platforms. In those cases, we have different copies of the command under different platform specific folders. Hope that clarifies some doubts.

You can post `fuck` command, under `common`.

**Comment by assemusr** [comment]
This one is has no options, however I submitted the PR.
