### ISSUE TITLE
There is no document when I use the tldr the Second time.

### ISSUE THREAD

**Issue by ramwin** [tldr-pages/tldr#1099]
![Picture](https://raw.githubusercontent.com/ramwin/source/master/tldr.png)

I'm using ubuntu 16.04. I tried to upgrade my tldr using `sudo pip3 install --upgrade tldr`, but the problem still exist.

**Comment by ramwin** [comment]
I use `tldr -u` to update the cached commands. and now it worked.

**Comment by waldyrious** [comment]
@ramwin can you tell us what client you're using? That seems to be the python client, can you confirm?

**Comment by ramwin** [comment]
I ran `which tldr`, the path is `/usr/local/bin/tldr`: 

```
#!/usr/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from tldr import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

I remember I use `sudo pip install tldr` to install it, but I'm not sure whether I'm using pip2 or pip3.

**Comment by waldyrious** [comment]
ok, so that's the python client. Pinging @felixonmars for further investigation into what could be the problem.

**Comment by zero-jack** [comment]
I have the same problem. But I could not get information when executing the same command again or running `tldr -u`. 

## ENV

- Mac OSX 10.11.16
- tldr (pip3 install tldr)

## Problem Detailed

```
➜  全量数据 tldr cp
# cp

  Copy files.

- Copy files in arbitrary locations:

  cp /path/to/original /path/to/copy

- Copy a file to a parent directory:

  cp /path/to/original ../path/to/copy

- Copy directories recursive using the option -r:

  cp -r /path/to/original /path/to/copy

- Show files as they are copied:

  cp -vr /path/to/original /path/to/copy

- Make a copy of a file, adding an extension:

  cp file.html{,.backup}

- Make a copy of a file, changing the extension:

  cp file.{html,backup}



➜  全量数据 tldr cp



➜  全量数据 tldr -u
Updated cache for cp (common)
Updated cache for find (common)
Updated cache for man (common)
Updated cache for rm (common)
Updated cache for tar (common)

➜  全量数据 tldr cp



```
The blank means there is nothing information.

**Comment by agnivade** [comment]
Hi @zero-jack and @ramwin - it seems like @felixonmars is not active. I would recommend trying out the node client if its a persistent issue.

**Comment by sbrl** [comment]
Hey! Are there any updates on this? Can anyone still reproduce this issue?

(and shouldn't it be moved to be against tldr-pages/tldr-python-client?)

**Comment by ramwin** [comment]
This problem still exists. And I posted it in the [tldr-pages/tldr-python-client](https://github.com/tldr-pages/tldr-python-client/issues/45)

**Comment by waldyrious** [comment]
Thanks @sbrl and @ramwin for revisiting this. @zero-jack please check the suggestion I left in the issue @ramwin linked above, as that may fix the issue until @felixonmars makes a new release (that's now tracked in https://github.com/tldr-pages/tldr-python-client/issues/47)

**Comment by zero-jack** [comment]
@waldyrious I have turned to node client and it works. I don't know whether it's ok for python-client because I had uninstalled(`pip3 uninstall tldr`)

**Comment by waldyrious** [comment]
That's understandable. Thanks for confirming :)
