### ISSUE TITLE
page request: ddgr

### ISSUE THREAD

**Issue by Nekosis** [tldr-pages/tldr#11045]
### Command description

[`ddgr`](https://github.com/jarun/ddgr) is a tool maintained by the same person as the now archived `googler` tool (which does have a `tldr` page). The README describes it as:

> `ddgr` is a cmdline utility to search DuckDuckGo ([html version](https://html.duckduckgo.com/html/)) from the terminal. While [googler](https://github.com/jarun/googler) is extremely popular among cmdline users, in many forums the need of a similar utility for privacy-aware DuckDuckGo came up. [DuckDuckGo Bangs](https://duckduckgo.com/bang) are super-cool too! So here's `ddgr` for you!

`ddgr` is almost a one-to-one clone of `googler` in terms of interface, so this should only require a modification of the `googler` page.

### Command details

v2.1

### OS

- [X] Android
- [X] Linux
- [X] macOS (osx)
- [ ] sunOS
- [X] Windows

**Comment by aditya-shrivastavv** [comment]
I am working on this please assign this issue to me.
