### ISSUE TITLE
MAINTAINERS: add @sebastiaanspeck as collaborator

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#11075]
Hi, @sebastiaanspeck! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3Asebastiaanspeck+is%3Aclosed)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

Edit. Can we add you to the codeowners file for Dutch so that you are automatically requested review when someone modifies the pages in a PR?

**Comment by sebastiaanspeck** [comment]
Hi, @kbdharun! 

Thanks for inviting me as a collaborator to tldr-pages. You can surely add me as a collaborator and code owner for Dutch. I have read the maintainer's guide as well.

**Comment by kbdharun** [comment]
Congratulations, I have sent an invite.

Feel free to close this issue with a PR.
