### ISSUE TITLE
page modification request: android/*

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#11099]
### Command description

54 pages have a reference to `https://cs.android.com/android/platform/superproject/+/master`, but visiting this links shows an alert:

> [!WARNING]
ALERT: This file is stale. Please view the [main](https://cs.android.com/android/platform/superproject/main) branch for the latest version of this code.

The files that need to be updated are:
- [x] pages.tr/android/bugreport.md
- [x] pages.tr/android/bugreportz.md
- [x] pages.tr/android/cmd.md
- [x] pages.ta/android/bugreport.md
- [x] pages.ta/android/bugreportz.md
- [x] pages.ta/android/cmd.md
- [x] pages.pt_PT/android/bugreport.md
- [x] pages.pt_PT/android/bugreportz.md
- [x] pages.pt_PT/android/cmd.md
- [x] pages.es/android/bugreport.md
- [x] pages.es/android/bugreportz.md
- [x] pages.es/android/cmd.md
- [x] pages.pt_BR/android/bugreport.md
- [x] pages.pt_BR/android/bugreportz.md
- [x] pages.pt_BR/android/cmd.md
- [ ] pages.pt_BR/common/fastboot.md
- [x] pages.pl/android/bugreport.md
- [x] pages.pl/android/bugreportz.md
- [x] pages.pl/android/cmd.md
- [x] pages.ko/android/bugreport.md
- [x] pages.it/android/bugreport.md
- [x] pages.it/android/cmd.md
- [x] pages.it/common/fastboot.md
- [x] pages.de/android/bugreport.md
- [x] pages.de/android/bugreportz.md
- [x] pages.de/android/cmd.md
- [x] pages.uz/android/bugreport.md
- [x] pages.uz/android/bugreportz.md
- [x] pages.uz/android/cmd.md
- [x] pages.id/android/bugreport.md
- [x] pages.id/android/bugreportz.md
- [x] pages.id/android/cmd.md
- [x] pages.zh/android/bugreport.md
- [x] pages.zh/android/bugreportz.md
- [x] pages.zh/android/cmd.md
- [x] pages.ru/android/bugreport.md
- [x] pages.ru/android/bugreportz.md
- [x] pages.ru/android/cmd.md
- [x] pages/android/bugreport.md
- [x] pages/android/bugreportz.md
- [x] pages/android/cmd.md
- [x] pages/common/fastboot.md
- [x] pages.fr/android/bugreport.md
- [x] pages.fr/android/bugreportz.md
- [x] pages.fr/android/cmd.md
- [x] pages.zh_TW/android/bugreport.md
- [x] pages.zh_TW/android/bugreportz.md
- [x] pages.zh_TW/android/cmd.md
- [x] pages.fa/android/bugreport.md
- [x] pages.fa/android/bugreportz.md
- [x] pages.fa/android/cmd.md
- [x] pages.bn/android/bugreport.md
- [x] pages.bn/android/bugreportz.md
- [x] pages.bn/android/cmd.md
- [ ] pages.hi/android/cmd.md

### OS
- Android

**Comment by Magrid0** [comment]
I'm working on the <pages.it> folder.
