### ISSUE TITLE
Update tldr-cpp-client installation instructions

### ISSUE THREAD

**Issue by Leandros** [tldr-pages/tldr#1114]
The page still reads 

```
brew tap tldr-pages/tldr
brew install tldr
```

which can simply be replaced by

```
brew install tldr
```

**Comment by waldyrious** [comment]
You seem to be referring to the website. That's another repo; I've fixed it in https://github.com/tldr-pages/tldr-pages.github.io/commit/dade6c3, and will also change the readme on this repo.

**Comment by Leandros** [comment]
Yes, perfect! 👍
