### ISSUE TITLE
Reduce amount of different clients

### ISSUE THREAD

**Issue by Leandros** [tldr-pages/tldr#1115]
There is a proposal to create a spec for clients (#1065). Wouldn't it be easier to simply remove the already way to many clients?

We already have to many "official" clients, my proposal is  to have one reference client which is maintained by the organization and every other client can be maintained by the community.

This client should satisfy the following constraints:
- mature
- bug free
- no third-party dependency
- distributable via one binary
- multi-platform

This can easily be satisfied by the following clients:
- [official tldr c client](https://github.com/tldr-pages/tldr-cpp-client)
- [unofficial go client](https://github.com/anoopengineer/tldr)
- [unofficial go client](https://github.com/pranavraja/tldr)

If decide to pick the c client, I would have to invest some time to fix a few bugs on windows and make sure it runs on linux (and submit it to the packages on different distros). I'm happy to accept any help and opinion.

**Comment by waldyrious** [comment]
Locked this thread as it was merged into #1056.
