### ISSUE TITLE
page request: hub subcommands

### ISSUE THREAD

**Issue by WangLinSongss** [tldr-pages/tldr#11156]
# hub subcommands

- [x] [init](https://hub.github.com/hub-init.1.html)
- [x] [clone](https://hub.github.com/hub-clone.1.html)
- [x] [issue](https://hub.github.com/hub-issue.1.html)
- [x] [browse](https://hub.github.com/hub-browse.1.html)
- [x] [create](https://hub.github.com/hub-create.1.html)
- [x] [ci-status](https://hub.github.com/hub-ci-status.1.html)
- [x] [delete](https://hub.github.com/hub-delete.1.html)
- [x] [fork](https://hub.github.com/hub-fork.1.html)
- [x] branch

[pr 11228](https://github.com/tldr-pages/tldr/pull/11228)

# Additional info
- hub version 2.14.2
- [Hub auth issue](https://github.com/mislav/hub/issues/2655)

**Comment by gutjuri** [comment]
Can this issue be closed now that all pages have been added?
