### ISSUE TITLE
Define progression path for contributor to maintainer

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1117]
Collecting notes I've put elsewhere:

From https://github.com/tldr-pages/tldr/pull/1048#issuecomment-247834196:

> [We should] ensure resilience of the project over the long term by making the barriers between user, contributor and maintainer as permeable as possible -- case in point: none of the the currently active maintainers were part of the original team. We want this fluid adaptation to continue into the future.

From https://github.com/tldr-pages/tldr/issues/980#issuecomment-235387355:

> One thing we clearly need is a way to handle the natural flow of maintainers: people's availability varies over time, so a hand-picked, small maintainer team won't be resilient in the long-run. I suggest something more permeable, inspired in the model used by Wikipedia: after a contributor has, say, 3 PRs merged, they should automatically get commit rights, and after X more commits they should be made part of the tldr-pages organization. If this could be implemented automatically, even better. That way the project is able to scale naturally, and avoid the stagnation that often plagues to such endeavors once the original team loses steam.

**Comment by waldyrious** [comment]
There are interesting notes in http://docs.brew.sh/#maintainers which we could take some inspiration from. But let's try making the whole thing lighter (i.e. less documents to read, and more automated steps).

**Comment by sbrl** [comment]
I'd want to field-test the whole thing for a while first in manual-mode - to make sure we get the right balance.

**Comment by waldyrious** [comment]
From https://github.com/tldr-pages/tldr/pull/1407#issuecomment-308665847:

> when merging PRs by squashing, it's generally recommended to edit the commit message body and remove any superfluous details, or those that only make sense within the sequence of changes made during the PR (in effect, ensuring the whole thing is written as if it was a single commit from the start).
>
> For PRs that introduce new pages, it would suffice to use a single-line commit message (without a body) saying ": add page", unless the submitter includes details in the PR thread such as the URL for the manpage from where the tldr-page was derived, or other similar metadata.

**Comment by waldyrious** [comment]
From the [Gitter chat room, on 20 April 2017](https://gitter.im/tldr-pages/tldr?at=58f8f91a8e4b63533de9ce0a):

> We generally prefer to have at least two maintainers review each PR, so for example if one reviews and approves it, the other can merge the PR once they agree as well (unless someone else raises objections).
> If other maintainers are too busy and a PR lingers around for too long without a second maintainer’s approval, they can be merged with a single maintainer’s approval, in the interests of providing a timely response to contributions

> Generally we try to avoid merge commits, to allow a cleaner git history. If the commits in the PR are worth keeping separately (i.e. they represent semantic changes rather than typo fixes or syntax corrections revealed by TravisCI, have descriptive commit messages, etc.), then the "rebase and merge” option is the preferred one.
> Otherwise, if they’re just a bunch of commits named “edited command.md” or similar, then the "squash and merge” option is to be used instead.
> Another thing: For simple, uncontroversial fixes and typos to PR files, it’s best if the maintainer does them rather than ask the contributor, especially because the actual content-related discussion may end up requiring quite a bit of changes
> In such cases, it’s preferable to either use “rebase and merge” option on the github web interface, or an interactive rebase in the comand line, to clean up any commits that would need to be squashed, reworded, etc.i
