### ISSUE TITLE
Where did homebrew-tldr go?

### ISSUE THREAD

**Issue by jasonkarns** [tldr-pages/tldr#1118]
Error: Fetching /usr/local/Homebrew/Library/Taps/tldr-pages/homebrew-tldr failed!

**Comment by jrdelarosa3** [comment]
I received a similar warning

```
jose@macbook:~$ brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/tldr-pages/homebrew-tldr failed!
```

**Comment by waldyrious** [comment]
@jasonkarns please refer to #1104, particularly https://github.com/tldr-pages/tldr/issues/1104#issuecomment-253641166.

@Leandros, can you provide some insight here?

**Comment by Leandros** [comment]
We've removed homebrew-tldr in favour of the distribution in the official homebrew repositories.

As far as I know, since tldr is now in the official repo, the old tap should've been overwritten. Since that doesn't seem to be the case, we need to take action.

You can easily fix it by untapping the old tap:

```
brew untap tldr-pages/tldr
```

@waldyrious Can you restore the repository, I still got it cloned on my disk and can simply push it. I'll talk to the homebrew guys how we can proceed.

**Comment by jasonkarns** [comment]
I don't know if restoring is necessarily helpful. As far as I can see, homebrew doesn't provide any facility for warning users ahead of time that a tap is being deprecated and will eventually be removed. I just wanted to verify that untapping was the correct step and that it wasn't accidental or anything.

**Comment by Leandros** [comment]
[As per Mike's comment,](https://github.com/Homebrew/homebrew-core/issues/5909#issuecomment-253842997) 

```
brew install tldr
```

should already favour the core instead of a non-existant tap.

**Comment by jasonkarns** [comment]
Right, the problem is that `brew update` fails with an error when attempting to pull/update the (nonexistent) tldr tap. Probably the ideal solution is to have some better tap deprecation in place (in homebrew itself) so that users can be notified prior to the tap going away; and breaking `brew update`

**Comment by Leandros** [comment]
Absolutely correct! For the time being I've restored the old tap, to not cause any issues for existing users.
The homebrew developers are notified and will look into the issue, hopefully providing a fix in the upcoming versions.

**Comment by agnivade** [comment]
Wow .. the homebrew devs are fast !
