### ISSUE TITLE
Issues when install or using TLDR 

### ISSUE THREAD

**Issue by mansoorbarri** [tldr-pages/tldr#11190]
I had tldr which I installed via pip but then it gave me this error when I used it for any comment: 

```bash 
Traceback (most recent call last):
  File "/usr/local/bin/tldr", line 5, in <module>
    from tldr import cli
ModuleNotFoundError: No module named 'tldr'
```
I uninstalled it and tried installing again with pip, npm & snap but either it gives an error while installing or when using it.

my machine: 
![image](https://github.com/tldr-pages/tldr/assets/90044118/877aba8c-67b4-4cea-a46b-fdaf6af06b67)

**Comment by kbdharun** [comment]
Hi, can you execute the command `which tldr` and share the path output? (This would allow us to see if something is conflicting)

**Comment by mansoorbarri** [comment]
I installed it via npm using `--force` 

`which tldr` outputs `/usr/local/bin/tldr`

**Comment by kbdharun** [comment]
Can you try removing the client using `npm remove tldr` and then remove the directory too (if it still exists) with `rm -rf /usr/local/bin/tldr`. Then, can you try installing it again with `npm install -g tldr` without the force flag.

**Comment by mansoorbarri** [comment]
works 

![Uploading image.png…]()
