### ISSUE TITLE
page modification request: remove locale from link

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#11229]
### Command description

In pages/windows there are four pages that include `en-us` in the url. We don’t include a locale in the url as described [here](https://github.com/tldr-pages/tldr/pull/10963#pullrequestreview-1677793645). The four pages are:
- [ ] [sc](https://github.com/tldr-pages/tldr/blob/015e62b12817ab9d712a266a47b116ba9d3018c0/pages/windows/sc.md?plain=1#L4)
- [ ] [net](https://github.com/tldr-pages/tldr/blob/015e62b12817ab9d712a266a47b116ba9d3018c0/pages/windows/net.md?plain=1#L4)
- [ ] [w32tm](https://github.com/tldr-pages/tldr/blob/015e62b12817ab9d712a266a47b116ba9d3018c0/pages/windows/w32tm.md?plain=1#L4)
- [ ] [choice](https://github.com/tldr-pages/tldr/blob/015e62b12817ab9d712a266a47b116ba9d3018c0/pages/windows/choice.md?plain=1#L4)

Also please check if the pages are still up-to-date.

### OS

- Windows

**Comment by deadpyxel** [comment]
I think I can get this done quickly, we just need to update the URLs, correct?

**Comment by deadpyxel** [comment]
I already opened a draft pr, just checking the commands, I think a small bit of syntax has changed, but I'll double check
