### ISSUE TITLE
MAINTAINERS: add @leonvsc as collaborator

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#11495]
Hi, @leonvsc! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests [merged](https://github.com/tldr-pages/tldr/commits?author=leonvsc)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?  
Can we add you to the [CODEOWNERS](https://github.com/tldr-pages/tldr/blob/main/.github/CODEOWNERS) file for Dutch as well so that you are automatically requested review when someone modifies/adds pages in the Dutch folder in a PR?

Either way, thanks for all your work so far!

**Comment by leonvsc** [comment]
Hey @sebastiaanspeck!

Thanks for the invite! Yes, you can add me as collaborator of the project. The codeowners file is also fine for me.

Thanks!

**Comment by kbdharun** [comment]
Congratulations @leanvsc, I have sent an invitation. Feel free to close this issue with a PR.
