### ISSUE TITLE
Add top CLI tools from "Who needs a GUI?" article

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1162]
@BryanLunduke's "[Who needs a GUI? How to live in a Linux terminal.](http://www.networkworld.com/article/3091139/linux/who-needs-a-gui-how-to-live-in-a-linux-terminal.html)" presents a list of the best CLI tools after attempting to go GUI-less for 30 days. These are probably good candidates for us to cover.

- [x] [mutt](https://en.wikipedia.org/wiki/Mutt_(email_client)) ([common](../blob/master/pages/common/mutt.md) / [linux](../blob/master/pages/linux/mutt.md))
- [x] [notmuch](https://notmuchmail.org/manpages/) ([common](../blob/master/pages/common/notmuch.md) / [linux](../blob/master/pages/linux/notmuch.md))
- [x] [alpine](https://www.washington.edu/alpine/mans.html) ([common](../blob/master/pages/common/alpine.md) / [linux](../blob/master/pages/linux/alpine.md))
- [x] [w3m](https://en.wikipedia.org/wiki/W3m) ([common](../blob/master/pages/common/w3m.md))
- [x] [nano](https://en.wikipedia.org/wiki/GNU_nano) ([common](../blob/master/pages/common/nano.md))
- [x] [wordgrinder](http://cowlark.com/wordgrinder/index.html) ([common](../blob/master/pages/common/wordgrinder.md) / [linux](../blob/master/pages/linux/wordgrinder.md))
- [x] [cmus](https://en.wikipedia.org/wiki/Cmus) ([common](../blob/master/pages/common/cmus.md) / [linux](../blob/master/pages/linux/cmus.md))
- [ ] [finch](https://developer.pidgin.im/wiki/Using%20Finch) ([common](../blob/master/pages/common/finch.md) / [linux](../blob/master/pages/linux/finch.md))
  - [Guide to Using Finch - Terminal-Based Chat Client](https://tuxarena.blogspot.com/2010/09/guide-to-using-finch-terminal-based.html)
  - [Finch - Howto use Pidgin via Terminal Console](https://coderstalk.blogspot.com/2008/09/finch-howto-use-pidgin-via-terminal.html)
- [x] [hangups](https://github.com/tdryer/hangups) ([common](../blob/master/pages/common/hangups.md) / [linux](../blob/master/pages/linux/hangups.md))
- [x] [rainbowstream](http://rainbowstream.readthedocs.io/en/latest/#usage) ([common](../blob/master/pages/common/rainbowstream.md) / [linux](../blob/master/pages/linux/rainbowstream.md))
- [x] [rtv](https://github.com/michael-lazar/rtv) ([common](../blob/master/pages/common/rtv.md) / [linux](../blob/master/pages/linux/rtv.md))
- [x] [htop](http://hisham.hm/htop/) ([linux](../blob/master/pages/linux/htop.md))
- [x] [mc](https://en.wikipedia.org/wiki/Midnight_Commander) ([common](../blob/master/pages/common/mc.md) / [linux](../blob/master/pages/linux/mc.md))
- [x] [tmux](https://tmux.github.io/) ([common](../blob/master/pages/common/tmux.md))
- [x] [screen](https://en.wikipedia.org/wiki/GNU_Screen) ([common](../blob/master/pages/common/screen.md))
- [x] [tpp](http://www.ngolde.de/tpp.html) ([common](../blob/master/pages/common/tpp.md) / [linux](../blob/master/pages/linux/tpp.md))

Most of these are interactive tools, which will present a challenge for documenting them in the tldr format, but if we can do vim and nano, we can do these as well :)

**Comment by rudinskizvonimir** [comment]
Hi, I've started to document some of these.
Should be done very soon.

**Comment by sbrl** [comment]
Update: `mc` and `wordgrinder` are now done, and there's a PR for `mutt` on the way :D

**Comment by luk3yx** [comment]
@waldyrious `mutt` and `tpp` seem to exist. Will this be updated?

**Comment by agnivade** [comment]
Thanks, updated.

**Comment by waldyrious** [comment]
Only 3 to go (`notmuch`, `finch` and `rainbowstream`)! Anyone up for checking the last boxes? :grinning:

**Comment by sbrl** [comment]
Just 1 left - so close!

**Comment by waldyrious** [comment]
@sbrl I've edited the opening comment to add two links to guides to using ´finch` that seem easier to parse than their official documentation — hopefully that helps whoever wants to work on that page!

**Comment by bl-ue** [comment]
Great jobs guys!

Thank you @qhyun2 for finishing this up!
