### ISSUE TITLE
[Archive] Reorganise entries and add short descriptions to Projects; remove stale and stalebot-ignore labels

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#11643]
Today, I have updated our tracking projects and reorganized moving completed entries to Done. 

## Changes

- Reordered entries in projects.
-  Added descriptions to each column/section in projects.
- Added short descriptions (for a quick summary view of the projects on the Org wide page https://github.com/orgs/tldr-pages/projects).
-  Minor fixes to the README descriptions for projects.
- Added a new "Not Planned" section to archive unmerged PRs/issues dealing with architecture, smooth contribution experience, and multilingual support projects.
- Removed `stale` and `stalebot-ignore` labels as we no longer use the stalebot.

**Edit.** Updated and added label descriptions too for all labels. Feel free to check it out at https://github.com/tldr-pages/tldr/labels.

### Short descriptions

> I took the screenshot a bit late after adding short descriptions to the two projects (before this there weren't any short descriptions).

![image](https://github.com/tldr-pages/tldr/assets/26346867/1284102c-98fa-4486-a70b-361468839d15)
![image](https://github.com/tldr-pages/tldr/assets/26346867/e5498969-9772-44e8-a29b-4d5b862b6bed)

### Field labels

![image](https://github.com/tldr-pages/tldr/assets/26346867/59983443-e925-48d8-af6d-103b168e2572)

**Comment by sbrl** [comment]
This issue should remain open for a week to enable discussion. These changes seem generally good, but I would like to ask about a specific point:

> Removed stale and stalebot-ignore labels as we no longer use the stalebot

Any reasoning for this?

**Comment by kbdharun** [comment]
> Removed stale and stalebot-ignore labels as we no longer use the stalebot

> Any reasoning for this?

We decided to remove stalebot a few months ago after discussions in the chatroom and here mainly due to:

1. It's activity taking up a majority of space in a PR/issue.
2. It closing legitimate issues/PRs that got lost in our notification abyss and we forgot to add "stalebot ignore" label.

We had multiple people expressing their concern/frustration regarding this, while this issue made a relatively minor impact here the same can't be said about tldr-lint where we don't actively check issues and maybe crucial ones were closed (ofcourse we could reopen them, but at this point having stale bot just became a burden and we instead decided to manually handle the issues).

Feel free to checkout https://github.com/tldr-pages/tldr-lint/issues/249

**Comment by sbrl** [comment]
Ah okay. That seems reasonable. In this case we just need to keep on top of old PRs them to avoid some lingering from authors who unfortunately abandon them after making them and never respond to suggested changes.

**Comment by kbdharun** [comment]
> Ah okay. That seems reasonable. In this case we just need to keep on top of old PRs them to avoid some lingering from authors who unfortunately abandon them after making them and never respond to suggested changes.

Yeah, that's why we have the one-month before takeover clause in [maintianer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md). 

If the person hasn't allowed maintainers to push to the PRs branch then we can create a new PR with the changes (having the commit author's credits intact). In case, they haven't signed the CLA, we have no choice but to abandon it for non-trivial PRs in past we have created/merged new PRs with no credits to the original creator.
