### ISSUE TITLE
page request: couchdb

### ISSUE THREAD

**Issue by dikarel** [tldr-pages/tldr#1175]
This is the command that runs the server

https://linux.die.net/man/1/couchdb

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of CONTRIBUTING.md, which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if yo need any assistance, just ask :-)

**Comment by agnivade** [comment]
Hey @sbrl - we have a lot of issues like this. They aren't really "issues" as such. More like starter tasks if someone wants to take up something.

IIRC, @dikarel had opened these to keep a note of his own TODO page list; and as well as for someone else to pick them up as and when they feel like.

Lets keep this one open :)

**Comment by sbrl** [comment]
@agnivade I closed this? Oops! I didn't mean to do that :P

**Comment by agnivade** [comment]
Haha ok. :)

**Comment by waldyrious** [comment]
You're not the first one to click the wrong button, @sbrl :) It would really help if the "close issue" button was properly marked as a destructive action. This sort of issue has happened before in other places, and Github did eventually solve it: https://webapps.stackexchange.com/questions/36816/how-to-delete-a-github-wiki-page

**Comment by lamar-frankie** [comment]
If this is still needed. I can work on it.

**Comment by sbrl** [comment]
@lamar-frankie Doesn't look like anyone else has taken it! We're always interested in documenting new commands, so go ahead :smiley_cat:

**Comment by lamar-frankie** [comment]
I'll get on it. Thanks!
