### ISSUE TITLE
page request: mysqld

### ISSUE THREAD

**Issue by dikarel** [tldr-pages/tldr#1177]
This is the command that runs the server

https://linux.die.net/man/1/mysqld

**Comment by morrme** [comment]
I would like to help with this one.  I do not see a PR, assignment or any other activity on it. Is there a process for "claiming" issues?

**Comment by agnivade** [comment]
> I would like to help with this one.

Yes please !

>  Is there a process for "claiming" issues?

Just send a PR referring this issue in it. And please take a look at CONTRIBUTING.md.

**Comment by russellg** [comment]
I've had a go at this. Let me know if I can improve it in any way.

**Comment by bl-ue** [comment]
🎉
