### ISSUE TITLE
page request: foreman

### ISSUE THREAD

**Issue by dikarel** [tldr-pages/tldr#1180]
A tool to manage running multiple processes

https://ddollar.github.io/foreman

**Comment by lamar-frankie** [comment]
Hi, @waldyrious I'd like to work on this.

**Comment by russsaidwords** [comment]
This was handled in #1526.

**Comment by sbrl** [comment]
Good spot - thanks @russsaidwords! If the PR doesn't have a `closes #....` in it, I usually forget to close the associated issue :P
