### ISSUE TITLE
OpenPrinting CUPS vs. Apple CUPS

### ISSUE THREAD

**Issue by vitorhcl** [tldr-pages/tldr#11845]
According to the Apple CUPS GitHub repo:

> Note: Apple CUPS is the version of CUPS that is shipped with macOS and iOS. For the current version of CUPS that is used on other operating systems, see https://openprinting.github.io/cups for details.

Considering that CUPS is in the common directory, I think we should use the OpenPrinting documentation as a reference instead of Apple CUPS one and replace the links accordingly, using https://openprinting.github.io/cups/ instead of cups.org.

**Comment by isaacvicente** [comment]
Sounds good to me as well.
