### ISSUE TITLE
NPM Installation Problem

### ISSUE THREAD

**Issue by MrOggy85** [tldr-pages/tldr#1190]
Hi, 

I really enjoy this program, but I found an issue when I'm installing it thorugh npm on Linux Mint:
`Error: EACCES: permission denied, mkdir '/home/oskar/.tldr`

My machine: 
`uname -a Linux oskar-HP-EliteBook-820-G1 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
`npm -v 3.10.8`

I install with the command: `sudo npm i tldr -g`
I need to use `sudo` when installing globally cause my user doesn't have access to `/usr/lib/node_modules`

To go around this problem I need to:
1. `mkdir /home/oskar/.tldr`
2. `mkdir /home/oskar/cache`
3.`touch /home/oskar/cache/LICENCE.md`
4. `chmod 777 /home/oskar/cache`

if I don't do step 4 I get the following error:
```
fs.js:1089
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: EACCES: permission denied, unlink '/home/oskar/.tldr/cache/LICENSE.md'
```

**Comment by agnivade** [comment]
> I need to use sudo when installing globally cause my user doesn't have access to /usr/lib/node_modules

You can change the folder permissions. Npm recommends it to have non-root permissions. https://docs.npmjs.com/getting-started/fixing-npm-permissions

Anyways, if you have to use sudo, use this command -
`sudo npm install -g tldr --user=$(whoami)`.

We are working on a proper fix for this.

**Comment by C0rn3j** [comment]
>Anyways, if you have to use sudo, use this command -
>sudo npm install -g tldr --user=$(whoami).

This doesn't work for me on Arch Linux

nodejs 7.2.1-1
npm 4.0.3-1


>sudo npm install -g tldr --user=c0rn3j   
>Error: EACCES: permission denied, mkdir '/root/.tldr/cache'

It still apparently tries to install as root.

**Comment by agnivade** [comment]
The settings of the user `c0rn3j` must be a bit messed up. It tries to install the cache in `/root/.tldr`, which the user doesn't have permission to. If its a normal user, it should try to put it in `/home/c0rn3j/.tldr`.

>  Which also broke my system because it changed ownership of stuff in /usr/bin

Sorry about that :(. If you have followed the instructions properly in https://docs.npmjs.com/getting-started/fixing-npm-permissions and it still broke your system, you should raise an issue with npm.

**Comment by C0rn3j** [comment]
I'm pretty sure I missed the "WARNING:" there, so I'm at fault.

> If its a normal user

It is a normal user. Can I provide you with some info/logs that'd help you diagnose the issue?
I'm using Arch Linux.

in /etc/sudoers:
c0rn3j ALL=(ALL) ALL

**Comment by agnivade** [comment]
Since you have already fixed the issue, I would say there is not much use in looking into it further because we plan to make a proper fix for it, which will change the whole `--user` logic.
