### ISSUE TITLE
MAINTAINERS: add @isaacvicente as Org member

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#11918]
Hi, @isaacvicente! After joining as a collaborator in the repository, you have been regularly performing [maintenance tasks](https://github.com/tldr-pages/tldr/pulls?q=reviewed-by:isaacvicente).

Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public and (in case you don't already) start hanging out in our [Matrix chat room](https://matrix.to/#/#tldr-pages:matrix.org).
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/GOVERNANCE.md).

How does that sound? Are you up for it?

**Comment by isaacvicente** [comment]
Hi @kbdharun, thank you for the recommendation!! I'm very happy with it.

However I need to say that recently I contributed more often because I'm on a vacation from my university, so I got a little  extra time. As soon as I get back to studies, I cannot guarantee that I will be available for the project, as I'm on a half time work as well; of course that I would contribute anytime possible. That being said, if it's not a problem, sure, it would awesome to be a member. If that's a problem, I would be grateful just being a contributor.

Cheers.

**Comment by kbdharun** [comment]
> However I need to say that recently I contributed more often because I'm on a vacation from my university, so I got a little extra time. As soon as I get back to studies, I cannot guarantee that I will be available for the project, as I'm on a half time work as well; of course that I would contribute anytime possible. That being said, if it's not a problem, sure, it would awesome to be a member. If that's a problem, I would be grateful just being a contributor.

That's understandable, I am currently on vacation too once university starts I too won't have time to be as active as now (i.e. replying to issues/reviewing PRs in a few hours, I check back on PRs on evenings/weekends). That being said, feel free to contribute at your own pace (and whenever you are free). I will send an invite now (as usual you can close this PR with an issue).

**Comment by isaacvicente** [comment]
I accepted the invitation. Thanks!

**Comment by kbdharun** [comment]
Great, please update the same in `MAINTAINERS.md`.

**Comment by sbrl** [comment]
Welcome on board, @isaacvicente! Please can you:

1. Enable 2-factor authentication on your GitHub account
2. Join our Matrix chat as mentioned, if you haven't already (I can't find you in there, but it doesn't mean to say you don't exist!) <https://matrix.to/#/#tldr-pages:matrix.org>

Many thanks!

**Comment by kbdharun** [comment]
@sbrl in future should we make it mandatory for Org members to have 2FA enabled in their account?

**Comment by sbrl** [comment]
@kbdharun This may be worth doing - the additional security it provides is significant. Open an issue?
