### ISSUE TITLE
Add date

### ISSUE THREAD

**Issue by C0rn3j** [tldr-pages/tldr#1193]
Seems like it was added before and then mysteriously deleted.

https://github.com/tldr-pages/tldr/issues/15

**Comment by waldyrious** [comment]
Thanks for the concern, @C0rn3j. Actually, the `date` page was not deleted -- it was split into linux and osx versions in #1043.

**Comment by C0rn3j** [comment]
Oh, so you need to type linux/ or osx/ before it instead it tells you that the page does not exist..

Could this be changed to tell you that the command is actually there but you need to select which specific one you want?

**Comment by waldyrious** [comment]
That depends on the clients' implementations. They usually search in the current system's folder for a matching page, and only then look in the common folder. I'm not sure there's an easy way to make this work beyond the clients.

**Comment by C0rn3j** [comment]
I should have noted that I was talking about the web version.

**Comment by waldyrious** [comment]
Ah, that changes things :) That's @ostera's jurisdicion then. Could you open an issue at https://github.com/ostera/tldr.jsx? Apparently it's only considering pages under `common`, but since web pages can detect the OS of the client, it's conceivable that the same fallback logic used in the desktop clients could be applied to the web client as well.

**Comment by ostera** [comment]
It's on the roadmap! https://github.com/ostera/tldr.jsx/issues/70

**Comment by ostera** [comment]
@C0rn3j, just released this in v3.7.0 check it out: https://tldr.ostera.io/date :)

**Comment by ostera** [comment]
I am sorry I had to revert the change -- I found a bug that was pretty massive :/ making all commands fallback to the platform version of them, which of course failed for commands that didn't have a platform version.

I'll be addressing this in detail during the week.

**Comment by waldyrious** [comment]
@ostera you probably should reopen https://github.com/ostera/tldr.jsx/issues/70 then :)
