### ISSUE TITLE
Proposal: Use keith's export of Xcode's man pages in all builtin osx commands

### ISSUE THREAD

**Issue by vitorhcl** [tldr-pages/tldr#11963]
Website: https://keith.github.io/xcode-man-pages/
This can change in the future, but for now, it seems the best website for visualizing macOS documentation.

We can document this on the style guide.

**Comment by vitorhcl** [comment]
@sebastiaanspeck any opinion on this?

**Comment by kbdharun** [comment]
> Website: https://keith.github.io/xcode-man-pages/ This can change in the future, but for now, it seems the best website for visualizing macOS documentation.
> 
> We can document this on the style guide.

Agreed, we could document in the style guide as a default fallback for macOS (`osx`).

**Comment by pixelcmtd** [comment]
> Website: [keith.github.io/xcode-man-pages](https://keith.github.io/xcode-man-pages/) This can change in the future, but for now, it seems the best website for visualizing macOS documentation.
> 
> We can document this on the style guide.

Sounds like a great idea to me, too. I've used `keith.github.io` as a fallback for when `manpagez.com` (which had kind of been our go-to man page site for macOS) was too outdated (e.g. #8670, #9623, #9624, #9818, #10700), and it sounds like a good option to adopt it everywhere 😄
