### ISSUE TITLE
manned.org/*.posix vs pubs.opengroup.org

### ISSUE THREAD

**Issue by vitorhcl** [tldr-pages/tldr#11965]
In my opinion, we should use manned.org for POSIX utilities because:
- They are in the last version of the specification
- The link is shorter and easier to type and remember
- No need to update if a new version is released
- You can access the rest of manned.org website from there

Of course, we should document this on the style guide, no matter which one is the final decision.

**Comment by tricantivu** [comment]
Are there commands/utilities that are only documented for older specifications (e.g. POSIX.1-2008)?

**Comment by vitorhcl** [comment]
The first commit of manned.org's repo was in 2011, so I don't think so, but we can verify this.

**Comment by vitorhcl** [comment]
I've tested manned.org using a bash script and yes, all pages are up-to-date, so issue resolved :tada:
The script:
```bash
#!/bin/bash
commands_array=("alias" "ar" "at" "awk" "basename" "batch" "bc" "bg" "cal" "cat" "cd" "cflow" "chgrp" "chmod" "chown" "cksum" "cmp" "comm" "command" "compress" "cp" "crontab" "csplit" "ctags" "cut" "date" "dd" "df" "diff" "dirname" "du" "echo" "ed" "env" "ex" "expand" "expr" "false" "fc" "fg" "file" "find" "fold" "getconf" "getopts" "grep" "hash" "head" "iconv" "id" "ipcrm" "ipcs" "jobs" "join" "kill" "link" "ln" "locale" "localedef" "logger" "logname" "lp" "ls" "m4" "mailx" "make" "man" "mesg" "mkdir" "mkfifo" "more" "mv" "newgrp" "nice" "nl" "nm" "nohup" "od" "paste" "patch" "pathchk" "pax" "pr" "printf" "ps" "pwd" "read" "renice" "rm" "rmdir" "sact" "sccs" "sed" "sh" "sleep" "sort" "split" "strings" "strip" "stty" "tabs" "tail" "talk" "tee" "test" "time" "touch" "tput" "tr" "true" "tsort" "tty" "type" "ulimit" "umask" "unalias" "uname" "unexpand" "uniq" "unlink" "uucp" "uudecode" "uuencode" "uustat" "uux" "val" "vi" "wait" "wc" "what" "who" "write" "xargs" "yacc")

for command in "${commands_array[@]}"; do
    man_page_url="https://manned.org/${command}.1posix"
    echo "Testing ${man_page_url}"

    if curl -s --head "$man_page_url" | grep "HTTP/2 200" >/dev/null; then
        if curl -s "$man_page_url" | grep -q "IEEE/The Open Group                   2017"; then
            echo "$command: Found and is updated"
        else
            echo "$command: Found but not updated"
        fi
    else
        echo "$command: Not found"
    fi
done
```

**Comment by tricantivu** [comment]
> I've tested manned.org using a bash script and yes, all pages are up-to-date, so issue resolved :tada:
> 
> The script:
> 
> ```bash
> 
> #!/bin/bash
> 
> commands_array=("alias" "ar" "at" "awk" "basename" "batch" "bc" "bg" "cal" "cat" "cd" "cflow" "chgrp" "chmod" "chown" "cksum" "cmp" "comm" "command" "compress" "cp" "crontab" "csplit" "ctags" "cut" "date" "dd" "df" "diff" "dirname" "du" "echo" "ed" "env" "ex" "expand" "expr" "false" "fc" "fg" "file" "find" "fold" "getconf" "getopts" "grep" "hash" "head" "iconv" "id" "ipcrm" "ipcs" "jobs" "join" "kill" "link" "ln" "locale" "localedef" "logger" "logname" "lp" "ls" "m4" "mailx" "make" "man" "mesg" "mkdir" "mkfifo" "more" "mv" "newgrp" "nice" "nl" "nm" "nohup" "od" "paste" "patch" "pathchk" "pax" "pr" "printf" "ps" "pwd" "read" "renice" "rm" "rmdir" "sact" "sccs" "sed" "sh" "sleep" "sort" "split" "strings" "strip" "stty" "tabs" "tail" "talk" "tee" "test" "time" "touch" "tput" "tr" "true" "tsort" "tty" "type" "ulimit" "umask" "unalias" "uname" "unexpand" "uniq" "unlink" "uucp" "uudecode" "uuencode" "uustat" "uux" "val" "vi" "wait" "wc" "what" "who" "write" "xargs" "yacc")
> 
> 
> 
> for command in "${commands_array[@]}"; do
> 
>     man_page_url="https://manned.org/${command}.1posix"
> 
>     echo "Testing ${man_page_url}"
> 
> 
> 
>     if curl -s --head "$man_page_url" | grep "HTTP/2 200" >/dev/null; then
> 
>         if curl -s "$man_page_url" | grep -q "IEEE/The Open Group                   2017"; then
> 
>             echo "$command: Found and is updated"
> 
>         else
> 
>             echo "$command: Found but not updated"
> 
>         fi
> 
>     else
> 
>         echo "$command: Not found"
> 
>     fi
> 
> done
> 
> ```

That's quite a huge array! 😅
