### ISSUE TITLE
page request: gitrevisions

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1200]
This is just a manpage (see [man gitrevisions](https://git-scm.com/docs/gitrevisions)), not an actual command. Still, it might be useful to provide a summarized version that other git command pages can point to.

I'm particularly concerned about the confusion between `^` and `~`. The first one only makes sense for merge commits, but is often used to get the ancestor of a commit -- see [this page](http://www.paulboxley.com/blog/2011/06/git-caret-and-tilde) by @baxter for details. The mnemonic I use is:
- `HEAD~1` = parent, `HEAD~2` = grandparent (identify ancestors)
- `HEAD^1` = father, `HEAD^2` = mother (identify merge parents)

**Comment by agnivade** [comment]
Hmm .. I still feel that this doesn't need a tldr page. Somehow, it doesn't feel right. I have always imagined tldr pages to be a friendly alternative to man pages. Though sometimes, exceptions can be made. I feel that `gitrevisions` doesn't need to be a page.

**Comment by bl-ue** [comment]
I agree with @agnivade.  This is a very old issue&mdash;@waldyrious, do you mind if we close it?

**Comment by marchersimon** [comment]
Closing, since there hasn't been any response and we generally only document commands.
