### ISSUE TITLE
Organize style guide content

### ISSUE THREAD

**Issue by vitorhcl** [tldr-pages/tldr#12008]
It would be nice to split the content there in some sections and add a contents subtitle in the start.

Here is my proposal:
```md
## Contents

1. [General layout](#generallayout)
2. [General rules](#generalrules)
3. [Special pages](#specialpages)
4. [Heading](#heading)
5. [Example descriptions](#exdescriptions)
6. [Example commands](#excommands)
7. [Language-specific rules](#langrules)
```

**Comment by kbdharun** [comment]
Nice, the new proposed structure does indeed look clean, if possible can you start a discussion for this in the chatroom so the previous maintainers and others can chime in too actively.

**Comment by vitorhcl** [comment]
> Nice, the new proposed structure does indeed look clean, if possible can you start a discussion for this in the chatroom so the previous maintainers and others can chime in too actively.

Sorry, what is the chatroom? The Matrix room? Or GitHub Discussions?
