### ISSUE TITLE
Page request: `:`

### ISSUE THREAD

**Issue by mooreye** [tldr-pages/tldr#12070]
### Command description

The command `:` is a bash builtin equivalent to `true`. Its tldr page can just be copied over from `true`.

### Platform

Linux

**Comment by Magrid0** [comment]
i'll work on it

**Comment by mooreye** [comment]
Note: the `:` command is not a coreutil, it is a bash builtin.

https://github.com/tldr-pages/tldr/pull/12091/files#diff-e5914957fa6556926558ba3d8563ab6f0a1d4643b043939984c0ef430a06ceb3R5
