### ISSUE TITLE
MAINTAINERS: add @vitorhcl to Org

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#12094]
Hi, @vitorhcl! After joining as a collaborator in the repository, you have been regularly performing [maintenance tasks](https://github.com/tldr-pages/tldr/pulls?q=reviewed-by:vitorhcl).

Thank you for that!

According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public and (in case you don't already) start hanging out in our [Matrix chat room](https://matrix.to/#/#tldr-pages:matrix.org).

Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).

As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/GOVERNANCE.md).

How does that sound? Are you up for it?

**Comment by vitorhcl** [comment]
Thank you so much for the invitation! Sure, I would love to join the organization :smile:

**Comment by kbdharun** [comment]
Keep up the great work and congratulations, I have sent an invitation. Feel free to close this issue with a PR.

**Comment by kbdharun** [comment]
@vitorhcl Can you set your membership to public at https://github.com/orgs/tldr-pages/people and also update the MAINTAINERS.md file for the same?
