### ISSUE TITLE
Page modification request: act

### ISSUE THREAD

**Issue by iTrooz** [tldr-pages/tldr#12116]
### Command description

I think the following examples are wrong:
```
  - [l]ist the available actions:
    act -l
  - Run a specific [a]ction:
    act -a action_id
```

I think what tldr refers to as "actions" here are really "jobs", and the `-a` flag is for something else (simulated github user)

I would propose this:
```
  - [l]ist the available jobs/workflows:
    act -l
  - Run a specific [j]ob:
    act -j job_id
```

### Command details

act 0.2.57

### Documentation

act --help

### Platform

Linux

**Comment by vitorhcl** [comment]
Looks good to me, that's what the documentation says. Feel free to open a PR :slightly_smiling_face:

**Comment by iTrooz** [comment]
Thanks ! But I have one issue

How should I deal with existing act.md files in other languages ? I need to change the word "action" to "job", but I don't know every language in there

**Comment by kbdharun** [comment]
> Thanks ! But I have one issue
> 
> How should I deal with existing act.md files in other languages ? I need to change the word "action" to "job", but I don't know every language in there

You could just update the English page and leave the translation pages as it is for native speakers to update it later.
