### ISSUE TITLE
Add pygmentize

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1213]
http://pygments.org/docs/cmdline/

**Comment by sbrl** [comment]
See #1355 - I believe this page has been added!

**Comment by waldyrious** [comment]
Actually, #1333, whose title doesn't even mention pygmentize (it was sneakily added midway through the PR :P)

**Comment by sbrl** [comment]
Oh right! I even contributed to the discussion on that one! That was sneaky :P
