### ISSUE TITLE
Proposal: enforce 2FA requirement for Org members and collaborators

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#12209]
**Continuing https://github.com/tldr-pages/tldr/issues/11918#issuecomment-1930727032.** (cc @sbrl)

I want to propose enabling two-factor authentication (2FA) at an organisational level for all members and outside collaborators to have better operational security (OPSEC) at tldr. This would prevent unauthorized access to the repositories and clients at Org in case the maintainer's credentials are leaked/their device is compromised.

Since we are a decentralized organization, it is essential to implement basic OPSEC practices like 2FA, private vulnerability reporting, etc. We already have some practices in place, 2FA would be the recent addition to it, GitHub is actively requiring accounts to enable 2FA, so you would want to enable it nonetheless.

The following users don't have 2FA enabled for your account, I would like to request you guys to enable it soon (to prevent being automatically removed when enabling the [setting](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication) in future).

**_Org Members:_** ~@isaacvicente~ (Enabled 2FA)
**_Outside Collaborators:_**
- ~@CairnThePerson~ (Enabled 2FA)
- ~@Managor~ (Enabled 2FA)
- ~@MrMw3~ (Enabled 2FA)
- ~@patricedenis~ (Enabled 2FA)
- @quantumflo
- ~@rubenvereecken~ requested to be removed from the tldr-pages organisation

---

You can enable two-factor authentication here -> https://github.com/settings/security

---

## Reference links/settings

https://github.com/organizations/tldr-pages/settings/security

![image](https://github.com/tldr-pages/tldr/assets/26346867/bc19ec03-3da6-460c-9dea-f24422b74374)

1. https://github.com/orgs/tldr-pages/outside-collaborators?query=two-factor%3Adisabled
2. https://github.com/orgs/tldr-pages/people?query=two-factor%3Adisabled

**Comment by Managor** [comment]
Enabled.

**Comment by sbrl** [comment]
I definitely support this, as soon as everyone has it enabled. We haven't had a breach (that I know of) yet, but we can never be too careful.

We could consider what to do for people who don't reply on a case-by-case basis e.g. after 1 month.

**Comment by patricedenis** [comment]
Hi every one.
I haven't got much time to contribute right now but I enabled the functionality to stay with you guys.
Cheers !

**Comment by rubenvereecken** [comment]
Feel free to drop me :)

**Comment by MrMw3** [comment]
Enabled.

**Comment by kbdharun** [comment]
**Update:** It's been a month and only 1 more person is yet to respond, I will try contacting @isaacvicente regarding this through other channels, we can enable this setting after a few more days.

**Comment by isaacvicente** [comment]
I'm sorry, I had some exams in my college this week, so I haven't checked anything from Github. I've enabled 2FA now.

**Comment by kbdharun** [comment]
> We could consider what to do for people who don't reply on a case-by-case basis e.g. after 1 month.

@sbrl only one more person (@quantumflo) is yet to respond (I sent an email and tried contacting them through other means a few days ago but to no avail). IG we can enable this setting for now (and update MAINTAINERS.md), we can reinvite them back when they respond in future. What do you think about this?

**Comment by MrMw3** [comment]
@kbdharun
I agree with you.

**Comment by kbdharun** [comment]
Almost enabled the setting where I noticed a new name which didn't appear in both the lists (under the query but just normally), no idea why. @Geipro (previously @Proscream) can you enable 2FA for your account?

![image](https://github.com/tldr-pages/tldr/assets/26346867/c6dbc064-6b2d-4f2f-9f7d-ae63eb214915)

Will wait till this weekend to enable this fully and update the `MAINTAINERS.md` file.

**Comment by kbdharun** [comment]
**Update**: I have enabled the setting now and the 3 collaborators have been removed (will update `MAINTAINERS.md` to reflect the same and close this issue).
