### ISSUE TITLE
Improve brew.md

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1235]
From [this comment](https://github.com/tldr-pages/tldr/pull/1229#issuecomment-270600770) by @MarloweW:

> Maybe we could add `brew info -f {{formula}}`, it's useful to find out files contained in a formula.

We should also revise the `list` example, as discussed [here](https://github.com/tldr-pages/tldr/pull/1229#discussion_r94899548), to get rid of the square brackets, which can be confusing. Ideally that could be done by rewording the description rather than splitting the example in two, since we're already at 6 examples and with the `info -f` we'd reach 7.

**Comment by MarloweW** [comment]
Since I commented that, I'll fire a PR for this.
