### ISSUE TITLE
add -pie example to perl page

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1239]
Something like this:

```
- Replace all occurrences of a string in a file, overwriting the file (i.e. in-place):

`perl -p -i -e 's/{{find}}/{{replace}}/g' {{filename}}`

- Same, saving the previous file to an extension:

`perl -p -i'.old' -e 's/{{find}}/{{replace}}/g' {{filename}}`
```

Inspired in http://www.itfromallangles.com/2012/05/bash-a-better-way-to-sed/

More info:
- [http://perlpie.com](https://web.archive.org/web/20161230202527id_/http://www.perlpie.com/)
- http://explainshell.com/explain?cmd=perl+-p
    > **perl -p**  causes Perl to assume the following loop around your program,
    >         which makes it iterate over filename arguments somewhat like sed:
    >```
    >LINE:
    >   while (<>) {
    >       ...             # your program goes here
    >   } continue {
    >       print or die "-p destination: $!\n";
    >   }
    >```

**Comment by waldyrious** [comment]
Maybe add the `-0` option to the second example, for multi-line search-replace.

**Comment by morrme** [comment]
Is this issue one that you'd just like your suggestions added and formatted onto the correct page?

**Comment by agnivade** [comment]
Yes, its a suggestion to improve the page. Anyone is free to take this up and send a PR.

**Comment by sbrl** [comment]
Since the attached PR has been merged, can we close this issue?

**Comment by agnivade** [comment]
Yes !

(Ideally, the PR should have the word "Closes #<issue_no>" which auto-closes the issue. In this case, it must have missed out)

**Comment by waldyrious** [comment]
Yeah, it was titled "per issue #1239", which understandably can't be automatically assumed to mean it will close the issue.

**Comment by waldyrious** [comment]
I'm planning to add the `-0` example mentioned above. Do you guys have opinions about whether we could remove one of the existing examples on [the page](https://github.com/tldr-pages/tldr/blob/master/pages/common/perl.md)? I was thinking either the `-c` or the `-d` examples -- any thoughts, @morrme, @agnivade, @assemusr, @sbrl?

**Comment by agnivade** [comment]
I vote for `-d`.

**Comment by morrme** [comment]
`-c` and `-d` are really useful.  a new example would get the page to 8, right at the example limit, but i'd actually vote for `-M` if we *had* to remove one.

**Comment by waldyrious** [comment]
I would rather not push the page to the max limit unless absolutely necessary. I'm fine with removing the `-M` example. If there are no objections, that will be my proposal in a upcoming PR.

**Comment by waldyrious** [comment]
For future reference: I considered using 777<sub>8</sub> as a record separator (i.e. `perl -0 777... `) rather than -0, which defaults to NUL (000<sub>8</sub>), for correctness.

This is [recommended](http://perldoc.perl.org/perlrun.html#Command-Switches) because if the file does contain characters with octal value equal to the parameter passed to (or implied by) the -0 option, these characters will be treated as line breaks. The exception is values that exceed 377<sub>8</sub> (i.e. 255), which won't be matched to characters on the file. 777 is the preferred convention within that range, as the highest value that keeps to 3 octal digits.

However, considering that (1) this nuanced behavior is hard to convey succinctly; (2) such cases (of text files with NUL characters) would be rare; and (3) tldr-pages' focus is on simplicity and common use cases; I believe that sticking to the simple -0 to emulate such a "slurp" mode is preferable.
