### ISSUE TITLE
Add wodim

### ISSUE THREAD

**Issue by hillam** [tldr-pages/tldr#1253]
I've been working on an application that uses this cdrom burning command. There are a lot of options but the man page is very vague/unclear about a lot of things.

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
