### ISSUE TITLE
How to get colors?

### ISSUE THREAD

**Issue by pepa65** [tldr-pages/tldr#1262]
I installed by: `sudo npm install -g tldr`
But it's only black & white. How can I get colors??

**Comment by agnivade** [comment]
Please have a look at this- https://github.com/tldr-pages/tldr-node-client#configuration

**Comment by waldyrious** [comment]
The instructions linked by @agnivade should solve this issue, but please confirm if not and we'll investigate further.

**Comment by pepa65** [comment]
Thanks for your help. Sorry for asking in the wrong place. So I downloaded `https://raw.githubusercontent.com/tldr-pages/tldr-node-client/master/config.json` to `$HOME/.tldrrc` but I still have no colors. I do have some italics (which I've never seen on my terminal) but I had those before copying as well. It doesn't seem to make any difference... Is there another client you can recommend?

**Comment by agnivade** [comment]
You have to change the "theme" variable to a different one to get colors. Choose from "base16", "ocean" or "matrix". All of this is already mentioned in the link. Let me know if its still confusing.

**Comment by pepa65** [comment]
OK, gotcha. This indeed works. I have now also installed the C++ client and the bash client, and I guess they all have different locations for their colors..? The C++ one worked out of the box with color.

**Comment by waldyrious** [comment]
Yes, each client has their own defaults (which is one of the reasons it makes sense to have multiple clients).

**Comment by pepa65** [comment]
I guess most of then build a pages cache in different locations as well.

**Comment by kaushalmodi** [comment]
@agnivade I stumbled across this because I am also not getting colors at all even when using the themes.

I tried these but nothing worked:

- `tldr -t ocean tar`
- Copied the example from [here](https://github.com/tldr-pages/tldr-node-client#configuration) and ran both `tldr tar` and `tldr -t ocean tar`

How can I help debug?

**Comment by agnivade** [comment]
hey @kaushalmodi - sorry this slipped under my radar.

Can you verify you are using latest tldr (`tldr --version`) ?

**Comment by kaushalmodi** [comment]
@agnivade Thanks for the follow up. At the time of posting that comment, I had freshly installed `tldr` using `npm install -g tldr`. But since it didn't work, I uninstalled it. Unfortunately I didn't record the version of `tldr` then.

I re-installed it and now it is working with `tldr -t ocean tar`. The version is *2.0.1*.

Thanks!

**Comment by agnivade** [comment]
Cool.

On a side note, you uninstalled a tool just because its theming didn't work ?

**Comment by kaushalmodi** [comment]
@agnivade 

> you uninstalled a tool just because its theming didn't work?

Nope, not *just* that; because I found an equivalent client that works great from within emacs. But not that your app works from the terminal, I'll keep it too :)

[1]: https://github.com/kuanyui/tldr.el

**Comment by lfsabcd7** [comment]
@agnivade @waldyrious  I also tried adding .tldrrc.json file in HOME directory in which below code is written. I'm on 3.3.2 version Please help me.
### {
    "pagesRepository": "https://github.com/tldr-pages/tldr",
    "repository": "https://tldr-pages.github.io/assets/tldr.zip",
    "themes": {
      "simple": {
        "commandName": "bold, underline",
        "mainDescription": "bold",
        "exampleDescription": "",
        "exampleCode": "",
        "exampleToken": "underline"
      },
      "base16": {
        "commandName": "bold",
        "mainDescription": "",
        "exampleDescription": "green",
        "exampleCode": "red",
        "exampleToken": "cyan"
      },
      "ocean": {
        "commandName": "bold, cyan",
        "mainDescription": "green",
        "exampleDescription": "green",
        "exampleCode": "cyan",
        "exampleToken": "dim"
      },
      "inverse": {
        "commandName": "bold, inverse",
        "mainDescription": "inverse",
        "exampleDescription": "black",
        "exampleCode": "inverse",
        "exampleToken": "green, bgBlack, inverse"
      },
      "myOwnCoolTheme": {
        "commandName": "bold, red",
        "mainDescription": "white",
        "exampleDescription": "underline, green",
        "exampleCode": "blue",
        "exampleToken": "inverse, magentaBright"
      },
      "matrix": {
        "commandName": "bold",
        "mainDescription": "underline",
        "exampleDescription": "green, bgBlack",
        "exampleCode": "green, bgBlack",
        "exampleToken": "green, bold, bgBlack"
      }
    },
    "theme": "myOwnCoolTheme"
  }

**Comment by lfsabcd7** [comment]
ISSUE resolved by below command i.e. providing user while install as mentioned in the installing section [https://www.npmjs.com/package/tldr/v/1.6.1](url)
`sudo npm install -g tldr --user=$root`

**Comment by vladimyr** [comment]
@lfsabcd7 Glad that you managed to fix it 👍 

Word of advice, do **not** install `node` and global npm packages using `sudo`, use [`nvm`](nvm.sh) or [`fnm`](https://github.com/Schniz/fnm) instead. It will save you a lot of headaches in the long run 😉

**Comment by lfsabcd7** [comment]
thanks @vladimyr

**Comment by T3sT3ro** [comment]
> @agnivade @waldyrious I also tried adding [(.tldrrc.json) or (.tldrrc.sh) or (.tldrrc) <--tried all of them] file in HOME directory in which below code is written. I'm on 3.3.2 version, v12.18.0 node version also I'm on fedora32 using Terminal(bash). I installed tldr using `sudo npm install -g tldr && tldr --update` Please help me. 5 Attachments added
> 
> ```
> ### {
>     "pagesRepository": "https://github.com/tldr-pages/tldr",
>     "repository": "https://tldr-pages.github.io/assets/tldr.zip",
>     "themes": {
>       "simple": {
>         "commandName": "bold, underline",
>         "mainDescription": "bold",
>         "exampleDescription": "",
>         "exampleCode": "",
>         "exampleToken": "underline"
>       },
>       "base16": {
>         "commandName": "bold",
>         "mainDescription": "",
>         "exampleDescription": "green",
>         "exampleCode": "red",
>         "exampleToken": "cyan"
>       },
>       "ocean": {
>         "commandName": "bold, cyan",
>         "mainDescription": "green",
>         "exampleDescription": "green",
>         "exampleCode": "cyan",
>         "exampleToken": "dim"
>       },
>       "inverse": {
>         "commandName": "bold, inverse",
>         "mainDescription": "inverse",
>         "exampleDescription": "black",
>         "exampleCode": "inverse",
>         "exampleToken": "green, bgBlack, inverse"
>       },
>       "myOwnCoolTheme": {
>         "commandName": "bold, red",
>         "mainDescription": "white",
>         "exampleDescription": "underline, green",
>         "exampleCode": "blue",
>         "exampleToken": "inverse, magentaBright"
>       },
>       "matrix": {
>         "commandName": "bold",
>         "mainDescription": "underline",
>         "exampleDescription": "green, bgBlack",
>         "exampleCode": "green, bgBlack",
>         "exampleToken": "green, bold, bgBlack"
>       }
>     },
>     "theme": "myOwnCoolTheme"
>   }
> ```
> 
> ![Screenshot from 2020-06-09 22-59-35](https://user-images.githubusercontent.com/57378900/84182147-8d978800-aaa7-11ea-9225-372c903bf41e.png) ![Screenshot from 2020-06-09 23-00-39](https://user-images.githubusercontent.com/57378900/84182154-8f614b80-aaa7-11ea-9c26-1c5abc93264d.png) ![Screenshot from 2020-06-09 23-01-01](https://user-images.githubusercontent.com/57378900/84182155-8ff9e200-aaa7-11ea-863f-d0fabcd111e7.png) ![Screenshot from 2020-06-09 23-01-44](https://user-images.githubusercontent.com/57378900/84182156-90927880-aaa7-11ea-912e-19287b920d28.png) ![Screenshot from 2020-06-09 23-03-49](https://user-images.githubusercontent.com/57378900/84182159-912b0f00-aaa7-11ea-9117-b03522b09549.png)

Sorry for necroing this, but I came here with the same problem. The problem is not with your installation, but with the content of your file - it starts with `###` which is not a valid JSON. The main problem is that... tldr doesn't tell you that -- it just silently fails. To fix this, some maintainer should handle the error message properly in the `lib/config.js` lines 16-22 (I can't pinpoint the location of the file in the repo):
```js
// ../lib/config.js in installed package
  try {
    customConfig = JSON.parse(fs.readFileSync(CUSTOM));
  } catch (ex) {
    /*eslint-disable */
    console.error(`error when parsing ${DEFAULT}\n`, ex); // <-- add this or similar
    /*eslint-enable */
  }
```

**Comment by marchersimon** [comment]
> I can't pinpoint the location of the file in the repo

@T3sT3ro it is in a different repo [here](https://github.com/tldr-pages/tldr-node-client/blob/master/lib/config.js). Would you like to open a PR to fix that there?

**Comment by T3sT3ro** [comment]
> > I can't pinpoint the location of the file in the repo
> 
> @T3sT3ro it is in a different repo [here](https://github.com/tldr-pages/tldr-node-client/blob/master/lib/config.js). Would you like to open a PR to fix that there?

On it: https://github.com/tldr-pages/tldr-node-client/issues/365

**Comment by Philip1435** [comment]
Hey. I have similar issues. I want to customize color, but I don't know which client am I on. I am using WSL, ubuntu specifically. and I am running Ubuntu terminal (bash), and I installed tldr through `sudo apt install tldr`. I tried https://github.com/tldr-pages/tldr-node-client#configuration but it didn't work, so I thought maybe it's because I am not on node cliend (?). 

Anybody know how to do this?

**Comment by pepa65** [comment]
@Philip1435 That is the Haskel client, no obvious way to modify the coloring (I'm sure it's possible, but not straighforward).
For this reason I made the bash client, it needs no compilation, you can just edit the file to change the colors to your liking.
