### ISSUE TITLE
Multi-line code does not render in CLI

### ISSUE THREAD

**Issue by abhijit-paul** [tldr-pages/tldr#1263]
Markdown supports multi-line code-snippet in the form of 
<pre>
```input {}
filter {}
output {}```
</pre>

Rendering this in CLI ends up showing only the first line
<img width="199" alt="multi-line markdown code" src="https://cloud.githubusercontent.com/assets/2553438/22550810/f143d1b4-e977-11e6-866b-b4fac6ae5583.png">

**Comment by waldyrious** [comment]
What's the client that you're using? I.e., how did you install it?

**Comment by agnivade** [comment]
As per our [format](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format) here, multi-line code snippets are not supported. All the pages have a specific format which is written in markdown. But the entire markdown spec is not supposed to work.

Now coming to the issue at hand, I believe you are talking about #1245. This is a problem with the linter actually. It is supposed to fail the changes. I will file a separate issue in https://github.com/tldr-pages/tldr-lint.

**Comment by waldyrious** [comment]
😖 Ugh, I misread the initial report. I assumed this was about a multi-line (main) description -- sorry about that.

**Comment by agnivade** [comment]
The linter actually gives error for scenarios like this. Maybe at that time, somehow it didnt work properly. Closing this until it happens again.
