### ISSUE TITLE
Page request: huggingface-cli

### ISSUE THREAD

**Issue by osbm** [tldr-pages/tldr#12807]
### Command description

This huggingface-cli command deals with the cache system of huggingface hub library. Deleting the cache, logging in, creating repositories on the huggingface hub. It is very useful to have a tldr page of its own.

### Command details

Huggingface hub utility command

### Documentation

https://hf.co/docs/huggingface_hub

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://github.com/huggingface/huggingface_hub/

**Comment by osbm** [comment]
@spageektti  
Hello, any updates?
 If you are not available, can i make a PR attempt?

Thanks. :)

**Comment by spageektti** [comment]
> If you are not available, can i make a PR attempt?

@osbm yes you can.
