### ISSUE TITLE
Truncating Repo

### ISSUE THREAD

**Issue by ARMummert** [tldr-pages/tldr#12820]
I noticed that the tldr repo is truncating a lot of files.  The files still exist when searching for a particular one.  The message I get is as follows:

"Sorry, we had to truncate this directory to 1,000 files. 2,107 entries were omitted from the list. Latest commit info may be omitted."

Have you considered sharding?

**Comment by spageektti** [comment]
GitHub automatically truncates file listings in directories that exceed 1,000 items.
Sharding is not an option, as it would change nothing but the display of files on GitHub, would introduce a lot of chaos and require changes to the tldr clients.

**Comment by ARMummert** [comment]
Thanks for letting me know.
