### ISSUE TITLE
Passing "*" as the only parameter to TLDR results in an AutoRelease Pool stats being sent to stdout

### ISSUE THREAD

**Issue by mbangert-smarsh** [tldr-pages/tldr#1293]
If you execute tldr with ***** as the only parameter AutoRelease Pool stats are printed in the terminal.  Note, if you perform this actions multiple times in quick succession you will end up seeing the expected message.  However, if you wait five minutes or more you will be able to reproduce the error.

OS Information
`ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32`

TLDR build info:
`tldr v1.3.0 (v1.3.0)`

### Steps To Reproduce
- Execute the following
`tldr *`

### Expected Results
- The following message is displayed
`This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr`

### Observed Results
- An error similar to the below is presented to the user
`objc[44497]: autorelease pool page 0x7f88d7807000 corrupted
  magic     0xa1a1a100 0x4f545541 0x454c4552 0x21455341
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x7fff951bd3c0
  should be 0x7fff951bd3c0`

**Comment by agnivade** [comment]
Which client is this ?

**Comment by pepa65** [comment]
This is a client issue, and should be reported to the client. It also depends on the shell used, and the shell settings.

**Comment by agnivade** [comment]
@mbangert-smarsh - I thought of doing the initial discussion here and then create an issue in the respective client's page, but I am going to close now this due to inactivity. Feel free to reopen anytime.
