### ISSUE TITLE
install should work

### ISSUE THREAD

**Issue by edouard-lopez** [tldr-pages/tldr#1314]
After installation the `tldr` command did not output anything. I had to run `tldr --update` which is nowhere to see in the `README.md`.

Could you add the `tldr --update` to the `postinstall` hook?

```
❯ sudo yarn global add tldr
yarn global v0.21.3
[1/4] Resolving packages...
warning tldr > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "tldr@2.0.0" with binaries:
      - tldr
Done in 5.78s.

~ 6s 
❯ tldr cd

~ 
❯ tldr man

~ 
❯ tldr tar

~ 
❯ which tldr 
/usr/bin/tldr

```

**Comment by agnivade** [comment]
Hey @edouard-lopez - couple of things -

- First of all, this is the tldr pages repo. Your issue actually belongs with the tldr-node client repo. :smile: 
- Secondly, you don't actually need to run `tldr --update` at all. There was an issue with running `tldr --update` as a postinstall [step](https://github.com/tldr-pages/tldr-node-client/pull/122). So we changed it to update every time when a page isn't found. As a result, after the first install, whenever you run any command, it will not find that and fetch the pages and show the result.

In your case, tldr seems to fail to do that. This I believe is a versioning issue. From your logs, I can see that its tldr@2.0.0. We need to debug this further.

Can you clear your current tldr installation, delete everything and freshly install it ? If that doesn't work out, we need to debug further.

**Comment by edouard-lopez** [comment]
@agnivade `2.0.0` is the latest available version from NPM.

**Comment by agnivade** [comment]
Yes, I know. Which is the reason why this shouldn't happen. But since it *is* happening, I guess there is some installation issue somewhere. That's why I had asked you to delete everything and  reinstall. And btw, I am assuming your node version is greater than 4.7 ?

**Comment by besseker** [comment]
Had 100% same issue. 
Had to use
`tldr --update`

My node version was 4.2.6.
After that updated to 7.8.0

If the node version is important, why won't mention it in README file?
As "tldr" is quite useful for newbies like me, I believe it is important to make installation clear and understandable for them.

**Comment by kwhsiung** [comment]
I have same issue.
But my node version is 6.10.0, which is greater than 4.7.

After I install tldr@1.7.1, the problem solved.

**Comment by edouard-lopez** [comment]
@agnivade the version I gave you was after the reinstall

```
$ sudo yarn global remove tldr
$ sudo yarn global add tldr
$ tldr --version
```

```
node --version                                                                                                                                                                              
v6.10.1  
```

**Comment by agnivade** [comment]
Sorry, my npm knowledge is still limited. I had mentioned in the package.json 
```json
"engines": {
  "node": ">=4.7"
}
```

I had assumed that on machines with node version less than 4.7, it will throw an error. I think on machines where tldr is already installed with node version less than 4.7, on updating the npm package, it goes till the version where lower node versions were allowed. And then it fails silently. I will test it out to confirm my theory.

I will update the README on this.

@kwhsiung - Can you mention the steps that you performed ? Are you installing tldr for the first time ? Or were you performing an upgrade ? Going back to tldr@1.7.1 is not ideal because you will miss out bug fixes which were done on later versions.

**Comment by kwhsiung** [comment]
@agnivade - I think I performing a upgrade by `$ npm install -g tldr,` because I uninstall tldr and install tldr@2.0.0 now, the problem solved too.

**Comment by agnivade** [comment]
@kwhsiung - Sorry, I am a bit confused. You initially said going back to 1.7.1 solved your problem. Now you are saying that after doing `npm install -g tldr` solved your problem. But `npm install -g tldr` is supposed to install 2.0.0. 

So what version do you have now ?

**Comment by kwhsiung** [comment]
@agnivade - Sorry about that I didn't explain very clearly. 

First of all, I am not installing tldr for the first time, but I forgot about it, so I am doing `$ npm install -g tldr` in the beginning before I want to using tldr, which I think I was performing an upgrade. At this time, I had the same issue here, so I delete everything of my tldr by `$ npm uninstall -g tldr` and freshly install tldr@1.7.1 by `$ npm install -g tldr@1.7.1`, then problem solved.

After doing my first comment on this issue, I was trying to delete everything of my tldr@1.7.1 by `$ npm uninstall -g tldr` and freshly install tldr@2.0.0 by `$ npm install -g tldr`, so my tldr version is 2.0.0 now, the problem doesn't exist anymore too.

So i think the point is that I am not delete everything of my tldr and freshly install it at very first.

**Comment by agnivade** [comment]
> I will test it out to confirm my theory.

Its not a node version issue. It seems to be a bug from the code. Filed https://github.com/tldr-pages/tldr-node-client/issues/143 for tracking.
