### ISSUE TITLE
Add losetup

### ISSUE THREAD

**Issue by dgadelha** [tldr-pages/tldr#1316]
[man page is available here](https://linux.die.net/man/8/losetup)

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if yo  need any assistance, just ask :-)

**Comment by sbrl** [comment]
Should we remove the `up for grabs` label now that someone's opened a PR, @waldyrious/

**Comment by waldyrious** [comment]
@sbrl uh, right, my bad.

Also, closing now that #1415 has been merged :)
