### ISSUE TITLE
Let's document: thefuck

### ISSUE THREAD

**Issue by kabrol98** [tldr-pages/tldr#13278]
### Command description

- zsh Setup
```bash
eval "$(thefuck --alias)"
```
- Basic overview
https://github.com/nvbn/thefuck?tab=readme-ov-file#how-it-works
- Create your own rules
https://github.com/nvbn/thefuck?tab=readme-ov-file#creating-your-own-rules

### Documentation

https://github.com/nvbn/thefuck/wiki

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://github.com/nvbn/thefuck

### Commands

https://github.com/nvbn/thefuck?tab=readme-ov-file#how-it-works

https://github.com/nvbn/thefuck?tab=readme-ov-file#creating-your-own-rules

**Comment by spageektti** [comment]
It is already documented. See https://github.com/tldr-pages/tldr/blob/main/pages%2Fcommon%2Ffuck.md.

**Comment by fazlearefin** [comment]
Closing issue as it is already documented.
