### ISSUE TITLE
Must manual run `--update` to make it work

### ISSUE THREAD

**Issue by xJeremie** [tldr-pages/tldr#1338]
I supposed after install `tldr` through `npm`, I just need type `tldr tar` and it will work. 

But I see nothing. After I try `tldr --help` and know about `tldr --update`. Tried it and worked as expect.

I didn't know it a bug or feature?

**Comment by agnivade** [comment]
What's your tldr version ?

**Comment by agnivade** [comment]
Filed https://github.com/tldr-pages/tldr-node-client/issues/143 for tracking.
