### ISSUE TITLE
Proposal: metadata files

### ISSUE THREAD

**Issue by spageektti** [tldr-pages/tldr#13466]
I was thinking about adding separate metadata file for pages some time ago, but now we have some real use case.

> That would also be nice if it was user configurable which one it showed.

Yes, that would be cool. I think this and some other cool features could be implemented by having a .json or some other kind of additional file for each page, so this would break existing clients but will add extra features.

something like:
```json
"commands": {
  "0": {
    "short": "git add -A",
    "long": "git add --all"
  },
  "1": {
    "short": "git add .",
    "long": "git add ."
  },
}

```

If someone is interested in discussing this idea I will open a separate issue about this.

_Originally posted by @spageektti in https://github.com/tldr-pages/tldr/pull/13441#discussion_r1720844599_

**Comment by jxu** [comment]
What I worry about is that this reduces the simplicity of just having one markdown page per command. I'm not opposed but if it is additional then there will need to be processes to keep this file in sync with the markdown.

**Comment by spageektti** [comment]
The file could be optional, and only info that cannot be stored in markdown could be stored here, like the long/short options case.

**Comment by spageektti** [comment]
> Can we do it smarter? If the page has `command {{--long|-short}}` and the user has configured that he wants to see the long options, it will show `command --long`. I do not know how this may impact performance, but it is better than having a JSON per page 

Yes, it would be better, but clients that won't implement it will show both in a way that isn't pasteable. This doesn't matter for me, but there are people for which that is important.

**Comment by spageektti** [comment]
There are also other uses of JSON, such as help and version commands defined in metadata files, so they don't take the space for other commands in markdown files.

But yeah, the advantages of using JSON are not as great as I thought, and it's fine for me to implement the @sebastiaanspeck idea instead.

**Comment by kbdharun** [comment]
Hi, I think having a separate JSON file wouldn't be ideal for options. @sebastiaanspeck's suggestion can be configurable in clients so that the short or long option can alone be displayed depending on the user's preference (but implementing it would lead to a few instances with conflicting syntax).

> Yes, it would be better, but clients that won't implement it will show both in a way that isn't pasteable. This doesn't matter for me, but there are people for which that is important.

We currently don't aim for the pastability of a command but instead of understandability, there are a few unmaintained old clients that allow running tldr commands from examples directly and user input is taken for placeholders but those clients haven't kept up with our changing syntax so their working may be inconsistent.

**Comment by jxu** [comment]
I support the {{--long|-short}} syntax. Anything else is too much complexity for little gain.

**Comment by fazlearefin** [comment]
Just want to reiterate what @jxu said. Using metadata files is a nice idea but this maye break all clients, including external unofficial clients like **tealdeer**. There is also overhead of maintaining additional files.

**Comment by spageektti** [comment]
> Using metadata files is a nice idea but this may break all clients, including external unofficial clients like **tealdeer**.

Not breaking clients, because the metadata files should be optional, and everything should be stored in markdown as is now.

**Comment by spageektti** [comment]
I am closing this issue as the metadata doesnt provide as many advantages, and there are lot of downsides.

**Comment by Managor** [comment]
I think the best way to implement this would be to create an offshoot project that has a new format, translate all the pages to the new format and then eventually retire the old project. That way there would be no breaking changes to current clients.
