### ISSUE TITLE
tldr --update fails after install via `yarn add`

### ISSUE THREAD

**Issue by jonschoning** [tldr-pages/tldr#1348]
```
$ yarn add tldr
$ tldr --update
Updating...
undefined
```

https://gist.github.com/jonschoning/3e65ee7311fa55d8cc8d4287ff5707bf

**Comment by agnivade** [comment]
I am unable to repro this. Also, actually you dont need to manually run `--update`, tldr will auto-update when it fails to find a command. 

Can you try something like this `tldr sshblabla` ?

**Comment by jonschoning** [comment]
(Ubuntu 16.10)
```
jon at kestrel in ~
[1] $ tldr sshblabla                                                                          ✘
Page not found. Updating cache ..
undefined

**Comment by waldyrious** [comment]
@agnivade is this related to https://github.com/tldr-pages/tldr-node-client/issues/143?

**Comment by agnivade** [comment]
No, that is not the case. Here, it atleast enters the cache updating logic. But then, somehow the response it gets is `undefined`. I have not been able to repro it though.

**Comment by jonschoning** [comment]
this appears to have been a permsissions issue on `~/.tldr` which i found by printing out the `err` object from `fs.copy(tempFolder, CACHE_FOLDER, {clobber: true}, (err) => { if (err) { return done(err); }`
was confusing because it repored undefined instead of showing the permission error on the terminal

**Comment by agnivade** [comment]
wow .. interesting. This used to be a problem on old versions of tldr where we used to populate the cache as a postinstall step. As a result, the cache folder used to have root permissions.

I am assuming you had an older installation of tldr, and then upgraded to this.

I think a `sudo chown -R jon:jon ~/.tldr` should solve the issue.

I will fix the error reporting issue from my side.

**Comment by agnivade** [comment]
Hi @jonschoning - Did the chown fix solve your issue ?

**Comment by jonschoning** [comment]
chown prevented the error, but i had to debug the source to even figure out what the error was

**Comment by agnivade** [comment]
Thanks. Yes, I have fixed that in the [code](https://github.com/tldr-pages/tldr-node-client/pull/146) now.
