### ISSUE TITLE
Urgent! CLA Page Not Responding

### ISSUE THREAD

**Issue by stanleyogada** [tldr-pages/tldr#13611]
## I need help signing the CLA

I am getting this blank page

![image](https://github.com/user-attachments/assets/7b13a398-85f6-48a4-bf0c-0aa33c5f11c2)

**Comment by stanleyogada** [comment]
Please I seek help signing the CLA agreement. This page (https://cla-assistant.io/tldr-pages/tldr) under the Licencing section of the CONTRIBUTE.md seems broken.

Or is there a new page for signing the CLA?

![image](https://github.com/user-attachments/assets/938cbceb-2318-4332-a3bd-69c6705c524b)

**Comment by kbdharun** [comment]
A note for people encountering this blank page in the CLA Assistant platform in future. I would suggest hard refreshing your browser cache with Ctrl + F5 shortcut or else check https://github.com/cla-assistant/cla-assistant/issues to see if others are experiencing the same issue, if that's the case then notify our maintainers regarding the same.
