### ISSUE TITLE
Proposal: Remove `www` from links

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#13633]
#13629 triggered me to search for the different link-formats:

> [!NOTE] 
> I only searched `pages/` to remove translation-pages which include the same link

- `https://www.`: [576](https://github.com/search?q=repo%3Atldr-pages%2Ftldr+%22More+information%3A+%3Chttps%3A%2F%2Fwww%22+path%3Apages%2F&type=code).
- `http://www.`: [28](https://github.com/search?q=repo%3Atldr-pages%2Ftldr+%22More+information%3A+%3Chttp%3A%2F%2Fwww%22+path%3Apages%2F&type=code)
- `http://`: [117](https://github.com/search?q=repo%3Atldr-pages%2Ftldr+%22More+information%3A+%3Chttp%3A%2F%2F%22+path%3Apages%2F&type=code), side-note: this of course includes the 30 from the second search
- `https://`: [4.7k](https://github.com/search?q=repo%3Atldr-pages%2Ftldr+%22More+information%3A+%3Chttps%3A%2F%2F%22+path%3Apages%2F&type=code), side-note: this of course includes the 576 from the first search

IMO the best option is `https://`, before making the huge change, I want to use this issue to see what others think about this. As you can see, `https://` is the most common format.

**Comment by spageektti** [comment]
We can remove www, but we should not automatically add `s` to all `http` sites, as they may not support https. We should check the http sites manually.

**Comment by gutjuri** [comment]
> We can remove www, but we should not automatically add `s` to all `http` sites, as they may not support https. We should check the http sites manually.

There are pages where `www.example.org` is different from `example.org` -> We also shouldn't remove the `www` automatically.

**Comment by sbrl** [comment]
Upgrading links to HTTPS from HTTP is a great idea, so long as they are checked to make sure they resolve. Makes our links on the whole more secure!

Removing `www.` is more problematic because as @gutjuri suggests some sites may be different without `www.`, but manually checking them when we come across them would be cool!
