### ISSUE TITLE
MAINTAINERS: add @LiLittleCat as collaborator

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#13780]
Hi, @LiLittleCat! You seem to be enjoying contributing to the tldr-pages project.
You now have had over more than five distinct pull requests [merged](https://github.com/tldr-pages/tldr/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3ALiLittleCat+is%3Amerged)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?  

Either way, thanks for all your work so far! 

> [!NOTE]
> It is required to have [two-factor authentication](https://github.com/settings/security) (2FA) enabled for your GitHub account to be added as a collaborator to the tldr-pages/tldr repository.

**Comment by LiLittleCat** [comment]
@sebastiaanspeck Thanks for the invite! I'd love to join and help out with the project.

**Comment by LiLittleCat** [comment]
> > @sebastiaanspeck Thanks for the invite! I'd love to join and help out with the project.
> 
> Congratulations and welcome to tldr, I have sent an invite.
> 
> Feel free to close this issue with a PR to add yourself to the list of [maintainers](https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md), just like #13782.
> 
> If you want, feel free to add yourself as [CODEOWNER](https://github.com/tldr-pages/tldr/blob/main/.github/CODEOWNERS) for Chinese as well in the same PR. By adding yourself, you will get added as reviewer for every PR affecting the Chinese pages.


Thanks for the reminder! I’ll contribute as a collaborator for a while before considering joining as a codeowner.
