### ISSUE TITLE
Page request: animdl

### ISSUE THREAD

**Issue by StrongSand94191** [tldr-pages/tldr#13854]
### Command description

animdl is a highly efficient, powerful and fast anime scraper.

### Documentation

https://github.com/justfoolingaround/animdl

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://github.com/justfoolingaround/animdl

**Comment by DarkMatter-999** [comment]
What would be the proper category for this page?

I am guessing "common".

**Comment by Arnav-2004** [comment]
Can I work on this, if no one else is currently working on it?

**Comment by Managor** [comment]
Go right ahead. If you're unsure, [search the pull requests page](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+is%3Aopen+animdl). We strive to be a sort of [do-ocracy](https://communitywiki.org/wiki/DoOcracy) where people that do get things done.

**Comment by Arnav-2004** [comment]
@Managor I have created a PR for the same.
