### ISSUE TITLE
301 redirect https to http - blocked by iOS

### ISSUE THREAD

**Issue by mflint** [tldr-pages/tldr#1392]
Hello team,

I notice you're now doing a 301 redirect from `https://tldr-pages.github.io/assets/tldr.zip` to `http://tldr.sh/assets/tldr.zip`.

Unfortunately this breaks [my iOS client](https://github.com/mflint/ios-tldr-viewer), because iOS blocks plain http requests unless an explcit exception is made. (See [App Transport Security](https://developer.apple.com/news/?id=12212016b)).

However! I see that `https://tldr.sh/assets/tldr.zip` also hosts the required zip file - can the 301 be redirected to https instead of http please?

Thanks!
 Matthew

**Comment by agnivade** [comment]
cc /@ostera.

**Comment by waldyrious** [comment]
For reference, there's prior discussion related to the custom domain tldr.sh and https, here: https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302050558

I'm afraid github doesn't provide us with the option to redirect to the https domain :(
Here's what I see at https://github.com/tldr-pages/tldr-pages.github.io/settings:

![screen shot 2017-05-25 at 19 19 43](https://cloud.githubusercontent.com/assets/478237/26464302/3356c390-417f-11e7-9d0e-4ab596e99c18.png)

Note the disclaimer at the bottom ☝️

**Comment by mflint** [comment]
Ah, got it - thanks for the explanation @waldyrious.

I can switch the iOS app to use `https://tldr.sh/assets/tldr.zip` directly - would that be a safe thing to do?

**Comment by waldyrious** [comment]
As long as @ostera keeps the domain up, sure :)
