### ISSUE TITLE
MAINTAINERS: add @renie as collaborator

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#13946]
Hi, @renie! You seem to be enjoying contributing to the tldr-pages project.
You now have had over more than five distinct pull requests [merged](https://github.com/tldr-pages/tldr/commits?author=renie)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator? And since you have contributed to Portuguese Brazilian pages, would you like to be added as CODEOWNER? If so, you will get added as a reviewer to all PR's affecting Portuguese Brazilian pages

Either way, thanks for all your work so far!

> [!NOTE]
> It is required to have [two-factor authentication](https://github.com/settings/security) (2FA) enabled for your GitHub account to be added as a collaborator to the tldr-pages/tldr repository.

**Comment by kbdharun** [comment]
Hi @sebastiaanspeck are you sure the username is right, I can't find the PRs merged under their account.

**Comment by renie** [comment]
That sounds very nice, @sebastiaanspeck ! Thank you very much for the invitation!
And sure, it will be a pleasure and an honor to become contributor, and to be added as CODEOWNER!

PS.: I found it funny that you've mentioned me as `lenie`. I've got some people spelling/speaking it not correctly but this was a totally new one 😄

**Comment by renie** [comment]
[The PR is opened](https://github.com/tldr-pages/tldr/pull/13966). Would you please have a look at it before I merge it, @sebastiaanspeck ?
