### ISSUE TITLE
Suggestion: Use automated check for detecting placeholder errors

### ISSUE THREAD

**Issue by debghs** [tldr-pages/tldr#13959]
While looking for placeholders that had not been translated in the translated pages( #13958 ), I wrote a simple python script to find out which of the files had this problem. The script returned an output like this for pages.hi/:

```bash
Markdown files containing problematic placeholders:
android\am.md: android.intent.action.VIEW, android.intent.action.MAIN, android.intent.category.HOME, android.intent.action.VIEW
android\settings.md: global, global, system, secure
common\7za.md: on
common\aireplay-ng.md: count, interface
common\alias.md: la
common\fuck.md: yes|yeah|hard
common\neofetch.md: enable|disable, on|off, on|off
common\time.md: command
common\tldr.md: tar
common\wget.md: bar
linux\archinstall.md: minimal|unattended
linux\backlight_control.md: +|-
linux\bluetoothctl.md: on|off
linux\free.md: b|k|m|g
linux\lsblk.md: NAME, SERIAL, MODEL, TYPE, SIZE
linux\mkfs.md: path/to/partition, path/to/partition, path/to/partition
linux\parted.md: primary|logical|extended
linux\systemctl.md: start|stop|restart|reload, enable|disable, mask|unmask
windows\bcdboot.md: S:, en-us, S:
windows\cd.md: C
windows\cmd.md: on|off, on|off
windows\eventcreate.md: success|error|warning|information
windows\winget.md: import|export, --import-file|--output
```

Now, obviously this is a very basic script and has much room for improvement. But I was wondering could we implement such a script as a check for the add-page-PRs committed to the translation directories so that it would automatically flag such commits?

**Comment by kbdharun** [comment]
Hi, thanks for the script. But I think it would have a lot of false positives since not all placeholders should be translated and it should be considered by the translator on a case by case basis.

**Comment by debghs** [comment]
Yeah I know it gives loads of erroneous flags, but maybe we could refine that? And then this would be useful?
Obviously the current method of manual checking works pretty well and building this check is kind of redundant and unnecessary.
