### ISSUE TITLE
bug - blank pages

### ISSUE THREAD

**Issue by Jopp-gh** [tldr-pages/tldr#13973]
No matter what cmd I open on my Android, TLDR returns always a blank page (with a button smaller than its description). I just downloaded your app and tabbed on cmd keywords, what else should do users to consult man pages ?

**OS**: Android 11
**TLDR v**: 8f6f43

<a href="Image"><img src="https://github.com/user-attachments/assets/9d04e10c-72a8-4422-a753-c24f10fa186a" align="left" height="660" width="300" ></a>

**Comment by rffontenelle** [comment]
Doesn't this belong https://github.com/Techno-Disaster/tldr-flutter, a tldr client for Android?

**Comment by rffontenelle** [comment]
I'm not this project's maintainer and I've been contributing here for literally 2 days, so I don't know much thing about the project ecosystem. But normally open source is about someone use your own free (or hopefully paid) time to implement something nice. And to keep maintaining. So I believe the question is who has time, energy and dev skill to implement/maintain such app. I agree with you that it is useful for mobile devices.

**Comment by kbdharun** [comment]
> However, I hoped to install a simple viewer app which downloads locally and updates examples whenever there's fresh content.. this was my idea 😐.

https://tldr.inbrowser.app/ by default supports caching pages so you can still view the pages offline, additionally, you can install it as a PWA and access it directly from your app screen.
