### ISSUE TITLE
Translation progress for alias-page mention

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#13989]
Progress of translating all [alias-page mention](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/alias-pages.md) for the supported languages:

- [x] en
- [x] ar
- [x] bn
- [x] bs
- [x] ca
- [x] cs
- [x] da
- [x] de
- [x] es
- [x] fa
- [x] fr
- [x] hi
- [x] id
- [x] it
- [x] ja
- [x] ko
- [x] lo
- [x] ml
- [x] ne
- [x] nl
- [x] no
- [x] pl
- [x] pt_BR
- [x] pt_PT
- [x] ro
- [x] ru
- [x] sh #14124
- [x] sr
- [x] sv
- [x] ta
- [x] th
- [x] tr
- [x] uk
- [x] uz
- [x] zh
- [x] zh_TW

**Comment by Bucke200** [comment]
hello is this still open, do u need conversion to sh?

**Comment by Bucke200** [comment]
please check the pull request i created https://github.com/tldr-pages/tldr/pull/14124 and let me know if any changes are necessary.
