### ISSUE TITLE
Let's document: pacman options in shortform

### ISSUE THREAD

**Issue by Managor** [tldr-pages/tldr#14003]
### Command description

Almost everywhere you look, pacman documentation and guides use shortform for its options, including the manpage. The main pacman.md page uses these the way you see everywhere else, but the subcommands use longform. I suggest that we convert these pages to look more like what people are used to and use mnemonics and the page title to indicate what it means.

### Documentation

https://manned.org/pacman.8

### Platform

Linux

### Commands

- [x] [pacman](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman.md)
- [x] [pacman-database](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-database.md)  #15177
- [x] [pacman-query](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-query.md)  #15180
- [x] [pacman-remove](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-remove.md) #14807
- [x] [pacman-sync](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-sync.md) #14658
- [x] [pacman-deptest](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-deptest.md) #15178
- [x] [pacman-upgrade](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-upgrade.md) #15179
- [x] [pacman-files](https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-files.md) #14858

**Comment by Waples** [comment]
Personally (daily arch user), I don't see the need for this. as for example the https://github.com/tldr-pages/tldr/blob/main/pages/linux/pacman-sync.md sync page is doing this already, or am I missing your point / pages you are missing/ what are you talking about?

**Comment by Managor** [comment]
The sync page does exactly the opposite what I requested

**Comment by cyqsimon** [comment]
I second this. Nobody actually uses pacman's long form commands, at least not anyone that I know of.
