### ISSUE TITLE
Add range option at curl command

### ISSUE THREAD

**Issue by voyeg3r** [tldr-pages/tldr#1419]
Download a range of files using curl
curl -O http://somelocation/wallpaper-[1-33].jpg

**Comment by agnivade** [comment]
Hi @voyeg3r, we limit the no. of options of each page to 8 (because our scope is limited). Currently, the curl page is at 8, so we wouldn't be able to add any more examples without removing one of them.

**Comment by agnivade** [comment]
@voyeg3r - I am guessing you do not have any other concerns after my reply. I am going ahead and closing this issue.

Please feel free to reopen any time you have any other questions about our process or you want any clarifications.
