### ISSUE TITLE
Question: `wall` super-user only wording

### ISSUE THREAD

**Issue by sethwoodworth** [tldr-pages/tldr#1421]
The current page on `wall` says:

> Only available to super-user.

But according to the wall man page:

> Only the superuser can write on the terminals of users who have chosen to deny messages or are using a program which automatically denies messages.

IMO, I think it makes sense to remove the current sentence about super-user entirely.  If folks agree I'll put up a PR.

**Comment by agnivade** [comment]
Hmm interesting, so even a normal user can write on other user's terminals ? That doesn't sound right. Can you verify this ?

**Comment by slicer69** [comment]
Normal users can use "wall" to write to other people's terminal if (and only if) other users enable the feature. If the other use does not turn on the wall feature then messages from non-root users are blocked.
The TDLR page is correct for default situations.

**Comment by agnivade** [comment]
Got it. How about we clarify the line to explain it better ?
```
Needs root permissions if the user has disabled the feature.
```

**Comment by slicer69** [comment]
Or perhaps something like, "Users can block incoming wall messages from other users via the mesg command. Only messages from root override this block."

**Comment by agnivade** [comment]
That sounds like a mouthful. Can we shorten it ? (in the spirit of tldr :wink: )

**Comment by slicer69** [comment]
Or, since showing the message is the default, we could simply drop the part about the root user.

**Comment by agnivade** [comment]
Agree, makes sense.

**Comment by agnivade** [comment]
@sethwoodworth - Would you like to file a PR for it ?
