### ISSUE TITLE
MAINTAINERS: add @renie to Org

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#14343]
Hi, @renie! After joining as a collaborator in the repository, you have been regularly performing [maintenance tasks](https://github.com/tldr-pages/tldr/pulls?q=reviewed-by:renie).

Thank you for that!

According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.

To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public and (in case you don't already) start hanging out in our [Matrix chat room](https://matrix.to/#/#tldr-pages:matrix.org).

Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).

As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/GOVERNANCE.md).

How does that sound? Are you up for it?

**Comment by renie** [comment]
That sounds great! Sure I am up to it!
I am on the Matrix chat already and following the organization already.
Anything else I should do?

**Comment by kbdharun** [comment]
> That sounds great! Sure I am up to it! I am on the Matrix chat already and following the organization already. Anything else I should do?

That would be all. 

Congratulations and welcome to the Org, I have sent an invitation. After accepting it, update your membership status to public at https://github.com/orgs/tldr-pages/people and also update the MAINTAINERS.md file in a PR.

**Comment by renie** [comment]
All ready ;)

**Comment by rffontenelle** [comment]
Congratulations @renie for this recognition of your contributions! 👏🎉

**Comment by renie** [comment]
Thanks @rffontenelle ! I am excited with it!
