### ISSUE TITLE
Manage tldr Commands

### ISSUE THREAD

**Issue by jasonxia23** [tldr-pages/tldr#1455]
Very glad to use this tool :)
Sometimes I find myself want to remember some commands for daily use, so I build [tldr-management](https://github.com/jasonxia23/tldr-management), which can be embed to Chrome Extension, so people can manage their daily used commands.

**Comment by agnivade** [comment]
Thank you for the kind words :)

Though I am not sure if there is anything you wanted us to do, since you raised an issue ? If you just want to generally chat or share info, you can always use our gitter channel - https://gitter.im/tldr-pages/tldr

**Comment by jasonxia23** [comment]
Sorry for the misunderstanding :)
It would be nice to me if I can customize my tldr commands.(so I can review them)

**Comment by agnivade** [comment]
I am sorry, I still do not get what you want to mean. What do you mean by "customize" here ? Are you saying you want to edit the tldr pages ?

**Comment by jasonxia23** [comment]
I mean you can store tldr commands locally, and no need to search for commands you have searched, next time you can review the commands you have stored.

**Comment by agnivade** [comment]
Oh I see, so you want to maintain a search history of commands. Well, that depends on which client you are using. You need to file an issue on that client's repo. This repo is only for the tldr pages.

**Comment by jasonxia23** [comment]
I wish the chrome extension will have this function :)

**Comment by jasonxia23** [comment]
I thought it has been done.
So @ostera , wish the chrome extension under development could support storing tldr commands locally.

**Comment by agnivade** [comment]
Ah I see. Ok then, I would recommend to place your request on that issue instead as that's the right place. 

Going ahead and closing this now.
