### ISSUE TITLE
Page modification request: speedtest

### ISSUE THREAD

**Issue by sohang3112** [tldr-pages/tldr#14804]
In the [speedtest page](https://tldr.inbrowser.app/pages/common/speedtest), all commands are not working (except for the first one with no CLI arguments: `speedtest`). I'm running the *speedtest-cli 2.1.3* (it's the latest version) - it's possible these CLI arguments worked in an earlier version.

All these commands are not working (in each case error `unrecognized arguments` is shown):
- `speedtest --unit=auto-decimal-bits|auto-decimal-bytes|auto-binary-bits|auto-binary-bytes`
- `speedtest --format=human-readable|csv|tsv|json|jsonl|json-pretty`
- `speedtest --precision=precision`
- `speedtest --progress=yes|no`
- `speedtest --servers`
- `speedtest --server-id=server_id` 

Available options are listed in speedtest's github repository: https://github.com/sivel/speedtest-cli - there also the above mentioned CLI arguments are not mentioned. Note that a flag similar to last one listed (`-server-id`) exists, so it might have been renamed at some point: `--server SERVER`.

**Comment by spageektti** [comment]
Hi. We have Issues templates. Please use them.

**Comment by acuteenvy** [comment]
The `speedtest` page documents a different program (https://www.speedtest.net/apps/cli).
The page for https://github.com/sivel/speedtest-cli is `speedtest-cli`, and there's already a note about this in both pages.

https://github.com/tldr-pages/tldr/blob/936bebbd521214f47887021e164ad0069db90bd9/pages/common/speedtest.md?plain=1#L4
https://github.com/tldr-pages/tldr/blob/936bebbd521214f47887021e164ad0069db90bd9/pages/common/speedtest-cli.md?plain=1#L4

**Comment by sohang3112** [comment]
@acuteenvy You're right that I confused `speedtest-cli` and `speedtest` (it was aliased on my system). But these commands are not working even in the official `speedtest` program (installed with official Fedora instructions at https://www.speedtest.net/apps/cli):

```console
$ speedtest --servers
Unknown option --servers
$ speedtest --unit=auto-decimal-bytes
Unknown option --unit=auto-decimal-bytes
$ speedtest --format=json
Unknown option --format=json
$ speedtest --progress=no
Unknown option --progress=no
```

**Comment by acuteenvy** [comment]
These examples work on my system. Are you sure you've installed the official `speedtest`? What is the output of `speedtest --version`?

```
$ speedtest --version
Speedtest by Ookla 1.2.0.84 (ea6b6773cf) Linux/x86_64-linux-musl 6.11.7-arch1-1 x86_64

The official command line client for testing the speed and performance
of your internet connection.
```

**Comment by spageektti** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/acuteenvy?size=32">@acuteenvy](https://github.com/acuteenvy) You're right that I confused `speedtest-cli` and `speedtest` (it was aliased on my system). But these commands are not working even in the official `speedtest` program (installed with official Fedora instructions at [speedtest.net/apps/cli](https://www.speedtest.net/apps/cli)):
> 
> $ speedtest --servers
> Unknown option --servers
> $ speedtest --unit=auto-decimal-bytes
> Unknown option --unit=auto-decimal-bytes
> $ speedtest --format=json
> Unknown option --format=json
> $ speedtest --progress=no
> Unknown option --progress=no

I think that is because `sudo yum install speedtest` by default installs the package from the default fedora repo, which is a different tool. At least that is what it has done on my system.
https://packages.fedoraproject.org/pkgs/speedtest/speedtest/
https://github.com/Ketok4321/speedtest

**Comment by sohang3112** [comment]
>Update: Someone added a comment on packages.fedoraproject.org about the conflict 9 hours ago
https://bugzilla.redhat.com/show_bug.cgi?id=2257536

Fedora maintainers closed the issue since it said Fedora 39 which is EOL. @spageektti do you or anyone else here know who originally raised the issue in Redhat Bugzilla? If you do, please ask them to re-open issue & mark it Fedora 41.

**Comment by Abhishek-1804** [comment]
The speedtest-cli page already points to its official repository, clarifying it's not the official Ookla CLI. The speedtest page has been updated in PR #15288 to clearly state it's the official package but notes that some platforms link speedtest to speedtest-cli or other tools like librespeed, which may also be installed as speedtest on some linux distros. The updated description advises users to ensure they have the official Ookla CLI from https://www.speedtest.net/apps/cli for the examples to work. Additionally, the speedtest-rs page has been updated to specify that it's an unofficial Rust-based tool, inspired by speedtest-cli.
