### ISSUE TITLE
page request: stat

### ISSUE THREAD

**Issue by opticyclic** [tldr-pages/tldr#1487]
`stat` is useful for showing octal permissions:
https://askubuntu.com/questions/152001/how-can-i-get-octal-file-permissions-from-command-line

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by juan88** [comment]
Hello! Can I give it a go?

**Comment by agnivade** [comment]
By all means, yes. :)
