### ISSUE TITLE
[ToBeRemoved]Generated files should not be committed

### ISSUE THREAD

**Issue by bibirico** [tldr-pages/tldr#1498]
Implement a mechanism (based on names ?) to prevent default committing of generated files.

**Comment by agnivade** [comment]
Which generated file are you talking about ? This repo only contains `.md` files and some scripts.

We can always add some paths to `.gitignore` if that file is not meant to be committed.

**Comment by bibirico** [comment]
Waow, sorry, I really don't know how this issue get there... a very strange misclick.
Sorry about this, not intended to be posted here...

**Comment by sbrl** [comment]
No problem, @bibirico :smiley_cat:
