### ISSUE TITLE
Screenshot font name

### ISSUE THREAD

**Issue by the-c0d3r** [tldr-pages/tldr#1503]
I just saw your screenshot and couldn't help but notice the font looks so good on it. Can you please tell me what font you are using? I have tried looking it up myself since I don't want to bother other people, but I just can't seem to identify it.

**Comment by waldyrious** [comment]
On the repository's [main page](https://github.com/tldr-pages/tldr) (or on the [README](https://github.com/tldr-pages/tldr/blob/master/README.md)) you can click the screenshot image, which will take you to [its location in the source](https://github.com/tldr-pages/tldr/blob/master/screenshot.png). There, you'll see in the banner above the file that the last person to edit it was @agnivade, in #957. From that PR he references #667, where that particular image can be found in [this comment](https://github.com/tldr-pages/tldr/issues/667#issuecomment-192442018) by @jedahan. He is the one who can answer you about the font for that screenshot.

**Comment by jedahan** [comment]
I believe its Inconsolatas or InconsolataForPowerline Nerd Font https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Inconsolata/complete

**Comment by the-c0d3r** [comment]
I believe it is. Thank you so much. Fonts really do matter in programming environment. I'm always looking for better fonts to help my coding.
