### ISSUE TITLE
Page request: `socket()`

### ISSUE THREAD

**Issue by RushilJalal** [tldr-pages/tldr#15082]
### Command description

socket() is a C method which creates an endpoint for communication and returns a file descriptor that refers to that endpoint.

### Documentation

https://man7.org/linux/man-pages/man2/socket.2.html

### Platform

Linux

### Additional information

I would like to work on this but I would need some assistance...

**Comment by acuteenvy** [comment]
> socket() is a C method

Programming languages are not documented in `tldr`. We only document command-line tools.
