### ISSUE TITLE
split CONTRIBUTING.md into main guidelines and auxiliary docs

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1508]
This has been discussed in a couple PRs now -- most recently in #1495 (/cc @vivekkrish).

#1018 is the only issue specifically related to additions to the CONTRIBUTING.md file that I could find in a quick search (I'm pretty sure there have been discussions to that effect in a few other threads). Such tasks should be included/considered when performing the split.

Links to other discussions where this topic has been discussed would be appreciated. I hope to be able to work on this when I get some time on my hands, but in the meantime, any contribution is welcome :)

**Comment by agnivade** [comment]
@waldyrious - Shouldn't this be closed ?

**Comment by waldyrious** [comment]
@agnivade indeed. I haven't been able to stay on top of my notifications, hence the delay, but yeah, #1594/#1665 (and to some extent #1694) implemented this.
