### ISSUE TITLE
page request: popd

### ISSUE THREAD

**Issue by juan88** [tldr-pages/tldr#1510]
There is a `pushd` tldr page for what I found out to be a very useful command but there is no `popd` page for the command that pops the directory out of the stacks and cd-in.

I could give it a try if you want. Cheers!

**Comment by agnivade** [comment]
Sure. Go ahead.

**Comment by sbrl** [comment]
Go for it! :smiley_cat:

**Comment by sbrl** [comment]
All done! Looks like this issue wasn't automagically closed by #1517.
