### ISSUE TITLE
Let's get the new windows section started!

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#1579]
As a sort of celebration of the new `windows` platform folder, here's a list of 10 useful commands that are specific to windows machines.

 - [x] sfc
 - [x] sigverif
 - [x] driverquery
 - [x] nslookup
 - [x] ping
 - [x] pathping
 - [x] ipconfig
 - [x] repair-bde
 - [x] tasklist
 - [x] taskkill

_From [this tech republic article](http://www.techrepublic.com/blog/10-things/10-windows-7-commands-every-administrator-should-know/)_

**Comment by itsjzt** [comment]
some more are 

- [ ] cls
- [ ] color
- [ ] set
- [ ]  systeminfo
- [ ] tree
- [ ] wmic

**Comment by Leandros** [comment]
You forgot the most import ones!

- [ ] dir
- [ ] xcopy
- [ ] rmdir
- [ ] del

and the most important one:

- [ ] How to install gnu coreutils

**Comment by sbrl** [comment]
Good thinking, @Leandros! Not sure about `How to install gnu coreutils` though - unless that's a command.

**Comment by Leandros** [comment]
More or less a joke. The gnu coreutils are all available on Windows, and work lovely. Often better than their Windows "native" counterparts.

**Comment by sbrl** [comment]
Ah, ok! Yeah, they are really good, aren't they?

_(Sorry, I sometimes miss jokes :P)_

**Comment by pxgamer** [comment]
@sbrl, the `sigverif` command is just a GUI and has no options. Should that still be added?

**Comment by Leandros** [comment]
Added a couple more tools, including the super useful `doskey`.

**Comment by sbrl** [comment]
@pxgamer Hrm, good question. If it has no options at all, then I'm not sure it would be particularly useful as a page - except to ensure people that its behaviour can be altered through the use of flags. Someone can go ahead if they want I guess!

@agnivade, thoughts?

**Comment by agnivade** [comment]
We do have a lot of pages for GUI. Check `rainbowstream` and `rtv`. Originating from this issue - https://github.com/tldr-pages/tldr/issues/1162. 

We can go ahead with `sigverify`.

**Comment by pxgamer** [comment]
@agnivade, fine with me. 👍

**Comment by agnivade** [comment]
We just have one page [wmic](https://docs.microsoft.com/en-us/windows/desktop/WmiSdk/wmic) left to close this issue. Anybody wants to take a stab ?

**Comment by pxgamer** [comment]
@agnivade, I might have a look tomorrow or Monday. :+1:

**Comment by sbrl** [comment]
We might have to do a `git` on it...

**Comment by zdroid** [comment]
Anyone up to finish this? I haven't used Windows actively in years, so I can't help with a command as specific as `wmic`.

**Comment by ivanhercaz** [comment]
> Anyone up to finish this? I haven't used Windows actively in years, so I can't help with a command as specific as `wmic`.

If someone usually uses Windows, really nice! If not, sometimes I have to use Windows or help to some familiar with a Windows issue, so I could try to test this command and try to write a page (of course, only if I consider my knowledge enough to write it).

**Comment by sbrl** [comment]
It's a pretty extensive command if I recall correctly. It might even end up warranting a whole suite of pages :P

**Comment by sbrl** [comment]
:tada:
