### ISSUE TITLE
page request: pyflakes

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1603]
Webpage here - https://pypi.python.org/pypi/pyflakes

Specific documentation on how to invoke from command line is sparse. Installation step is here - https://github.com/PyCQA/pyflakes#installation. One has to install and and find out the parameters.

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by lamar-frankie** [comment]
I would like to claim this issue.

**Comment by agnivade** [comment]
Feel free to go ahead.
