### ISSUE TITLE
page request: eslint

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1606]
webpage here - https://eslint.org/
cli documentation here - https://eslint.org/docs/user-guide/command-line-interface

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by phillip055** [comment]
Hi, I would like to try and take this up! 👍

**Comment by agnivade** [comment]
Umm, this was part of the issue list for the Google Code-In event. Hence the gci tag. But sure, go ahead. I guess we will add new issues.

**Comment by sbrl** [comment]
Should we remove the `gci` tag?
