### ISSUE TITLE
page request: gofmt

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1607]
webpage and cli documentation here - https://golang.org/cmd/gofmt/

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by juan88** [comment]
Can I give it a go?

**Comment by agnivade** [comment]
Are you participating in GCI (Google Code-In) or is this a general request to add a page ?

**Comment by juan88** [comment]
Oh no, I'm not. Just googled Google Code-In and I think it's better to
leave that issue for that :)

2017-11-27 9:17 GMT-03:00 Agniva De Sarker <notifications@github.com>:

**Comment by agnivade** [comment]
Thanks. Appreciate it. :)

**Comment by sbrl** [comment]
We've still got load of other pages that need doing if you'd still like to help out, @juan88 :P
