### ISSUE TITLE
ps: add more CLI options

### ISSUE THREAD

**Issue by amitsharma928** [tldr-pages/tldr#1610]
Need to add more command line options for ps command.

**Comment by agnivade** [comment]
Feel free to send a PR. We will be happy to take a look at it.

**Comment by sbrl** [comment]
Thanks for requesting this edit Do you want to have a go yourself?

Pages are best created and edited by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :smiley_cat:
