### ISSUE TITLE
It is possible to configure my tldr to be offline, avoiding checking every time on the internet if the command I feed is not valid?

### ISSUE THREAD

**Issue by soulomoon** [tldr-pages/tldr#1624]
Due to my poor network, tldr takes a long time to fetch from internet, 
Is it possible from me to switch it off,  
and manually update my source in my will?

Additional information:
```shell
~/g/p/C/u/u/intro > time tldr lss
This page doesn't exist yet!
Submit new pages here: https://github.com/tldr-pages/tldr
tldr lss  0.02s user 0.01s system 0% cpu 4.425 total
```

**Comment by agnivade** [comment]
If the command you feed is not valid, you won't get an output anyway. You can just press ctrl-c to cancel the network fetch operation. 

For valid commands, they are always fetched locally.

To answer your question - no its not possible to do that. If a page you enter is not there, you would almost always want to update your cache and check whether the page has been added to the remote repo or not. This just automates that action. In case, you have no network, feel free to cancel the operation.

**Comment by soulomoon** [comment]
Thanks
