### ISSUE TITLE
tldr --update not working, tldr -update works

### ISSUE THREAD

**Issue by thegreyfellow** [tldr-pages/tldr#1626]
Hi guys,

Just a quick thing I noticed it's when I try to update it says this message: 

`Local data is older than two weeks, use --update to update it.`

If I try it with `tldr --update` it does not update, but if I try it with one dash `tldr -update` it works. Thanks for your hard work.

**Comment by agnivade** [comment]
I am assuming you are talking about the node client. That message used to come in a very old version of the client. Please upgrade to a newer version and check.

Please close the issue here and open a new issue in the node-client repo if you still see the issue. This repo is only used for pages.

**Comment by thegreyfellow** [comment]
I installed tldr using homebrew, I'm sorry I couldn't understand the relationship of node-client to this.

**Comment by agnivade** [comment]
Ah its the cpp client then. Please file an issue in that [repo.](https://github.com/tldr-pages/tldr-cpp-client) /cc @Leandros

**Comment by agnivade** [comment]
Closing this issue now. Please file an issue in the cpp-client repo to get clarifications.
