### ISSUE TITLE
page request: zeek

### ISSUE THREAD

**Issue by YangVincent** [tldr-pages/tldr#1627]
http://bro.org

**Comment by sbrl** [comment]
Looks interesting! I'm actually building something related to this for my final year project, so I'll take a little look at this project. Thanks :smiley_cat:

**Comment by gutjuri** [comment]
bro is now called "zeek" (https://zeek.org/).
Maybe @sbrl or @YangVincent can update this issue's title.

**Comment by sbrl** [comment]
Great spot, @gutjuri!

Anyone want to give this page a go?

**Comment by bl-ue** [comment]
Finally! 🎉 😅
