### ISSUE TITLE
page request: ipsumdump, ipaggmanip, ipaggcreate

### ISSUE THREAD

**Issue by YangVincent** [tldr-pages/tldr#1628]
http://read.seas.harvard.edu/~kohler/ipsumdump/

**Comment by bl-ue** [comment]
Thanks for requesting this page, @YangVincent! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
