### ISSUE TITLE
pull request iptables

### ISSUE THREAD

**Issue by jonnywang** [tldr-pages/tldr#1643]
Feel free to send a pull request to: https://github.com/tldr-pages/tldr

**Comment by agnivade** [comment]
We already have a page for iptables. Can you explain the purpose of this issue ?

**Comment by agnivade** [comment]
Hi @jonnywang - I will go ahead and close this issue. Feel free to reopen if you had something else in mind.

**Comment by Akronix** [comment]
Why it doesn't work here: https://tldr.ostera.io/iptables ? or here http://tldr.sh/?

**Comment by agnivade** [comment]
Please raise an issue in that repo.
