### ISSUE TITLE
page request: mdadm

### ISSUE THREAD

**Issue by sena73** [tldr-pages/tldr#1645]
http://www.ducea.com/2009/03/08/mdadm-cheat-sheet/

**Comment by sbrl** [comment]
Hey, thanks for the request! It looks like we've already go ta page on `mdadm` [here](https://github.com/tldr-pages/tldr/blob/master/pages/linux/mdadm.md).

 - If you're not on linux, is this command available on platforms other than linux?
 - Depending on your client, try running `tldr --update` and `tldr --cache` to update your local copy of tldr-pages.

**Comment by sbrl** [comment]
I'm closing this issue for now due to inactivity. Let us know if you have any further questions / issues :-)
