### ISSUE TITLE
page request:kubectl

### ISSUE THREAD

**Issue by aksaha2311** [tldr-pages/tldr#1649]
https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by pxgamer** [comment]
Looks like this has been added in #1954.
