### ISSUE TITLE
page request: g++

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1661]
Webpage here - https://linux.die.net/man/1/g++

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by nalinbhardwaj** [comment]
Taking this(as GCI task).

**Comment by sbrl** [comment]
I've merged your PR, @nalinbhardwaj! I couldn't find the associated task in the GCI dashboard though :confused:

**Comment by nalinbhardwaj** [comment]
yep, that's because I'm still waiting for the previous task and "Parent's Consent" to get accepted.

**Comment by sbrl** [comment]
Ah, ok. As soon as I see it pop up, I'll accept it for you :-)
