### ISSUE TITLE
page request: grunt

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1663]
Webpage here - https://gruntjs.com/getting-started

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by lamar-frankie** [comment]
I can work on this.

**Comment by agnivade** [comment]
Will you be contributing through GCI ? Or just as a normal PR ?

**Comment by lamar-frankie** [comment]
What is GCI?

**Comment by agnivade** [comment]
Google Code-In (https://codein.withgoogle.com/about/). This PR was made for GCI participants. Hence the `gci` tag.

**Comment by lamar-frankie** [comment]
Oh, I'm not apart of that. I'll leave this issue for participants.

**Comment by sbrl** [comment]
Ok. Please feel free to attempt any other page (or even this page once Google Code-In has ended) though!

**Comment by pxgamer** [comment]
@lamar-frankie this is now available if you still want it. :+1:

**Comment by lamar-frankie** [comment]
OK, I'll take care of it this weekend.
