### ISSUE TITLE
page request: gulp

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1664]
Webpage here - https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by rowanfreeman** [comment]
The Gulp CLI has pretty limited features. I feel like it's mostly covered at the moment.

Is there anything else that needs to be listed?

Does tldr deal with example config files (which is mostly what Gulp is about)?

**Comment by agnivade** [comment]
Even a single example will be okay. For eg. look at the webpack page. Webpack is also mostly about config files, but we mention minimal examples.

**Comment by pxgamer** [comment]
It looks like this already exists?
https://github.com/tldr-pages/tldr/blob/master/pages/common/gulp.md

Unless you're looking to add additional examples. If so, Gulp v4 now adds some actual flags:
https://github.com/gulpjs/gulp-cli#flags

**Comment by agnivade** [comment]
Yep. Closing it.
