### ISSUE TITLE
Installation warnings and errors

### ISSUE THREAD

**Issue by navjotjsingh** [tldr-pages/tldr#1666]
While trying to install tldr on Ubuntu 16.04 with nodejs v8.9.1, I get the following warning

> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

Also the following errors

> gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/tldr/node_modules/webworker-threads/.node-gyp/8.9.1"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tldr/node_modules/webworker-threads/.node-gyp"

Please look into it.

**Comment by agnivade** [comment]
You should not be using root to install a global module. If you have to, use `--unsafe-perm`. More info here - https://github.com/tldr-pages/tldr-node-client#npm-install--g-tldr-throws-an-error.

I am going to close this issue now as its related to the node client and not the tldr repo. If your issue still persists after trying out the options above, feel free to raise an issue in the node client repo.

**Comment by navjotjsingh** [comment]
Not using root also gave errors.

**Comment by agnivade** [comment]
Did you first try what is mentioned here - https://docs.npmjs.com/getting-started/fixing-npm-permissions ? Or you just tried the same command without root ?

**Comment by navjotjsingh** [comment]
Thanks. That worked.
