### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by feimosi** [tldr-pages/tldr#1673]
This happens on the first run:
```sh
Page not found. Updating cache ..
{ Error: ENOENT: no such file or directory, unlink '/home/feimosi/.tldr/cache/pages/shortIndex.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/home/feimosi/.tldr/cache/pages/shortIndex.json' }
Creating index...
^[[CDone
```

Steps to reproduce:
- `npm i -g tldr`
- `tldr tar`

My environment:
- Arch Linux (kernel 4.13.12-1)
- npm: v5.5.1
- node: v8.9.1

**Comment by agnivade** [comment]
Yes, that happens for the first time. The command works fine though. So its not a blocker. I will close this and create a separate tracking issue on the node client repo.

Thanks for reporting.

**Comment by feimosi** [comment]
Sure, I know it's a minor issue. Thanks for a quick reply 👍

**Comment by sbrl** [comment]
The issue that @agnivade opened I think was tldr-pages/tldr-node-client#180 - though it appears to have been fixed and closed now.

**Comment by agnivade** [comment]
Right. I should have linked it here though.

**Comment by jakeNiemiec** [comment]
No such luck on OSX 11:
![image](https://user-images.githubusercontent.com/16782063/33282270-c7a9d818-d36d-11e7-8940-36a443b291e6.png)

**Comment by agnivade** [comment]
@jakeNiemiec - You have to be a bit more specific with your issue. The issue you linked talks about a bash client. But this issue deals with the node client.  Which client are you using ?

Please file an issue in the respective client's repo with appropriate debug information about your setup and the steps to repro your issue.

**Comment by jakeNiemiec** [comment]
@agnivade Thanks for the reply, it turned out that another package created an alias for tldr.

If anyone has the same problem, debug with: `which tldr`

**Comment by broisnischal** [comment]
> @agnivade Thanks for the reply, it turned out that another package created an alias for tldr.
> 
> If anyone has the same problem, debug with: `which tldr`

so it solved?

**Comment by sbrl** [comment]
Hey, @broisnischal! If you're having an issue, I recommend opening a separate issue or joining us on Matrix to discuss :-)
