### ISSUE TITLE
page request: eval

### ISSUE THREAD

**Issue by rachelkelly** [tldr-pages/tldr#1678]
`eval` resources here:
- https://ss64.com/bash/eval.html
- https://ss64.com/osx/eval.html
- https://linux.die.net/man/1/eval
- https://www.unix.com/man-page/posix/1posix/eval/

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by sbrl** [comment]
Thanks for requesting this page, @rachelkelly! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by rachelkelly** [comment]
Ok thank you I'll give it a go!

**Comment by agnivade** [comment]
eval is already present under linux. Perhaps, you can add a similar page under osx.

**Comment by itsjzt** [comment]
Hey, did @rachelkelly not copied and pasted the same command in OS X section, can I do it

**Comment by agnivade** [comment]
Go ahead.
