### ISSUE TITLE
Change background color formatting

### ISSUE THREAD

**Issue by JacobCallahan** [tldr-pages/tldr#1679]
The current background color formatting can clash with different terminal emulator color profiles. For example, see the output in this image, which is a screenshot from my terminal (Fedora 27, default emulator, monokai dark color profile).
https://i.imgur.com/EuJTEXL.png
If possible, don't specify a background color, or use general codes which override a user's color profile for a consistent look an all platforms.

**Comment by freesouls** [comment]
similar problem occurred!

**Comment by agnivade** [comment]
Which client are you using ? Please file an issue in that client's repo. This repo is only for the tldr pages.

**Comment by JacobCallahan** [comment]
@agnivade python client, and i certainly can move the issue over there. Thanks for pointing me in the right direction.
@freesouls, if you are using a different client, would you mind opening an issue for yours?

**Comment by freesouls** [comment]
@JacobCallahan same python client under linux
