### ISSUE TITLE
page request: git

### ISSUE THREAD

**Issue by achikin** [tldr-pages/tldr#1684]
`git` resources:
- https://git-scm.com/doc
- https://services.github.com/on-demand/downloads/github-git-cheat-sheet/
- https://www.git-tower.com/blog/posts/git-cheat-sheet
- https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet

Please go through the [CONTRIBUTING](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) page to understand what is the format we use for our pages.

**Comment by agnivade** [comment]
We already have pages for git and its subcommands. See `tldr git`, `tldr git commit`, `tldr git push` etc. What is this issue for ?

**Comment by achikin** [comment]
@agnivade `tldr git` returns very basic information. Like `git --help`. I think it should contain at least a list of basic operations like `checkout`, `commit`, `push` and `status`.

**Comment by achikin** [comment]
```→ tldr git

git

Distributed version control system.

- Check the Git version:
    git --version

- Call general help:
    git --help

- Call help on a command:
    git help command

- Execute Git command:
    git command```

**Comment by achikin** [comment]
Compare to `docker`
```
→ tldr docker

docker

Manage Docker containers and images.

- List currently running docker containers:
    docker container ls

- List all docker containers (running and stopped):
    docker container ls -a

- Start a container:
    docker container start container

- Stop a container:
    docker container stop container

- Start a container from an image and get a shell inside of it:
    docker container run -it image bash

- Run a command inside of an already running container:
    docker container exec container command

- Remove a stopped container:
    docker container rm container
```

**Comment by agnivade** [comment]
Please look into this conversation - https://github.com/tldr-pages/tldr/pull/1675#issuecomment-347082938

**Comment by agnivade** [comment]
I am going to close this issue now. PR #1675 has a plan to tackle this. Let's continue the discussion there.
