### ISSUE TITLE
page request: authconfig

### ISSUE THREAD

**Issue by fcpexpert** [tldr-pages/tldr#1685]

**Comment by sbrl** [comment]
Thanks for requesting this page, @fcpexpert! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
