### ISSUE TITLE
Grep page has 10 examples

### ISSUE THREAD

**Issue by dospunk** [tldr-pages/tldr#1695]
This might be overly pedantic, but the contribution guidelines specify no more than 8 examples. Grep has 10.

**Comment by angsuman** [comment]
grep probably needs even more examples. Similar commands which needs lot of examples are are awk, sed.

**Comment by agnivade** [comment]
You are right. Actually its a relic from the past. Initially there was no limit on the no. of examples. Over the course of time, we decided that we should keep an explicit hard limit to force ourselves to be more precise and focus on the most useful examples.

The grep page was one of the first pages. So the limit was not applied at that time. And our linter is not updated to throw an error if the no. of examples exceed 8.

@dospunk - A PR which removes 2 least used options from the page would be most welcome :)
