### ISSUE TITLE
page request: where

### ISSUE THREAD

**Issue by ahmetb** [tldr-pages/tldr#1703]

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself, @ahmetb?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by ahmetb** [comment]
I wish I understood this command well enough to write about it but I currently do not.

**Comment by sudoio** [comment]
Did you mean the `whereis` command? I can neither find `where` in `man` nor in the web.

**Comment by ahmetb** [comment]
Try it on your bash. There might not be a manpage for it, but it’s a command.

**Comment by sudoio** [comment]
![where](https://user-images.githubusercontent.com/19972511/33360536-261af7a6-d4e5-11e7-82e1-33ee0cc2c1b1.png)

**Comment by ahmetb** [comment]
Hmm it works in my macOS + bash/zsh, I use it all the time. `man where` brings up BSD General Commands Manual.

```
$ where git
git: aliased to hub
/Users/ahmetb/.homebrew/bin/git
/usr/bin/git
```

**Comment by sudoio** [comment]
Looks like this command is simillar to `whereis` in linux:
```bash
[av@av-pc ~]$ whereis git
git: /usr/bin/git /usr/share/man/man1/git.1.gz
```

But I think there is some difference, so we need two separate _tldr_'s: 
- `osx/where.md`.
- `linux/whereis.md` (#1708).

**Comment by agnivade** [comment]
Yes, we need 2 separate pages in that case.

**Comment by fangyi-zhou** [comment]
`where` is a `csh` built in, but it seems `zsh` has it as well

`man 1 csh`
```
       where command (+)
               Reports  all  known  instances  of command, including aliases, builtins and
               executables in path.
```

**Comment by fangyi-zhou** [comment]
Note that `where` is not available in `bash`
Previous commands seem to suggest this is an osx thing, I believe that is incorrect.

**Comment by fangyi-zhou** [comment]
Also notice the difference between `where` and `whereis`
![image](https://user-images.githubusercontent.com/7815439/33429195-b49d6bce-d5c3-11e7-8cc8-451086df53b9.png)
