### ISSUE TITLE
Adding PSQL shell commands?

### ISSUE THREAD

**Issue by scottwhudson** [tldr-pages/tldr#1706]
Wanted to get an opinion before opening a PR, are you open to adding PSQL shell commands to the psql doc or creating a new command dedicated to working in the PSQL shell? Happy to write it up myself. I'm constantly referencing cheat sheets in the browser and I'd prefer to have a CLI option.

**Comment by agnivade** [comment]
I get your point. However, our scope here in tldr is very limited. We do not aim to be a command line cheat sheet reference. While we do aim to keep the most useful and practical examples, we try to refrain from adding sneaky one-liners which, may do a task very quickly, but maybe daunting to a newcomer to linux.

With that in mind, note that the page for `psql` should be limited to psql commands and its options only. We do have some exceptions like `vim`, `less` etc. However, if you look at other pages like `sqlite3`, `mysql`, `mongo` etc, all of them have the same format, keeping only the command and its options and not mentioning internal shell commands. Therefore, I am reluctant to add psql shell commands to the page.

Let me know your thoughts.

**Comment by sbrl** [comment]
I certainly wouldn't be averse to a link to a quick command-line reference in another repository here in GH.

**Comment by scottwhudson** [comment]
That's understandable, I noticed that these docs stay in the *nix realm which was why I asked.

Would adding a subcommand to output tool-specific sheets make sense (i.e. something like `tldr tools psql`)?  That might be outside of your desired scope though. It might be worth rolling a separate tool for this.

**Comment by agnivade** [comment]
It is very much outside the scope of the current tool. The idea is that you should be able to replace `man`  with `tldr` in a command and it should work. Doing a `tldr tools <tool>` would break that convention.

I would recommend that you look into other tools like `cheat` which is more suited for purposes like these.

**Comment by agnivade** [comment]
Thanks for understanding @scottwhudson. I hope this does not discourage you from contributing to this project !
