### ISSUE TITLE
Page request: dd

### ISSUE THREAD

**Issue by gganley** [tldr-pages/tldr#1721]

**Comment by agnivade** [comment]
There is already a page for dd. What is this issue for ?

**Comment by gganley** [comment]
[Safari - Nov 30, 2017 at 08:02.pdf](https://github.com/tldr-pages/tldr/files/1517849/Safari.-.Nov.30.2017.at.08.02.pdf)

For some reason it is not working on my end

https://tldr.ostera.io/dd

**Comment by sbrl** [comment]
@gganley Which client are you using?

**Comment by agnivade** [comment]
He is using the web client. 

@gganley - I would suggest raising an issue in the web client's repo. This repo is only for the pages.

**Comment by sbrl** [comment]
@agnivade Ahh, I see. I believe tha tth  web client only updates every so often - I get a message that @igorshubovych has committed to the web-pages web repo on the GH dashboard every so often. I think it's automated

**Comment by agnivade** [comment]
@gganley - I am going to close the issue now as it's related to the web client. Please file an issue on that repo.
