### ISSUE TITLE
page request: pdftotext

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1736]
Would nicely complement the existing [pdftk.md](https://github.com/tldr-pages/tldr/blob/master/pages/common/pdftk.md) page and other pdf-related commands.

Relevant links: [Wikipedia article](https://en.wikipedia.org/wiki/Pdftotext), [man page](https://linux.die.net/man/1/pdftotext).

**Comment by redant333** [comment]
I'll do it.
