### ISSUE TITLE
fsck is different on macOS X

### ISSUE THREAD

**Issue by gingerbeardman** [tldr-pages/tldr#1764]
```
fsck usage: fsck [-fdnypq] [-l number]
```

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/fsck.8.html

**Comment by agnivade** [comment]
A PR would be most welcome. :smile:

**Comment by gingerbeardman** [comment]
Will do so. 

Would it override the common entry?

**Comment by agnivade** [comment]
Please move the page from common to linux and create a separate entry in osx folder.

**Comment by gingerbeardman** [comment]
Done https://github.com/tldr-pages/tldr/pull/1775

**Comment by agnivade** [comment]
Let's keep this open until the PR is merged.
