### ISSUE TITLE
page request: ghci

### ISSUE THREAD

**Issue by wisn** [tldr-pages/tldr#1772]
Requesting man page for [GHC Interpreter](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html).

**Comment by sbrl** [comment]
Thanks for requesting this page, @wisn! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by sbrl** [comment]
Go ahead, @mira01 - no need to ask for permission :smiley_cat:

**Comment by UserBlackBox** [comment]
I saw this command request from 2017 and noticed that `ghci` doesn't have a tldr page yet. I was wondering if @mira01 was working on this page. If not, I would like to write a page.

**Comment by sbrl** [comment]
Considering the length of time, I think it's safe to assume that nobody is working on it at the moment @UserBlackBox. Go ahead - it'd be great if you could write such a page :D
