### ISSUE TITLE
page request: speedtest-cli

### ISSUE THREAD

**Issue by Scarsz** [tldr-pages/tldr#1787]
Test down/uplink connection via Speedtest.net servers with shareable image (`--share`)

Reference: https://github.com/sivel/speedtest-cli#usage

**Comment by sbrl** [comment]
Thanks for requesting this page, @Scarsz! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by Scarsz** [comment]
Went ahead and did a PR for this. https://github.com/tldr-pages/tldr/pull/1794

**Comment by sbrl** [comment]
Cool, thanks! I'll check it out now :D
