### ISSUE TITLE
Pages already in the system fail the bot checks

### ISSUE THREAD

**Issue by gingerbeardman** [tldr-pages/tldr#1798]
Such as "descriptions must end in a period"

https://github.com/tldr-pages/tldr/pull/1797

**Comment by agnivade** [comment]
I don't understand the issue. The rule says "descriptions must end in a period". Therefore, a whitespace after a period will fail the check. Seems right to me.

**Comment by gingerbeardman** [comment]
I shouldn't have added that paragraph and it's confused the issue. 

If you click the link and then vote the commit you'll see that the `file` text had a description that ended in a colon. So it would fail the bot check. But it was already in the system. I was modifying that file so I was forced to change it to a period, even though I want editing that section of the file. 

So I guess what I'm saying is that the existing content does not pass the bot checks.

**Comment by agnivade** [comment]
So I believe the original file was at "pages/common/fsck.md" right ? I just checked the file, and there is no whitespace at the end of line 3. Is it possible that is got introduced somehow through your editor or some other means when copying the file to the osx folder ?

**Comment by gingerbeardman** [comment]
They original file was at "pages/common/file.md" and the description ended in a colon.

**Comment by agnivade** [comment]
But this is the error that it gave - `pages/osx/fsck.md:3: TLDR004 Command descriptions should end in a period`. Are you sure it was file.md ? 

This is what I see in pages/common/file.md - `> Determine file type.`

**Comment by gingerbeardman** [comment]
OK ignore me, if it happens again I'll raise a new issue. I've even managed to confuse myself :)
