### ISSUE TITLE
Explanation of the abbreviation

### ISSUE THREAD

**Issue by vitkulov** [tldr-pages/tldr#1805]
Hello. I speak russian and I'm novice in linux. But one thing always interested me.
Why is there no verbatim interpretation of the abbreviation of command, (_where it's possible_) in help/man pages?

e.g.
**pwd** _(print working directory)_
**grep** _(«search **g**lobally for lines matching the **r**egular **e**xpression, and **p**rint them»)_

imho this allows you to better understand and remember the commands.

Do you plan to add this feature?

**Comment by agnivade** [comment]
You raise a valid point. Unix has its quirks. After years of usage, some things have become part of our lives so much that we don't think about it.

The tldr page of `pwd` does say `Print name of current/working directory`. Although, it's not a direct expansion but I think you can figure out what `pwd` stands for. FWIW, my native language is also not English.

I believe acronyms like these are handful. We can try to include the expansion of them in the heading. Do you have more examples like these ?

**Comment by vitkulov** [comment]
No, i don't have more. Anyway I'm trying to search it in google or wiki.
It's just a question that has interested me for a long time. And this is a problem not only for unix.
Almost all the reference books never explain this.

**Comment by agnivade** [comment]
Ok if it is only these 2, I think we can live with it. Thanks for raising the issue.

**Comment by sbrl** [comment]
Indeed, I'd never thought of that! acronyms.thefreedictionary.com appears to have a category for unix commands, if that helps. Other than that, yeah, explaining the expansion in the description sounds like a good idea.

**Comment by Victor-IT** [comment]
Where in the source tree can I see how many commands have already been made?
I can try to add abbreviations and create a pull request later.

**Comment by agnivade** [comment]
They are inside the pages/ folder.

**Comment by sbrl** [comment]
Each folder in pages/ is a separate platform, with each file in each platform folder being for a different command.
