### ISSUE TITLE
page request: runit

### ISSUE THREAD

**Issue by alexbuzzbee** [tldr-pages/tldr#1808]
`runit` is an alternative init system for various Unix-like OSes. It doesn't currently have `tldr` pages for its several commands. The programs in the `runit` suite include:

* `runsv` - The most important part, manages a single service/daemon.
* `runsvdir` - Starts and monitors multiple services using `runsv` from a directory.
* `runsvchdir` - Changes "runlevels."
* `sv` - Talks to `runsv` to control a service.
* `runit` - Acts as an init daemon: runs a startup script, starts `runsvdir` on the default "runlevel," responds to signals, and finally shuts down the machine.

There are also some ancillary tools, such as a logging service and a substitute `/sbin/init` that `exec`s the main `runit` program.

The main `runit` docs can be found [here](http://smarden.org/runit/).

**Comment by sbrl** [comment]
Thanks for requesting this page, @alexbuzzbee! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
