### ISSUE TITLE
mktemp option --directory should be -d

### ISSUE THREAD

**Issue by g-ongenae** [tldr-pages/tldr#1836]
Hello,
I wanted to create a tempory directory as the [tldr page](https://github.com/tldr-pages/tldr/blob/master/pages/common/mktemp.md) says, I tried running `mktemp --directory` on OSX and got the following output:
```bash
$ mktemp --directory
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

From the manual page of [mktemp](https://www.mktemp.org/manual.html), `--directory` option is not listed and a [linux manual page](http://man7.org/linux/man-pages/man1/mktemp.1.html) for `mktemp` seems to allow both `-d` and `--directory`, thus I think tldr manual page for mktemp should list `-d` and not `--directory`.

Also, thank you for this great project.

**Comment by sbrl** [comment]
Good spot - thanks! Perhaps you'd like to send a pull request to update this?
