### ISSUE TITLE
page request: lrzip

### ISSUE THREAD

**Issue by eukaryote31** [tldr-pages/tldr#1849]
lrzip is a compression program for very large files.

Other commands of lrzip: `lrztar`, `lrz`, `lrzuntar`, `lrunzip`

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself, @eukaryote31?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by russsaidwords** [comment]
I put in a PR for lrzip, it's at #2436.

**Comment by pxgamer** [comment]
Looks like this was closed by PRs #2436, #2453, #2456 and #2450 👍
