### ISSUE TITLE
page request: envsubst

### ISSUE THREAD

**Issue by ahmetb** [tldr-pages/tldr#1862]
I don't know how to use it myself so can't contribute.

**Comment by ahmetb** [comment]
this doesn't show up on my tldr setup even after updating through --update. I'm using zsh on macOS. I have the gnu gettext package, so I should be able to use it. Any ideas why it's not showing up on macOS?

**Comment by sbrl** [comment]
@ahmetb Hrm. Sometimes it can take a day or two for it to come through. What client are you using?
