### ISSUE TITLE
tldr organisation

### ISSUE THREAD

**Issue by rprieto** [tldr-pages/tldr#188]
Hi @felixonmars, @edgurgel, @danzimm, @pranavraja.

As suggested by @shrayas, I moved `tldr` and `tldr-node-client` to a new [tldr-pages](https://github.com/tldr-pages/tldr) organisation. Let me know if you want to move the other clients over there too, so they're easy to find. I'll make sure you have admin rights on the repos over there!

**Comment by aloisdg** [comment]
@pranavraja any news related to the archlinux package?
