### ISSUE TITLE
New collaborator additions

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#1885]
Hi, @pxgamer and @jsonbruce! You seem to be enjoying contributing to the tldr-pages project. You now have had at least five distinct pull requests merged each, which qualifies you to become a collaborator in this repository, as explained in our (brand new!) [governance guidelines](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md).

As a collaborator, you will have commit access and can therefore merge pull requests from others, label and close issues, and perform various other maintenance tasks that are needed here and there. Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

Thanks for all your work so far!

**Comment by waldyrious** [comment]
(I took the liberty to tweak the text above, @agnivade, to adjust the links and the wording a bit.)

**Comment by jsonbruce** [comment]
Thanks, I'm so happy to get your invitation. @agnivade

**Comment by agnivade** [comment]
ping @pxgamer

**Comment by pxgamer** [comment]
Apologies for the delay, I have just been thinking about the invite. I'd be happy to help. :+1:

**Comment by agnivade** [comment]
Great. Thanks ! Closing this now since both of you have accepted the invitations. Welcome :)

**Comment by sbrl** [comment]
Welcome aboard, @jsonbruce and @pxgamer! :D

**Comment by maxsxu** [comment]
@sebastiaanspeck Thanks for reminding, and yes, the GitHub username changed to @maxsxu
