### ISSUE TITLE
feature request: Allow for proxy to man page

### ISSUE THREAD

**Issue by viztor** [tldr-pages/tldr#1922]
allow user to bypass -m to access man cmd. useful for users want substitute man with tldr.

**Comment by agnivade** [comment]
Firstly, this repo is for the tldr pages. You should file this issue in a client repo.

Secondly, this won't be possible for windows users. 

Now coming to your point, frankly its overcomplicating a simple thing when somebody can just type the `man` command instead. Use `tldr` normally, and use `man` when you want the man page. Adding another flag to open the man page does not seem like an elegant solution to me.

**Comment by sbrl** [comment]
What's wrong with something like this?

```shellsession
~$ tldr some_command
<tldr-page shows>
~$ ^tldr^man
<man page opens>
```

**Comment by pxgamer** [comment]
I'd agree with @agnivade on this. `man` is both 1 character shorter to type, and doesn't require additional bulk in the clients.

Unless you are meaning that you've aliased `man = tldr`. In which case, I'm not sure what would be the best option.

**Comment by agnivade** [comment]
@viztor - Let me know your thoughts on this.
