### ISSUE TITLE
page request: trap

### ISSUE THREAD

**Issue by chamini2** [tldr-pages/tldr#1924]
https://www.gnu.org/software/bash/manual/bashref.html
http://basiclinuxcommand.com/linux-command/trap.html

**Comment by pxgamer** [comment]
Thanks for requesting this page! Do you want to have a go yourself, @chamini2?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
