### ISSUE TITLE
Add collaborators retroactively

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#1949]
Since #1839 and #1897, we now have [explicit guidelines](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#when-to-change-roles) for when to invite regular contributors to become collaborators in the repository.

As I mentioned in #1878 (particularly in the opening comment, and in [this one](https://github.com/tldr-pages/tldr/issues/1878#issuecomment-358644482)), for now we just added the contributors who have been particularly active recently (@pxgamer and @jsonbruce), but we'll eventually want to parse the entire [list of contributors](https://github.com/tldr-pages/tldr/graphs/contributors) and assess them against the newly adopted thresholds.

Besides it being only fair to apply the same metrics to everyone, it would also very beneficial for the project to do this: we'd be empowering a bunch of prolific contributors to help out with management and onboarding, and perhaps we'll even spark one or two back to more active participation.

In case anyone wants to tackle this, some potentially helpful notes can be found in the entry a) of #1878's opening comment. Otherwise, I'll try to carve out a suitable time slot do do this (although I suspect it may take a while until I get that kind of availability).

**Comment by zdroid** [comment]
What's actually the issue in this? Every contributor in the list has at least 5 commits, which fits the threshold.

Now, if you want it to be automated, there may be a solution. tldr-bot can watch for every merge, and check if the number of PRs merged by PR's author so far on https://github.com/tldr-pages/tldr/pulls?utf8=%E2%9C%93&q=is%3Amerged+is%3Apr+author%3A{{name}} (where only `{{name}}` needs to be changed).

**Comment by waldyrious** [comment]
> Every contributor in the list has at least 5 commits, which fits the threshold.

The threshold is not 5 commits, though. Quoting the linked page:

> once a contributor has had _5 non-trivial pull requests merged_

So one would have to manually assess the PRs in order to validate this threshold. 

(Of course, this metric can be questioned if we think we could get another one that is easier to apply while still working as a good predictor of future contributions.)

**Comment by zdroid** [comment]
That's true, but I put it this way on purpose. How wrong is it to assume someone with 6-7 commits has at least 5 PRs merged?

**Comment by agnivade** [comment]
There's no urgency to add collaborators. I would prefer that we keep it manual so that a human element is maintained. It may be lengthier, but there is no urgency to finish it quickly also.

**Comment by sbrl** [comment]
Also, you can filter PRs by merged + author, which is what I do when opening issues for role changed.

**Comment by CleanMachine1** [comment]
I am going to close this PR, since it is more than stale and there is no real reason to add contributors who have clearly stopped contributing.

Contributors have been added as they contribute actively (at least while I have started).

Feel free to open agagin if you disagree.
