### ISSUE TITLE
No fsck man page

### ISSUE THREAD

**Issue by stephane-archer** [tldr-pages/tldr#1950]

**Comment by agnivade** [comment]
```
./pages/linux/fsck.md
./pages/osx/fsck.md
```

Am I missing something ?

**Comment by stephane-archer** [comment]
Why https://tldr.ostera.io/fsck is not working?

**Comment by agnivade** [comment]
You might want to raise an issue at https://github.com/ostera/tldr.jsx/issues. This repo is only for pages. Alternatively, you can also use our command line clients.

Cheers.

**Comment by gingerbeardman** [comment]
@stephane-archer if you read that page you have to specify your platform 'osx/fsck' or 'linux/fsck'

https://tldr.ostera.io/osx/fsck
