### ISSUE TITLE
Rename "common" directory to "unix"?

### ISSUE THREAD

**Issue by colinmorris** [tldr-pages/tldr#1960]
According to comments on #1930, pages listed under `common/` must be available (natively) on all platforms, including Windows.

"For historical reasons" (presumably the fact that [the Windows platform was added fairly recently](https://github.com/tldr-pages/tldr/issues/1579)), the commands currently under `common/` don't all meet that requirement. 

In fact, if someone did clean up `common/` to enforce that requirement, I think it would go from 532 commands, to... less than 5? I don't have much Windows experience, but based on some searching, it seems like the few commands it has in common with the other OSes (`ping`, `more`, `sort`, `find`) differ significantly in their usage. The only command I could find in `common/` whose examples would run on Windows was `whoami`.

The other three platforms (linux, OSX, SunOS), are all unix-based, and have a lot of commands in common for that reason. A directory encompassing those 3 platforms (i.e. what `common/` used to refer to), is useful, and saves a lot of duplication of content.

Windows has no common ancestry with them. A directory for commands common to all 4 OSes isn't very useful. (Though if someone wants to create it *in addition to* renaming `common` -> `unix/`, I wouldn't particularly object. It'd just be very small.)

**Comment by pxgamer** [comment]
I slightly disagree with renaming it due to the massive backwards compatibility issue. I do think though that there could be a `unix-common` directory (which has been mentioned before by @agnivade).

A lot of the commands in `common` I know run on Windows. More than just `whoami`. :thinking:

**Comment by colinmorris** [comment]
What's the backwards compatibility issue?

> A lot of the commands in common I know run on Windows. More than just whoami.

Could you give some examples? Just curious - like I said, I'm not very familiar with Windows.

**Comment by pxgamer** [comment]
Most clients use the `common` directory as the common location for finding pages. Suddenly renaming it would probably break quite a few of them. I guess the other thing would be that a lot of them do work on Windows, and therefore wouldn't be available on Windows clients without specifying `--os unix`.

Regarding the commands that run on Windows, there are a load of compilers (clang, cmake, make), editors (nano, atom, sublime, etc.), archive tools (7z) shells (bash, sh) and general tools (cp, mv, curl, wget, apm, composer, node, etc.) that all work on Windows using `cmd` if they are installed.

In fact, I use a lot of them on a daily basis through Git for Windows' `usr/bin` directory.

**Comment by colinmorris** [comment]
I don't know what the canonical definition of "available natively on Windows" is, but I don't think the one you're working with agrees with the one the commenters on #1930 had in mind. That PR added a page for `case`, which is an sh/bash keyword. If those shells were counted as available on Windows, there wouldn't have been a problem including it in `common/`.

**Comment by pxgamer** [comment]
Fair enough. :+1:

I don't use the shells though. Only pure `cmd`. `case` isn't available through cmd. But executables are. I'm sure others can discuss this in a better way than me. :smile:

**Comment by agnivade** [comment]
The definition is not "natively" available on windows. Then we wouldn't have any "installable" tools anywhere in our repo. :smile:  Anything that you can "install" or "compile and run" in Windows is fair game. Can you install bash in windows ? If yes, then sure `case` can be added. If not, then no.

Renaming `common` to `unix` will break conventions. We _need_ to have a folder common to all platforms. Along with it, we need to have a `unix-common` folder for *nix commands. 

Sorry if I have caused any confusion.

**Comment by colinmorris** [comment]
> The definition is not "natively" available on windows. Then we wouldn't have any "installable" tools anywhere in our repo. :smile: 

Okay, I was just quoting @sbrl's comment on #1930. I don't know if they're working under a different definition or if they just misspoke. Either way, I think this is a good indication that this should be documented somewhere (probably under the contributor guidelines?). I opened an issue for this here: #1965. 

As for the original renaming proposal, I just noticed it's basically a dupe of #1868, so I'm going to close this in favour of that one. (My contention with this issue was mostly that a directory for the unix-based OSes would be a very useful thing to have. I'm pretty agnostic on whether it should be called "common" or "unix-common" or something else.)

**Comment by gingerbeardman** [comment]
Interesting discussion and some overlap with my issue https://github.com/tldr-pages/tldr/issues/1953

whilst `unix-common` is a noble idea, I do not think it will work for the simple reason that whilst commands of the same name exist across unix platforms the majority of them have different arguments across platforms. 

example: synopses for find (i know these don't list all arguments but it demonstrates the issue)

BSD/macOSX [ref](https://www.freebsd.org/cgi/man.cgi?find(1))
`find [-H |	-L | -P] [-EXdsx] [-f path] path ... [expression]`

Linux [ref](http://man7.org/linux/man-pages/man1/find.1p.html)
`find [-H] [-L] [-P] [-D debugopts] [-Olevel] [path...] [expression]`

**Comment by gingerbeardman** [comment]
Also see https://github.com/tldr-pages/tldr/issues/1966

**Comment by gingerbeardman** [comment]
@colinmorris I agree with you 100% - bravo!
