### ISSUE TITLE
One command missing

### ISSUE THREAD

**Issue by Majestcx** [tldr-pages/tldr#1962]
There is no page for "uname" command, you could create it?

**Comment by agnivade** [comment]
It already exists.

```
./pages/linux/uname.md
./pages/osx/uname.md
```

**Comment by sbrl** [comment]
Which client are you using, @Majestcx?

**Comment by agnivade** [comment]
Try - https://tldr.ostera.io/osx/uname or https://tldr.ostera.io/linux/uname

**Comment by sbrl** [comment]
Perhaps a bug could be filed against tldr-pages/tldr-pages.github.io, @Majestcx?

**Comment by agnivade** [comment]
This is a bug in the web client, not the github pages repo. You should file a bug here - https://github.com/ostera/tldr.jsx/

**Comment by sbrl** [comment]
Ah, thanks, @agnivade! I had difficulty locating the repo for the web client.
