### ISSUE TITLE
page request: ldapsearch

### ISSUE THREAD

**Issue by grafuls** [tldr-pages/tldr#2056]
ldapsearch command can be pretty complex, would be nice to see this here.
https://linux.die.net/man/1/ldapsearch

**Comment by sbrl** [comment]
Thanks for requesting this page, @grafuls! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by lamar-frankie** [comment]
I'd like to claim this issue. If @grafuls hasn't started working on it.

**Comment by grafuls** [comment]
@lamar-frankie I haven't got the time to get to it, all yours.

**Comment by lbonanomi** [comment]
Is this issue up-for-grabs?

**Comment by sbrl** [comment]
It looks like it, @lbonanomi. Go ahead :-)

**Comment by lbonanomi** [comment]
LDAP is mature enough to have spawned several "standard" clients across different platforms, so I opened a draft PR (https://github.com/tldr-pages/tldr/pull/2915) for the generic features that appear across both Linux and SunOS clients. 

The major difference seems to be support for timelimit, sizelimit and extensions; Linux has these, SunOS' stock ldap client doesn't. Would it be appropriate to maintain Linux and SunOS pages independently to show Linux users all their options without teasing SunOS users?

**Comment by schneiderl** [comment]
Hi @lbonanomi 
I think that the way to go: having two pages.
1 under common/linux and 1 under common/sunos.

Would you send a PR with the proposed changes?

**Comment by lbonanomi** [comment]
https://github.com/tldr-pages/tldr/pull/2915 has been upgraded to a regular PR.

I'd appreciate feedback about any examples maintainers think could be dropped, I'd like to add a line for result-paging on the Linux client but don't want to violate the 8 examples limit without a formal go-ahead.

**Comment by sbrl** [comment]
Thanks, @lbonanomi! I'm not sure which example we could drop.

**Comment by lbonanomi** [comment]
@sbrl I hate to nag but is there anything left to be done on this issue before it gets closed?

**Comment by agnivade** [comment]
Nope. In future, you can use the "Fixes #issue_no" string in a PR, which will automatically close an issue when the PR is merged.

**Comment by lbonanomi** [comment]
Thank you @agnivade!
