### ISSUE TITLE
Error output in python virtualenv environment

### ISSUE THREAD

**Issue by Zminghua** [tldr-pages/tldr#2062]
I install tldr with command 'npm install -g tldr', everything is fine with tldr.
then i enter the python virtualenv environment, 
when i typed 'tldr tar', i got the following ouptut:

Usage: tldr [OPTIONS] COMMAND [ARGS]...

Error: No such command "tar".

**Comment by sbrl** [comment]
Hey there, @Zminghua! If you're still experiencing issues, I'd recommend heading over to the repository of the python client and submitting an issue there, as this repository is only for the pages themselves.

Thanks! :-)
