### ISSUE TITLE
page request: mail

### ISSUE THREAD

**Issue by chamini2** [tldr-pages/tldr#2065]
`man mail`

**Comment by chamini2** [comment]
When I do `man mail` I get

>  MAIL(1)                                                                                                BSD General Commands Manual                                                                                               MAIL(1)
> 
> NAME
>      mail, mailx, Mail — send and receive mail
> 
> SYNOPSIS
>      mail [-dEIinv] [-a header] [-b bcc-addr] [-c cc-addr] [-s subject] to-addr ...
>      mail [-dEIiNnv] -f [file]
>      mail [-dEIiNnv] [-u user]
> 
> DESCRIPTION
>      mail is an intelligent mail processing system which has a command syntax reminiscent of ed(1) with lines replaced by messages.
> 
>      The options are as follows:
> 
>      -a      Specify additional header fields on the command line such as "X-Loop: foo@bar" etc.  You have to use quotes if the string contains spaces.  This argument may be specified more than once, the headers will then be con‐
>              catenated.
> ...

*****

I do not know how to use it well! I was surprised that it wasn't in tldr already.

**Comment by pxgamer** [comment]
Looks like it's different across different Linux distros. :thinking:

**Comment by sbrl** [comment]
Looks like we already have a page for that, @chamini2! It's under `mailx` - one of that particular `mail` command's aliases.

**Comment by chamini2** [comment]
Cool, thanks! Maybe an alias in tldr would be good?

**Comment by sbrl** [comment]
No problem, @chamini2 :-)

If you're interested in alias support, head on over to issue #787!
