### ISSUE TITLE
history: add expansion commands

### ISSUE THREAD

**Issue by willthemoor** [tldr-pages/tldr#2066]
These aren't specific single commands but it's one of those things I find myself looking up. How to get the last argument used, re-running the last command starting with X, etc.

~Since it's not a specific command, I'm not sure 1) if it's out of scope for this project and/or 2) what to use as a trigger (`tldr history`?).~ Edit: missed the existing file.

Not sure if there's value in having both a general 'Using History' page (searching, up arrow, `$  <- space to omit`...) and a more specific 'History Expansion' page (`!!`, `!$`...).

Happy to take crack at expanding the current history file and/or creating a new history expansion file.

Couple of sample pages:

1. https://www.thegeekstuff.com/2011/08/bash-history-expansion/
2. https://www.howtogeek.com/howto/44997/how-to-use-bash-history-to-improve-your-command-line-productivity/
3. https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps

**Comment by agnivade** [comment]
We already have https://github.com/tldr-pages/tldr/blob/master/pages/common/history.md. Are you referring to something else ?

**Comment by willthemoor** [comment]
Oops, I missed that one, sorry @agnivade. Will edit the title.

I guess the updated question is: is it worth updating that with history expansion commands? Or a new, separate history-expansion.md?

**Comment by agnivade** [comment]
Yes, feel free to add to the page.

**Comment by bl-ue** [comment]
Finally! 🚀
