### ISSUE TITLE
Feature request: A brief history

### ISSUE THREAD

**Issue by saatchimatt** [tldr-pages/tldr#2103]
In the tar example in the readme, it shows that the first man page argument deals with tape drives, which these days for majority of people using it is definitely useless. But it may be helpful to include a brief history on each command, like for tar - it could be something like: History: the command tar is derived from Tape Archive and was originally created to write data to tape drives.

Just curious if there would be any interest in this.

**Comment by agnivade** [comment]
I don't think it will be useful. The spirit of this project is to be short and to the point, aka tldr. We deliberately limit the no. of examples in each page to be 8 just for this reason. Adding a separate section on the history of a command goes against that idea.

Plus, we need to add a new section to display the history. This needs to be implemented by all clients. At this point, it is a non-trivial, if not almost impossible task.

**Comment by agnivade** [comment]
@saatchimatt - I am going to close the issue. Feel free to raise a new issue if you have other ideas like these. Thanks !
