### ISSUE TITLE
color highlighting

### ISSUE THREAD

**Issue by cryptozeny** [tldr-pages/tldr#2109]
tldr is working, but `color highlighting` is not work as advertised... 

```
tldr 3.2.3
npm 5.6.0
node v8.11.1
```

![ADVERTISED...](https://github.com/tldr-pages/tldr/blob/master/screenshot.png)

this command is working, however how to set this theme to default?
```bash
$ tldr --theme ocean tar
```

**Comment by agnivade** [comment]
See this - https://github.com/tldr-pages/tldr-node-client#configuration.

This is the repo for the pages. If you still face issues - please file an issue on the tldr-node-client repo.

Thanks.

**Comment by CottonEaster** [comment]
I think a mention of this matter on the main github page would be a good idea. It's come up twice as an issue - for, see also #1688.

**Comment by agnivade** [comment]
That would be catering to the issue of a specific client. There are other clients in different programming languages. We want the main repo to be neutral and focused on just page content.
