### ISSUE TITLE
fswatch command does not work for OS X

### ISSUE THREAD

**Issue by ptzz** [tldr-pages/tldr#2119]
> - Run a bash command on file creation, update or deletion:
>
> `fswatch -0 path/to/file | xargs -0 bash_command`

This does nothing for me on macOS X with `fswatch` version 1.11.3. For anything to happen, I need to add either `-n1` or `-I{}` to the `xargs` command.

In the example with xargs at https://github.com/emcrisostomo/fswatch, `-n1 -I{}` are passed to xargs.

**Comment by sbrl** [comment]
Hey, good spot! Thanks for flagging this. Would you like to have a go at editing it yourself?

Pages are best edited by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of editing a page. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
