### ISSUE TITLE
page request: ls

### ISSUE THREAD

**Issue by josephmcasey** [tldr-pages/tldr#2124]
[Based on an answer provided in this Linux StackExchange conversation](https://unix.stackexchange.com/questions/70614/how-to-output-only-file-names-with-spaces-in-ls-al
), It seems like showing people how to list only the files is particularly useful for anyone planning on using the pipe operator with xargs. 

- Lists only file names with one file name per line
`ls -A1`

**Comment by agnivade** [comment]
@josephmcasey - Thank you for raising the issue.

With tldr pages, we do not aim to provide all possible usages of a command. We just try to focus on the most useful ones that people will use.

Given this scenario, we already have `ls -1` and `ls -a`. So an user can already construct `ls -a1`. I think this is as far as we should go. The `-A` option is rare and I don't think that should be in a tldr page. If the user needs more knowledge, he/she can always refer to the man page.

**Comment by sbrl** [comment]
Hrm, I have `-A` in my various ls aliases, actually. I find the listing of `.` and `..` to be rather annoying. I've vote for changing `-a` to `-A`, actually.

**Comment by agnivade** [comment]
ping @CBrowne , @notpeter for more opinions.

**Comment by pxgamer** [comment]
I think this is kind of an interesting point. I've never used `-A`, but it seems like possibly a better option despite seemingly being used less frequently.

I guess the only place without `..` would be `/`? And `.` is always going to exist. :thinking:

Personally I'd vote to stick with `-a`, solely because I prefer listing everything, no matter whether they are semi-useless in a lot of cases.

**Comment by sbrl** [comment]
@pxgamer You'd think so, but apparently `/` has a `..` too O.o

Especially when automating things, I feel that `.` and `..` are kind of redundant. I know that they exist - I don't need `ls` to tell me - and technically are _aren't_ actually files in the directory I've invoked `ls` in anyway....

**Comment by pxgamer** [comment]
@sbrl, well that's really weird. :joy:

True about your point with automation, if they always exist then you are right about them being virtually redundant, so maybe I'll change my stance to `-A` lol

**Comment by agnivade** [comment]
The .. at `/` points to itself. Both the single dot(.) and double dots(..) are bread and butter for command line users. I would rather have tldr show full output than hide it for brevity.

**Comment by sbrl** [comment]
Huh, I guess it's down to personal taste, then - I don't find myself using it personally - and I spend quite a bit of time in a terminal.

**Comment by notpeter** [comment]
I don't have a strong preference, obviously `ls -la` or `ls -a` are the much more common incantations for most of us, but I'd actually be for `ls -A` replacing `ls -a` because life without seeing `.` and `..` is just better.

Note: there's no need to use `ls -A1` with pipelines, ls detects when stdout is a pipe and automatically puts one entry per line. (ls is fancy like that)

**Comment by agnivade** [comment]
Ok, as I see this, the arguments for removing `.` and `..` are just that it looks better. @sbrl - Surely you would use `..` to `cd` to a parent directory ? :smile: 

Keeping newbies in mind, who are yet to understand the relevance of `.` and `..`, I would rather keep it and let people understand the significance of them.

If there are no further objections, let us end the discussion and close this issue ?

**Comment by sbrl** [comment]
Yeah, I do use `cd ..` (actually I have a set of aliases: `..`, `...`, `....`, etc.) - but personally I found it very confusing as to why `.` and `..` were appearing in a list of items in a directory (why would a directory and it's parent be inside said directory? It makes no sense!). To this day I'm still unsure as to why that is - I assume it's an implementation detail or something?

We may as well close this issue though, I guess? I'm unsure.

**Comment by agnivade** [comment]
> (why would a directory and it's parent be inside said directory? It makes no sense!).

Those are just entries to the current and parent directory. Don't think of them as items containing inside a directory. Rather, as places you can go from the directory.

Does that make sense ?

**Comment by agnivade** [comment]
@sbrl - Just checking whether you are good with this.

**Comment by sbrl** [comment]
@agnivade Ah, thanks for the reminder! Between final exams and finishing up at University, this must have slipped though the net. Yeah, I'm ok with this :smiley_cat:
