### ISSUE TITLE
page request: kext* utilities (macOS)

### ISSUE THREAD

**Issue by ldorigo** [tldr-pages/tldr#2130]
`kextload`, `kextunload`, `kextfind`, `kextlibs`, `kextstat`, `kextutil` are all command line utilities used to manage Kernel Extensions on macOS. They are all missing from tldr!

- [ ] `kextload`
- [ ] `kextunload`
- [ ] `kextfind`
- [ ] `kextlibs`
- [ ] `kextstat`
- [ ] `kextutil`

**Comment by sbrl** [comment]
Thanks for requesting these pages! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by bl-ue** [comment]
@ldorigo have you ever gotten back to this?

**Comment by Managor** [comment]
Since kmutil has replaced kext tools as per #6550, I'm closing this issue. If these commands are still in use, please reopen the issue.
