### ISSUE TITLE
page request: nl

### ISSUE THREAD

**Issue by SanjanaSunil** [tldr-pages/tldr#2142]
Command to number lines of a file.

Refer:
http://man7.org/linux/man-pages/man1/nl.1.html
https://linux.die.net/man/1/nl

**Comment by agnivade** [comment]
We already have a page for `nl`. Are you facing any issues seeing it ?

**Comment by SanjanaSunil** [comment]
I was facing issues facing it - but searched and have found it. Thank you and sorry!

**Comment by agnivade** [comment]
No probs.

**Comment by sbrl** [comment]
@agnivade It seems like we have several issues like this. I assume it's to do with platform-specific pages not displaying on other platforms (e.g. on Windows a `linux` page doesn't show if there isn't one registered in `windows`)? It's client-specific thing, but I was wondering if there's any specific client to blame for this. Perhaps if it could be tracked down, then I could take a look at improving the documentation there in a PR?

**Comment by agnivade** [comment]
Yea .. maybe the client can point out that the page you are looking for exists for another platform. @SanjanaSunil - what was the issue that you were facing ?

**Comment by SanjanaSunil** [comment]
@agnivade The issue is similar to what @sbrl mentioned - platform-specific pages. I was looking at a platform different from the one I was supposed to. Improving the documentation would help this.

**Comment by agnivade** [comment]
Which client were you using ?
