### ISSUE TITLE
Addition of libc functions?

### ISSUE THREAD

**Issue by nbulischeck** [tldr-pages/tldr#2151]
It's a rather large undertaking and may not be one suited for the goals of the project, but would the developers accept a PR that contained `tl;dr`'s of libc functions? I commonly find myself needing a quick reference to libc functions more often than I do `tar` and friends.

For example:

# free

> Free dynamic memory.

- Prototype:

`void free(void *ptr);`

- Return Value:

`None`

- Behavior:

`The free() function frees the memory space pointed to by ptr. If free(ptr) has already been called before, undefined behavior occurs. If ptr is NULL, no operation is performed.`

Or a slightly more useful reference for beginners would be to have a quick example of using the function:

# free

> Free dynamic memory.

- Prototype:

`void free(void *ptr);`

- Return Value:

`None`

- Example:

```
char *ptr = malloc(1);
free(ptr);
```

**Comment by agnivade** [comment]
Sorry, I'm afraid this is not the goal of this project. Feel free to fork it though and use it as you feel. 

In general, we do not _just_ aim to be a cheat sheet sort of thing where you can just look up something in case you don't remember. Rather, we create pages that is helpful for the user to understand what a command does and learn its basic usage.

Also, there is a command called `free`, which would clash with this. :wink:

**Comment by nbulischeck** [comment]
I'd have to say that the description is "community-driven man pages" and the libc programmer manual is a hefty part of the man pages 😉

But if it truly doesn't fit the goals of the project, feel free to close unless anyone else has some input. Thank you for your consideration!

**Comment by sbrl** [comment]
Yeah, I'm inclined to agree that this doesn't fit within the aims of this project. Although, if it were to be included, I'd suggest a separate 'platform' for libc pages. It certainly sounds like something useful to have.

I didn't even know the man pages included that kind of thing! Though to be honest, the one for `free()` doesn't look particularly useful (there aren't any examples for one), so there's certainly some work that could be done there.

**Comment by agnivade** [comment]
@sbrl - Oh yes, there is extensive documentation (including examples!) for libc functions. :smile:
