### ISSUE TITLE
page request: <nokogiri>

### ISSUE THREAD

**Issue by Mozart409** [tldr-pages/tldr#2164]
https://www.rubydoc.info/github/sparklemotion/nokogiri

**Comment by sbrl** [comment]
Thanks for requesting a page on `nokogiri`, @Mozart409! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
