### ISSUE TITLE
page request: svgcleaner

### ISSUE THREAD

**Issue by daylightbrightledlight** [tldr-pages/tldr#2179]
Command name: `svgcleaner`
Repo: https://github.com/RazrFalcon/svgcleaner
Documentation: https://github.com/RazrFalcon/svgcleaner/blob/master/docs/svgcleaner.adoc
Page:

```
# svgcleaner

> SVG image optimizing utility.

- Compress an SVG image:

`svgcleaner {{input.svg}} {{output.svg}}`
```

**Comment by sbrl** [comment]
Thanks for requesting this page! Have you considered opening a pull request with that page info?

If you'd like to, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository.

If you need any assistance, just ask :-)

**Comment by daylightbrightledlight** [comment]
So from https://github.com/tldr-pages/tldr/pull/2182#pullrequestreview-136091151, @agnivade mentions that there are a couple more options. Having used the command, I know that there are way too many options to put into the tldr page.

Which options are most commonly used?

**Comment by agnivade** [comment]
Since you have used the command, it is upto you to decide what options are necessary for day to day use.

If you think just 2 is fine, I am good with it. I just saw that there are lot more options, and we have space to accommodate a couple more. There is no requirement to add more options if they are not used commonly.

**Comment by daylightbrightledlight** [comment]
I accidentally closed the PR https://github.com/tldr-pages/tldr/pull/2182. Can someone reopen it?
