### ISSUE TITLE
print() is a function in Python 3

### ISSUE THREAD

**Issue by cclauss** [tldr-pages/tldr#2185]
Python 3 syntax error:
* https://github.com/cclauss/tldr/blob/master/scripts/send_to_bot.py#L16

**Comment by agnivade** [comment]
This code is run inside travis. I think travis runs in python2. Feel free to send a PR updating the `.travis.yml` to explicitly run python3 along with the new code.

**Comment by sbrl** [comment]
Updating to Python 3 is probably a good idea :P
