### ISSUE TITLE
page request: aspell

### ISSUE THREAD

**Issue by Wesalius** [tldr-pages/tldr#2189]
interactive spell checker - [man page](https://linux.die.net/man/1/aspell), [git repo](https://github.com/GNUAspell/aspell)

**Comment by Wesalius** [comment]
tried to contribute myself at [this PR](https://github.com/tldr-pages/tldr/pull/2193)

**Comment by sbrl** [comment]
Thanks for the contribution, @Wesalius! It looks great. I've left a few comments on the PR though to help bring it closer to what our other pages look like for consistency :smiley_cat:
