### ISSUE TITLE
List of GNU Core Utilities commands missing in tldr

### ISSUE THREAD

**Issue by Wesalius** [tldr-pages/tldr#2213]
I compared [GNU Core Utilities commands list](https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands) with contents of tldr/pages and found out that the following are missing from tldr:

* [x] arch
* [x] b2sum
* [x] chcon
* [x] csplit
* [x] dircolors
* [x] dirname
* [x] factor
* [x] false
* [x] fmt
* [x] groups
* [x] hostid
* [x] join
* [x] link
* [x] logname
* [x] mknod
* [x] nproc
* [x] numfmt
* [x] pathchk
* [x] pinky
* [x] pr
* [x] printenv
* [x] ptx
* [x] realpath
* [x] runcon
* [x] stdbuf
* [x] stty
* [x] true
* [x] tsort
* [x] unlink
* [x] users
* [x] vdir

We are missing 31 from the 101 commands listed in the list, so I am posting them here just in case anyone is looking for ideas for what to add to tldr :-)

**Comment by sbrl** [comment]
Hey, thanks for the list! I've edited your comment to add checkboxes. Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by ronniegane** [comment]
`csplit` added in https://github.com/tldr-pages/tldr/pull/2571

**Comment by andrik** [comment]
chcon added in #2895

**Comment by schneiderl** [comment]
Congrats for those involved in closing this 😄

**Comment by sbrl** [comment]
Hey, wow! Looks like we're got em all :D

Closing this tracking meta-issue.

(Does anyone have any other cool lists we could work on next?)

**Comment by waldyrious** [comment]
> (Does anyone have any other cool lists we could work on next?)

There's #1162 (which is only missing `notmuch` and `finch`), and #2214 (which still has a bunch to be added). 😉

**Comment by sbrl** [comment]
Great idea @waldyrious! I'll do that now.
