### ISSUE TITLE
List of util-linux commands missing in tldr

### ISSUE THREAD

**Issue by Wesalius** [tldr-pages/tldr#2214]
I compared [List of util-linux commands](https://en.wikipedia.org/wiki/Util-linux#Included) with contents of tldr/pages and found out that the following are missing from tldr:

* [x] addpart
* [ ] agetty
* [x] blkdiscard
* [x] blkid
* [ ] blockdev
* [x] cfdisk
* [x] chcpu
* [x] chfn
* [x] chrt → #5398
* [ ] col
* [ ] colcrt
* [x] colrm
* [x] ctrlaltdel
* [x] delpart → #11135
* [x] eject
* [ ] fdformat
* [x] findfs
* [x] flock
* [ ] fsck.cramfs
* [ ] fsck.minix
* [ ] fsfreeze
* [x] fstrim
* [x] getopt
* [ ] Hex
* [x] ipcmk
* [x] ipcrm
* [x] isosize
* [ ] ldattach
* [x] line
* [x] login
* [x] lslocks
* [x] lslogins
* [x] mcookie
* [x] mesg
* [x] mkfs
* [ ] mkfs.bfs
* [x] mountpoint
* [x] namei
* [x] newgrp
* [x] nologin
* [x] nsenter
* [x] partx
* [ ] pg
* [ ] pivot_root
* [x] prlimit→ #7113
* [x] raw → #6557 
* [ ] readprofile
* [ ] resizepart
* [x] runuser
* [x] script
* [x] scriptreplay
* [ ] setarch
* [ ] setpriv
* [x] setsid → #7841
* [ ] setterm
* [ ] sfdisk
* [ ] sulogin
* [x] swaplabel → #10462
* [ ] switch_root
* [ ] tailf
* [x] taskset
* [ ] tunelp
* [x] ul
* [x] unshare → #7920
* [x] utmpdump
* [x] uuidd
* [x] uuidgen
* [x] vipw
* [x] wdctl→ #7112
* [x] wipefs

We are missing 35 from the 107 commands listed in the list, so I am posting them here just in case anyone is looking for ideas for what to add to tldr :-)

**Comment by sbrl** [comment]
Thanks for this list! I've updated your comment to add checkboxes. Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by sbrl** [comment]
Erm `fstab` doesn't appear to be a page on my machine though.

**Comment by bl-ue** [comment]
We're down to 35 missing (of 70 @Wesalius listed).

**Comment by CleanMachine1** [comment]
Why have I never seen these, I will have to do a few when I spot one I can write documentation for.

**Comment by gutjuri** [comment]
The OP is outdated, could you please add checkmarks to:

- prlimit
- setsid
- swaplabel
- unshare
- wdctl

As these pages exist now.

**Comment by kbdharun** [comment]
> The OP is outdated, could you please add checkmarks

Done, thanks for letting us know.

**Comment by kbdharun** [comment]
**Update:** Thanks for this issue, it is now being tracked at #11827.
