### ISSUE TITLE
page request: systemd.directives

### ISSUE THREAD

**Issue by zbczyvgy** [tldr-pages/tldr#2233]
systemd tldr variations are not very informative and having a tldr with examples of unit files would have been pretty nice. RHEL has a [good page](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-managing_services_with_systemd-unit_files) on that topic.

**Comment by sbrl** [comment]
Hey, thanks for requesting this! Are you suggesting something like we have for `git` - where we have a page for each subcommand?

Do you want to have a go yourself? Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by rdnlsmith** [comment]
I took a shot at a page for [systemd.service](https://raw.githubusercontent.com/rdnlsmith/tldr/systemd_service/pages/linux/systemd.service.md), but the linter doesn't like the code blocks:

```
Error: Parse error on line 12:
...ription of Program[Service]# Default 
---------------------^
Expecting 'BACKTICK', got 'TEXT'
pages/linux/systemd.service.md:8: TLDR103 Command example is missing its closing backtick
pages/linux/systemd.service.md:10: TLDR102 Example description probably not properly annotated
Refraining from formatting because of fatal error
```

Are there any other file types which are currently documented in tldr? If not, is that something that you want to support? What needs to happen to make it work?

**Comment by agnivade** [comment]
We cannot have examples of unit files in the page. tldr pages are just meant to describe commands and their usages. Our scope is limited in that regard.

**Comment by rdnlsmith** [comment]
That’s fair. But that being the case, it sounds like this issue ought to be closed?

**Comment by agnivade** [comment]
If that's what @zbczyvgy intended, then yes. Sorry, but tldr pages is not the right place for detailed documentation like that.

**Comment by sbrl** [comment]
You're welcome to start your own project or fork ours though :smiley_cat:

**Comment by mebeim** [comment]
Closing because @zbczyvgy is talking about:

> having a tldr with examples of unit files [...]

which, as already explained, is not in the scope of tldr pages unfortunately.
