### ISSUE TITLE
Add @pxgamer as org member

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#2258]
Hi, @pxgamer ! After joining as a collaborator in the repository,
you have been regularly performing maintenance tasks. Thank you for that!
According to
[GOVERNANCE.md](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md),
you've now met the thresholds to be effectively considered
an active maintainer of the project.
To publicly acknowledge that fact, we'll add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public,
and (in case you don't already) start hanging out in our Gitter chat room.
You'll now be one of the public faces of the tldr-pages project.
Welcome aboard!

**Comment by pxgamer** [comment]
Thank you very much! :tada:

**Comment by agnivade** [comment]
You're welcome. Have fun !
