### ISSUE TITLE
page request: set

### ISSUE THREAD

**Issue by Tadaboody** [tldr-pages/tldr#2268]
Requesting a page for the built-in command [set](http://linuxcommand.org/lc3_man_pages/seth.html)

**Comment by pxgamer** [comment]
Thanks for requesting this page, @Tadaboody! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by mfrw** [comment]
Since this is **not** a command but a shell _**builtin**_, the options may differ from `zsh` to `bash` etc.
If we are to include this, what should be the correct way of taking this forward?
@agnivade @sbrl @pxgamer what are your suggestions :)

**Comment by sbrl** [comment]
Ooooh, good question @mfrw. I guess it depends on how different it is in the different shells, and whether we can get away with a selection of examples that work the same in all major popular shells :P

If not, then I'd probably suggest a 'stub' page that points to pages like `set-bash`, `set-zsh`, etc.

**Comment by mfrw** [comment]
@sbrl I think if we target the basic options, they probably should be the same but I am not sure.
I am planning to take this with just the bare bones options if i can find them on popular shells like `fish`, `zsh`, `bash` and the likes.
