### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by diegoperini** [tldr-pages/tldr#23]

**Comment by igorshubovych** [comment]
@diegoperini,

Thank you for suggestion. It seems like currently nobody created a page for `openssl`. Feel free to create a page yourself. We are accepting pull requests. Here is [Contributing guidelines](/tldr-pages/tldr/blob/master/CONTRIBUTING.md)

**Comment by waldyrious** [comment]
For future reference: while this shouldn't have been closed (see the other issues labeled "command"), #494 fixed it a couple months later.
