### ISSUE TITLE
cp: Oops! Command not found!

### ISSUE THREAD

**Issue by sjackman** [tldr-pages/tldr#2305]
Typing `cp` into either https://tldr.sh or https://tldr.ostera.io returns `Oops! Command not found!`. See for example https://tldr.ostera.io/cp Am I doing something wrong? I'm using Safari 11.1.2 on macOS 10.11.6 El Capitan.

**Comment by agnivade** [comment]
Works for me.

**Comment by sjackman** [comment]
Mysteriously and magically started working again. Sorry for the hassle. ¯\_(ツ)_/¯

**Comment by sbrl** [comment]
No problem! If it happens again and you get more information, let us know and we'll investigate :smiley_cat:
