### ISSUE TITLE
Add @mfrw as a collaborator

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#2306]
Hi, @mfrw! You seem to be enjoying contributing to the tldr-pages project. You now have had five distinct pull requests merged (#2297, #2294, #2288, #1651, #1532), which qualifies you to become a collaborator in this repository, as explained in our [governance guidelines](https://github.com/tldr-pages/tldr/blob/master/GOVERNANCE.md).

As a collaborator, you will have commit access and can therefore merge pull requests from others, label and close issues, and perform various other maintenance tasks that are needed here and there. Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

Thanks for all your work so far!

**Comment by waldyrious** [comment]
@sbrl was it intentional that you linked to the PRs in some cases and to the issues in others? I think it would be more consistent to link to the PRs in all cases.

**Comment by mfrw** [comment]
Thank you folks for the opportunity.

**Comment by waldyrious** [comment]
> Thank you folks for the opportunity.

@mfrw repeating what I said [on Gitter](https://gitter.im/tldr-pages/tldr?at=5b922be1f86b741b05202393), for the record:

> On the contrary, you took the first step of donating your time and energy to this project! we're simply moving out of the way ;)
>
> We don't believe it's in the best interests of a vibrant community to have leaders making the shots and "giving out opportunities" -- we're all here to serve the project one way or the other, and maintenance work is just another way to serve :)
>
> Hopefully we can be a blip in the efforts to reverse the traditional command structure of organizations, at least in the open source world.
>
> Do take a read of the GOVERNANCE.md and COMMUNITY-ROLES.md documents if you haven't already :)

**Comment by sbrl** [comment]
Nope, not intentional @waldyrious :P

I've corrected that.

I've also actually invited you to be a collaborator now @mfrw, so clicking [this link](https://github.com/tldr-pages/tldr/invitations) should take you to the invite if you don't receive an email.

**Comment by mfrw** [comment]
Should we close this now ?

**Comment by agnivade** [comment]
Yep. Welcome aboard !
