### ISSUE TITLE
Hacktober Fest 2018: prep repo

### ISSUE THREAD

**Issue by mfrw** [tldr-pages/tldr#2332]
We should start preparing our repo for this year's version of `Hacktober Fest`.
[https://hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com)

For starters, how about we start creating issues for commands not currently documented and adding a `help-wanted` label to them and probably a `hacktober-fest` label as well.

**Comment by sbrl** [comment]
I think we had a `hacktoberfest` tag last year, IIRC - so we can definitely recreate it. What's it meant to be called exactly to be counted, @mfrw?

Also, we've got a few issues left over from _Google Code-In_ which we can probably tag too. They are all testing frameworks of one form or another, I think.

**Comment by mfrw** [comment]
> What's it meant to be called exactly to be counted, @mfrw?
Could please explain a little more, I could not get the context @sbrl

**Comment by pxgamer** [comment]
I'm assuming @sbrl was asking the exact label name, I can't remember if there was a recommended one. But `hacktoberfest` seems to be more common than with a dash. As far as I know, any repositories are included whether or not they have a [`hacktoberfest`](https://github.com/search?q=label%3Ahacktoberfest) label. :thinking:

**Comment by mfrw** [comment]
@pxgamer yes, any repo that is public is eligible.

**Comment by agnivade** [comment]
Last time, I had simply renamed help-wanted to hacktoberfest. And then reverted that once it was over. Saves time adding new labels to all issues.

**Comment by pxgamer** [comment]
As Hacktoberfest has started, I have renamed the `help-wanted` label to [`hacktoberfest`](https://github.com/tldr-pages/tldr/labels/hacktoberfest) as per last year.

Ping @agnivade, @sbrl, @mfrw

**Comment by sbrl** [comment]
Awesome, thanks @pxgamer! Does that mean that we can close this issue then?

**Comment by mfrw** [comment]
@sbrl I guess so..

**Comment by pxgamer** [comment]
I'd say so, yeah. :+1: Closing it now.

Just need to remember to change it back in November. :stuck_out_tongue:

**Comment by sbrl** [comment]
I might need to set a reminder email there @pxgamer :P
