### ISSUE TITLE
Maintainers: Link for current collaborators broken.

### ISSUE THREAD

**Issue by mfrw** [tldr-pages/tldr#2388]
The [link](https://github.com/tldr-pages/tldr/settings/collaboration) for collaborators `https://github.com/tldr-pages/tldr/settings/collaboration`, seems broken.

I think it may only be visible to the owners/members.
Should I send a fix to remove it?

**Comment by agnivade** [comment]
The link is fine. Perhaps you can mention that it is visible only for owners and members.

**Comment by waldyrious** [comment]
For context, the link is mentioned [here](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md#current-collaborators). I agree that it would be preferable to make it explicit that the link is only visible for org members. Perhaps change that sentence from

> An automated list can be found [here](https://github.com/tldr-pages/tldr/settings/collaboration).

to

> If you're a member of the organization, you should be able to see an automated list [here](https://github.com/tldr-pages/tldr/settings/collaboration).

WDYT?

**Comment by pxgamer** [comment]
Is it only owners? 🤔 Cause as a member, that link doesn't work for me.

**Comment by mfrw** [comment]
Sure, I think we should update it as per @waldyrious and mention only owners can view it.
