### ISSUE TITLE
Cannot populate cache behind corporate certificate authority

### ISSUE THREAD

**Issue by richardhendricks** [tldr-pages/tldr#2416]
My company is using self-signed certificates so they can monitor traffic, but that is not allowing tldr to populate its cache.

~$ tldr du
⠸ Page not found. Updating cache{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
~$ 

Is it possible to change the setting, similar to NPM?

https://stackoverflow.com/questions/34498736/npm-self-signed-cert-in-chain

**Comment by agnivade** [comment]
Yes, you need to add the CA in your local computer. I bet this will be an issue with other sites too. There is no such setting in tldr unfortunately to point to a custom cert file. You just have to add the CA.

Please open a new issue in the https://github.com/tldr-pages/tldr-node-client repo if there is something which can be fixed from tldr side.

**Comment by richardhendricks** [comment]
Thanks for the pointer, it was a set of narrow twisty passages, all alike, but I managed to make my way through it.
