### ISSUE TITLE
page request: enscript

### ISSUE THREAD

**Issue by JZJisawesome** [tldr-pages/tldr#2431]
Man page can be found at: [https://linux.die.net/man/1/enscript](https://linux.die.net/man/1/enscript)

**Comment by mfrw** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by JZJisawesome** [comment]
Sure, I'll try.

**Comment by JZJisawesome** [comment]
Pull request for page addition: #2432
Pull request for page fixing (oops): #2446
