### ISSUE TITLE
Error in wget.md

### ISSUE THREAD

**Issue by megan201296** [tldr-pages/tldr#2471]
This could be just me not understanding but I believe there is an issue with the description for the first example of https://github.com/tldr-pages/tldr/blob/master/pages/common/wget.md. 

I don't believe that command downloads the contents of the file to a file named "foo" (similar to second example). No options outputs the contents to the terminal.

Please correct me if I am wrong with this. Otherwise I am happy to submit a PR to fix.

**Comment by megan201296** [comment]
Oops! You are correct. I was getting mixed up with curl. My mistake. Disregard

**Comment by sbrl** [comment]
No problem :-)
