### ISSUE TITLE
Inconsistencies in token definitions

### ISSUE THREAD

**Issue by glenacota** [tldr-pages/tldr#2509]
Hello,
I'd like to start uniforming the definition of tokens among TLDR pages, while also enforcing the [syntax guidelines](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md). I believe that more consistency will not only help TLDR users, but also new contributors.

For convenience, I was thinking about creating a number of narrow-scoped pull-requests instead of a single massive one. Each pull-request will refer to this issue. 

If you also believe this is a good idea, please feel free to join me in the process. If instead you don't think this is the right approach, let's discuss how to improve it! 😄 

Cheers,
Guido

**Comment by waldyrious** [comment]
Hey @glenacota! Your suggestions are most welcome, and individual narrow-scoped pull requests indeed seem like a good approach for mass changes.

I'm not really sure I understand what kinds of changes you have in mind, though. Before starting making PRs, it might be a good idea to lay out your plans here, so they can be discussed and refined if needed.

**Comment by glenacota** [comment]
Hi @waldyrious, the kind of changes I had in mind were something like:
- enforce the syntax guidelines, e.g., use only snake case notations, no capital letters
- use a common definition for the same token, e.g., ```filename``` instead of ```file_name```. As a rule of thumb to select the common definition, I'd choose the most recurrent correct definition among all pages

**Comment by agnivade** [comment]
Thanks for taking this initiative. I had done that long time ago, after which we actually created the syntax guideline. Before that it was the wild west ! But sometimes things fall through the cracks and it's always good to clean things up.

Your first point seems fine. Regarding the second point, I am willing to let it be. Reason being, it will cause unnecessary churn at no good cost. We also allow "file" and "path/to/file" where it seems appropriate. Bottom line is that a file token is so common, keeping it 100% consistent is a near impossible task. So unless there is a glaring issue, I would rather let it be.

**Comment by waldyrious** [comment]
I do think changes such as those in #2510 have value (so I think its closure was too hasty). Granted, some of the changes there might be arguable, as the variations in capitalization or choice of word separators might represent conventions in the ecosystem of the corresponding tools; but overall the changes seemed sensible. Even whether we should reflect context-specific naming conventions in tldr pages might be worth discussing, IMO.

While I agree with @agnivade that it doesn't make sense for the project to commit to keeping the tokens 100% consistent moving forward, if someone wants to take up the work to do it (as is the case here), I don't see a reason to not incorporate the changes, as long as they're consistent with the tldr-pages's explicit and implicit conventions.

**Comment by glenacota** [comment]
Thanks for your feedback, I'm glad the issue has some value. 
Hehe, yes maybe the closure of #2510 was too hasty, but also it was its creation, which I submitted before listening to the community's opinions. 😄 

As a start, I'm willing to go through the application of the token syntax guidelines wherever necessary. For this task, I propose to create one PR per platform folder, to keep the review process bearable. WDYT?

As for the common definition for similar tokens (e.g., ```file_name``` vs ```filename```), I agree that it might be an overkill, especially without a preliminary discussion leading (or not) to new, documented guideline agreements.

Thanks for your time

**Comment by waldyrious** [comment]
Cool, sounds good to me. So let's start with fixing violations of the explicit token guidelines first, and then move to additional adjustments that are not encoded there yet.

As for the PR division strategy, I think it would be more useful if you split them by conceptual change rather than by folder. That way even if the number of changes is large, the fact that they're all related makes the review process more streamlined.

**Comment by mfrw** [comment]
@glenacota should we close the issue now?

**Comment by waldyrious** [comment]
@mfrw, if I understood @glenacota's intents, most of the changes he was planning to make were not done yet; #2518 was just the first (and easiest) step.

**Comment by mfrw** [comment]
@waldyrious cool. Let's keep it open to track it.

**Comment by glenacota** [comment]
Hi @mfrw, sorry for the late reply. The understanding of @waldyrious is right, I wanted to keep working on this issue. Only, I don't have much time these days, and I might need a longer time.

While working on the first PR, I noted down some possible candidates for future style guidelines. I'd like to hear your opinion about them.
- List of values: with an ellipsis (e.g., ‘calibredb’, ‘7za’) or without ellipsis (‘mvn’, ‘stow’, ‘tar’)?
- How to define commands with arguments? At the moment there are very different styles, e.g., ‘for’, ‘mosh’, ‘nohup’, ‘ssh’, ‘lua’.
- Quotes: inside the token (e.g., ‘eyeD3’, ‘notify-send’, ‘fc-*’, ‘units’) or outside (e.g., ‘eval’, ‘watch’)?
- Quote: single quote (e.g., ‘fc-list’, ‘fc-match’) or double quotes (e.g., ‘eval’)?
- Use of numbers to distinguish between token values: underscore (e.g., file_1, file_2) or not (file1, file2)?

I don't mean to be pedantic 😄 these are just some ideas

**Comment by ivanhercaz** [comment]
I haven't read this awesome and interesting PR. The last comment was on November 2, 2018, more than one year ago! I don't know if @glenacota or someone has contribute to this until now due there aren't commits referring this issue nor PRs opened or merged, although I imagine that someone might have help with this issue.

I want to help with this and I would like to begin with the consistence of token names, for example one that has been mentioned here: `{{filename}}`/`{{file_name}}`.However, I think it should be better to open issues to address each inconsistency, and if there are some inconsistency very similar change the title of that issue. If we use just a single issue to track this, the issue could be enlarged a lot.

**Comment by sbrl** [comment]
Hey, @ivanhercaz! Yeah, it'd be great if you could help.

I agree. Let's open 1 issue at a time.

**Comment by kbdharun** [comment]
> Since it has been so long since last activity, I'm assuming all issues have been resolved.

Yep, all token syntax and other special cases are now fully documented in the recently revamped style guide.
