### ISSUE TITLE
page request: radare2

### ISSUE THREAD

**Issue by neodyma** [tldr-pages/tldr#2521]
I'd like to request a radare2 tldr page, would be nice if someone who uses it much could have a go at it.
normal man pages are pretty sparse.

[Github Source](https://github.com/radare/radare2)

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by neodyma** [comment]
I don't think I understand even half of what radare is capable of, so it would be better if someone else made the page 😅

**Comment by sbrl** [comment]
Sure thing, @neodyma! Perhaps someone else has more experience :-)

You could always contribute a basic page to start with, and we could iterate from there, if you wanted?

**Comment by cdminigun** [comment]
@neodyma What exactly are you looking for? Radare is a bit complicated, similar to GDB. The GDB page just has some of the commands on how to run an executable, but nothing really on how to debug. So something similar for radare could be added of how to run it with a binary and going over the CLI options here: https://manpages.debian.org/wheezy/radare2/r2.1.en.html  

https://github.com/tldr-pages/tldr/blob/master/pages/common/gdb.md

**Comment by sbrl** [comment]
@cdminigun Ah, I see. That does make it a challenge to boil it down into a tldr page.

Does it have subcommands? Could we perhaps do something like the `git-XXXX` pages?

**Comment by DigitalPhilosopher** [comment]
radare2 has some subcommands (rabin2, rasm2, etc.), however the main tools are accessible through radare2.

I think a good start for the main command could be the basic commands as explained in the free book (https://radare.gitbooks.io/radare2book/content/) which is given on the official page of the tool.

I would like to have a go on this.
