### ISSUE TITLE
colorscheme unreadable under solarized light

### ISSUE THREAD

**Issue by Konfekt** [tldr-pages/tldr#256]
How to disable the colorscheme of tldr ? As things stand, only the command lines are readable. 

Tested with 

* Konsole (that ships with Solarized Light by default), 
* urxvt, and 
* Xterm

**Comment by rprieto** [comment]
Hi, which client are you using?
Some clients let you configure/disable the color output (e.g. https://github.com/tldr-pages/tldr-node-client).

**Comment by Konfekt** [comment]
Oh, it is `pip`

**Comment by rprieto** [comment]
I see you started commenting on https://github.com/tldr-pages/tldr-python-client/issues/7, I'll close this issue for now.

**Comment by Konfekt** [comment]
Well, perhaps its on the behest of this repository that all the clients fuddle with the colorschemes? If so, I'd vote for leaving it unchanged. 

`tldr` should display its content and not entangle in color scheme customizations.

**Comment by rprieto** [comment]
Not at all, in hindsight I agree that it would be better if clients produced text-only by default.

It can be up to each client to offer customisation to make things easier to read, but it should be an option / or at least easy to disable. Such options should also be easy to setup once and for all, e.g. with a `.tldr` config file, so you don't have to specify something like `--colors` or `--text` every time.

**Comment by waldyrious** [comment]
I agree that any color customization should be opt-in rather than opt-out.
