### ISSUE TITLE
Restructure docker page

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr#2592]
In #1505, the docker page was restructured such that it has `docker container` in front of every command with the vague line that the old CLI interface might be gotten rid of. It never did (or was going to be) and in most resources I've seen, you'll see people using and recommending the shorter core commands over the longer form (like `docker ps` over `docker container ls`).

Would it restructure the docker page such that it has the short commands then have a `docker-container`, `docker-image`, etc. pages that has the longer form commands?

**Comment by mfrw** [comment]
@MasterOdin Should we close this now?

**Comment by waldyrious** [comment]
@mfrw we still need the `docker-container` and `docker-image` pages, for completeness. The former, in particular, would be required for us not to lose information that was on the `docker` page prior to #2597.

**Comment by Aracki** [comment]
@waldyrious @mfrw This should be closed after #3061 & #3062 gets merged.

**Comment by agnivade** [comment]
Thanks for taking care of this.

**Comment by Aracki** [comment]
#3061 & #3062 merged. Closing this.
