### ISSUE TITLE
leostera/tldr.js – web client

### ISSUE THREAD

**Issue by leostera** [tldr-pages/tldr#261]
Hi there guys,

Both amused by the `tldr` concept and eager to try out `duo`, I put this together as a simple test: https://github.com/leostera/tldr.js

I'll throw some styles to it as soon as I get some free time, and I think if the rate-limits from the github api can be worked around then this could be nice to have?

Anywho, cheers!

**Comment by rubenvereecken** [comment]
Cool it's the first time I've heard of `duo`! Looks neat. I'll have a look around and keep an eye on your client :).

**Comment by leostera** [comment]
Sweet. Just in case, it's up and running here: https://leostera.github.io/tldr.js

**Comment by leostera** [comment]
@rubenvereecken, I think it's good to include in the README.md now? Closing this too. Hope you like it!

**Comment by rprieto** [comment]
That's awesome! I like the command-line-like UI :+1: 
If you want to PR the README we'll merge that today.

One quick idea: would it be possible to process the `{{token}}` syntax and display them in a different color?

**Comment by waldyrious** [comment]
+1 for the `{{token}}` styling :D
