### ISSUE TITLE
Moving objdump to /common

### ISSUE THREAD

**Issue by guilhermeleobas** [tldr-pages/tldr#2626]
In the current layout, `objdump` is only available on Linux systems. However, this command is also available on OS X, sunos and windows through the [gnu binutils](https://www.gnu.org/software/binutils/) project. Can we move it to the `common/` folder? Other commands like `timeout` which are part of [gnu coreutils](https://www.gnu.org/software/coreutils/) are placed on `common/` instead of `linux/`

**Comment by sbrl** [comment]
Hrm, interesting proposal. Not sure what we've done before here. How would this handle with the windows built-in command `timeout`?

**Comment by sbrl** [comment]
Ahh I see. You're saying that the gnu coreutils `timeout` is already in `common`? Then moving the others from `linux` to `common` shouldn't be an issue. Want to open a PR?

**Comment by guilhermeleobas** [comment]
Sure!
