### ISSUE TITLE
android it

### ISSUE THREAD

**Issue by Cyberhan123** [tldr-pages/tldr#2658]
it show This command is not yet available.
Submit new command to tldr all time .
what should I do

**Comment by sbrl** [comment]
Thanks for requesting this page! I'm unsure what command you're referring to, but dyou want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by Cyberhan123** [comment]
I try some like ls mkdir but it doesn't work in Android client , it show me This command is not yet available.
Submit new command to tldr
how can i get the Android client i want try my best and fix it

**Comment by Cyberhan123** [comment]
my English. not well so it can't help me to describe all mean.emmmm ,sorry

**Comment by agnivade** [comment]
What is the actual problem here ? Are you trying some commands in android and not getting results ? Please raise an issue in the repo of the android client. This repo is only for pages.

Or do you want a tldr page to be added ? In which case, I don't understand which command.

**Comment by waldyrious** [comment]
@Cyberhan123 maybe you could write in your original language and we'll try using an automated translator to help understand what your issue is. Can you try that?

**Comment by 9Ajiang** [comment]
I have the same problem, It seems that Android client doesn't work.

**Comment by waldyrious** [comment]
For reference, there are two Android clients, at least [according to the README](https://github.com/tldr-pages/tldr#clients).

**Comment by Cyberhan123** [comment]
thank for all your help
