### ISSUE TITLE
page request: iex/elixir

### ISSUE THREAD

**Issue by shmink** [tldr-pages/tldr#2680]
iex being the interactive terminal for the elixir language. But there is also `elixir` as well they work very similarly only seeming to have a few differences. Might be able to put both into the one page? I'll look into doing this myself in future.

https://www.mankier.com/1/iex

**Comment by sbrl** [comment]
Not sure that it would work with our current structure having just 1 page. If you'd like to attempt it yourself, that'd be great :D

**Comment by bl-ue** [comment]
`iex` and `elixir` were added by #4658 and #4693.  Thank you @Schoonology!
