### ISSUE TITLE
page request: uvcdynctrl

### ISSUE THREAD

**Issue by aaronfranke** [tldr-pages/tldr#2695]
uvcdynctrl is a program to manage webcams. It can be installed with `sudo apt install uvcdynctrl`

https://www.mankier.com/1/uvcdynctrl https://www.unix.com/man-page/all/1/UVCDYNCTRL/

The man page and `--help` page for this program are very unhelpful. They provide no examples whatsoever. I would appreciate a TLDR page for how to use this tool.

**Comment by nightfox0909** [comment]
Can I take a crack at adding this page?

**Comment by sbrl** [comment]
Sure, go ahead @nightfox0909!

**Comment by gutjuri** [comment]
This issue can be closed, since the page for uvcdyncrtl exists now.
