### ISSUE TITLE
Keep default background

### ISSUE THREAD

**Issue by ProgVal** [tldr-pages/tldr#270]
tldr uses a blue background with a green font. This makes it quite hard to read the output on my computer.

Shouldn't the default background color (ie. the one the user set in the terminal's config) be used?

**Comment by ostera** [comment]
I agree with this. Using Solarized on iTerm 2 works like a charm, but default theme on Terminal app (white background) is illegible.

**Comment by waldyrious** [comment]
This is a client-specific issue. I suppose you're using the python one? If so, see tldr-pages/tldr-python-client#7

**Comment by ProgVal** [comment]
Indeed.
