### ISSUE TITLE
page request: arc

### ISSUE THREAD

**Issue by ua741** [tldr-pages/tldr#2712]
`Arcanist`(Arc) is a command-line interface to `Phabricator`.

Arcanist provides command-line access to many Phabricator tools (like Differential, Files, and Paste), integrates with static analysis ("lint") and unit tests, and manages common workflows like getting changes into Differential for review.

https://secure.phabricator.com/book/phabricator/article/arcanist/

**Comment by sbrl** [comment]
Thanks for requesting this page, @ua741! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by einverne** [comment]
Close since arc command has been added.
