### ISSUE TITLE
Page request: mosquitto_sub & mosquitto_pub

### ISSUE THREAD

**Issue by mmphego** [tldr-pages/tldr#2713]
[Eclipse Mosquitto](https://mosquitto.org/): 
Eclipse Mosquitto is an open source (EPL/EDL licensed) message broker that implements the MQTT protocol versions 3.1 and 3.1.1. Mosquitto is lightweight and is suitable for use on all devices from low power single board computers to full servers.

The MQTT protocol provides a lightweight method of carrying out messaging using a publish/subscribe model. This makes it suitable for Internet of Things messaging such as with low power sensors or mobile devices such as phones, embedded computers or microcontrollers.

The Mosquitto project also provides a C library for implementing MQTT clients, and the very popular mosquitto_pub and mosquitto_sub command line MQTT clients.

Please add `mosquitto_pub` and `mosquitto_sub` to the library.
You can find the man pages [here](https://mosquitto.org/man/)

**Comment by sbrl** [comment]
Thanks for requesting this page, @mmphego! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by mmphego** [comment]
Created PR:
https://github.com/tldr-pages/tldr/pull/2718 and https://github.com/tldr-pages/tldr/pull/2719 respectively.

Thanks,

**Comment by waldyrious** [comment]
@mmphego thanks for the request and the submissions! We usually only close the issues once the PRs are merged, just to make sure the tracking stays updated, so I'll reopen the issue for now; it will be re-close once the PRs are merged in.

**Comment by mebeim** [comment]
Closing as both #2718 and #2719 were merged.
