### ISSUE TITLE
Questoin: how to resolve the confict between different platforms.

### ISSUE THREAD

**Issue by vastpeng** [tldr-pages/tldr#2717]
The same command,  some usage may be different on different platforms.

### Example:

```shell
# On Linux
sed -i 's/find/replace/g' files

# On macOS
sed -i '' -E 's/find/replace/g' files
```

some is different between the platforms, but some is the same.

### Fix it?

my way:

first, in markdown.

```shell
- [Linux]Replace all occurrences of a string in a file, overwriting the file (i.e. in-place):
`sed -i 's/{{find}}/{{replace}}/g' {{filename}}`

- [macOS]Replace all occurrences of a string in a file, overwriting the file (i.e. in-place):
`sed -i '' -E 's/{{find}}/{{replace}}/g' {{filename}}`
```

then, add judgment in the code.

so, how should I do to realize it.

Sorry for my  pool English.

**Comment by agnivade** [comment]
You need to place separate versions of the page under platform-specific folders. Does that clarify ?

**Comment by vastpeng** [comment]
@agnivade 
LGTM.
