### ISSUE TITLE
Add contributor: @mebiem

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#2735]
Hi, @mebeim! You seem to be enjoying contributing to the tldr-pages project. You now have had five distinct pull requests merged (#2703, #2691, and the _massive_ #2730 :fireworks:), which qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access and can therefore merge pull requests from others, label and close issues, and perform various other maintenance tasks that are needed here and there. Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

Thanks for all your work so far!

**Comment by mebeim** [comment]
Oh wow. You're welcome, and yes I love this project indeed! I already read the maintainer's guide a while ago while taking a look at the overall project and its various guidelines. It seem reasonable and simple enough, so no problem getting familiar with it I suppose.

So thank you, and yes, I'd be glad to help maintaining this awesome project :smile:

**Comment by sbrl** [comment]
No need to do maintenance if you don't want to, but if you would that'd be great :D

The `COMMUNITY-ROLES.md` file says 5 non-trivial contributions, but you've bundled multiple non-trivial changes in places (#2691, and of course #2730) - so personally I count it to be 5 :P

I'll leave it until either @waldyrious, @agnivade, @pxgamer, or @mfrw drop in here until I send the invite - just to be sure - but I'm pretty certain it counts :P

**Comment by mebeim** [comment]
Oh yeah, I was wondering about the number since you said 5 and mentioned only 3. Got it. As for the maintenance well yes sure, why not :slightly_smiling_face:

**Comment by pxgamer** [comment]
Seems good to me. :+1:

**Comment by sbrl** [comment]
Awesome! I'll send the invite then :D

**Comment by mebeim** [comment]
Got it. Thanks again :smile:

**Comment by agnivade** [comment]
Sounds good to me. Welcome @mebeim !

As your first collaborator task, please close out the issue once you have accepted the invitation. :)

**Comment by mfrw** [comment]
Welcome @mebeim

**Comment by mebeim** [comment]
Thanks guys 😁
