### ISSUE TITLE
Travis build failure on PRs due to impossibility to decrypt the deploy key

### ISSUE THREAD

**Issue by mebeim** [tldr-pages/tldr#2749]
[Travis fails to build pull requests](https://travis-ci.org/tldr-pages/tldr/builds/488184528) because on PRs the variables `$encrypted_973441be79af_key` and `$encrypted_973441be79af_iv` are not defined (for obvious security reasons). Since those are not defined, the `ssh-add` command waits for a passphrase on standard input, making the build time out and fail.

My eye didn't unfortunately spot this rather simple mistake when reviewing #2747, whoops :(

The solution is simple: only deploy when on the master branch. I'm working on a PR to solve this and will submit it as soon as possible.

**Comment by mfrw** [comment]
This error is quite strange. I would really want to understand the why of this

**Comment by mebeim** [comment]
@mfrw yeah, me too...

The build for @agnivade's PR should have failed since those variables should not be defined inside a PR build. If what happened is real, it looks like a major security flaw in the Travis CI build system.

**Comment by MasterOdin** [comment]
Travis only makes available encrypted variables in PRs only if its a PR from the inside the repo. Any pull request from a fork will not have access to them.

See https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions for more info.

**Comment by agnivade** [comment]
Ah that's right ! This was the reason due to which we moved tldr-bot to a dedicated server. And I forgot about it :)

**Comment by mebeim** [comment]
Ohhh, thanks @MasterOdin, I did not k ow about that subtle difference. Now it all makes sense.

**Comment by sbrl** [comment]
I see. So I guess we'll have to move it to the bot after all?

**Comment by mebeim** [comment]
@sbrl nah, not necessary to move to the bot ;) it wouldn't improve security, just make it more complicated.
