### ISSUE TITLE
Pages of different languages not being checked/linted when building

### ISSUE THREAD

**Issue by mebeim** [tldr-pages/tldr#2756]
As you can see from the build logs, the `npm test` command is only executing:

    bash -c 'markdownlint pages/ && tldr-lint ./pages 2>&1 | tee test_result; test ${PIPESTATUS[0]} -eq 0'

This only checks pages in the main English `/pages/` directory, but does not check pages written in any other language. In fact, I just reviewed a PR where some Italian pages were passing the build without being checked.

The test defined in `package.json` should be updated to test all the languages that *can* be tested. I'm not sure if writing everything inside the `package.json` is a good idea though, it might be needed to create a proper script that does all the necessary testing.

This also brings up another issue: as of now only languages which use the [Latin alphabet](https://en.wikipedia.org/wiki/Latin_script) can be correctly checked, since the `tldr-lint` tool checks for stuff like capital letters etc. So it can be used for English, Italian, Portuguese and similar languages, but not for Chinese, Thai, etc. However this is something that concerns the linter itself, and not this repository. Maybe another issue should be opened there to discuss how linting of different languages could be implemented. I unfortunately don't know much about Yacc to be able to help there (at least for now).

**Comment by agnivade** [comment]
A separate script for testing en, it, and pt-br and calling that from package.json sounds good to me.
