### ISSUE TITLE
ping: option -O does not exists on MacOS

### ISSUE THREAD

**Issue by thiswind** [tldr-pages/tldr#2769]
<img width="850" alt="wx20190210-181722 2x" src="https://user-images.githubusercontent.com/23764/52532642-5b670080-2d63-11e9-8b22-c77bbf1f0b90.png">

the page: [ping](https://github.com/tldr-pages/tldr/blob/master/pages/common/ping.md)

**Comment by sbrl** [comment]
See my comment on #2203 :-)

**Comment by thiswind** [comment]
> See my comment on #2203 :-)

thank you and I will close this issue:)

**Comment by sbrl** [comment]
It's probably best if we leave this open until we've actually created that duplicate page.

Would you like to send a PR for it?

**Comment by thiswind** [comment]
> It's probably best if we leave this open until we've actually created that duplicate page.
> 
> Would you like to send a PR for it?

Yes, I'd like to. Maybe we are on the other side of the Earth. I will send the PR tomorrow morning :)

**Comment by thiswind** [comment]
new page was created /osx/ping, so close this issue.
