### ISSUE TITLE
page request: rbt

### ISSUE THREAD

**Issue by LachlanMarnham** [tldr-pages/tldr#2782]
rbt (Review Board Tools) is the CLI for reviewboard, which enables the user to post diffs for code review. 

Example documentation: https://www.reviewboard.org/docs/rbtools/dev/

I'm happy to submit a PR for this myself :)

**Comment by sbrl** [comment]
Thanks for requesting this page, @LachlanMarnham! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by LachlanMarnham** [comment]
Sorry for the slow reply. Sure, I'll do it this weekend.

**Comment by pxgamer** [comment]
Looks like this was technically closed in #2789.

@LachlanMarnham, if there's any additional examples you'd like to add, feel free to open a PR. 👍
