### ISSUE TITLE
page request: create_ap

### ISSUE THREAD

**Issue by ryukinix** [tldr-pages/tldr#2816]
```

## Examples
### No passphrase (open network):
    create_ap wlan0 eth0 MyAccessPoint

### WPA + WPA2 passphrase:
    create_ap wlan0 eth0 MyAccessPoint MyPassPhrase

### AP without Internet sharing:
    create_ap -n wlan0 MyAccessPoint MyPassPhrase

### Bridged Internet sharing:
    create_ap -m bridge wlan0 eth0 MyAccessPoint MyPassPhrase

### Bridged Internet sharing (pre-configured bridge interface):
    create_ap -m bridge wlan0 br0 MyAccessPoint MyPassPhrase

### Internet sharing from the same WiFi interface:
    create_ap wlan0 wlan0 MyAccessPoint MyPassPhrase

### Choose a different WiFi adapter driver
    create_ap --driver rtl871xdrv wlan0 eth0 MyAccessPoint MyPassPhrase

### No passphrase (open network) using pipe:
    echo -e "MyAccessPoint" | create_ap wlan0 eth0

### WPA + WPA2 passphrase using pipe:
    echo -e "MyAccessPoint\nMyPassPhrase" | create_ap wlan0 eth0

### Enable IEEE 802.11n
    create_ap --ieee80211n --ht_capab '[HT40+]' wlan0 eth0 MyAccessPoint MyPassPhrase

### Client Isolation:
    create_ap --isolate-clients wlan0 eth0 MyAccessPoint MyPassPhrase
```

ref: https://github.com/oblique/create_ap

**Comment by sbrl** [comment]
Thanks for requesting this page, @ryukinix! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by agnivade** [comment]
No need to ask for permission. Feel free to send a PR.

**Comment by ryukinix** [comment]
@7vikpeculiar totally, go for it.

**Comment by 7vikpeculiar** [comment]
# #2883 
Hi, I put up a pull request for the same

**Comment by 7vikpeculiar** [comment]
Hi @sbrl I am not able to get one error cleared (error from travis)

**Comment by sbrl** [comment]
Hey! Yeah, we have a linter that checks pages against our style guidelines. We've got the style we prefer documented over [here](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format), and a few good examples are the pages for `tar`, `eyeD3`, and `ln`. If you need any assistance, just ask :smiley_cat:

I noticed you closed the PR. Can I help at all?

Our bot (@tldr-bot) posts messages to let you know what's gone wrong, if that helps.

**Comment by bl-ue** [comment]
`create_ap` was added almost 2 years ago on April 14, 2019 in #2884.  Thank you @7vikpeculiar!

**Comment by bl-ue** [comment]
As of July 22, 2020, `create_ap` is no longer maintained...I'll add that to the page's description.
