### ISSUE TITLE
Searching for a command on the web-frontend

### ISSUE THREAD

**Issue by Kreijstal** [tldr-pages/tldr#2818]
When you search for a command on the web frontend, every keystroke you type is pushed to the browser history so your history is cluttered with every key, you just typed.

**Comment by pxgamer** [comment]
I guess this is more related to the website repository ([ostera/tldr.jsx](https://github.com/ostera/tldr.jsx)).

Are you thinking of a delay? Or pressing enter to submit?

**Comment by Kreijstal** [comment]
Oh, you are right it has to do with the website, not with this project.
No, there is no delay, nor need to press enter to submit, the problem is that every keystroke is saved in your browser history

**Comment by sbrl** [comment]
There's a new _transfer issue_ feature in beta. If you'd like, I can reopen this issue and transfer it to the repo for the website?

**Comment by Kreijstal** [comment]
oh, can you do that? then sure.

**Comment by agnivade** [comment]
You can only transfer issues to repos under the same org. tldr.jsx is under @ostera's account.
