### ISSUE TITLE
Add collaborator: @schneiderl

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#2898]
Hi, @schneiderl! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#2885, #2879, #2871, #2727, and #2707),
which qualifies you to become a collaborator in this repository,
as explained in our
[community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access
and can therefore merge pull requests from others, label and close issues,
and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary
— you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though,
we only ask you to get familiar with the
[maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by schneiderl** [comment]
Hi,
Thanks a lot for the invite. It will be a pleasure to be a collaborator of this project. :)
I have already read the maintainers guide and it should not be a problem following it.

So thank you again and I will make sure to keep myself as active as possible on the project. 👍

**Comment by sbrl** [comment]
Invite sent :D

**Comment by schneiderl** [comment]
Accepted. Thank you once again guys :D

**Comment by mebeim** [comment]
Let's honor the new guidelines and let this close this automatically when your PR is merged. I added "Closes xxx" to do so :)

**Comment by waldyrious** [comment]
Oh my, the line breaks are preserved when the message template is rendered :(

@sbrl maybe we should remove them from the COMMUNITY-ROLES.md page? I hate long lines especially within preformatted blocks, but the message above does look awkward with some of the breaks.

Alternatively, we could remove only the most egregious ones, and keep those after commas and periods. WDYT?

**Comment by mebeim** [comment]
@waldyrious Personally I'd remove them to make it easier for everyone. Those code blocks will end up being copy-pasted entirely anyway so I don't see a real problem with them being less readable in the community roles Markdown file.

**Comment by waldyrious** [comment]
@mebeim I made some tweaks to the message above to illustrate what it would look like if we removed only the non-semantic breaks. I think the text reads well with the line breaks, which in fact even help indicate sentence structure; but if you guys still prefer full soft-wrapping, I won't object.

**Comment by mebeim** [comment]
@waldyrious I'm all for the clarity, but while that text looks ok on my PC, it really does not look so good on my phone (and probably other narrower devices, [screenshot here](https://i.imgur.com/A13N83W.png)). I'd let the automatic wrapping do its job in this case.

**Comment by sbrl** [comment]
Hrm, that's odd @waldyrious - I didn't notice that! I thought that they only stuck around if you had whitespace at the end of the line.

**Comment by waldyrious** [comment]
You've convinced me, @mebeim :) I'll make the change.
