### ISSUE TITLE
Remove the gem path?

### ISSUE THREAD

**Issue by lord63** [tldr-pages/tldr#300]
In the `Makefile` and `lint-changed.sh`, we specified the gem path.

Currently, I'm using rvm. After I installed the gems, the original setting would crash when I run `make lint` or `make lint-changed` because of the gem path.

If I remove the gem path setting, everything should works. I don't know why we should specify it, could someone explain it to me ?

**Comment by lord63** [comment]
ping @rubenvereecken

**Comment by igorshubovych** [comment]
BTW, I have the same issue. I have installed gems locally using bundler and tried global too.

This line does not work for me
```shell
[[ -z "$MD_FILES" ]] || GEM_PATH=.gem .gem/bin/mdl "$MD_FILES"
```
This line works
```shell
[[ -z "$MD_FILES" ]] || mdl $MD_FILES
```

@rubenvereecken, can you help?

Maybe it makes sense to write simple instruction on installing?

**Comment by lord63** [comment]
Just creat a PR #337 . I think this issue is very important, cause it may block our users when they want to contribute to tldr.

**Comment by igorshubovych** [comment]
This is not needed anymore because of #350
