### ISSUE TITLE
line.md : move to correct folder

### ISSUE THREAD

**Issue by schneiderl** [tldr-pages/tldr#3022]
Hi,
I have just noticed that the [line.md](https://github.com/tldr-pages/tldr/blob/master/line.md) file is not where it is supposed to be. It is hanging around the project front page.

As I don't know which is the correct folder it should be under, I'm just opening this issue. 

@lbonanomi maybe you can help us here as you were the one who commited this.

**Comment by lbonanomi** [comment]
*facepalm*

Under the Linux heading, please.

**Comment by mebeim** [comment]
Oh well, this is awkward, LOL.

**Comment by lbonanomi** [comment]
Certainly not my finest hour, that's for sure.

**Comment by mebeim** [comment]
@lbonanomi no problem, that's not your fault at all, it was an oversight when reviewing the PR. I just thought it was fun.

**Comment by schneiderl** [comment]
> Certainly not my finest hour, that's for sure.

Happens to all of us haha.

**Comment by lbonanomi** [comment]
I feel like the collegial spirit of this org is making me a better person to work with.
