### ISSUE TITLE
Introduce the new python client: tldr.py, look for feedback and suggestions.

### ISSUE THREAD

**Issue by lord63** [tldr-pages/tldr#307]
Recently, I made a new python client: [tldr.py](https://github.com/lord63/tldr.py).

Features:

* python 2.x && 3.x support.
* you can custom the color output.
* support update to fetch the latest changes.

To make it become better, I need your suggestions and feedback. Please file an issue if you have something to say.

Hava a try! ;)

**Comment by rprieto** [comment]
Thanks for letting us know, I'll take it for a spin! Interesting approach to let `Git` do the fetching (with a local repo), definitely makes the client simpler.

Are you happy to feature it in the README next to other clients?

**Comment by lord63** [comment]
@rprieto  Sure, I was intend to send a PR later after some people test it, tldr.py is still at very early stage. And if it sucks, just forget this client, haha.
