### ISSUE TITLE
page request: ac

### ISSUE THREAD

**Issue by StewAlexanderACC** [tldr-pages/tldr#3083]
[AC Man Page](http://man7.org/linux/man-pages/man1/ac.1.html)

### The **AC** command prints user connection time status in day / hours
-----
* Using **AC** command without flags shows total connection time to the server for the current user in hours:
```
support@ntopng:/$ ac
        total        2.16
```
* The most useful way to use this is ""***ac -dp***"" which shows connect time by day per user in hours:
````
support@ntopng:/$ ac -dp
        support                              1.89
May  6  total        1.89
        support                              0.06
May 16  total        0.06
        support                              0.25
Today   total        0.25
```

**Comment by sbrl** [comment]
Thanks for requesting this page, @StewAlexanderACC! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by dajomareyes** [comment]
This should be closed :)

**Comment by StewAlexanderACC** [comment]
Thanks, closing
