### ISSUE TITLE
Insert final newline in every markdown file?

### ISSUE THREAD

**Issue by lord63** [tldr-pages/tldr#310]

**Comment by lord63** [comment]
`osx/caffeinate.md` has three newlines at the end of the file;
`linux/wall.md` has two;
`common/ab.md' don't have final newline;
most of the markdown files have one.

And I think one is good, it's good for output when we make a client.

**Comment by rprieto** [comment]
Agreed on 1 blank line at the end of every file (seems standard :+1:), although does it affect rendering that much? Is that something the linter can do?

**Comment by lord63** [comment]
A dirty script show that:

* end wth no line: 176
* end with one line: 15
* end with more that one line: 5

Most of the pages don't have final newline, I'm sorry.

> And I think one is good, it's good for output when we make a client.

this was not true, I'm sorry ;(. In my case, tldr.py will be happy if there is no final line. But I don't know how other client will treat it.

My suggestion is only have one style, maybe the first one: with no endline.

**Comment by rprieto** [comment]
:+1: for normalizing then.

I'd still vote for a line break at the end, mostly for reasons detailed at http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline (most tools like `cat`, `read`, `wc` all expect a line break at the end under "normal" behaviour).

**Comment by rubenvereecken** [comment]
Nothing very useful to add to this discussion, except that I'd agree on normalizing.

I've got a creeping sense this is when I learn that notorious vim batch mode and go at it with some vim markdown formatter. On the other hand, @lord63 maybe already has something :)?

**Comment by lord63** [comment]
@rubenvereecken haha, actually, nothing special. With bronson/vim-trailing-whitespace, remove all the trailing space is <kbd>,</kbd><kbd>space</kbd>. Most modifies are made by hand.

**Comment by lord63** [comment]
@rprieto I think I miss-up the newline and new line. :(
So, we should end with one '\n', right?

**Comment by rprieto** [comment]
Ah yes I meant newline, as in a single `\n` after the last bit of text. Is that what you meant too?

**Comment by lord63** [comment]
> a single \n after the last bit of text

Yes, that's it.
