### ISSUE TITLE
Suggestion: Include installation recommendations for OS

### ISSUE THREAD

**Issue by jpmcb** [tldr-pages/tldr#3115]
When running

```
$ curl cheat.sh/rg
```

there is no information about installation.
Seeing as the curl.sh uses tldr for basic commands, it could be beneficial to include installation information. For example, on macOS:

```
#
# ripgrep
#
# A fast command-line search tool.
# install with `brew install rg`
```

Additionally, this would be beneficial as it's not immediately obvious if a binary is on a system by default. 

Let me know if I can provide any more information on this suggestion!

**Comment by agnivade** [comment]
Thanks for the suggestion @jpmcb.

Adding installation instructions is certainly helpful. But we would not want to clutter our pages with too much information. Moreover, we have a "More information:" sub-heading now where the users are directed towards the home page of the tool, from where they can get installation instructions. So it feels to me that information is anyways just one click away.

I would prefer to let this one sit for a while and see if we have more requests like this. And then we can decide on what action to take.

**Comment by waldyrious** [comment]
I also think that adding installation instructions goes beyond the scope of tldr-pages project.

Besides, installation procedures typically differ a lot between platforms and between tools; in fact, often multiple ways of installation are available for the same tool-platform combination. So it would be very hard to keep these consistent and concise across pages without omitting important information.

**Comment by waldyrious** [comment]
> Perhaps a database of install instructions would be useful

[Repology](https://repology.org/) kind of helps toward that goal, but yeah, it's a whole different project :)

**Comment by pxgamer** [comment]
I'd have to agree with the other comments here. 👍 I've previously thought about adding install commands for some of the PHP tools like Composer. But they can be installed in so many ways, as with most other commands.

**Comment by jpmcb** [comment]
Thanks for the feedback on this suggestion everyone! 

I definitely recognize that binary dependency and installation information is a dense web that encompasses various operating systems, architectures, and security concerns. And perhaps including install information in the tldr-pages project is beyond this scope.

However, as a user and consumer of the tldr-pages, it would be beneficial to include this information or make it immediately obvious where to find it.

@agnivade unfortunately, for my use case using `cheat.sh`, the "More information" section is not included in the page output and therefore, the install info is not easy to find. Additionally, as a command line user, I do not want to open a browser, navigate to the tldr-pages, and find additional information on a tool and it's installation. I want a seamless experience that retrieves all valid information in one command. 

Perhaps this is actually an issue with the cheat.sh project using the tldr-pages as a dependency and not including "more information" as an option? My primary use case revolves around this tool.

**Comment by waldyrious** [comment]
@jpmcb it does seem to me that the best solution here is indeed for cheat.sh to display the `More information:` field of tldr-pages. But let us know if you think some other solution is preferable.

Btw, if you open an issue with that project asking for this, make sure to link this one for context.

**Comment by sbrl** [comment]
Yeah, the `More Information:` is actually rather new - so it's not surprising that cheat.sh (great find, btw! I didn't know about that one. Is it worth mentioning in the README?) hasn't been updated yet to support it.

It might be worth opening an issue against cheat.sh, yeah.

Are you aware of the [large number of tldr clients](https://github.com/tldr-pages/tldr#clients) we have listed in the README? Most of these are command-line based applications. Maybe you could find one in there that's to your liking?

**Comment by jpmcb** [comment]
Opened the following issue with the cheat.sh project - https://github.com/chubin/cheat.sh/issues/146

**Comment by waldyrious** [comment]
Thanks, @jpmcb. I'll close this issue then, since we've agreed that installation instructions are not appropriate for tldr-pages.
