### ISSUE TITLE
Should the 0.0.1 tag be removed?

### ISSUE THREAD

**Issue by mebeim** [tldr-pages/tldr#3121]
Currently, this repository only has [this tag: 0.0.1](https://github.com/tldr-pages/tldr/releases/tag/0.0.1), created on Mar 4, 2014 (quite some time ago, at the time the repo only had 192 commits). This also counts as the only "release" listed here on GitHub. 

I've been wondering about this tag for quite a while, and I don't know the reason it was created, but by looking at it more closely, it seems quite random to say the least. The fact that this creates a "release" doesn't really make it helpful either, and it looks kind of confusing. Therefore I'd suggest deleting this tag since it doesn't seem to serve any particular purpose. 

A note on clients: if any client is relying on this tag, that would mean that that particular client could be outdated and also not following the correct page syntax spec, since at the time of that tag, pages didn't follow the same syntactic rules which are enforced today by the build process. As far as I could see when reviewing the clients for #2865, no client seemed to be outdated. This is just to say that I don't see a problem regarding clients that would prevent us from removing the tag without notice.

**Comment by waldyrious** [comment]
Judging from the reactions above, it looks like there's broad agreement to delete the tag. Let's let this sit for a couple more days, just in case an edge case or concern comes up; if no objection is raised, I'd say let's go ahead and remove it.

**Comment by mebeim** [comment]
Well, I'd say this has been waiting enough. I just deleted the tag. For future reference, it was pointing to [`22f033842e1b80f7ef9db94d2a5ab02429e216e3`](https://github.com/tldr-pages/tldr/tree/22f033842e1b80f7ef9db94d2a5ab02429e216e3).

**Comment by waldyrious** [comment]
Wow, look at the repo at that snapshot! Those were simpler times. 😄
