### ISSUE TITLE
page request: autoclean

### ISSUE THREAD

**Issue by tosim91** [tldr-pages/tldr#3134]
Please list "autoclean" in tldr. Thank you.

**Comment by sbrl** [comment]
Hey, @tosim91!

Looks like this issue is empty to me. Can we help at all? If not, then perhaps we could close this issue?

**Comment by mebeim** [comment]
@sbrl sneaky HTML comment ;) it's actually a page request :eyes:

**Comment by sbrl** [comment]
Ah, I see. `autoclean` doesn't appear to be a command on my Linux box though.

@tosim91, do you have a link to the command in question?

Is it `apt autoclean` you're referring to?

**Comment by tosim91** [comment]
Nor do I have it listed. I just checked using "man autoclean" , and nothing.

**Comment by tosim91** [comment]
Yes, please close this issue, and, thank you.

**Comment by mebeim** [comment]
As you wish @tosim91 :thinking: closing as it was opened by mistake.

**Comment by tosim91** [comment]
Thank you.
