### ISSUE TITLE
Automated deploy of updated ZIP archive failing

### ISSUE THREAD

**Issue by mebeim** [tldr-pages/tldr#3148]
See the latest build [here](https://travis-ci.org/tldr-pages/tldr/builds/551699390#L215), and also [previous builds](https://travis-ci.org/tldr-pages/tldr/builds) of the master branch. They seem to randomly fail to deploy the ZIP archive because this particular command fails:

https://github.com/tldr-pages/tldr/blob/241155bfd72de97c9b22ebddb7e66ac2dfa87cf9/scripts/deploy.sh#L36

For example:

    (adding: pages.it/common/clockwork-cli.md (deflated 51%)
    (adding: pages.it/common/arch.md (deflated 28%)
    (adding: pages.it/common/alex.md (deflated 42%)
    (stored 0%) <------------------------------- this seems suspicious
    Script failed with status 1

NOTE: this is a problem in the deploy step, the build is still working fine (in fact Travis says "error", not "failed"). We should check what's wrong.

**Comment by agnivade** [comment]
Great work @mebeim. Indeed this is strange.

**Comment by sbrl** [comment]
Hrm. Maybe we could rewrite it to use `7za` instead? It supports zip IIRC.

Untested:

```bash
7za a -tzip "$TLDR_ARCHIVE" pages*/ LICENSE.md index.json 
```

**Comment by mebeim** [comment]
This is very strange. I don't really think there's anything wrong with that command. Travis has always been known for having strange bugs. I manually restarted [this build](https://travis-ci.org/tldr-pages/tldr/builds/551418147) and it deployed with no problem. I'm kind of lost :thinking:

**Comment by agnivade** [comment]
I wonder if we can just tweak the script to add a retry logic if it fails.

**Comment by pxgamer** [comment]
Maybe we could use `travis_retry`? Although does the command return an error exit code? 🤔

**Comment by sbrl** [comment]
Also untested:

```bash
i=0;
retries=3'
while [[ "${i}" -lt "${retries}" ]]; do
    some_command;
    exit_code="$?";
    if [[ "${exit_code}" -eq 0 ]]; then break fi
    echo "Command failed with exit code ${exit_code}.";
    i=$((i+1));
done
```

**Comment by mebeim** [comment]
Unfortunately:

> Note that `travis_retry` does not work in the deploy step of the build, although it does work in the other steps.

Also wrapping the command in a `while` doesn't really feel right.

I'd suggest this:

1. Move the building of the ZIP and the `index.json` in the build step of Travis.
2. Wrap the zip generation with `travis_retry`, which works in the build step.
3. In the deploy step, just upload the already generated files to the gh-pages repository.

**Comment by agnivade** [comment]
Ah .. `travis_retry` not working in deploy is a bummer. But I can understand that a deploy step is a potentially non-idempotent task.

Even in this case, if the `git push` fails, we are in the dark. But, it is risky to retry git pushes. The above solution SGTM.
