### ISSUE TITLE
Cloudflare security check blocking tldr.sh/assets/tldr.zip

### ISSUE THREAD

**Issue by principis** [tldr-pages/tldr#3227]
So for some reason Cloudflare is currently blocking the network I'm on from accessing tldr.sh without first passing the recaptcha. This is a problem for clients because they can't download the zip. I already bypassed it but maybe something can be changed on the cloudflare side? Accepting the captcha isn't enough because it only sets a cookie which the clients don't have.

![Screenshot_20190806_150300](https://user-images.githubusercontent.com/16706228/62542044-517a1200-b85b-11e9-8641-8c5251726a69.png)

**Comment by agnivade** [comment]
I have seen this happen only on vpns. I don't think it is possible to just undo cloudflare security. Are you  using one by any chance ? In any case, you can always download the original zip from the github site.

**Comment by principis** [comment]
Not at the moment. I was on my University network so someone could be doing stuff they shouldn't...
What's the URL for the GitHub zip? I've tried tldr-pages.github.io/assets/tldr.zip but it redirects to tldr.sh

**Comment by agnivade** [comment]
Now I am confused. I meant  tldr-pages.github.io/assets/tldr.zip. But I see that due to it having the CNAME file, it will get redirected to the CF site. Which one did you find ?

**Comment by principis** [comment]
This one: https://github.com/tldr-pages/tldr-pages.github.io/blob/master/assets/tldr.zip (or https://github.com/tldr-pages/tldr-pages.github.io/raw/master/assets/tldr.zip)

**Comment by agnivade** [comment]
I see. Yes it's the same one. You can use it.

**Comment by principis** [comment]
Ok thanks, I'm adding it as a fallback. (Not sure if I should close this so you may close the issue it if you want. :))

**Comment by agnivade** [comment]
I don't think it is good to disable the captcha check even if it was possible. It is there for a reason :) I will close this since there is a easy enough workaround.

**Comment by sbrl** [comment]
Generally speaking, you shouldn't notice that _CloudFlare_ is in the middle at all. I suspect that it's causing an issue because of the network you're on, and some suspicious activity has been detected coming from your network.

It's probably not even your IP address specifically - it could even be just a number of people 'close by' in internet IP address terms.

**Comment by principis** [comment]
It's probably the university network. There are a few thousand people on the same small IP range, so I'm not shocked by it ;)
