### ISSUE TITLE
Clients which support private pages

### ISSUE THREAD

**Issue by halloleo** [tldr-pages/tldr#3269]
Hi all

I tried some tldr clients and noticed that the ones I tried do not support private pages.

With private pages I mean pages for a command or even better just additional parts (examples) to an existing page, which are specific for personal use and not appropriate to be added to the public repo.

I was wondering, are there clients which support such private pages/parts?

**Comment by agnivade** [comment]
Yes, the tldr-node client does.

**Comment by mebeim** [comment]
Hi @halloleo if you don't have any other comments or questions I would say we can close this as it has been answered, is everything clear?

**Comment by sbrl** [comment]
Perhaps someone could put together a feature matrix at some point for the different clients. Another project for the wiki?

**Comment by halloleo** [comment]
Hi @mebeim, sorry for the late response. 

@agnivade  I just had a look at the node client and I cannot see any mechanics to integrate private pages.

(Are you referring to the `--render` option? From my understanding this option needs the full path to a pages and therefore this pages will not automatically show up in the normal command search in tldr...)

**Comment by agnivade** [comment]
I am referring to the "repository" key here - https://github.com/tldr-pages/tldr-node-client#configuration. See the last point under that section.

**Comment by halloleo** [comment]
Ah, I see. You can switch completely to another set of pages.

Not really what I had in mind: It means you have to fork the default repo, add your stuff to it and then later regulaly update your fork manually from the base repo. Plus you cannot have sensitive examples in your repo if you cannot look your repo down.

But if that's what it is, then, well, that's what it is...

**Comment by sbrl** [comment]
You could always write your own tool, or fork the existing client and add support @halloleo.

We have a [client specification](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md) already - perhaps such a feature could be an optional module that clients could support if they wanted to.

**Comment by halloleo** [comment]
Good idea @sbrl. I might get to enhamcing th Pytgon client in that way.

Thanks for the link to the client spec. Certainly useful!

**Comment by sbrl** [comment]
Do keep us posted on how it goes, @halloleo!

**Comment by Phuker** [comment]
Hey guys, I am making a new Python client [Phuker/multi-tldr](https://github.com/Phuker/multi-tldr) which support private pages. If you prefer Python, you may try it out, and tell me how do you like it.

Maybe someday when it is mature and stable enough, I will create a PR to add it to the community clients list.

（Sorry for my duplicated comment in #4344)
