### ISSUE TITLE
page request: ceph

### ISSUE THREAD

**Issue by dizzi90** [tldr-pages/tldr#3298]
`ceph`
[docs.ceph.com](https://docs.ceph.com/docs/master/man/8/ceph)
A comprehensive cli for administration of the ceph storage system.
Imho not obvious which sub-commands to cover in a summary.

**Comment by pxgamer** [comment]
Thanks for requesting this page, @dizzi90! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by amitech** [comment]
@dizzi90 can I take this?

**Comment by pxgamer** [comment]
@amitech, of course 👍

**Comment by amitech** [comment]
Raised PR #3464

**Comment by agnivade** [comment]
This was done at https://github.com/tldr-pages/tldr/pull/3351. I will go ahead and close this.

**Comment by amitech** [comment]
Ah, I didn't check this. I will create a PR to move it to common instead of linux.
