### ISSUE TITLE
Git-commands in Italian

### ISSUE THREAD

**Issue by glenacota** [tldr-pages/tldr#3317]
Hi folks,
I'd like to add the Italian translations of the git commands to `pages.it/common/`.
I'm planning to split my contribution into two PRs (the first one with 10 translations, to get early feedback from other Italian contributors on whether I'm doing this right; the second batch with all the remaining commands). 

Evviva `tldr`!

**Comment by sbrl** [comment]
Hey, awesome! Thanks for this @glenacota. Sounds like a great plan to me!
