### ISSUE TITLE
Brazilian Portuguese 'More Information' token

### ISSUE THREAD

**Issue by schneiderl** [tldr-pages/tldr#3329]
Hi,
I was browsing around some brazilian portuguese pages and found some inconsistencies on the "More Information" token. 

Some pages have it as "Mais informações", which translates to "More information" and some of them have it as "Homepage". 
Shouldn't we have a single token for this?

**Comment by sbrl** [comment]
That's a good idea. `Homepage` was the initial wording we used on the main English pages. It's possible some of those are lying around with the old wording too.

**Comment by mebeim** [comment]
I'd probably go with "Mais informações". It's the same in Italian ("Maggiori informazioni").

**Comment by schneiderl** [comment]
Tottaly agree with @mebeim . If everybody agrees I will work on the PR.
