### ISSUE TITLE
page request: expect

### ISSUE THREAD

**Issue by kelthuzadx** [tldr-pages/tldr#3431]
`expect` can simulate users' I/O behaviors, and it's the standard linux command

https://linux.die.net/man/1/expect

**Comment by schneiderl** [comment]
Thanks for requesting this page, @kelthuzadx! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by einverne** [comment]
hi @kelthuzadx I have added this command, do you have any other examples to add?

**Comment by sbrl** [comment]
I'll close this issue for now, since the page has been added. Anyone is always free to submit a PR to expand it.
