### ISSUE TITLE
Investigate using Git LFS for storing the pages tarball

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#344]
Instead of polluting the repo with binary files.

**Comment by pepa65** [comment]
The pages archive is currently in the order of 100kB right? That doesn't qualify as a large file since decades...

**Comment by waldyrious** [comment]
I'd say we should close this issue, for the same reason given in #343:

> We won't invest time changing the format of the archive since we don't recommend that method of updating.

Also, the pages archive is currently being kept in the [tldr-pages/tldr-pages.github.io](https://github.com/tldr-pages/tldr-pages.github.io) repo (in the "assets" folder), so the main tldr-pages repo isn't being polluted by it. Of course, we would rather not pollute either repo, but I don't think it's a big enough deal to warrant the effort of implementing LFS -- although if anyone wants to do it, feel free to step up, we'd certainly welcome it.
