### ISSUE TITLE
get colored output in tldr snap

### ISSUE THREAD

**Issue by dddeveloperrr** [tldr-pages/tldr#3449]
Hello guys.
 I installed TLDR via snap. how can I get a colored output in tldr? at the moment, all output in my terminal is in White color
 thanks

**Comment by sbrl** [comment]
This depends on which client the snap package is giving you. Looking at snapcraft.io [here](https://snapcraft.io/tldr) it appears that it gives you the official Node.js client. I suggest looking at the documentation here, @dddeveloperrr:

https://github.com/tldr-pages/tldr-node-client/

If you still continue to experience issues, I'd recommend opening an issue against the tldr-node-client repository about it. This repository is only about the pages themselves - not any clients that display said pages :-)
