### ISSUE TITLE
page change request: windows/findstr

### ISSUE THREAD

**Issue by NNRepos** [tldr-pages/tldr#3504]
The 2 most common usages of findstr are not in the .md file:
findstr -sinr (recurSive, Insensitive, Numbered, Regex search), and
{{something}}|findstr.
I recommend removing /i, /n, /r which are rarely used by themselves.

**Comment by sbrl** [comment]
Thanks for requesting this edit! Do you want to have a go yourself?

Pages are best created and edited by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
