### ISSUE TITLE
To lint-changed, or not to lint-changed? That is the question.

### ISSUE THREAD

**Issue by igorshubovych** [tldr-pages/tldr#351]
There are 2 thoughts about whether we should have `lint-chaged.sh` script in repo:

1. Remove it completely (#350). `make lint` is currently quite fast (around 1 sec). 
2. Fix it - #348. This was a newcomer contributor will see only their mistakes, not mistakes of others.

@rprieto [thinks](https://github.com/tldr-pages/tldr/pull/347#issuecomment-162379251) that we should remove it (see here #347).

Thoughts?

**Comment by ostera** [comment]
Hmm. Okay, if `make lint` is fast enough, then it shouldn't be a problem to lint everything all the time in order to keep our sanity.

I upvoted https://github.com/tldr-pages/tldr/pull/348, but it should be closed.

**Comment by rprieto** [comment]
Agreed, I'd recommend always running `make lint` to keep things simple. If pages are kept clean people should never see other's mistakes (since the PRs with mistakes won't get merged).

**Comment by igorshubovych** [comment]
Simplicity wins
