### ISSUE TITLE
Error: Invalid signature (FYI)

### ISSUE THREAD

**Issue by nmaxcom** [tldr-pages/tldr#352]
Fresh install with no errors:

```bash
~ tldr --list
Local cache is empty
Please run tldr --update

~ tldr --update
Updating...
Done
Error: invalid signature: 0x5455646d
    at /usr/local/lib/node_modules/tldr/node_modules/unzip2/lib/parse.js:63:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)

~ tldr --list
Cache last updated Mon Dec 07 2015 11:06:00 GMT+0100 (CET)

ab, ack, ag, alias, apropos, ar, awk, bundle, cal, calibre-server, calibredb, cat, cd, chmod, chown, chsh, cksum, clang, convert, cp, curl, cut, date, deluser, df, diff, dig, drush, ebook-convert, echo, electrum, env, exiftool, fdupes, ffmpeg, find, fswebcam, gcc, gem, gifsicle, git-add, git-branch, git-checkout, git-clone, git-commit, git-diff, git-init, git-log, git-merge, git-push, git-remote, git-stash, git-status, git, gpg, grep, gzip, handbrakecli, haxelib, iconv, ipcs, kill, less, ln, lp, lpstat, ls, lsof, man, mkdir, more, mount, mp4box, mtr, mv, mysql, mysqldump, nc, nmap, node, nohup, npm, pandoc, passwd, patch, pgrep, php, ping, pip, play, ps, psql, pushd, pwd, redis-cli, rename, rm, rmdir, rsync, salt-call, salt-key, salt-run, salt, scp, screen, sed, sort, sox, split, srm, ssh, sshfs, sudo, svn, tail, tar, tcpdump, tee
```

Looks like it works fine though, just FYI.

**Comment by blittle** [comment]
Just got the same problem

**Comment by igorshubovych** [comment]
@nmaxcom and @blittle,

Sorry for inconvenience.

We know about the issue, it is almost fixed, and soon will be merged.
To temporary overcome the issue, you can try to do update several times.

If it does not work and you want to use the app, you can do things manually:

* Download zip file from Github: https://github.com/tldr-pages/tldr/archive/master.zip
* Unpack it, let's say it is in ~/Downloads/tldr-master folder
* `mkdir -p ~/.tldr/cache`
* `cp -r ~/Downloads/tldr-master/pages ~/.tldr/cache`

And then you can just try `tldr tar`.

**Comment by blittle** [comment]
@igorshubovych thanks! I manually fixed it by cloning the repo and copying the pages into cache :)

**Comment by igorshubovych** [comment]
@rprieto,

It is related to https://github.com/tldr-pages/tldr-node-client/pull/21

**Comment by igorshubovych** [comment]
@nmaxcom,
@blittle,

Please update tldr-node-client to 1.1.0:

`npm update -g`

And then run pages update again

`tldr --update`
