### ISSUE TITLE
Error: invalid distance too far back (Zlib)

### ISSUE THREAD

**Issue by voodah** [tldr-pages/tldr#355]
Ubuntu 14.04. After a fresh install ("sudo npm install -g tldr") doing "tldr --update" outputs:
 
Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:363:17)

From what I've read in issues from other packages, using "decompress" instead would solve this problem.

**Comment by ostera** [comment]
Concerns @rprieto, but should be closed since we'll be moving to `node-tar` (https://github.com/tldr-pages/tldr/issues/343)

**Comment by igorshubovych** [comment]
@rprieto,
It is related to https://github.com/tldr-pages/tldr-node-client/pull/21

**Comment by igorshubovych** [comment]
@voodah,

Please update tldr-node-client to 1.1.0:

`npm update -g`

And then run pages update again

`tldr --update`

**Comment by voodah** [comment]
Working fine now !

Thanks and good job.
