### ISSUE TITLE
add contributor: @Proscream

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#3592]
Hi, @Proscream! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#3549, #3553, #3560, #3577, #3578, #3579, #3582, #3585, and #3586)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by Proscream** [comment]
Hi @sbrl  First of all, thank you for the offer. I'm really enjoying the work of translating. I'm thinking of continuing to translate Korean. It would be great if you could add me as a collabulator.
Have a nice day!

**Comment by andrik** [comment]
Hi @Proscream 

Thank you for your contribution to the project. 

Welcome aboard :rocket:

**Comment by Proscream** [comment]
@andrik  Thank you for your hospitality. :)

**Comment by sbrl** [comment]
Invite sent :D

You should have privileges to close this issue when you accept the invite :D

**Comment by Proscream** [comment]
@sbrl Thanks! I will close this issue.

**Comment by waldyrious** [comment]
@sbrl these issues should not be closed manually, but rather with the [PR adding the new collaborator name to the MAINTAINERS.md document](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#adding-new-collaborators). 😉

**Comment by Proscream** [comment]
@waldyrious  Thank you for your advice!

**Comment by waldyrious** [comment]
No problem @Proscream. Please make sure to read the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md), which contains guidelines for performing the main maintenance tasks, and [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), which has instructions specifically about when and how to perform role changes like this one. 🙂

**Comment by Proscream** [comment]
@waldyrious Of course. I'll be well-informed of it as soon as I can. :)

**Comment by einverne** [comment]
Welcome @Proscream !

**Comment by sbrl** [comment]
Oops, I totally forgot about that step @waldyrious! I'll do that now.

**Comment by zdroid** [comment]
@sbrl Do older PRs count too? I had 17 PRs merged back in 2016. [Source](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3Azdroid+is%3Aclosed) :medal_military:

**Comment by waldyrious** [comment]
@zdroid definitely! Ideally we should collect statistics across the entire repo history so that we can recognize contributions older than the adoption of this policy, but as always, manpower has been limited 😅 (if it's something you'd like to do, please go ahead!)

In your case in particular, we can just go ahead and make the change, sure. Can you open a separate issue similar to this one for yourself, so we can keep a better record of these additions? Then @sbrl can include your name in #3617 as well :)

**Comment by bl-ue** [comment]
FYI/FTR - **Proscream** changed their username to **Geipro**. ;)
