### ISSUE TITLE
ANN: Request to try out the latest node client

### ISSUE THREAD

**Issue by agnivade** [tldr-pages/tldr#3612]
Hello folks,

I wasn't sure whether everyone was available on gitter or not, so I thought of creating a github issue ccing everyone. This is basically an announcement that the latest node client (v3.3.1) has language support now, and a request for the language translators to try it out and give feedback.

Korean - @JJByun @Proscream 

Chinese - @starccy @wizarot 

French - @julienc91 

Tamil - @arunisaac 

German - @pascaliske 

Portuguese - @xRuiAlves 

To get the pages for the correct language, your console should have a `LANG` environment variable containing a valid POSIX locale (such as zh, pt_BR, or fr). This is usually present in all `*nix` systems, but in case it is not set in your system, please do that to get the results.

Please try it out and file any issues that you see on the [node client repo](https://github.com/tldr-pages/tldr-node-client). Thank you !

P.S. I will close this issue within a few days.

**Comment by Proscream** [comment]
@lch7167

**Comment by lch7167** [comment]
It works well by korean :)

**Comment by Proscream** [comment]
![KakaoTalk_20191123_181950194](https://user-images.githubusercontent.com/28556734/69478447-bde24680-0e35-11ea-85ed-2bae95e2d668.png)
Its working!

**Comment by arunisaac** [comment]
I am travelling now. I can only get back to you in about a week.

**Comment by pascaliske** [comment]
Awesome – German translations are working too in the latest node client!

**Comment by agnivade** [comment]
Closing this now. Thank you all for trying it out.

**Comment by arunisaac** [comment]
I am a little late, but I tried the new client just now. It works
perfectly! Love it! :-) Thank you!
