### ISSUE TITLE
Add contributor: @zdroid (i.e. shameless self-promotion) 

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3636]
Related to [comment](https://github.com/tldr-pages/tldr/issues/3592#issuecomment-559563849) in #3592. (For the record, I have had [17 merged PRs](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3Azdroid+is%3Aclosed+sort%3Aupdated-desc) in the past.)

**Comment by sbrl** [comment]
Hey, @zdroid! Wow, you must have slipped through the net. There's actually no automated system for detecting these things. I've sent you an invite :-)

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

**Comment by zdroid** [comment]
@sbrl It wasn't present back then a few years ago. Somehow I became a collaborator in `tldr-node-client` repository, but not in this one.

Should I add myself in the `MAINTAINERS.md`?

**Comment by sbrl** [comment]
Ah, that's strange. Yeah, it'd be great if you could open a PR for that D:
