### ISSUE TITLE
Having OS-specific teams

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3639]
Since this project is scaling quickly, it may be a good idea to have OS-specific teams in the maintainers. It'd allow easier reviewing by mentioning qualified people for each task.

The result could be them pinged any time a page is added under an OS-specific folder. Related: #1068

**Comment by sbrl** [comment]
Interesting idea, @zdroid! I'd suggest that the primary divide at the moment is actually languages and translation, which we have #2793 currently tracking some improvements (but I think we're back to the drawing board on what to do about it though). Quite a few commands are actually cross-platform these days. It would be great if there was a way to quickly @mention people who have previously contributed to translations for a given language.

**Comment by zdroid** [comment]
There is a divide, at least on Windows and UNIX-based operating systems. Commands definitely aren't the same, far from it. Additionally, some more niche environments like Sun OS (or BSD if we add it in the future) cannot be followed that easily by all people.

**Comment by sbrl** [comment]
Very true, @zdroid. Perhaps we could solve a wider issue with @mentioning groups of people here though. Perhaps a bot where you can click a link to be added to a named group of people, and then use something like `|group_name|` would automatically generate the a comment @mentioning everyone in that group, perhaps?

Also of interest may be #1068.

**Comment by ivanhercaz** [comment]
Both ideas, languages and OS teams, are really interesting and useful. If this idea progress it would be a pleasure to contribute as a member of a Linux group, as well of the Spanish group.

**Comment by zdroid** [comment]
@sbrl Doesn't GitHub do that automatically, though?

**Comment by sbrl** [comment]
I'm not aware of any mechanism by which it does @zdroid. There are teams, but IIRC this requires that you're an org member first before you can be made a team member?

**Comment by zdroid** [comment]
I cannot test that, since I'm not an owner in any organization with outside collaborators. Did you try making a team and putting outside collaborators in?

**Comment by sbrl** [comment]
My point is that it would be cool if there was a mechanism by which users could join the teams themselves @zdroid - rather than having to make a request to join.

**Comment by zdroid** [comment]
Don't we have a condition for each collaborator to get 5 PRs merged first? Even if we had a bot, then you also need to add a mechanism to regulate the people in the team.

**Comment by sbrl** [comment]
True, but a bot that comments on a PR to say how many previous PRs someone has merged would be nice.

**Comment by zdroid** [comment]
I'm against this idea now so I'm closing it. Most of the commands are in `common` anyway and the individual differences between the systems are not that big anymore. On top of that, the maintainers team is already small enough so there's no need to split it further.

If anyone is interested in having mentions for some specific-topic, I suggest a more relevant issue to be opened.
