### ISSUE TITLE
?committer search option doesn't work

### ISSUE THREAD

**Issue by zlatanvasovic** [tldr-pages/tldr#3648]
From [`COMMUNITY-ROLES.md`](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md):

> Specifically: once a repository collaborator has _merged at least 10 PRs_ (see `https://github.com/tldr-pages/tldr/commits?committer=<username>`) and submitted at least _5 non-trivial reviews to PRs_ (see `https://github.com/tldr-pages/tldr/pulls?q=reviewed-by:<username>`), which can overlap with the 10 they merged themselves, they should be invited to become a [**member**](https://github.com/orgs/tldr-pages/people) of the tldr-pages organization.

The syntax provided for committer search, i.e. `https://github.com/tldr-pages/tldr/commits?committer=<username>` doesn't work. The information about `committer` [exists](https://developer.github.com/v3/git/commits/) in GitHub API, but it doesn't contain any reference to GitHub username. Do we replace it with some other wording?

**Comment by agnivade** [comment]
Woops, it should be `author`, not `committer`. Good catch @zdroid ! Would you like to open a PR to fix this ?

**Comment by zdroid** [comment]
@agnivade I will, but author doesn't show the commits merged by you.

**Comment by agnivade** [comment]
That's true actually. I don't know of any option that shows merged_by users offhand.

**Comment by sbrl** [comment]
I use something like this myself:

```
https://github.com/tldr-pages/tldr/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3A{{username}}
```

**Comment by zdroid** [comment]
@sbrl But again, that shows only the PRs made by you, not the ones merged by you.

**Comment by sbrl** [comment]
Ah, I misread what you were saying I thought you were talking about the opened 5 PRs one.

**Comment by zdroid** [comment]
This is an even bigger problem now, as GitHub often obscures such information. I suggest the requirement for that role being changed into non-trivial review of 10 PRs.

**Comment by sbrl** [comment]
Hrm. It might be worth implementing a script that determines how many merged PRs each person has.

**Comment by zdroid** [comment]
@sbrl Isn't it much easier to just see 10, 15 or 20 non-trivial PR reviews?

**Comment by agnivade** [comment]
I think both are important. Making reviews and writing the pages by themselves. It is the same in a normal codebase where a person should have submitted enough code first to get access. Reviews come after that IMO.

Writing a page from scratch requires you to think about the command, what options are important, in what order to write them and what examples are appropriate. It is good to be in those shoes to get an overall idea of the entire process. It also enables one to make better reviews because one has an idea of the background thinking required to write a page.

**Comment by zdroid** [comment]
@agnivade we are talking about "once a repository collaborator has merged at least 10 PRs", not the one before (about having your own PRs merged).

**Comment by agnivade** [comment]
Ah my bad. Yes, I don't see any big downsides of it.

**Comment by zdroid** [comment]
@agnivade downsides of what exactly? What would you suggest to replace the obviously not present option `?committer`?

**Comment by zdroid** [comment]
Found a solution: https://stackoverflow.com/questions/29277128/find-pull-requests-merged-by-a-specific-user
Is somebody up to write a script for this?

**Comment by sbrl** [comment]
Ah, that sounds like what we want. You could probably do it in Bash with `curl` + `jq` I'd guess, but it might be a little complicated.

**Comment by zdroid** [comment]
@sbrl Are you experienced with jq and curl? Author of that post already provided JS code:
```js
var result = {};
$.get("/api/v3/repos/atg/atgse/pulls?state=closed&per_page=100", function(pulls){
    pulls.forEach(function(listPullItem){
        $.get(listPullItem.url, function(pull) {
            if (pull && pull.merged_by) {
                result[pull.merged_by.login] = result[pull.merged_by.login] || 0;
                result[pull.merged_by.login] ++;
            }
        });
    });
});
```

**Comment by sbrl** [comment]
@zdroid haha I do have skills in that area, yeah lol

/cc @mebeim, @owenvoke, @agnivade: I implemented a script that might be useful (see below)

I just looked it up in the GitHub API, and implemented the script at the bottom of this comment . It creates a list of usernames and the number of PRs that have been merged that were opened by them.

## Usage
1. First, get a personal access token from <https://github.com/settings/tokens>.
2. Save the below script to a file (e.g. `pulls.sh` will be assumed in the below examples)
3. `chmod +x path/to/pulls.sh`
3. Then, execute it like this:

```bash
echo "YOUR_GITHUB_USERNAME PERSONAL_ACCESS_TOKEN" | path/to/pulls.sh >path/to/output_file.txt
```

Progress information will be written to the standard error. Currently tldr-pages/tldr has ~122 pages of closed PRs, so it takes a while - for me it took ~3m32s.

For those unable to run the script, here is the output as of the time of commenting: [tldr-pages-pulls.txt](https://github.com/tldr-pages/tldr/files/4956036/tldr-pages-pulls.txt)

.....clearly we have a number of people we might want to ask to about external collaborator access :P

The top 3 contributors are @waldyrious, @owenvoke, and @sbrl.

---------------------------------------

```bash
#!/usr/bin/env bash

# pulls.sh: Fetches the numbe of closed PRs submitted by users.

# ENVIRONMENT VARIABLES
#	REPO_USER		The username that owns the repo (default: tldr-pages)
#	REPO_NAME		The  name of the repository (default: tldr)

# I/O
# 	stdin	A GitHub username and Personal Access Token combo
#	stdout	A list of users and the number of merged PRs they've submitted.
#	stderr	Progress information

# EXAMPLE
#	echo "username access_token" | path/to/pulls.sh

REPO_USER="${REPO_USER:-tldr-pages}";
REPO_NAME="${REPO_NAME:-tldr}";

user_agent="tldr-pages-pr-counter/0.1 ($(arch); $(uname -o); +https://github.com/tldr-pages/tldr/issues/3648; implementor: @sbrl Starbeamrainbowlabs) curl/$(curl --version | head -n1 | cut -d' ' -f2)";

# $1	page number
iterate() {
	local page_number="${1}";
	local content;
	echo "[${SECONDS}] Fetching page ${page_number}" >&2;
	content="$(curl --user-agent "${user_agent}" -sSL "https://${auth_username}:${access_token}@api.github.com/repos/tldr-pages/tldr/pulls?state=closed&page=${page_number}")";
	
	# Return with exit code 1 when we've reached the end - this will break the below while loop
	if [[ "$(echo "${content}" | jq 'length')" -eq 0 ]]; then
		return 1;
	fi
	
	echo "${content}" | jq --raw-output '.[] | select(.merged_at != null) | .user.login';
}

read -r auth_username access_token;

if [[ -z "${auth_username}" ]]; then
	echo "Error: No AUTH_USERNAME specified";
	exit 1;
fi
if [[ -z "${access_token}" ]]; then
	echo "Error: No access token supplied via stdin";
	exit 2;
fi

# Continue so long as iterate exits with code 0
i=1
while iterate "${i}"; do
	i=$((i+1));
	# Uncomment to do just the first 5 pages
	# if [[ "${i}" -gt 5 ]]; then break; fi
done | sort | uniq -c | sort -nr;
```


......does anyone think a PR against tldr-pages/tldr is a good idea for this script

**Comment by owenvoke** [comment]
Nice script @sbrl! Were you thinking of adding that to the `scripts` directory for general use? Or as part of the GitHub Action we were planning on? 🙂

**Comment by sbrl** [comment]
Just revised the script above to pull 100 PRs at a time, bringing the total number of requests down to ~38.

I wasn't really sure @owenvoke! It does take several minutes to complete due to the number of requests it has to make, so I'm unsure as to whether it's suitable to for a GitHub action. I could certainly open a PR for the `scripts/` directory though.

It would be great to use it as a component in your GH action for role detection though :D

What do you think?

**Comment by sbrl** [comment]
Looks like we have a number of users that have over the 10 PR threshold though that we haven't invited too. We should really do something about that.

**Comment by zdroid** [comment]
@sbrl Write another script to add them all? :wink:

**Comment by sbrl** [comment]
Perhaps we could open 1 big issue about it?

**Comment by zdroid** [comment]
Good idea! It'd be good if you put the list with those names here, or in that new issue.

**Comment by sbrl** [comment]
Well according to the list, the following contributors have over 10:

```
    250 waldyrious
    211 owenvoke
    163 sbrl
     80 mebeim
     79 agnivade
     57 Aracki
     56 zdroid
     54 igorshubovych
     38 Proscream
     38 oxguy3
     32 Rudloff
     30 einverne
     28 andrik
     26 schneiderl
     26 rubenvereecken
     24 jsonbruce
     23 felixonmars
     21 lbonanomi
     20 ivanhercaz
     18 xRuiAlves
     18 notpeter
     15 mstruebing
     15 jeeftor
     15 AnimiVulpis
     13 kalebo
     13 fuerbringer
     13 ericbn
     11 mfrw
     11 ghost
     11 dhondta
     11 Cvetomird91
     11 ChungZH
     11 Calinou
     10 onesuper
     10 Dahie
     10 85pando
```

....but generally speaking the guidelines suggest only inviting those that are "particularly active". I've been thinking about it, and now I'm unsure as to what to do. I'm probably over thinking it.

**Comment by zdroid** [comment]
I agree with *inviting those that are "particularly active"*, so we can just proceed with doing that if no one objects.

**Comment by zlatanvasovic** [comment]
This is definitely resolved. Perhaps the next step would be to open a new PR / issue to implement @sbrl's work into the formal docs of this project.

**Comment by waldyrious** [comment]
> This is definitely resolved.

How so, @zlatanvasovic? Do we have a way to get the data that ?committer was supposed to provide? Or do we rely manualy running @sbrl's script? If so, I'd prefer to keep this open until we either add that functionality to the bot, or we include information about on this script in the documentation.

**Comment by zlatanvasovic** [comment]
@waldyrious I just wanted to close my own issues, but you can open a new one if you think it's still an issue. :smile:

**Comment by waldyrious** [comment]
Well, the issues are not really "owned" by anyone — either they represent a legitimate issue with the project, or they don't. In this case, I'm trying to understand what in your view "resolved" the initial problem that was raised:

> The syntax provided for committer search, i.e. `https://github.com/tldr-pages/tldr/commits?committer=<username>` doesn't work.

That is still the case, isn't it?
