### ISSUE TITLE
page request: git-push.md

### ISSUE THREAD

**Issue by jwq1** [tldr-pages/tldr#3650]
The prior example, 
https://gist.github.com/hackjutsu/33b970dd117889485491c018543e5118

`# git push

> Push commits to a remote repository.
> More information: <https://git-scm.com/docs/git-push>.

- Send local changes in the current branch to its remote counterpart:

`git push`

- Send local changes in a given branch to its remote counterpart:

`git push {{remote_name}} {{local_branch}}`

- Set the remote branch for your current local branch. Send local changes. 

`git push -u origin {{local_branch}}`

- Send changes on all local branches to their counterparts in a given remote repository:

`git push --all {{remote_name}}`

- Delete a branch in a remote repository:

`git push {{remote_name}} --delete {{remote_branch}}`

- Remove remote branches that don't have a local counterpart:

`git push --prune {{remote_name}}`

- Publish tags that aren't yet in the remote repository:

`git push --tags``

**Comment by agnivade** [comment]
Hi @jwq1 - can you clarify what you want to achieve here ? It is not clear to me.

**Comment by sbrl** [comment]
Erm that page already exists, @jwq1. Furthermore, this text appears to be copied from the existing git push page.

**Comment by zdroid** [comment]
As far as I understood you, you wanted the options from that Gist added to `git-push.md`. However as you can see in [the file](https://github.com/tldr-pages/tldr/blob/master/pages/common/git-push.md), the command mentioned to push is already present.

I'm closing this now. If I didn't understand you correctly, this will be reopened. :smile:
