### ISSUE TITLE
Add organization member: @zdroid (more shameless self-promotion)

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3663]
It seems #3644 was my 10th PR merged, not sure which was the 5th one I reviewed.

Note: it also seems @mebeim has been an active organization member for more than 6 months. Shouldn't he become an organization owner now?

**Comment by mebeim** [comment]
Oh, right, I totally forgot about that promotion thing. I'm fine with either role, I'll let existing owners decide if they want to add me as owner.

**Comment by agnivade** [comment]
Yes of course. You're an old timer now @mebeim :) I will let @sbrl do the honours as they have done it the past few times.

**Comment by waldyrious** [comment]
@mebeim just to make this clear for the record — it is not up for the current owners to _decide_ whether to add new owners. We have a [written set of guidelines](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md#when-to-change-roles) that clearly define when that should happen, and you unambiguously fit the bill 🙂. (Those guidelines can, of course, be altered by the community by consensus following an open discussion, as can every other aspect of the project.)

**Comment by mebeim** [comment]
Err, sorry that came out wrong. I did not mean to imply that, of course, I know the guideline. I was just saying that it's fine for me either way and I'll let somebody else open the issue for me, there is no rush or need to.

**Comment by waldyrious** [comment]
No problem, @mebeim, I did assume that you were aware of it and probably had just worded your comment in a way that could imply otherwise 🙂 hence the "for the record" in my comment — it was just so make sure others didn't get misled by that phrasing (and to make good use of the opportunity to reiterate the open, democratic process we're aiming for in this project 😄).

**Comment by sbrl** [comment]
Invite sent :D

**Comment by waldyrious** [comment]
Let's create a separate issue for transitioning @mebeim to org owner?

**Comment by mebeim** [comment]
@waldyrious already happened! #3672

**Comment by waldyrious** [comment]
Hahah I missed it, thanks for the pointer :)

**Comment by sbrl** [comment]
Hey, @zdroid! We've noticed you haven't joined Gitter yet (https://gitter.im/tldr-pages/tldr). Perhaps you could start hanging out there please? It's great to be able to chat about reviews etc.

**Comment by zdroid** [comment]
I'm quite reluctant about making any new online account, which is why I didn't make one for Gitter either. However, I do open tldr's chat from time to time, so I may consider joining it in the future. I try not to drain my time on chats too, as I'll be busy for next few months.

**Comment by mebeim** [comment]
@zdroid you don't need any new account, you just log in using your existing GitHub account. Communicating with the rest of us is important, and being reachable through Gitter is also one of the requirements outlined in [`COMMUNITY-ROLES.md`](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md):

> If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
You'll now be one of the public faces of the tldr-pages project.

**Comment by zdroid** [comment]
@mebeim That's a deal I can make. It also turns out I've always had an account there, since I've made one in the past for Node.js / Jekyll.

**Comment by sbrl** [comment]
> I try not to drain my time on chats too

The tldr-pages chat isn't all that active. There are only 1 or 2 messages every few days, so it's perfectly fine to check it along with regular GH notifications :-)
