### ISSUE TITLE
Add owner: @mebeim

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#3672]
Hi, @mebeim! You've been an active tldr-pages org member for over 6 months.
Thanks for sticking around this far and helping out!
According to [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
Before performing such role transitions, make sure to review the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by mebeim** [comment]
Thank you @sbrl, I'm in for the ride :smile:
