### ISSUE TITLE
Add collaborator: @ivanhercaz

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3690]
Hi, @ivanhercaz! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#3669, #3682, #3670, #3675, #3680)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by sbrl** [comment]
Oops, looks like you missed the links to the relevant PRs here @zdroid :P

**Comment by zdroid** [comment]
They're already there in the commit list. :P 
#3669 #3682 #3670 #3675 #3680

**Comment by ivanhercaz** [comment]
@zdroid, for me it is a pleasure to accept your invitation and be a collaborator in this awesome and useful project. Thank you for this proposal. I am really happy to be part of this project as collaborator.

**Comment by waldyrious** [comment]
> They're already there in the commit list. :P

Do you mean here? https://github.com/tldr-pages/tldr/commits?author=ivanhercaz

Note that these issues are meant to serve as historical record for the role changes, so a dynamic listing will not work well for that purpose. (Also, the message looks rather unfinished with placeholder text left in!)

I've added the links you mentioned to the opening comment. Next time please do so when creating the issue. 🙂

**Comment by zdroid** [comment]
@waldyrious Oh you're right. I didn't notice that part of the template was left unedited.
