### ISSUE TITLE
Adapt issue template(s) for new GitHub workflow

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3702]
More info: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by ivanhercaz** [comment]
Do you mean to add different issue and PR templates to make easier the collaboration?

**Comment by zdroid** [comment]
Kind of. That's what GitHub suggests, as you can read on the page.

**Comment by sbrl** [comment]
Not sure what you're getting at here @zdroid. Do you mean to say that we should add additional issue / PR templates, or edit the existing ones?

**Comment by zdroid** [comment]
GitHub says there should be more than one, at least *feature request* and *bug report*.

**Comment by sbrl** [comment]
Ah, I see. I'm not sure that with issues that really applies here though? I mean we have page requests, but issues are more used to document discussion here rather being 'issues' that need closing.

**Comment by zdroid** [comment]
Re-reading the GitHub manual, I don't think the idea is useful for this repository. We don't really have bug reports, or feature requests. All use cases for the issues are already nicely explained in the current template.
