### ISSUE TITLE
Split "help wanted" and "hacktoberfest" labels

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#3706]
We've been using the same label for both purposes, renaming it to "hacktoberfest" when October starts, and renaming it back to "help needed" when it's over. That, however, causes unnecessary ambiguity. We already have a "GCI" label for the Google Code-In program, so we might as well have a dedicated label for Hacktoberfest as well.

To do so, we need to create a new label named "hacktoberfest", then relabel all the issues and PRs currently labeled "help wanted" that should use the new label instead (e.g. those created during the month of October or shortly before it).

**Comment by zdroid** [comment]
It's "help wanted", instead of "help needed". However, I'm not sure how adding more labels would help the project. It'll make things more complicated than they are now. In my opinion, there are already enough useless labels in the project.

**Comment by waldyrious** [comment]
Thanks for the correction. I don't think labels are at a point that they cause more harm than good, to be honest, though your point is well taken.

I think it would help a great deal if we add descriptions to the labels so that it's clear what context each of them applies to. In that process, we might find out that indeed we have duplicate or unnecessary labels.

But I'd like to discuss that in a separate issue, as we historically have had a hard time wrapping discussions when the theme gets too broad. 😅

**Comment by zdroid** [comment]
I agree with you on that, but then we could name this "Split/merge ..." instead of just "Split". It could go in both directions. :wink:

**Comment by sbrl** [comment]
Yeah, we really need to do this - to preserve the metadata associated with the different versions of the label.

@zdroid: The `clients` label in particular is pretty important. It's used to identify issues that are to do with tldr clients, rather than tldr itself.

**Comment by ivanhercaz** [comment]
Labels are very useful to manage the issues and filter them. I am agree with thematic labels (e.g., `hacktoberfest` and `gci`), because they are very useful to know what have been done in a specific context. But if an open issue labeled as one of these thematic labels is still open when the context have finished, these labels should be replaced by `help wanted`.

> To do so, we need to create a new label named "hacktoberfest", then relabel all the issues and PRs currently labeled "help wanted" that should use the new label instead (e.g. those created during the month of October or shortly before it).

But if I understand this, what you said, @waldyrious, is to label all the issues created shortly before and during as `hacktoberfest`, but if they are not solved during the Hacktoberst, it should be still labeled as `hacktoberfest`, no?

**Comment by waldyrious** [comment]
That's a good point, @ivanhercaz. Indeed I was talking implicitly about closed issues. I agree that the open ones should be relabeled. In fact, we have effectively been doing exactly that relabeling in a roundabout way, by renaming the label; so the intent is the same, even though the method was, in hindsight, not optimal — hence this issue :)

**Comment by waldyrious** [comment]
> The `clients` label in particular is pretty important. It's used to identify issues that are to do with tldr clients, rather than tldr itself

And just for completeness, the `invalid` label is specifically needed to mark spam PRs in Hacktoberfest so that they will not be counted for the event.

**Comment by agnivade** [comment]
Mattermost has 2 separate labels for [HW](https://github.com/mattermost/mattermost-server/labels/Help%20Wanted) and [hacktoberfest](https://github.com/mattermost/mattermost-server/labels/Hacktoberfest), so I think we should be fine doing this.

Just to confirm, before hacktoberfest starts, we plan to add the label to the desired issues, and after it ends, we would remove them from the open issues ?

**Comment by waldyrious** [comment]
> Just to confirm, before hacktoberfest starts, we plan to add the label to the desired issues, and after it ends, we would remove them from the open issues ?

I think that would be reasonable. Of course, the "help wanted" label should not be removed when doing so.

**Comment by sbrl** [comment]
Also for reference, labels with the name `help wanted` or `good first issue` are handled specially by GitHub, with issues labelled with them shown in some extra places I can't remember.

**Comment by marchersimon** [comment]
Since there are now separate labels for `help wanted` and `hacktoberfent`, I'll close this issue.
