### ISSUE TITLE
Add organization member: @ivanhercaz

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3736]
Hi, @ivanhercaz! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks.
Thank you for that!
According to [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project (#3700 #3714 #3713 #3720 #3722 #3723 #3729 #3728 #3735 #3731).
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
You'll now be one of the public faces of the tldr-pages project.

How does that sound? Are you up for it?

**Comment by ivanhercaz** [comment]
Wow! Thank you very much, @zdroid, for this invitation. For me it will be a pleasure to be a member of tldr-pages if the team is agreed with this.

To answer your last questions: that sounds really fine. I hope to contribute in everything I can.

A huge hug for everyone!

**Comment by sbrl** [comment]
Invite sent!

**Comment by ivanhercaz** [comment]
Invitation accepted! It is really awesome. Thank you to everyone :heart:
