### ISSUE TITLE
The use of repository's wiki

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3752]
Currently the project has its own [GitHub wiki](https://github.com/tldr-pages/tldr/wiki). What's the use of it in the current state of project? It seems most of the pages are quite outdated there, although some of the pages aren't present in the repository itself.

I see two issues with the sole existence of the Wiki:
1. lack of review system (like the one we have for PRs)
2. duplication of information

What are your thoughts on this?

**Comment by sbrl** [comment]
The wiki is useful for tracking additional information about the project. For example, the projects page details a number of pretty important projects that are waiting to be undertaken at some point - which would otherwise get lost.

**Comment by zdroid** [comment]
Do you agree it should be updated and re-structured?

**Comment by sbrl** [comment]
Looking more closely, I note a few things:

 - The "minimum specifications" page should be deleted. We now have a full client spec which we are now using instead.
 - The clients page could probably use being compared to the other list in the README and potentially folded in.
 - The 2 projects pages are probably fine as-is - but we could use advertising them in the contributing section of the README or something :P

**Comment by ivanhercaz** [comment]
> - The clients page could probably use being compared to the other list in the README and potentially folded in.

There is already a project in the [Season of Docs projects](https://github.com/tldr-pages/tldr/wiki/Season-of-Docs-projects) wiki page in which the objective is to "Merge the lists of clients on the wiki, the README and the website". This project with a bit of patience and working at least bit by bit might be done easily.

**Comment by zdroid** [comment]
@ivanhercaz porting docs from Wiki into repository can be done quite easily. I'm just waiting for the green light from other maintainers to begin.

**Comment by ivanhercaz** [comment]
@zdroid, for me it is a good idea, I think it should be useful to have the feedback of @mebeim and @waldyrious as possible mentors listed in the SoD project.

**Comment by mebeim** [comment]
> porting docs from Wiki into repository

This would only require additional work IMHO, I don't really see the need. The Wiki is meant to contain miscellaneous information that does not precisely fit inside the repo, and which doesn't need version control.

I agree that a bit of re-ordering could be done. I agree with the changes proposed in @sbrl's [comment](https://github.com/tldr-pages/tldr/issues/3752#issuecomment-574829548).

**Comment by zdroid** [comment]
Wiki system doesn't reward contributors, which is the reason why I'd avoid it at any costs. Projects could be moved to GitHub's Projects page, while everything else is useful information which would be valuable inside official docs.

**Comment by sbrl** [comment]
Not sure I'm getting your point about rewarding contributors, @zdroid. The wiki is for additional meta-information about the project. If a contributor takes on a project on the wiki, then they'd open a PR that would eventually get merged.

**Comment by zdroid** [comment]
I'm closing this as the issue is no more relevant. The wiki is here to stay, and it'll be updated by those who want to contribute to it.
