### ISSUE TITLE
What does tldr stand for? any easy way to remember?

### ISSUE THREAD

**Issue by halida** [tldr-pages/tldr#376]

**Comment by igorshubovych** [comment]
Simplified, community-driven man pages

**Comment by igorshubovych** [comment]
Oh, you mean what does the abbreviation means?

It is easy. Too Long Don't Read:
http://www.urbandictionary.com/define.php?term=TLDR

**Comment by igorshubovych** [comment]
@rprieto,

this probably should be mentioned in README.md

**Comment by rprieto** [comment]
Good idea having a link in the README. Also from Wikipedia: https://en.m.wikipedia.org/wiki/TL;DR

It was tongue-in-cheek for the fact that many people don't bother reading the `man` pages because they're too long (though I *do* believe it's worth reading them!)
