### ISSUE TITLE
Add organization member: @schneiderl

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3764]
Hi, @schneiderl! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks.
Thank you for that!
According to COMMUNITY-ROLES.md, you've now met the thresholds to be effectively considered an active maintainer of the project (for example, 14 merged PRs on https://github.com/tldr-pages/tldr/commits/master?after=711a1c4afb5913d0bdcaf489210e4290cd369a9e+314 and https://github.com/tldr-pages/tldr/commits/master?after=711a1c4afb5913d0bdcaf489210e4290cd369a9e+349).
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
You'll now be one of the public faces of the tldr-pages project.

How does that sound? Are you up for it?

**Comment by schneiderl** [comment]
Hi,  
Thank you for the invite. It will be a great honor to be a member. 
I've not been able to be as active lately but I intend to getting back as soon as possible.

Once again thank you :)

**Comment by mebeim** [comment]
@schneiderl invite sent :) you can merge #3766 yourself after accepting.

**Comment by schneiderl** [comment]
I`ve accepted and made it public. Once again thank you for your trust.

**Comment by zdroid** [comment]
Sorry for the mess. This issue was stuck in my open issues for some weird reason.
