### ISSUE TITLE
Adding Serbian/Croatian/... languages

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#3773]
I can translate the pages to Serbian and Croatian, but I'm unsure of how to label those. You can get a grasp on the situation from the first few sentences of the Wikipedia page for [Serbo-Croatian language](https://en.wikipedia.org/wiki/Serbo-Croatian). Most of the foreign linguists consider it as one language, under that name. Wikipedia, for example, has Serbian, Croatian, Bosnian and Serbo-Croatian versions.

The questions is should we
- follow Wikipedia's example (conciliatory)
- not include Serbo-Croatian but include others (realistic) or
- include Serbo-Croatian or some variant of that name only (extreme)?

The primary concern for me is not to alienate any future contributors, of course. What are your opinions?

**Comment by sbrl** [comment]
You probably want the 2-letter language codes for those languages. See here: https://www.linux.com/news/controlling-your-locale-environment-variables/

For reference, basically full language codes take the following form:

```
language(_territory)(.encoding)(@modifier)
```

Currently we're only interested in the `language` and possibly the `_territory`. For example, we currently have `pt` and `pt_BR` with translated pages.

Such 2-letter language codes are defined by ISO-639, I think. Quick reference: https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019)

In the case that a 2-letter code is not specific enough, the territory / country-specific codes can be found here: https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes (it's the alpha-2 column you want).

Looking at the sidebar of that page, the code we probably want here is `hbs` - that is the collective code for the entire group of languages. If there are significant differences for a page, we might want to have a copy under a more specific language code.

You know, it might be worth us writing up a generic help page on language codes - both for translators to know which ones to use (though the client spec does this - but could perhaps be improved in clarity?), and for users (so they know how to properly configure their `LANGUAGE` and `LC_ALL` environment variables according to the client specification.

**Comment by zdroid** [comment]
The main concern here aren't the language codes, but the possible existence of almost completely same pages under Serbo-Croatian, Serbian and Croatian page directories.

**Comment by sbrl** [comment]
Ah. Wait, we have pages under those directories already?

**Comment by zdroid** [comment]
We don't, I'm actually asking which of those directories to make.

**Comment by sbrl** [comment]
Ah, I see. I'd suggest creating them under `hbs`, and then we can create more specific ones as needed.

**Comment by ivanhercaz** [comment]
It isn't the same issue that with Spanish, but it has similarities. I created `pages.es` because personally I consider there isn't enough differences to differentiate between the Spanish-speaking from Spain, or any part of Spain (Canary Islands, Andalusia, etc.), and from countries of Latin American. However, there are sites in which they differentiate between `es-es` (Spain) and `es-la` (Latin American). I think if sometimes, in the future, another Spanish contributor proposed a differentiation it should be discussed. It seems a similar issue with Portuguese (cc. @waldyrious, @schneiderl), but I usually see more sites with a differentiation of `pt-pt` and `pt-br`.

I am agree with @sbrl and with your PR, @zdroid. And thank you for your contribution and initiative to translate pages to your language!

**Comment by schneiderl** [comment]
@ivanhercaz We did had the same problem with Portuguese pages. In this case, though, the differences between `pt-pt` and `pt-br` are very present and they need to be differentiated. If there aren't many differences I would think that the right way to do it is to have only one folder.

**Comment by zdroid** [comment]
There are differences (even in the tech terminology), but I think it can work out this way. Let's wait and see.
