### ISSUE TITLE
snap package hangs when updating

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#3777]
Ubuntu 18.04, `snap -u` 
pip client works fine

**Comment by sbrl** [comment]
Hey, thanks for the report @jxu! Unfortunately, this repository is only for the pages themselves, not any clients.

The snap package is actually the [Node.js client](https://github.com/tldr-pages/tldr-node-client/) perhaps you could file a bug over there instead?

Other troubleshooting steps could involve trying the Node.js client directly like this:

```bash
sudo npm install --global tldr
```

....making sure to remove all other tldr clients first, of course.

**Comment by jxu** [comment]
@sbrl you're right, snap package is apparently abandoned https://github.com/tldr-pages/tldr-node-client/issues/289

**Comment by sbrl** [comment]
No problem, @jxu! Don't forget though that there's a plathora of other clients you can use documented in the README :-)

**Comment by jxu** [comment]
Anyway the snap package should be removed from tldr.sh site for now (it is not on this repo's README)

**Comment by sbrl** [comment]
Wait, there's a link of tldr.sh? Oops. Could you open an issue against [tldr-pages/tldr-pages.github.io](https://github.com/tldr-pages/tldr-pages.github.io) please, @jxu?

**Comment by zdroid** [comment]
@sbrl I did it in tldr-pages/tldr-pages.github.io#44.
