### ISSUE TITLE
page request: dpkg

### ISSUE THREAD

**Issue by FortTheStrox** [tldr-pages/tldr#3782]
https://help.ubuntu.com/lts/serverguide/dpkg.html

**Comment by zdroid** [comment]
Check [`/pages/linux/dpkg.md`](https://github.com/tldr-pages/tldr/blob/d7696612276835826210b051b6993ff022c6a75c/pages/linux/dpkg.md) and [`/pages/linux/dpkg-query.md`](https://github.com/tldr-pages/tldr/blob/5ef55e6fc44ddb75672469a9403e49702bc27753/pages/linux/dpkg-query.md). To me it seems your issue has already been solved, so I'm closing it. If there's something missing on there, just comment here and the issue will be reopened.
