### ISSUE TITLE
Choose page / differentiate between shell command and C function?

### ISSUE THREAD

**Issue by NSExceptional** [tldr-pages/tldr#3803]
Maybe `tldr` is strictly for shell commands, but `man` is not. So I must ask: is there any way to, say, look at the page for `exit(3)`, the C function, instead of the command?

**Comment by zdroid** [comment]
That's out of the scope of the project, as far as I can tell. We're only dealing with the commands executable in Shell here.

**Comment by NSExceptional** [comment]
Gotcha, just wondering. Would be nice but I understand.

**Comment by zdroid** [comment]
If you're interested in that, you could also start a similar project of simplified man pages for C (or C functions). :p

**Comment by NSExceptional** [comment]
I honestly feel like this tool is perfect for it — I would be duplicating so much of the work done here if I tried.

Perhaps in the future I will submit a PR to add a flag to indicate that the user wants to look up a function. But if that would still be unwelcome, I probably won't do anything. I'd really rather not just fork this repo, rename the tool, and delete all the pages, because that's what it would encompass lol

**Comment by sbrl** [comment]
Since the tldr client ecosystem is open and thereare tons of different clients available, all you'd need to do is create your own custom repository of pages and point an existing client at it @NSExceptional :-)

**Comment by NSExceptional** [comment]
Oh, hm. That's fair.

It's no fun if I'm the only one using it though 😅

No worries, just wanted to bring it up!

**Comment by sbrl** [comment]
True, but it might be possible to add your project to the [similar projects](https://github.com/tldr-pages/tldr/#similar-projects) section of the readme

**Comment by NSExceptional** [comment]
Ah, I didn't see that. I just might do that then. Thanks! :)

**Comment by sbrl** [comment]
Keep us posted on how you get on!

**Comment by zdroid** [comment]
> Since the tldr client ecosystem is open and thereare tons of different clients available, all you'd need to do is create your own custom repository of pages and point an existing client at it @NSExceptional :-)

@sbrl We definitely could generalize this project and make it a bootstrap for the future document collections. Now that's an idea I like.
