### ISSUE TITLE
page request: sequelize

### ISSUE THREAD

**Issue by Izzur** [tldr-pages/tldr#3818]
Sequelize is a promise-based Node.js ORM for Postgres, MySQL, MariaDB, SQLite and Microsoft SQL Server. Sequelize has its own CLI tools and its manual available here:
https://sequelize.org/v5/manual/migrations.html#running-migrations

**Comment by zdroid** [comment]
Do you have any experience with the tool? Perhaps you could write a skeleton of the page, 2-3 examples. That's more than enough for the start. :)

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by Izzur** [comment]
Maybe I will try to create the pages and then submit PR

**Comment by ivanhercaz** [comment]
@Izzur, if you have some doubt, problem or whatever with the creation of the page, don't hesitate yourself for ask us in the PR! We are here to help in whatever we can :heart:

**Comment by schneiderl** [comment]
Thank you @Izzur for your contribution.
