### ISSUE TITLE
Using tldr behind a firewall & proxy ? 

### ISSUE THREAD

**Issue by long-nguyenxuan** [tldr-pages/tldr#3834]
I'm using tldr nodejs client, the client is OK, no problem when I use it on my home PC, but at work, I use a PC behind firewall and proxy, which only open for some specific sites. 
What is the tldr's repository website(s), so I could ask my IT dept to allow it? 
Or could I build a "internal cached repository" which sync periodically with global for using internally behind firewall?? 
Regards, LongNX.

**Comment by agnivade** [comment]
The repo is at - https://github.com/tldr-pages/tldr-node-client/blob/master/config.json#L3.

And yes, you can point this to any internal HTTP server in your network hosting that zip file.

**Comment by long-nguyenxuan** [comment]
Thank you, it works like a charm!
