### ISSUE TITLE
install show issues:ERROR:  While executing gem ... (Errno::EPERM)     Operation not permitted - /usr/bin/restclient

### ISSUE THREAD

**Issue by liujieyuu** [tldr-pages/tldr#384]
install show issues:ERROR:  While executing gem ... (Errno::EPERM)     Operation not permitted - /usr/bin/restclient

**Comment by igorshubovych** [comment]
@liujieyuu 
Could you please provide more detailed description of your environment?
- OS? (`uname -a`)
- Ruby version? (`ruby -v`)
- Rubygems version (`gem -v`)

**Comment by liujieyuu** [comment]
install in mac,the system is OSX IE Capitan 10.11.2 (15C50),ruby's version is 2.5.0,

**Comment by igorshubovych** [comment]
hmm. there is no such ruby version.
2.3.0 was released today.

Are you using jruby, mruby or anything like that?

**Comment by liujieyuu** [comment]
@igorshubovych  my mac own:
![image](https://cloud.githubusercontent.com/assets/6056620/12003015/16baf5a6-ab4b-11e5-900c-b436f3be8928.png)

**Comment by igorshubovych** [comment]
oh, so it is rubygems version. i see.

then which ruby version do you have?
`ruby -v`

**Comment by igorshubovych** [comment]
Also have you tried this command before?
`make setup`

**Comment by liujieyuu** [comment]
@igorshubovych  oh,so this.thanks.
![image](https://cloud.githubusercontent.com/assets/6056620/12003030/6f7c7732-ab4b-11e5-8d88-3fbeb431a794.png)

**Comment by liujieyuu** [comment]
it's this,may you tell me how to do?i want to use tldr

**Comment by liujieyuu** [comment]
@igorshubovych make setup?? i dont use this command before.

**Comment by igorshubovych** [comment]
Take a look here:
https://github.com/aanand/git-up/issues/96

If you are using system OSX Ruby, you need to install bundler with sudo
`sudo gem install bundler`

And then just
`make setup`

However, to use tldr you don't need `make setup`. To use it, just `npm install --global tldr`, and then run `tldr tar`.
Ruby scripts are used for contribution to tldr pages archive to lint pages.

**Comment by liujieyuu** [comment]
oh,thanks ,i go to do it.

**Comment by igorshubovych** [comment]
So I am closing this one. Feel free to reopen if you have if it is not addressed.

**Comment by liujieyuu** [comment]
@igorshubovych my god~.
![image](https://cloud.githubusercontent.com/assets/6056620/12003144/e5233806-ab4e-11e5-82ea-ba8975461592.png)

**Comment by igorshubovych** [comment]
It is not related to tldr. It is OSX or bundler issue.

I think this is the source:
https://github.com/bundler/bundler/issues/4065

I would recommend you to use the latest version of Ruby (2.2.4 or 2.3.0). It is easy to switch between several versions of Ruby with [rvm](https://rvm.io/) (my choice) or [rbenv](https://github.com/rbenv/rbenv).

**Comment by igorshubovych** [comment]
@liujieyuu did it help?

**Comment by liujieyuu** [comment]
@igorshubovych  the bundler i have install ,but "make setup" command is wrong ,show "make: *** No rule to make target `setup'.  Stop.
"

**Comment by igorshubovych** [comment]
You should run make setup inside your fork's folder

**Comment by liujieyuu** [comment]
@igorshubovych what's the folder name?can you tell me path

**Comment by igorshubovych** [comment]
Sure.
But first tell what is your goal? Are you going to just use tldr? Or you want to contribute too?

What have you previously done for it?

**Comment by liujieyuu** [comment]
i   want  use tldr ,and then improve the work efficiency,i'm ios developer. In the work,i often use mac's terminal.

**Comment by igorshubovych** [comment]
in this case just use it with node client (`npm i -g tldr`).

You don't need any gems.
