### ISSUE TITLE
page request: sponge

### ISSUE THREAD

**Issue by amitech** [tldr-pages/tldr#3864]

**Comment by einverne** [comment]
hi @amitech Thank you for your requesting. Could you please provider some reference pages? Or could you write one page?

If you want to do it yourself, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository.

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

@einverne: It's command that solves the `foo <file.txt >file.txt` problem. While it's not installed by default, on debian-based systems it is available in the `moreutils` package:

```
SPONGE(1)                          moreutils                         SPONGE(1)

NAME
       sponge - soak up standard input and write to a file

SYNOPSIS
       sed '...' file | grep '...' | sponge [-a] file

DESCRIPTION
       sponge reads standard input and writes it out to the specified file.
       Unlike a shell redirect, sponge soaks up all its input before writing
       the output file. This allows constructing pipelines that read from and
       write to the same file.

...
```

**Comment by amitech** [comment]
Okay, I will write the page.
