### ISSUE TITLE
Explain tar flags?

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#3876]
Just a thought from reading the README. The contributing guidelines say to allow people to understand the commands. The infamous tar flags can be easily explained by noting the common flags match their commands: (c)reate, e(x)tract, g(z)ip, (v)erbose, archive (f)ile, (a)uto-detect by extension. Perhaps these mnemonics should be added in each description.

**Comment by sbrl** [comment]
Hey there! We have done something like this on other pages, by doing `[f]oo, bar baz [e]xample` - but since `tar` is an older page - it hasn't received the same attention. Would you like to open a pull request?

Just let us know if you need any assistance, as we're happy to help :-)

**Comment by jxu** [comment]
Ok. The only tiny issue is that of capitalization of first word in the example description, ex. (C)reate vs (c)reate. I heavily favor the option that matches the flag at the expense of proper capitalization.

**Comment by sbrl** [comment]
Indeed. We should definitely be careful of capitalisation here - good point.

**Comment by sbrl** [comment]
Indeed. We should definitely be careful of capitalisation here - good point.

**Comment by zdroid** [comment]
@jxu Have you started rewriting the tar pages? You can open the draft pull request and get help from others to finish it.

**Comment by bl-ue** [comment]
This is currently not possible because `tldr-lint` only allows capital letters at the beginning of examples:
```
tar.md:7: TLDR015 Example descriptions should start with a capital letter
```

**Comment by bl-ue** [comment]
@sbrl @owenvoke @navarroaxel how about amending the linter to allow `[` and `*` at the beginning?

I'd like to do this:
```
- **[C]**reate an archive from files:
```
because that makes it really clear and obvious.

**Comment by bl-ue** [comment]
Oops! I didn't notice tldr-pages/tldr-lint#12
