### ISSUE TITLE
dd: should we include `kill -USR1`?

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#3877]
It is vulnerable to an obscure race condition (https://unix.stackexchange.com/questions/38589/why-does-sigusr1-cause-process-to-be-terminated) and it is of questionable value nowadays given we have `status=progress`.

**Comment by jxu** [comment]
Then again it should be mentioned `status=progress` is only available in GNU coreutils 8.24+. So for example Ubuntu distros older than 16.04 won't have it.

**Comment by zdroid** [comment]
Where should this be changed? If you've seen it in some page, you can propose a PR to change it.

**Comment by jxu** [comment]
Actually I changed my mind; I think it's useful enough in most uses to leave it.

**Comment by sbrl** [comment]
Hey there! I wasn't aware of status=progress - that's really useful!

Perhaps you could open a PR to add that to the `dd` page please? That sounds really very useful indeed - and much easier to use than the current system.

**Comment by jxu** [comment]
I should clarify that both kill USR1 and `status=progress` are mentioned in the tldr page already. My initial thought was that the kill example was unsafe, but I later changed my mind and thought that it should be left in, especially for users of old versions of `dd`.

**Comment by jxu** [comment]
Unrelated: if it weren't out of the scope of the tldr pages, I would add a warning about dd aka disk destroyer. `if` and `of` are one key away from each other and `dd` *will* erase and overwrite entire drives if the command is not typed correctly.
