### ISSUE TITLE
How to change color style

### ISSUE THREAD

**Issue by RominYue** [tldr-pages/tldr#388]
Ooops, awesome tools! But when I use tldr, it's color style mixed with my own terminal solarized style. I could not see any term clearly............

**Comment by rprieto** [comment]
Thanks @RominYue, that's a commonly requested feature. Which client do you use (nodejs, python, ruby...)? For example in the [node.js client](https://github.com/tldr-pages/tldr-node-client/) you can change colors in `.tldrrc`.

**Comment by wong2** [comment]
great

**Comment by johanhaleby** [comment]
I'm also interested in changing the colors. I'm using Mac and have installed tldr using brew. I'm using solarized and tldr looks like this:

![image](https://cloud.githubusercontent.com/assets/187029/12048200/2a5ffa76-aed8-11e5-92a0-f5ce75dac124.png)

**Comment by lord63** [comment]
Apart from the node.js client, the python client [tldr.py](https://github.com/lord63/tldr.py) also support custom the output color, you can have a try.

**Comment by johanhaleby** [comment]
I suppose I'm using the C++ client since I installed it using brew

**Comment by RominYue** [comment]
Well, I just modify the tldr.py source code to change it..................(Python client)

**Comment by lord63** [comment]
@RominYue you can just modify the colors in the configuration file, it supports custom the colors.

**Comment by rastersize** [comment]
I’ve made a PR to the C++ client which should resolve the issues with different themes. See tldr-pages/tldr-cpp-client#6.

Makes the output look like the following screenshot when using Solarized Light:
<img width="670" alt="screen shot 2015-12-30 at 14 09 31" src="https://cloud.githubusercontent.com/assets/23453/12055847/0060f334-aeff-11e5-8863-8f95d844e5e7.png">

**Comment by Leandros** [comment]
All integrated. Update published via homebrew.

**Comment by rastersize** [comment]
@Leandros Awesome, thank you! :tada:

**Comment by johanhaleby** [comment]
Works perfectly! Thanks everyone.
