### ISSUE TITLE
page request: dos2unix / unix2dos

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#3897]
The examples from the manpage are pretty good but require scrolling down some. https://waterlan.home.xs4all.nl/dos2unix.html

**Comment by schneiderl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by jxu** [comment]
I am definitely no expert when it comes to all the options. I just use it when I'm too lazy to remember the `tr` or regex solution with ascii CR.
