### ISSUE TITLE
trash: add trash-rm commands

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#3909]
Use case: permanently deleting file (removing from trash) 

Right now `tldr trash` lists commands for `trash` and related functions: `trash-list`, `trash-restore`, `trash-empty`, but not `trash-rm`

From trash-rm man page:

```
EXAMPLE
       $ trash-rm foo          # Removes all files with name 'foo' in trash can
       $ trash-rm '*.o'        # Removes all files ending with '.o' in trash can
       $ trash-rm /full/path   # Removes all files removed with exactly '/full/path' as original location
```

**Comment by schneiderl** [comment]
Thanks for requesting this change! Do you want to have a go yourself?

Pages are best maintained by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating or changing a page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by jxu** [comment]
Ok I went ahead and made a PR.
