### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by donglixp** [tldr-pages/tldr#3932]
```bash
○ → tldr zip
/usr/local/lib/node_modules/tldr/bin/tldr:74
let cfg = config.get();
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by sbrl** [comment]
Hey there, @donglixp! It looks like you're using the Node.js client.

This is the repository for the pages themselves - you probably want to open this issue in the [tldr-node-client](https://github.com/tldr-pages/tldr-node-client/) repository instead.

By the looks of things, you are using an old version of Node.js. I suggest updating and then trying again.

**Comment by sarnobat** [comment]
How can I upgrade tldr? I installed it via npm on Ubuntu 16

**Comment by zdroid** [comment]
@sarnobat I used this to upgrade node.js on Ubuntu 16.04: https://github.com/nvm-sh/nvm. It may help you. tldr is fine, you don't need to upgrade it, but npm / node instead.

**Comment by sarnobat** [comment]
Thanks for the suggestion, it looks a bit challenging but we can close this ticket.

**Comment by agnivade** [comment]
Hi @donglixp, this issue was filed quite a long time back, and since there hasn't been any response from you, I will go ahead and close this. If you are still having problems, please file an issue in the https://github.com/tldr-pages/tldr-node-client/ repo. Thanks !

**Comment by sbrl** [comment]
Hrm yeah, the version of Node.js in the Ubuntu repo is really old. I've been maintaining [a script](https://gitlab.com/sbrl/bin/-/blob/master/node-update) that I found somewhere, and I use this to update.

I keep meaning to turn it into a proper package with `fpm`, but I haven't got around to it yet :P
