### ISSUE TITLE
Typo in CLIENT_SPECIFICATION.md

### ISSUE THREAD

**Issue by arunisaac** [tldr-pages/tldr#3933]
In the third paragraph of the "Language" section at https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md , it should be "if this environment variable is present" not "if this environment variable present". Notice the addition of "is". Perhaps the sentence could also be improved a little to "If this environment variable is present and LANG is absent, a client must ...".

**Comment by zdroid** [comment]
Thank you for noting this. I proposed a PR to fix the typo.

**Comment by schneiderl** [comment]
Nice catch @arunisaac.
