### ISSUE TITLE
Let's document! Git edition

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#3953]
For those not in the know, tldr-pages is about more than just commands. Those commands that are too expansive to fit on 1  page often have multiple subcommands - which we can document on their own pages. For example, try these:

```bash
tldr git merge
tldr git add
tldr ip address
```

In the case of git, it has quite a number of subcommands (139 ❗). Let's document them all!

- [x] [`add`](https://git-scm.com/docs/git-add) (#159)
- [x] [`am`](https://git-scm.com/docs/git-am) (#2352)
- [x] [`annotate`](https://git-scm.com/docs/git-annotate) (#5096)
- [x] [`apply`](https://git-scm.com/docs/git-apply) (#4252)
- [ ] [`archimport`](https://git-scm.com/docs/git-archimport) - this is for importing projects that use the [GNU Arch SCM](https://www.gnu.org/software/gnu-arch/), which is deprecated in favor of [GNU Bazaar](http://bazaar.canonical.com/)...should we still add this page?
- [x] [`archive`](https://git-scm.com/docs/git-archive) (#4362)
- [x] [`bisect`](https://git-scm.com/docs/git-bisect) (#1227)
- [x] [`blame`](https://git-scm.com/docs/git-blame) (#366)
- [x] [`branch`](https://git-scm.com/docs/git-branch) (#159)
- [x] [`bugreport`](https://git-scm.com/docs/git-bugreport) (#5097)
- [x] [`bundle`](https://git-scm.com/docs/git-bundle) (#4364)
- [x] [`cat-file`](https://git-scm.com/docs/git-cat-file) (#4492)
- [x] [`check-attr`](https://git-scm.com/docs/git-check-attr) (#5098)
- [x] [`check-ignore`](https://git-scm.com/docs/git-check-ignore) (#3113)
- [x] [`check-mailmap`](https://git-scm.com/docs/git-check-mailmap) (#5099)
- [x] [`check-ref-format`](https://git-scm.com/docs/git-check-ref-format) (#5100)
- [x] [`checkout`](https://git-scm.com/docs/git-checkout) (#159)
- [x] [`checkout-index`](https://git-scm.com/docs/git-checkout-index) (#5107)
- [x] [`cherry`](https://git-scm.com/docs/git-cherry) (#4473)
- [x] [`cherry-pick`](https://git-scm.com/docs/git-cherry-pick) (#1196)
- [x] [`clean`](https://git-scm.com/docs/git-clean) (#1157)
- [x] [`clone`](https://git-scm.com/docs/git-clone) (#159)
- [x] [`column`](https://git-scm.com/docs/git-column) (#5108)
- [x] [`commit`](https://git-scm.com/docs/git-commit) (#159)
- [x] [`commit-graph`](https://git-scm.com/docs/git-commit-graph) (#5109)
- [x] [`commit-tree`](https://git-scm.com/docs/git-commit-tree) (#5113)
- [x] [`config`](https://git-scm.com/docs/git-config) (#363)
- [x] [`count-objects`](https://git-scm.com/docs/git-count-objects) (#5114)
- [x] [`credential`](https://git-scm.com/docs/git-credential) (#5115)
- [x] [`credential-cache`](https://git-scm.com/docs/git-credential-cache) - you're not actually supposed to invoke this one, the synopsis is `git config credential.helper 'cache [<options>]'`, see the [docs](https://git-scm.com/docs/git-credential-cache)
- [x] [`credential-store`](https://git-scm.com/docs/git-credential-store) - same here
- [x] [`cvsexportcommit`](https://git-scm.com/docs/git-cvsexportcommit)
- [ ] [`cvsimport`](https://git-scm.com/docs/git-cvsimport)
- [ ] [`cvsserver`](https://git-scm.com/docs/git-cvsserver)
- [x] [`daemon`](https://git-scm.com/docs/git-daemon) (#5938)
- [x] [`describe`](https://git-scm.com/docs/git-describe) (#4413)
- [x] [`diff`](https://git-scm.com/docs/git-diff) (#159)
- [x] [`diff-files`](https://git-scm.com/docs/git-diff-files) (#6896)
- [ ] [`diff-index`](https://git-scm.com/docs/git-diff-index)
- [ ] [`diff-tree`](https://git-scm.com/docs/git-diff-tree)
- [x] [`difftool`](https://git-scm.com/docs/git-difftool) (#4127)
- [ ] [`fast-export`](https://git-scm.com/docs/git-fast-export)
- [ ] [`fast-import`](https://git-scm.com/docs/git-fast-import)
- [x] [`fetch`](https://git-scm.com/docs/git-fetch) (#473)
- [ ] [`fetch-pack`](https://git-scm.com/docs/git-fetch-pack)
- [ ] [`filter-branch`](https://git-scm.com/docs/git-filter-branch)
- [ ] [`fmt-merge-msg`](https://git-scm.com/docs/git-fmt-merge-msg)
- [ ] [`for-each-ref`](https://git-scm.com/docs/git-for-each-ref)
- [x] [`for-each-repo`](https://git-scm.com/docs/git-for-each-repo) (#5490)
- [x] [`format-patch`](https://git-scm.com/docs/git-format-patch) (#2351)
- [x] [`fsck`](https://git-scm.com/docs/git-fsck) (#3954)
- [x] [`gc`](https://git-scm.com/docs/git-gc) (#1741)
- [ ] [`get-tar-commit-id`](https://git-scm.com/docs/git-get-tar-commit-id)
- [ ] [`gitweb`](https://git-scm.com/docs/git-gitweb)
- [x] [`grep`](https://git-scm.com/docs/git-grep) (#2833)
- [ ] [`gui`](https://git-scm.com/docs/git-gui)
- [x] [`hash-object`](https://git-scm.com/docs/git-hash-object) (#9060)
- [x] [`help`](https://git-scm.com/docs/git-help) (#4019)
- [ ] [`http-backend`](https://git-scm.com/docs/git-http-backend)
- [ ] [`imap-send`](https://git-scm.com/docs/git-imap-send)
- [ ] [`index-pack`](https://git-scm.com/docs/git-index-pack)
- [x] [`init`](https://git-scm.com/docs/git-init) (#159)
- [x] [`instaweb`](https://git-scm.com/docs/git-instaweb) (#4017)
- [ ] [`interpret-trailers`](https://git-scm.com/docs/git-interpret-trailers)
- [x] [`log`](https://git-scm.com/docs/git-log) (#159)
- [x] [`ls-files`](https://git-scm.com/docs/git-ls-files) (#159)
- [x] [`ls-remote`](https://git-scm.com/docs/git-ls-remote) (#4538)
- [x] [`ls-tree`](https://git-scm.com/docs/git-ls-tree) (#3644)
- [x] [`mailinfo`](https://git-scm.com/docs/git-mailinfo) (#5939)
- [ ] [`mailsplit`](https://git-scm.com/docs/git-mailsplit)
- [x] [`maintenance`](https://git-scm.com/docs/git-maintenance) (#5463)
- [x] [`merge`](https://git-scm.com/docs/git-merge) (#159)
- [ ] [`merge-base`](https://git-scm.com/docs/git-merge-base)(#9382)
- [ ] [`merge-file`](https://git-scm.com/docs/git-merge-file)
- [ ] [`merge-index`](https://git-scm.com/docs/git-merge-index)
- [ ] [`merge-one-file`](https://git-scm.com/docs/git-merge-one-file)
- [ ] [`merge-tree`](https://git-scm.com/docs/git-merge-tree)
- [x] [`mergetool`](https://git-scm.com/docs/git-mergetool) (#3947)
- [ ] [`mktag`](https://git-scm.com/docs/git-mktag)
- [ ] [`mktree`](https://git-scm.com/docs/git-mktree)
- [ ] [`multi-pack-index`](https://git-scm.com/docs/git-multi-pack-index)
- [x] [`mv`](https://git-scm.com/docs/git-mv) (#364)
- [ ] [`name-rev`](https://git-scm.com/docs/git-name-rev)
- [x] [`notes`](https://git-scm.com/docs/git-notes) (#4042)
- [ ] [`p4`](https://git-scm.com/docs/git-p4)
- [ ] [`pack-objects`](https://git-scm.com/docs/git-pack-objects)
- [ ] [`pack-redundant`](https://git-scm.com/docs/git-pack-redundant)
- [ ] [`pack-refs`](https://git-scm.com/docs/git-pack-refs)
- [ ] [`patch-id`](https://git-scm.com/docs/git-patch-id)
- [x] [`prune`](https://git-scm.com/docs/git-prune) (#4696)
- [ ] [`prune-packed`](https://git-scm.com/docs/git-prune-packed)
- [x] [`pull`](https://git-scm.com/docs/git-pull) (#368)
- [x] [`push`](https://git-scm.com/docs/git-push) (#159)
- [ ] [`quiltimport`](https://git-scm.com/docs/git-quiltimport)
- [x] [`range-diff`](https://git-scm.com/docs/git-range-diff) (#5701)
- [ ] [`read-tree`](https://git-scm.com/docs/git-read-tree)
- [x] [`rebase`](https://git-scm.com/docs/git-rebase) (#473)
- [x] [`reflog`](https://git-scm.com/docs/git-reflog) (#2042)
- [x] [`remote`](https://git-scm.com/docs/git-remote) (#274)
- [x] [`repack`](https://git-scm.com/docs/git-repack) (#4018)
- [x] [`replace`](https://git-scm.com/docs/git-replace) (#4496)
- [x] [`request-pull`](https://git-scm.com/docs/git-request-pull) (#4241)
- [ ] [`rerere`](https://git-scm.com/docs/git-rerere)
- [x] [`reset`](https://git-scm.com/docs/git-reset) (#1088)
- [x] [`restore`](https://git-scm.com/docs/git-restore) (#3247)
- [x] [`rev-list`](https://git-scm.com/docs/git-rev-list) (#3644)
- [x] [`rev-parse`](https://git-scm.com/docs/git-rev-parse) (#3644)
- [x] [`revert`](https://git-scm.com/docs/git-revert) (#3151)
- [x] [`rm`](https://git-scm.com/docs/git-rm) (#365)
- [x] [`send-email`](https://git-scm.com/docs/git-send-email) (#4265)
- [ ] [`send-pack`](https://git-scm.com/docs/git-send-pack)
- [ ] [`sh-i18n`](https://git-scm.com/docs/git-sh-i18n)
- [ ] [`sh-setup`](https://git-scm.com/docs/git-sh-setup)
- [x] [`shortlog`](https://git-scm.com/docs/git-shortlog) (#2044)
- [x] [`show`](https://git-scm.com/docs/git-show) (#1331)
- [x] [`show-branch`](https://git-scm.com/docs/git-show-branch) (#4016)
- [x] [`show-index`](https://git-scm.com/docs/git-show-index) (#5940)
- [x] [`show-ref`](https://git-scm.com/docs/git-show-ref) (#4426)
- [ ] [`sparse-checkout`](https://git-scm.com/docs/git-sparse-checkout)
- [x] [`stash`](https://git-scm.com/docs/git-stash) (https://github.com/tldr-pages/tldr/commit/891310fb948c882e30619f80366b9dbe508d9e0b)
- [x] [`status`](https://git-scm.com/docs/git-status) (#159)
- [x] [`stripspace`](https://git-scm.com/docs/git-stripspace) (#5094)
- [x] [`submodule`](https://git-scm.com/docs/git-submodule) (#837)
- [x] [`svn`](https://git-scm.com/docs/git-svn) (#591)
- [x] [`switch`](https://git-scm.com/docs/git-switch) (#3246)
- [x] [`symbolic-ref`](https://git-scm.com/docs/git-symbolic-ref) (#6938)
- [x] [`tag`](https://git-scm.com/docs/git-tag) (#367)
- [ ] [`unpack-file`](https://git-scm.com/docs/git-unpack-file)(#9168)
- [ ] [`unpack-objects`](https://git-scm.com/docs/git-unpack-objects)
- [x] [`update-index`](https://git-scm.com/docs/git-update-index) (#3911)
- [x] [`update-ref`](https://git-scm.com/docs/git-update-ref) (#4373)
- [ ] [`update-server-info`](https://git-scm.com/docs/git-update-server-info)
- [x] [`var`](https://git-scm.com/docs/git-var) (#5095)
- [x] [`verify-commit`](https://git-scm.com/docs/git-verify-commit) (#5946)
- [ ] [`verify-pack`](https://git-scm.com/docs/git-verify-pack)
- [x] [`verify-tag`](https://git-scm.com/docs/git-verify-tag) (#6139)
- [x] [`whatchanged`](https://git-scm.com/docs/git-whatchanged) (#5935)
- [x] [`worktree`](https://git-scm.com/docs/git-worktree) (#1232)
- [ ] [`write-tree`](https://git-scm.com/docs/git-write-tree)

**Comment by ivanhercaz** [comment]
I really the "Let's document them all!".

Just one question, are translations also included in this "challenge"? 🙈🤗

**Comment by sbrl** [comment]
Lol, if you'd like to join in and translate them, that'd be great @ivanhercaz! I only know English though, so I can't really participate in the translations department :P

**Comment by jn64** [comment]
These don't seem necessary:

1. **citool**: `citool` is a default alias to `gui citool` which starts git-gui in a particular mode. That's literally it.

2. **whatchanged**: From git-whatchanged(1):

   > New users are encouraged to use git-log(1) instead. [...] The command is kept primarily for historical reasons

3. **request-pull** has one specific usage, which is explained in the very short man page.

Also **remote-keybase** is not part of git, you may have it from a third party.

**Comment by sbrl** [comment]
Thanks, @jn64 - I'll update the list. I just took all the subcommands from the bash autocompletion list - -I haven't yet had time to check them all :P

 - `whatchanged`: agreed - this doesn't seem necessary.
 - `request-pull`: It might be short, but regular commands such as `arch` and `nproc` still have tldr pages, so I think this is fine.
 - `citool`: Hrm - my machine doesn't seem to even have that alias anymore. Either way, I think it's best to avoid documenting aliases if possible and stick to the canonical names unless there's a good reason.

**Comment by Amorymeltzer** [comment]
Not sure if `git-gitk` is needed, as it's really just linking to `gitk`, which exists.

**Comment by bl-ue** [comment]
@Alison-Li @samuel-w @jn64 only one more -- `git range-diff`.  Any of you feel up to adding it?

**Comment by bl-ue** [comment]
Hi guys, I found several more commands by running `git help -a`, then I used a tiny script [`tldr-find.sh`](https://github.com/tldr-pages/tldr/files/5775973/tldr-find.sh.zip) + VS Code multi-cursor to produce a grand list of 140 commands, with links to each commands docs page.

So the command count went from what @sbrl called quite a few, 20, to 140 (❗❗❗), so we have quite a bit of work to do.  65/140 are done, leaving 75/140 to do.

I've pinned this issue so everyone will see it.

**Comment by bl-ue** [comment]
I just added all 69 commands from [tj/git-extras](https://github.com/tj/git-extras) to the TODO list, making for a monolithic list of **208** subcommands, **75** of which are done. I'm working on powering through! 😊

**Comment by waldyrious** [comment]
@bl-ue I think we should have [git-extras](https://github.com/tj/git-extras) subcommands tracked in a separate issue, especially since there are many such git enhancers:

- [x] [hub](https://hub.github.com) → #4701
- [ ] [gh](https://cli.github.com)
- [ ] [gitsome](https://github.com/donnemartin/gitsome)
- [ ] [git town](https://git-town.com)
- [ ] [git-utils](https://github.com/ddollar/git-utils)
- [ ] [git-utils](https://github.com/mhartl/git-utils)
- [ ] [gitless](https://gitless.com)
- [ ] [git-scripts](https://github.com/jwiegley/git-scripts)
- [ ] [bit](https://github.com/chriswalz/bit)

...and likely others I'm not aware of! 😄

**Comment by bl-ue** [comment]
Gosh, you're right! I thought the same thing when I added those...but...

:shrug:

is what I did.  :smile:

and I thought about it no more.

**Comment by kbdharun** [comment]
How is this issue closed if all the pages weren't added?

**Comment by WangLinSongss** [comment]
gitweb points to a broken link, I believe it should point to https://git-scm.com/docs/gitweb

**Comment by shantanu-pai** [comment]
@Managor please remove `sh-setup` from this list as well as its a shell script setup code which is not a direct command and does not fall into the purpose of what tldr directly tries to do.

**Comment by Managor** [comment]
Done.

**Comment by shantanu-pai** [comment]
@sbrl please update the hyperlink for gitweb to [https://git-scm.com/docs/gitweb](https://git-scm.com/docs/gitweb) as the current one is broken.
