### ISSUE TITLE
page request: lvresize

### ISSUE THREAD

**Issue by DubbaThony** [tldr-pages/tldr#3955]
manpage online: http://man7.org/linux/man-pages/man8/lvresize.8.html

Cant find good docs by examples.

**Comment by sbrl** [comment]
Thanks for requesting this page, @DubbaThony! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by DubbaThony** [comment]
Sorry for delayed anwser,

Im not really good or comfortable with this command unfortunately, that's why I was seeking TL;DR and than manpages with usage of it.

**Comment by sbrl** [comment]
No problem, @DubbaThony! Hopefully someone else will be able to contribute it :-)
