### ISSUE TITLE
page request: zgrep

### ISSUE THREAD

**Issue by taki** [tldr-pages/tldr#3966]
Zgrep can search on compressed files. description is below link.

https://linux.die.net/man/1/zgrep

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by kazie** [comment]
I am no expert on peoples different implementations of `zgrep` that they are running.
But as my machine using using `GNU` grep I can easily read that:
> Zgrep  invokes  `grep`  on compressed or gzipped files.  _All options specified are passed directly to grep_
Together with:
> The following grep options are not supported: `--dereference-recursive` (`-R`), `--directories` (`-d`), `--exclude`, `--exclude-from`, `--exclude-dir`, `--include`, `--null` (`-Z`), `--null-data` (`-z`), and `--recursive` (`-r`).

Thus comparing to the `tldr grep`
```
  Matches patterns in input text.
  Supports simple patterns and regular expressions.

  Search for an exact string:

      grep search_string path/to/file

  Search in case-insensitive mode:

      grep -i search_string path/to/file

  Search recursively (ignoring non-text files) in current directory for an exact string:

      grep -RI search_string .

  Use extended regular expressions (supporting `?`, `+`, `{}`, `()` and `|`):

      grep -E ^regex$ path/to/file

  Print 3 lines of [C]ontext around, [B]efore, or [A]fter each match:

      grep -C|B|A 3 search_string path/to/file

  Print file name with the corresponding line number for each match:

      grep -Hn search_string path/to/file

  Use the standard input instead of a file:

      cat path/to/file | grep search_string

  Invert match for excluding specific strings:

      grep -v search_string
```

It looks like one could probably use the `grep` page for heavy inspiration of how to write the `zgrep` one. :)

**Comment by sbrl** [comment]
Reference in the associated PR didn't auto-close this issue (no `closes` prefix), so since it has been merged I'm closing this issue.
