### ISSUE TITLE
page request: chocolatey

### ISSUE THREAD

**Issue by grafst** [tldr-pages/tldr#3973]
https://chocolatey.org

https://chocolatey.org/docs/commands-reference

**Comment by schneiderl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by owenvoke** [comment]
I actually added all the Chocolatey commands a while back, however the command is `choco`, so maybe that's why it wasn't found?

https://github.com/tldr-pages/tldr/blob/master/pages/windows/choco.md

**Comment by owenvoke** [comment]
@grafst, I'm going to close this as it does appear to be part of tldr pages. 👍 If you have any further questions or page requests, feel free to let us know. 🙂

**Comment by grafst** [comment]
> @grafst, I'm going to close this as it does appear to be part of tldr pages. 👍 If you have any further questions or page requests, feel free to let us know. 🙂

Ok definitly my error sorry :(
