### ISSUE TITLE
update error:ERROR: getaddrinfo ENOTFOUND tldr-pages.github.io

### ISSUE THREAD

**Issue by yejijie** [tldr-pages/tldr#399]
```
➜  ~  tldr --update
Updating...
Error: getaddrinfo ENOTFOUND tldr-pages.github.io
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

**Comment by WANG-lp** [comment]
The `getaddrinfo` means you get an DNS error, maybe check your network environment, especially your DNS configure.

**Comment by igorshubovych** [comment]
@yejijie 
do you still see this issue? @WANG-lp is right, it is a DNS issue on your network.

**Comment by igorshubovych** [comment]
Feel free to reopen it if an issue reoccurs.

**Comment by yejijie** [comment]
@WANG-lp @igorshubovych You're right, Thanks.
