### ISSUE TITLE
page request: GetFileInfo

### ISSUE THREAD

**Issue by rachithaiyappa** [tldr-pages/tldr#3993]
Used to get the information of a file in macOS

https://ss64.com/osx/getfileinfo.html

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
