### ISSUE TITLE
Proposal: support subcommand

### ISSUE THREAD

**Issue by gonejack** [tldr-pages/tldr#4003]
Command tool like `go` has powerful subcommand tools like `go test` `go build` which are totally different tools but having same prefix, it would be better tldr distinguishing them well.

**Comment by zdroid** [comment]
Do you want to do that yourself? If you're familiar with the commands, that's the best way to go.

cc @agnivade, since he's also involved in Go

**Comment by sbrl** [comment]
Hey there, @gonejack! We do indeed support subcommands. For example, try `tldr git merge`. Unfortunately, we're lacking a bit on the documentation, so if you'd like to help us out by contributing some subcommand pages, that'd be awesome!

Just ask if you'd like any help :-)

**Comment by gonejack** [comment]
Awesome, I would like to make some PR later.

**Comment by agnivade** [comment]
Yeah, just send separate PRs for the subcommands. Look for git or aws pages for inspiration.
