### ISSUE TITLE
Request: apt package install?

### ISSUE THREAD

**Issue by ldorigo** [tldr-pages/tldr#4043]
Hi, as a long time user on macOS, I was surprised that doing "sudo apt install tldr" on an Ubuntu machine didn't work and that I needed to go through installing node/npm before being able to use it. 

I don't know if it would be a lot of work to include tldr as a package on the Ubuntu repository, but it would make it much easier for Linux people to install it.

**Comment by zdroid** [comment]
There is a snap package already, but it's built on top of npm client (and not maintained, I think). Since Ubuntu has python3 pre-installed, you can just run `pip3 install tldr` or `python3 -m pip install tldr`. The client is currently being updated and it will be released as v1.0 soon.

**Comment by ivanhercaz** [comment]
In addition, if I am not wrong, the package name on Ubuntu is `tldr-py`.

**Comment by ldorigo** [comment]
> There is a snap package already, but it's built on top of npm client (and not maintained, I think). Since Ubuntu has python3 pre-installed, you can just run `pip3 install tldr` or `python3 -m pip install tldr`, to use the Python client instead. The client is currently being updated and it will be released as v1.0 soon.

I did end up installing the python package, as the npm one was giving me errors. Might be worth it putting on the Readme that that is the recommended way to install on ubuntu(-like) systems?


> In addition, if I am not wrong, the package name on Ubuntu is `tldr-py`.

I am pretty sure that I ran "apt search tldr" and it didn't return any results at all. Will check again when I have access to the machine.

**Comment by zdroid** [comment]
@ldorigo What kind of errors does npm package give you? I used both npm and python clients on Ubuntu 18.04 and 20.04.
That's worth noting. The python client was long lacking support and options that npm client had, but recently that has changed drastically.

**Comment by ivanhercaz** [comment]
> I am pretty sure that I ran "apt search tldr" and it didn't return any results at all. Will check again when I have access to the machine.

[`tldr`](https://packages.ubuntu.com/eoan/tldr) package in Ubuntu is the one for the Haskell client, then [`tldr-py`](https://packages.ubuntu.com/eoan/tldr-py) is the one for the Python client. But I don't recommend the use of this Python client, it seems it is [inactive](https://github.com/lord63/tldr.py/commits/master), check [its repository](https://github.com/lord63/tldr.py).

If you are interested in a Python client I recommend you the one in which there are collaborators working, @zdroid included: [tldr-python-client](https://github.com/tldr-pages/tldr-python-client). I am sure if you have any issue with this one, you will probably get support.

**Comment by ldorigo** [comment]
Apparently, recent versions of Ubuntu do have a tldr package - I was trying to install it on a Ubuntu 14 machine. So I guess my issue is void,  although it does point to a need for a better communication of which clients are up-to date, cf. recent issue #4044 . 
I think 99% of users don't care if their client is coded in haskell, python or C++ - they just want a functioning way of typing "tldr <command>" in their terminal.

**Comment by ldorigo** [comment]
I'll close this, since it's not really relevant.

**Comment by zdroid** [comment]
It can be kept open until this is fully resolved, if you want.

**Comment by sbrl** [comment]
Hrm. I'm currently on 19.10 and I see the `tldr` package? Is this a change in 20.04 @ldorigo? If so then an issue should be opened against the haskell client repo to notify them of this
