### ISSUE TITLE
How to specify that a command (e.g. `ip addr`) is a synonym for another command (`ip address`)?

### ISSUE THREAD

**Issue by ldorigo** [tldr-pages/tldr#4049]
Is there some logic currently in place for this? Or should it just be added as a comment on the main command?  It would be nice if when a user does `tldr ip addr`, he automatically received the page for `tldr ip address`.

**Comment by principis** [comment]
At the moment there is no system in place because tldr is just markdown files.

Partially off-topic comment, `ip a` is a more common shortcut for `ip address`

**Comment by sbrl** [comment]
Yeah, we don't yet have a synonym system. That's been discussed in #787 IIRC

**Comment by zdroid** [comment]
@sbrl @ldorigo I suggest moving this to #787 as it is essentially the same. System that would support that would also support this.

**Comment by sbrl** [comment]
Indeed @zdroid. We should close this as a duplicate of #787.
