### ISSUE TITLE
page request: named

### ISSUE THREAD

**Issue by mikerouxfr** [tldr-pages/tldr#4051]
- https://linux.die.net/man/8/named
- https://www.tutorialspoint.com/unix_commands/named.htm

**Comment by owenvoke** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by mikerouxfr** [comment]
I actually used this command once, on the day I created this suggestion, but I'm no expert at all on this command 😕

**Comment by bl-ue** [comment]
It looks like this should have been closed.  Thank you @ev-john!
