### ISSUE TITLE
this are not man page, this are snippet

### ISSUE THREAD

**Issue by kolokd** [tldr-pages/tldr#4052]
fix documents

**Comment by ivanhercaz** [comment]
Hi @kolokd, could you explain what do you mean? tldr-pages are not man pages.

**Comment by kolokd** [comment]
but you are saying that this are man pages in description . can't you see. you are lying.

>A collection of simplified and community-driven man pages.

>Simplified and community-driven man pages https://tldr.sh

**Comment by zdroid** [comment]
They are simplified man pages, not complete man pages. This will be changed per #1192 anyway.

**Comment by waldyrious** [comment]
Thanks for raising this issue, @kolokd — we do agree about the potential for misinterpretation, as you may read in the discussion at #1192, so this issue can be considered a duplicate of that one. Please follow along there as it should be resolved pretty soon!

**Comment by kolokd** [comment]
stop this shit. close this repo. people should read man pages not this
