### ISSUE TITLE
convert example doesn’t use the right unit for delay

### ISSUE THREAD

**Issue by ariasuni** [tldr-pages/tldr#4064]
The page about `convert` states:

> - Create a gif from a series of images with 100ms delay between them:
>
> `convert {{image1.png}} {{image2.png}} {{image3.png}} -delay {{100}} {{animation.gif}}`

But the option `-delay` is in ticks. The base for convert is 100 ticks-per-seconds so a delay of 1 is equivalent to 1/100 of a second.

So the actual example set a delay of 1s, 100ms would correspond to `-delay {{10}}`.

[Documentation of `-delay`](https://imagemagick.org/script/command-line-options.php#delay)

**Comment by zdroid** [comment]
Thanks for noting this. Do you want to open a PR yourself?

**Comment by ariasuni** [comment]
Well I don’t use tldr myself and reported for a friend, so I feel it’s a bit overkill to open a PR for a one character change.

**Comment by zdroid** [comment]
Every change here requires a PR, so don't worry about it.

**Comment by sbrl** [comment]
Oh, my! Great spot there. I've open PR #4074 for this.

**Comment by agnivade** [comment]
This was an excellent catch. Thank you @ariasuni !
