### ISSUE TITLE
harmonize "command line" mentions

### ISSUE THREAD

**Issue by schneiderl** [tldr-pages/tldr#4068]
Hi
I was browsing around our pages and I've noticed that in multiple pages (especially on the descriptions) we state that the described command is a "command-line tool", "CLI Utility", "CLI", etc. 

There seems to be no pattern in that. 
Should we think of a standardized way to state that? 
Or should we state that at all? Being documented here doesn't already mean that it is a command-line tool? 

I'll wait for your comments on that for me to do something about this.

**Comment by zdroid** [comment]
TBH, I wouldn't change that at all. Such descriptions usually originate from the command's docs, as it was the case in #4066. I think it's safer and easier to assume the official docs are correct, rather than try to manually standardize them.

**Comment by einverne** [comment]
I will stay neutral. I think this may be the interesting of a language. We can describe one thing with a lot of ways and both pattern can be understand. Here I think "command-line tool" or "CLI Utility" or "CLI" can be understand through the context.

**Comment by sbrl** [comment]
I agree with @zdroid here. It's probably best to stick with the terminology that the program uses in its official documentation, as that's what users will usually be most familiar with.

**Comment by schneiderl** [comment]
That seems to be the general consensus then. I will give this some more hours if anyone wants to add anything on this discussion.
