### ISSUE TITLE
Linting rules should be in style guide

### ISSUE THREAD

**Issue by jn64** [tldr-pages/tldr#4078]
Linting rules like

> TLDR004 Command descriptions should end in a period

should be mentioned in the [Style Guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md), so you don't have to make a pull request and wait for Travis to fail before you find out the rules.

**Comment by sbrl** [comment]
Hey there! We do already implicitly mention this in the example in the layout section. While I'm all for documenting the linting rules, I'm wary of making the style guide too long.

Perhaps a separate document would be a better place for this.

**Comment by agnivade** [comment]
> so you don't have to make a pull request and wait for Travis to fail before you find out the rules.

There's no need to do that. One can always run "npm test" locally. Laying out each and every rule in the style guide would be madness. More documents are just more things for the developer to read. 

Just like any other language, the rules aren't documented explicitly in a separate document. Rather the developer is expected to run the linter and fix the issues.

**Comment by jn64** [comment]
> One can always run "npm test" locally

@agnivade I certainly can, but I only contributed because I could do it from GitHub web during a bit of downtime without running any code. Less technical contributors can't / wouldn't. This project claims ["Most people submit pull requests to the tldr-pages project using GitHub's web interface."](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/git-terminal.md)

I doubt you learnt to write Markdown by writing bad markup and linting it until the errors went away. You read a spec, a user manual, or at least a cheatsheet. Something nice written for humans, that can be read in whole or scanned easily, not fed to you in disjointed lines by a linter :robot:

On consideration I agree that the Style Guide shouldn't contain _every_ rule. However rules like "There should be only one command per example" or "Example descriptions should prefer infinitive tense" would not be out of place. They would serve to explain/reinforce the example template rather than make things more complicated.

The other more technical linter rules could be in a linked human-readable doc (maybe a separate issue for tldr-lint to provide it).

I would go further to suggest that the [Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#guidelines) section of CONTRIBUTING be moved to Style Guide, in addition to these select linter rules. CONTRIBUTING should be about the technical aspects of dealing with the project; Style Guide should be about writing the actual pages.

**Comment by agnivade** [comment]
Thanks for your thoughts on this @jn64. We have a lot of unspoken rules like this which are not there in the style guide. But they'll come up during review. It was a deliberate decision not to explicitily document them to avoid piling up more cognitive overhead to the contributor.

IMO, adding more rules does not help. Nobody reads them. If you are a "less-technical" contributor, it is even less likely you would go through a whole wall of rules before contributing. Rather, you would jump in head-first and go through the PR review process. We have seen this happen, and therefore I am wary of adding more rules.

As another data point, we even added an explicit PR checklist item for more than 8 items, and yet people don't read that.

It's true that it's not nice to get errors from the bot on every new commit, but IMO adding more documented rules does not help much.
