### ISSUE TITLE
page request: httpry

### ISSUE THREAD

**Issue by amitech** [tldr-pages/tldr#4095]
Reference: https://linux.die.net/man/1/httpry

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by amitech** [comment]
@sbrl okay, I will do it.

**Comment by bl-ue** [comment]
@WhileLoop added the page, but GitHub didn't close this issue.
