### ISSUE TITLE
Consider moving to GitHub Actions

### ISSUE THREAD

**Issue by owenvoke** [tldr-pages/tldr#4097]
It might be worth moving to GitHub Actions as has been discussed [previously on Gitter](https://gitter.im/tldr-pages/tldr?at=5ebc6bdd40e3122a8817d764). We've already moved the [Python client](https://github.com/tldr-pages/tldr-python-client) over to GH Actions in https://github.com/tldr-pages/tldr-python-client/pull/105. And it would also possibly make it easier to merge the [tldr-bot](https://github.com/tldr-pages/tldr-bot) code into the repository which would probably be faster (using the built in integrations).

I've started work on this and there are only a [few more variables](https://gitter.im/tldr-pages/tldr?at=5edf969d24a3382d5d56f48c) that are required for it to work.
https://github.com/tldr-pages/tldr/compare/master...owenvoke:feature/gh-actions?expand=1

- `TRAVIS_PULL_REQUEST`, this provides the id of the pull request and is empty when triggered by a non-PR. I've had a look and most things just say to parse the `GITHUB_REF` env variable instead.
- `TRAVIS_COMMIT_RANGE`, this provides the range of commits included in the PR or push. It's used only in the [deploy script commit messages](https://github.com/owenvoke/tldr/blob/100385f491ba133b3ee1a08191c65040e5674650/scripts/deploy.sh#L35).

---

Secrets can be added in [the settings](https://github.com/tldr-pages/tldr/settings/secrets), and we'd need to add three as far as I can tell. It's also worth noting that GitHub Actions doesn't allow lowercase env variable names, they are case-insensitive so the script would need to be updated. :+1:

- [`encrypted_973441be79af_key`](https://github.com/tldr-pages/tldr/blob/master/scripts/deploy.sh#L23) - used for decrypting the website repository deploy key
- [`encrypted_973441be79af_iv`](https://github.com/tldr-pages/tldr/blob/master/scripts/deploy.sh#L23) - used for decrypting the website repository deploy key
- `TRAVIS_BOT_GITHUB_TOKEN` - which looks like it's not being used (I think this was from [this script](https://github.com/tldr-pages/tldr/blame/2b0bc0be91019685476b1d13c23e5da831b0f839/scripts/post_pr_comment.py))

---

It may also be good to, once we've updated to use GitHub Actions, add some [scheduled workflows](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule) for tasks such as opening issues about contributor/maintainer/owner actions. See https://github.com/tldr-pages/tldr/issues/4113#issuecomment-647539108 for some more information.

**Comment by MasterOdin** [comment]
> TRAVIS_COMMIT_RANGE, this provides the range of commits included in the PR or push. It's used only in the deploy script commit messages.

Given the switch to "squash and merge" PR merge strategy, it looks like `TRAVIS_COMMIT_RANGE` is always one commit, so not sure it's valuable. If anything, I would recommend changing the message to be `upload assets for tldr-pages/tldr@{{ github.sha }}` (ex: `upload assets for tldr-pages/tldr@e3f9c6f33ea5` -> "upload assets for tldr-pages/tldr@e3f9c6f33ea5"). The benefit here would be that (as displayed in the example) the commit message now has a direct link within the web UI to the commit in question that generated the assets.

> encrypted_973441be79af_key - used for decrypting the website repository deploy key
> encrypted_973441be79af_iv - used for decrypting the website repository deploy key

You could just embed the key as a github secret and only use it on pushes to master, and not have a secrets file embedded into the repo.

**Comment by zdroid** [comment]
@MasterOdin Even though that true in 95% of the cases, sometimes we use rebase and merge too.

**Comment by MasterOdin** [comment]
Fair. I suppose a follow-up question though would be "is anyone using those commit messages in some way, and want to know what the range of commits are, or would they be fine only knowing the HEAD commit SHA?"

**Comment by owenvoke** [comment]
Thinking about this, I'm not sure that commit range is actually that useful for this. 🤔

In the website's [commit history](https://github.com/tldr-pages/tldr-pages.github.io/commits/master), you'd be able to see the commits that it is between even with just the current commit. I think it would probably be fine to use the following instead:
```bash
git commit -m "[GitHub Actions] uploaded assets after commits ${GITHUB_SHA}"
```

It still bugs me that there isn't a `GITHUB_PR_ID` variable as that's such an obvious one to include, but parsing it should be fine. 🤷 I'm going to work on finishing those changes and then open a PR.
