### ISSUE TITLE
page request: tmutil

### ISSUE THREAD

**Issue by ghost** [tldr-pages/tldr#4107]
I cannot find a website with the latest man page for this utility, but under a macOS install 10.11 or newer, just run `man tmutil`

**Comment by andrik** [comment]
Hi @gottabeleGIT

Thanks for requesting this page!

What about sending a PR describing this command? We'll be glad to review it.

If so, please take a look at CONTRIBUTING.md and if you need any assistance, just ask

**Comment by jonatasleon** [comment]
Would this the man page for tmutil? https://ss64.com/osx/tmutil.html

**Comment by gottabeleGIT** [comment]
Maybe, the latest revision of the manpage is 2015 (hence 10.11) and that website doesn’t list the year so I wasn’t sure...

**Comment by sbrl** [comment]
Looks like it is, as the `last-modified` HTTP header for that page reads `Sun, 17 May 2020 22:29:40 GMT` @jonatasleon, @gottabeleGIT

**Comment by bl-ue** [comment]
Thank you @GingkathFox for fixing this in PR #5054! Next time, please link the issue number in the PR description so that GitHub automatically closes the issue when the PR is merged.

Looks like "@ gottabeleGIT" is gone :-)

**Comment by GingkathFox** [comment]
oh, i didnt realize this was open, i just wanted to make a page for tmutil @bl-ue xD

**Comment by bl-ue** [comment]
Cool @GingkathFox! Thank you anyway!
