### ISSUE TITLE
Add organization owner: @zdroid

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#4113]
Hi, @zdroid! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
Before performing such role transitions, make sure to review the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

---

It seems 6 months passed 2 days ago (17th June).
I promise I won't break anything! :smile:

**Comment by sbrl** [comment]
Haha, well done for spotting this @zdroid :P

Everyone else is in agreement, right? @agnivade @owenvoke @mebeim 

I can add @zdroid as an owner if everyone agrees.

**Comment by mebeim** [comment]
Sure go ahead!

**Comment by agnivade** [comment]
No objections from my side. Well deserved!

**Comment by owenvoke** [comment]
Very well deserved. 👍

**Comment by sbrl** [comment]
Done! :D

We do need to keep better track of this lol

**Comment by owenvoke** [comment]
@sbrl, I was wondering if there is some way to do it with GitHub Actions, using [a scheduled action](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule). 🤷 So it does a daily check to see if contributors meet the requirements and opens an issue automatically.

Not really sure, but I may take a look at some point. Maybe after #4097 is implemented.

**Comment by sbrl** [comment]
That sounds like a great plan @owenvoke! I didn't even know that was a thing, but it sounds like just what we need.
