### ISSUE TITLE
page request: semanage

### ISSUE THREAD

**Issue by a-wip0** [tldr-pages/tldr#4115]
The page for `semanage` is not found, i hope this command will be added later

**Comment by andrik** [comment]
Hi @a-wip0 

Thanks for requesting this page!

What about sending a PR describing this command? We'll be glad to review it.

If so, please take a look at CONTRIBUTING.md and if you need any assistance, just ask

**Comment by jonatasleon** [comment]
Would this the online man page for semanage? https://linux.die.net/man/8/semanage

**Comment by sbrl** [comment]
Looks like that's the  one @jonatasleon :smiley_cat:

**Comment by savvyspoon** [comment]
#4353 Was created for this issue.
