### ISSUE TITLE
New directory structure

### ISSUE THREAD

**Issue by fejx** [tldr-pages/tldr#4120]
We will transform the organization of the pages to a new structure. After careful consideration of all the options in #190, we settled for the following:
```
pages
├─── en
│    ├─── common
│    │    └─── cmd.md
│    ├─── macos
│    │    └─── cmd.md
│    └─── windows
│         └─── cmd.md
└─── es
     ├─── common
     │    └─── cmd.md
     ├─── macos
     │    └─── cmd.md
     └─── windows
          └─── cmd.md
```

For backwards compatibility, the legacy structure will be served on the usual URL `tldr.sh/assets/tldr.zip`, while the new stucture is served on `tldr.sh/assets/v2/tldr-pages.zip` (we are renaming the filename as well, see #4035).

To accomplish this, the following tasks need to be performed:

* [ ] Create draft for new client spec.
* [ ] Create a transformation script to transform new ➤ legacy.
* [ ] Expand [the linter](https://github.com/tldr-pages/tldr-lint) to check if translations line up (see below for details).
* [ ] Prepare new build process (see below for details).
* [ ] Perform the transformation to the new layout.
* [ ] Notify client developers about the new layout.

### Check if examples line up

The number of examples between translations should match.
Additionally, the command-part of each example should match.

##### `pages/en/common/gh.md`

```
# gh

> Work seamlessly with GitHub from the command line.
> More information: <https://cli.github.com/>.

- Create a pull request:

`gh pr create`
```

##### `pages/de/common/gh.md`

```
# gh

> Arbeite nahtlos mit GitHub von der Kommandozeile aus.
> Mehr information: <https://cli.github.com/>.

- Neuen Pull Request anlegen:

`gh pr create`
```

This is fine because both pages have *one* example with the text `gh pr create`.

##### `pages/en/common/gh.md`

```
# gh

> Work seamlessly with GitHub from the command line.
> More information: <https://cli.github.com/>.

- Create a pull request:

`gh pr create`
```

##### `pages/de/common/gh.md`

```
# gh

> Arbeite nahtlos mit GitHub von der Kommandozeile aus.
> Mehr information: <https://cli.github.com/>.

- Status eines Pull Requests überprüfen:

`gh pr status`
```

This causes a linter error because both pages have *one* example, but the examples `gh pr create` and `gh pr status` do not match.

### Warn if translations may need an update

For every page edited in a PR, the bot should check if translations for this page exist.
If any translations are found, the bot should add a comment to the PR simliar to this:
> Hey! I noticed this PR changes the page for `cd`!
> This page has been translated to the following languages:
>
> * [Spanish](https://github.com/tldr-pages/tldr/blob/master/pages.es/common/cd.md)
> * [Italian](https://github.com/tldr-pages/tldr/blob/master/pages.it/common/cd.md)
>
> If you changed semantics of a sentence, be sure to update the translations as well.
> @asdf, @xyz or @qwery: Can you help out with translating the changes?

## Build process

The new build process should
* Publish the new structure to `tldr.sh/assets/v2/tldr-pages.zip`
* Transform files to the legacy structure.
* Publish the old structure to `tldr.sh/assets/tldr.zip`.

~The zip file published to `v2` should also omit the file `pages/index.json`, which is only kept for backwards compatibility (#2865).~ **Done with #5063.**

**Comment by zdroid** [comment]
A script is not needed to change the layout. It's easy to do it manually, in less than a minute.

**Comment by fejx** [comment]
You are right!
I will remove it from the list, but the transformation new ➤ old is still required because we need to publish the legacy structure.

**Comment by zdroid** [comment]
Regarding `tldr.sh/assets/v2/tldr.zip` URL, I think we had an idea in one of the previous threads to serve it as simply `tldr-pages.zip` instead. @waldyrious Am I right?

**Comment by waldyrious** [comment]
Not sure if you're talking only about the tldr.zip > tldr-pages.zip renaming (which yeah, was agreed recently) or about the location of the file (which I don't recall being discussed). Please confirm.

**Comment by fejx** [comment]
Although I would not care too much about the name, I would still use `/v2/tldr-pages.zip` then.
Having both `tldr.zip` and `tldr-pages.zip` that contain the same data in different structures is very confusing.
Using the `/v2` prefix would be future-proof and follow the usual HTTP API conventions.

If we nonetheless settle for `tldr.zip` for old and `tldr-pages.zip` for new, I would at least add a warning message to the client spec that warns about this aspect.

**Comment by zdroid** [comment]
@waldyrious only about the file renaming.

**Comment by waldyrious** [comment]
Exactly @fejx, that was what I was thinking too: using both the `v2/` prefix and the renamed archive name `tldr-pages.zip`.

**Comment by sbrl** [comment]
A `v2/` prefix sounds good. If we're going to rename the zip, then we may as well do it at the same time.

Regarding the new linter rules there - those would probably be implemented as a GH action or through tldr-bot instead. In the event the original copy is updated, we'd want to inform past contributors of the translations _after_ it gets merged I think.

**Comment by agnivade** [comment]
Great stuff @fejx. I see that some of my other linter related [suggestions](https://github.com/tldr-pages/tldr/issues/190#issuecomment-636276651) are missing from the issue. Any reason for that? Specifically:
- Adding a comment on a PR which modifies a page in one language, but there are copies of the page in other languages.
- If a page is added which has translations in other languages, post links to those pages in the PR so that it is easy to check for style consistency, and the PR submitter is made aware that other pages already exist. So the number of examples and their order has to be exactly same.
- Having language owners for non-english pages and ping them whenever a PR is created in any of those folders. (I think the GitHub CODEOWNERS file may automatically take care of this.)

In general, what I think needs to happen is that the linter needs to check for these rules and then send the event to the bot. The bot is just an event handler which makes a comment to a github PR.

I would also take this opportunity to suggest that we should write a new linter from scratch. The old one is unusable and not maintained for very long. It isn't very hard to enforce these simple rules using simple programming logic using any language. We don't need lex/yacc for that. We don't even have the max examples limit enforced through the linter.

**Comment by fejx** [comment]
> Exactly @fejx, that was what I was thinking too: using both the `v2/` prefix and the renamed archive name `tldr-pages.zip`.

Ok, that makes a lot more sense to me now, will add it to the description right away.

**Comment by fejx** [comment]
> I see that some of my other linter related [suggestions](https://github.com/tldr-pages/tldr/issues/190#issuecomment-636276651) are missing from the issue. Any reason for that?

Only reason was that I was typing this on my phone while abroad and this was the only one I could remember of the top off my head.
I should have added a notice that the task specification is not done yet.

**Comment by fejx** [comment]
> I would also take this opportunity to suggest that we should write a new linter from scratch. The old one is unusable and not maintained for very long. It isn't very hard to enforce these simple rules using simple programming logic using any language. We don't need lex/yacc for that. We don't even have the max examples limit enforced through the linter.

I like that idea, since I thought the same way when I recently took a look at the current implementation.
However, we should be careful on the task's scope.
This change is already pretty significant, if we rewrite the linter we should do it first, *then* add the translation linting rules, *then* refactor the linter to the new page structure.
Otherwise this might turn into a mess, especially because everyone has other jobs to do and the execution of these tasks might take longer than just a day or two.

**Comment by sbrl** [comment]
Sounds good @fejx. We've already got a task spec for the linter rewrite [on the wiki](https://github.com/tldr-pages/tldr/wiki/Coding-projects#convert-the-linter-from-clexyacc-to-a-more-popular-language), if anyone would like to step up :-)

**Comment by fejx** [comment]
> 
> 
> > I see that some of my other linter related [suggestions](https://github.com/tldr-pages/tldr/issues/190#issuecomment-636276651) are missing from the issue. Any reason for that?
> 
> Only reason was that I was typing this on my phone while abroad and this was the only one I could remember of the top off my head.
> I should have added a notice that the task specification is not done yet.

@agnivade: I have added a linter rule (or, rather a functionality for the bot) which I think covers all of your additional suggestions.
What do you think about it?

**Comment by fejx** [comment]
> We've already got a task spec for the linter rewrite [on the wiki](https://github.com/tldr-pages/tldr/wiki/Coding-projects#convert-the-linter-from-clexyacc-to-a-more-popular-language), if anyone would like to step up :-)

I can take a look at it, I also have (basic) experience with lex and yacc, but I will probably not get to it until next week or so. If noone else stepped up until then, I can do it 😀.

**Comment by agnivade** [comment]
> This change is already pretty significant, if we rewrite the linter we should do it first, then add the translation linting rules, then refactor the linter to the new page structure.

Yep, that's perfectly fine.

> @agnivade: I have added a linter rule (or, rather a functionality for the bot) which I think covers all of your additional suggestions.

Looks good to me @fejx. Thanks!

**Comment by mebeim** [comment]
Nice one. I think we might as well include the change proposed in #2865 to the `/v2/` ZIP file.

**Comment by mebeim** [comment]
About additional PR linting rules: this is currently impossible to implement in a way which makes sense. That would mean that if somebody makes a PR modifying an example for a page in language A, thus making it go out of sync with the same page in language B, the PR would fail the linter check. However, it is clearly impossible to require users to modify pages of ALL languages when submitting a PR.

The way this should be done is by integrating a translation framework... which is something we all would like, but it's pretty hard to accomplish, and we have been stuck on that [for quite a while](https://github.com/tldr-pages/tldr/issues/3591).

**Comment by agnivade** [comment]
Indeed. What if we make it a soft error rather than a hard error, so that we can atleast ping people about it and get it fixed at some point?

**Comment by mebeim** [comment]
@agnivade we would get multiple "errors" on basically every single PR. That would be really annoying. The only real solution is to either have a proper translation workflow. 

Instead of those soft errors we could create a script that checks translations and updates a status page somewhere on tldr-pages.github.io, which documents what is up-to-date and what is not.

**Comment by agnivade** [comment]
Sounds good. Or even a wiki page for that matter.

**Comment by fejx** [comment]
I like that there are so many good ideas, and I admit that I have no better solution either, but this idea does not seem pleasing to me.

The master branch should always have a consistent state. So a pull request should only transform the master branch from one consistent state to another.

Plus, there is a technical issue with the idea of having a list of inconsistent translations: Not all translation inconsistencies can be detected automatically. The linting rule can only *aid* in keeping consistency. If a page *description* for an example is changed semantically, the linter does not detect any inconsistencies as long as the command was not 

Could maybe multiple people work on the same pull request? One person figures out new examples, other people add translations to other languages. Is this technically possible?

---

Having said that: I think that the topic of discussion is spreading too far. Discussing about how to maintain consistency between translations is important. However, it only has marignally something to do with setting up a new directory structure.

You can:

* change the structure while not adding translation linting, and
* you can add translation linting while not changing the structure.

These two issues are not linked apart from the fact that tracking translations is *a little bit* harder with the new structure. However, in the existing structure, this is a problem aswell.

**Comment by bl-ue** [comment]
We also need to rename `osx/` to `macos/` because of macOS Big Sur 11.0. #5013

**Comment by bl-ue** [comment]
IMO the biggest problem with any architectural changes like this is keeping clients working while we and they make change over to a new spec. 🤔

**Comment by bl-ue** [comment]
>Plus, there is a technical issue with the idea of having a list of inconsistent translations: Not all translation inconsistencies can be detected automatically. The linting rule can only aid in keeping consistency. If a page description for an example is changed semantically, the linter does not detect any inconsistencies as long as the command was not

@fejx I've got a solution to that.  The linter could check the date that that line was last modified at in the English page, and check the date that that line was last modified at in the translated page, and if the former is newer than the latter, a translation update for that line is needed. Sounds like it will work to me 👍🏻

**Comment by gutjuri** [comment]
Is this still of interest? I do not think that we're realistically going to change the directory layout at this point.

**Comment by sbrl** [comment]
I agree @gutjuri. For better or for worse, our current directory structure is here to stay. Changing it now would be enormously disruptive to the entire ecosystem.

However, the new structure proposed does seem much neater.
