### ISSUE TITLE
Page update request: top/htop; Add sorting flag

### ISSUE THREAD

**Issue by mihainsto** [tldr-pages/tldr#4133]
Hello, I often want to use top/htop to order the processes by the use of memory. I think that other users would like to do this to find out what apps use the most memory.

I suggest we add the sorting flag to the pages. 
Add -o argument to top pages and -s argument to htop pages.

Order by memory with top:
`top -o %MEM`
or for htop
`htop -s PERCENT_MEM`

Current top and htop pages:
https://github.com/tldr-pages/tldr/blob/master/pages/linux/top.md
https://github.com/tldr-pages/tldr/blob/master/pages/linux/htop.md

**Comment by zdroid** [comment]
It's the best if you propose this change in a PR, since you are experienced with the command already. It'd also properly attribute the contribution to you.

**Comment by mihainsto** [comment]
Ok, I will make later this day a PR.

**Comment by mihainsto** [comment]
Pull requests merged. I will close this.
