### ISSUE TITLE
the command `rmdir -p` remove parents directory, not recursively

### ISSUE THREAD

**Issue by 4goodapp** [tldr-pages/tldr#4147]
From the man page for rmdir:
>  -p, --parents   remove DIRECTORY and its ancestors; e.g., 'rmdir -p a/b/c' is
                    similar to 'rmdir a/b/c a/b a'

So `rmdir` remove an empty directory and its parents.

**Comment by sbrl** [comment]
Great spot, @4goodapp! Would you like to open a PR to correct the page?

You can do so from the GitHub web interface if you like :-)
