### ISSUE TITLE
Page for "at" is incorrect

### ISSUE THREAD

**Issue by CrispyBaguette** [tldr-pages/tldr#4192]
The page for the `at` command shows time formatted as `hh:mm:ss`, but the command does not recognize seconds (`at` version 3.1.20-3 on Debian).

The time should be something like `hh:mm` or one of the many other formats.

**Comment by sbrl** [comment]
Hey, thanks @CrispyBaguette! Great spot. Would you like to open a pull request to fix it? You can do it all from the GitHub web interface if you like :-)
