### ISSUE TITLE
tail pages looks broken

### ISSUE THREAD

**Issue by tminei** [tldr-pages/tldr#4203]
If open tail page from tldr.sh, all good, but, if i do tldr tail i see that:
```
tldr tail
tail
Display the last part of a file.

 - Show last 'num' lines in file:
   tail -n {{num}} {{file}}

 - Show all file since line 'num':
   tail -n +{{num}} {{file}}

 - Show last 'num' bytes in file:
   tail -c {{num}} {{file}}

 - Keep reading file until 
   Ctrl + C
:
   tail -f {{file}}

 - Keep reading file until 
   Ctrl + C
, even if the file is rotated:
   tail -F {{file}}

 - Show last 'num' lines in 'file' and refresh every 'n' seconds:
   tail -n {{num}} -s {{n}} -f {{file}}
```

**Comment by sbrl** [comment]
Hey there, @tminei! Which client are you using (i.e. how did you install `tldr`)? This sounds like a bug in the client, not the page itself if I'm understanding this correctly.

**Comment by tminei** [comment]
> 
> 
> Hey there, @tminei! Which client are you using (i.e. how did you install `tldr`)? This sounds like a bug in the client, not the page itself if I'm understanding this correctly.

Hi, i use ubuntu and install tldr from apt: sudo apt install tldr. When i use current ver from GH all okay.

**Comment by zdroid** [comment]
@tminei That version is some old Python-based client. You should try something more recent like https://github.com/tldr-pages/tldr-python-client or https://github.com/tldr-pages/tldr-node-client.

If you agree, I suggest this issue to be closed and moved into https://github.com/tldr-pages/tldr/issues/4044, as it's regarding an inactive "client".

**Comment by tminei** [comment]
сlose
