### ISSUE TITLE
page request: rename (macOS)

### ISSUE THREAD

**Issue by phrohdoh** [tldr-pages/tldr#4218]
http://plasmasturm.org/code/rename/#TUTORIAL

**Comment by sbrl** [comment]
Hey there, @Phrohdoh! Which OS and client are you using? When I do `tldr rename`, I see one in the `linux` platform.

**Comment by Phrohdoh** [comment]
macOS and whichever client is installed via `brew install rename`, sorry I won't be at my machine to check for quite some time.

**Comment by sbrl** [comment]
I see. No problem @Phrohdoh! I'm unsure as to whether `rename` on macOS work identically to that we have in the `linux` page. If so, we should move the `linux` copy into `common`, and then create `windows`-specific version of the page.

Does anyone have a mac we can use to check? I forget who does that I can @mention.

**Comment by Phrohdoh** [comment]
https://github.com/Homebrew/homebrew-core/blob/5fa9dd480c91e8aa64cb546982256c9d2aba73ae/Formula/tldr.rb#L4 is `tldr-c-client`.

**Comment by sbrl** [comment]
Ah, I see. Could you check to see if [the `linux` page](https://github.com/tldr-pages/tldr/blob/master/pages/linux/rename.md) matches the functionality you see in the macOS `rename` command please? This determines where we need to go next with this.

**Comment by Phrohdoh** [comment]
Per that link:

> NOTE: this page refers to the command from the util-linux package. For the Perl version, see file-rename or perl-rename.

http://plasmasturm.org/code/rename/rename is perl, so they are not the same.

**Comment by Phrohdoh** [comment]
@zdroid for me edification, why was this given the `clients` label?

**Comment by zdroid** [comment]
Because I thought it's a client issue (a page in linux folder not displayed on macOS). But since it's a new page, then it definitely should have that label... :smile:

**Comment by sbrl** [comment]
Ah, I see. Thanks for the clarification @Phrohdoh. In that case, we should have a separate page for `rename` on macos. Strange - you don't often find a command that is present on 3 different platforms but functions in 3 different ways....! I will update the title of this issue.

Do you want to have a go yourself creating this page?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by cr33dx** [comment]
There is no default rename command in mac os (Catalina) or older.
There is a man page for rename though.
It says rename is a system call, cannot be executed through cli.

**Comment by sbrl** [comment]
Ah, I see @cr33dx, so this is a new feature as of Catalina? We should definitely mention that in the page then. Unfortunately, I don't have access to a mac, so I can't write the page. Do you want to have a go?

**Comment by Phrohdoh** [comment]
This confusion is entirely my fault as I was not sufficiently clear, I apologize.

I am using `rename` which was installed via `brew install rename` and am requesting a tldr entry for that `rename`.  I know nothing about the syscall.

**Comment by cr33dx** [comment]
@sbrl apologies for confusion, by older i meant earlier version too did not have rename in cli, it's a syscall.
i have macos catalina and it too does not have rename command.

I think the latest comment by @Phrohdoh clears out the confusion.

**Comment by sbrl** [comment]
I see! Thanks for clearing that up :-)

**Comment by sesam** [comment]
```
> brew info rename
rename: stable 1.601 (bottled), HEAD
Perl-powered file rename script with many helpful built-ins
http://plasmasturm.org/code/rename
Conflicts with: <-- it gets tricky right around here
  util-linux (because both install `rename` binaries)
```

Can tldr distinguish between these somehow? Something like a *disambiguation* flagging that Wikipedia uses.

**Comment by sbrl** [comment]
Hrm. At the moment [this algorithm](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#page-resolution) is used to resolve page names. We've got a name conflict with `dep` in #4476, but that one was easily solved because 1 command was deprecated.

**Comment by bl-ue** [comment]
Thank you @nikisix for fixing this in PR #4946! Next time, please link the issue number in the PR description so that GitHub automatically closes the issue when the PR is merged.
