### ISSUE TITLE
page request: grex

### ISSUE THREAD

**Issue by aunsbjerg** [tldr-pages/tldr#4245]
https://github.com/pemistahl/grex

Examples:
https://github.com/pemistahl/grex#53--examples-top-

**Comment by sbrl** [comment]
Thanks for requesting this page, @aunsbjerg! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by NanthR** [comment]
Hey, so, I made a pull request regarding this issue. Since this is my first time doing this, could somebody review it and let me know if there are any changes to be made

**Comment by sbrl** [comment]
Hey, thanks for the pull request @NanthR! I've left you a review. It's a great first PR!

The way PRs work here at tldr-pages is that once you have 2 approvals, the PR can be merged.

Note also that you do not need to submit a new PR to make the changes - you can simply update the existing one by either using the GitHub web interface to accept the suggestions left, using the web interface to edit the file, or pushing new commits to the branch from your desktop.
