### ISSUE TITLE
page request: e2fsprogs

### ISSUE THREAD

**Issue by samuel-w** [tldr-pages/tldr#4250]
Currently this is what we have:
- [x] badblocks
- [x] blkid
- [x] chattr
- [x] debugfs
- [x] dumpe2fs
- [x] e2freefrag
- [x] e2fsck
- [x] e2image
- [x] e2label
- [x] e2undo
- [x] e4defrag
- [x] filefrag
- [x] findfs
- [ ] ~findsuper~ ([deprecated](https://kernel.googlesource.com/pub/scm/fs/ext2/e2fsprogs/+/v1.42.7/debian/changelog#2881))
- [x] logsave
- [x] lsattr
- [x] mke2fs
- [x] resize2fs
- [x] tune2fs

**Comment by sbrl** [comment]
Thanks for the list, @samuel-w! They all look very useful!

**Comment by bl-ue** [comment]
2 left!  @teeteejo @amitech @samuel-w any time/familiarity with the commands to add pages for `e2undo` and `findsuper`?

**Comment by bl-ue** [comment]
Thank you @navarroaxel for `e2undo`!  Can anyone do `findsuper`?

**Comment by navarroaxel** [comment]
Looks like `findsuper` was dropped.
https://github.com/tytso/e2fsprogs/blob/master/misc/findsuper.c
In e2fsprogs 1.19
https://kernel.googlesource.com/pub/scm/fs/ext2/e2fsprogs/+/v1.42.7/debian/changelog

**Comment by bl-ue** [comment]
Looks like you're right @navarroaxel! [Here's the specific line.](https://kernel.googlesource.com/pub/scm/fs/ext2/e2fsprogs/+/v1.42.7/debian/changelog#2881)

In this case, would we add a page, and say it was deprecated?  Or still add a page?

**Comment by navarroaxel** [comment]
It's a similar scenario like `dep` https://github.com/golang/dep, this is deprecated and archived and was removed from tldr pages.

**Comment by bl-ue** [comment]
Okay.  And `findsuper` was deprecated long before dep was even started.  So I'll check that one off, and say we're done!

**Comment by bl-ue** [comment]
Thank you @navarroaxel! ❤️
