### ISSUE TITLE
make setup: "make: bundle: Command not found"

### ISSUE THREAD

**Issue by Permafacture** [tldr-pages/tldr#428]
on Debian Sid, fresh clone:

    me@laptop: ~/code/tldr$ make setup
    Git pre-commit hook installed.
    make: bundle: Command not found
    Makefile:21: recipe for target 'deps' failed
    make: *** [deps] Error 127

**Comment by igorshubovych** [comment]
`sudo apt-get install ruby`

**Comment by ostera** [comment]
We could check if bundler is available and print out to have it installed, but other than that this is going to happen if you don't have the minimal dependencies.

**Comment by Permafacture** [comment]
Some clear message about a missing dependency would be helpful.
