### ISSUE TITLE
add collaborator: navarroaxel

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#4291]
Hi, @navarroaxel! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#2688, #4213, #4238, #4252, #4277, #4278)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by navarroaxel** [comment]
Hi @sbrl

Yeah! I accept your invitation. :grin:

**Comment by mebeim** [comment]
Welcome @navarroaxel :)

**Comment by sbrl** [comment]
Invite sent!

Looks like there are more roles now for collaborators than before. The complete set available now is:

 - Read
 - Triage
 - Write
 - Maintain
 - Admin

**Comment by owenvoke** [comment]
Welcome @navarroaxel 👋🏻

**Comment by schneiderl** [comment]
Welcome @navarroaxel
