### ISSUE TITLE
Installation of tldr refused by OS

### ISSUE THREAD

**Issue by DenonDL304** [tldr-pages/tldr#4319]
Hi I tried to install tldr on my RPI4 but I got a whole bunch of error messages:

`pi@moode:~ $ npm install -g tldr
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to /usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
`

I fixed the presumed access problem to the "node_modules" directories and content (chmod -R 755 [dir]) with the above output as a result. sudo npm etc. gets an error message: "sudo: npm: command not found". 
What I found strange that all the files in '/usr/local/node/node-v14.9.0-linux-armv7l/lib/node_modules' have mpd:mpd as owner:group. 
So I assume the suggested install command ''npm install -g tldr'' only works after entering root mode with the command "sudo -i" or something? Why not "apt-get" etc. for us mortals?

I hope you can help you fix this for me. I've attached the two error log files.

Thanks & best regards,
Marco

[2020-09-06T12_52_01_212Z-debug.log](https://github.com/tldr-pages/tldr/files/5179711/2020-09-06T12_52_01_212Z-debug.log)
[2020-09-06T13_02_41_455Z-debug.log](https://github.com/tldr-pages/tldr/files/5179713/2020-09-06T13_02_41_455Z-debug.log)

**Comment by navarroaxel** [comment]
I didn't use RPI, but I think you have several options

1. You could use `npx tldr {{command}}`.
2. If you install `npm` using `apt` you need to install global packages using the `sudo` command. Maybe there is an issue in your installation and the `/usr/bin/npm` is not in the `$PATH` for the `root` user.
3. If you install node using `nvm` you don't need `sudo` to install global packages.
4. In the `apt` repositories (Debian and Ubuntu) the Haskell tldr client is available. It should be available in your distribution using `apt install tldr`.

**Comment by DenonDL304** [comment]
Hi Axel,

Thank you for your reply. I did resolve the installation eventually by
using:
pip install tldr

The response I got from the Raspberry Pi:
pip install tldr
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tldr
  Downloading
https://files.pythonhosted.org/packages/ff/bb/0870bf90ad1137172b3cc0758d18e99fd2325243139e0bb7652556c77e0e/tldr-0.5.tar.gz
Collecting colorama (from tldr)
  Downloading
https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
(from tldr) (1.12.0)
Collecting termcolor (from tldr)
  Downloading
https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Building wheels for collected packages: tldr, termcolor
  Running setup.py bdist_wheel for tldr ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/41/f5/5c/ded7a9274759a5a922883b515384a0c836018a373f47281357
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory:
/home/pi/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
Successfully built tldr termcolor
Installing collected packages: colorama, termcolor, tldr
Successfully installed colorama-0.4.3 termcolor-1.1.0 tldr-0.5

So it's been installed in ./home/pi/.local/bin/tldr
The tldr directory only holds three files:
pi@moode:~/.local/bin $ ls -la
total 56
drwxr-xr-x 2 pi pi  4096 Sep  6 16:29 .
drwx------ 4 pi pi  4096 Sep  6 16:29 ..
-rwxr-xr-x 1 pi pi 12775 Sep  6 16:29 tldr
-rwxr-xr-x 1 pi pi 12775 Sep  6 16:29 tldr.py
-rw-r--r-- 1 pi pi 13098 Sep  6 16:29 tldr.pyc

I guess that tldr's thesaurus or dictionary is held elsewhere, but I can't
figure it out.

I did need to include the tldr command in .bash_aliases, something I wanted
to avoid. Maybe you could check the RPI's above response so tldr can be
used & updated the way it should?

BTW: tldr is missing mpd (though mpc is included) maybe because of how it's
been installed? Is there an easy way to add a whole bunch of commands to tldr
as a package? And how would I update tldr, should such expansion packages
indeed be available, considering the way I installed tldr.

Anyway, I can use tldr without sudo (in fact, sudo doesn't know tldr). I
did look around on the GitHub tldr pages but couldn't make sense of any of
it (that happens a lot when I'm on GitHub)...

Otherwise, it's a great tool for the likes of me!

Thanks very much & best regards,
Marco

Op zo 6 sep. 2020 om 20:30 schreef Axel Navarro <notifications@github.com>:

**Comment by sbrl** [comment]
Hey there!

Your issue there with installing the Node.js client is that when you're installing globally, you have to use `sudo`. Do it like this:

```bash
sudo npm install --global tldr
```

> BTW: tldr is missing mpd 

We don't have that page yet, but you're welcome to contribute it! :D

> I did need to include the tldr command in .bash_aliases, something I wanted
to avoid.

This is because you are again installing locally. When you do that, you have noted that  you have installed to something in your home directory. Again, you probably want something like this:

```bash
sudo pip3 install tldr
```

> in fact, sudo doesn't know tldr

When you prefix a command with `sudo`, it clears the environment and runs the command in a new clean environment. This causes your aliases to be dropped and any `PATH` customisations to be lost. Installing `tldr` globally using one of the methods I've described above should do the trick here.

**Comment by sbrl** [comment]
Ping @DenonDL304, is this still an issue?

**Comment by bl-ue** [comment]
Obviously not @sbrl!
