### ISSUE TITLE
How to add private cheats and backup?

### ISSUE THREAD

**Issue by sayeduzzamancuet** [tldr-pages/tldr#4344]
I am looking for a way to add some private cheats and a way to back them up. Is it possible?

**Comment by sbrl** [comment]
Hey there, @sayeduzzamancuet! That's a client-specific feature that seems deceptively simple - there are actually a number of caveats. Which client are you currently using?

Backing up is a separate issue, and one that would can be served in any number of ways, from having a private git repo with a cronjob on a backup machine to `git pull` on a regular basis, to using tools such as [restic](https://github.com/restic/restic/) or [duplicity](http://duplicity.nongnu.org/). Cloud storage solutions such as [backblaze](https://backblaze.com/) may also be of interest.

It's been discussed before in #3269 and #2051 already - so I'd suggest we close this issue as a duplicate.

What do you think?

**Comment by sayeduzzamancuet** [comment]
I am using in windows. What I need is to add/delete/edit cheats. Sometimes I feel like I need to add a private cheat that should not be publicly published. Is it possible?

**Comment by sbrl** [comment]
I see. The repository for that client can be found here: https://github.com/tldr-pages/tldr-node-client

I'd generally consider private pages to be a client-specific feature.

See the discussion in #3269 and #2051 for more information. I'm going to close this issue as a duplicate, but I'm happy to re-open it if there's something else we've missed.

**Comment by Phuker** [comment]
Hey guys, I am making a new Python client [Phuker/multi-tldr](https://github.com/Phuker/multi-tldr) which support private pages. If you prefer Python, you may try it out, and tell me how do you like it.

Maybe someday when it is mature and stable enough, I will create a PR to add it to the community clients list.
