### ISSUE TITLE
Token inconsistency: quotes inside/outside tokens

### ISSUE THREAD

**Issue by glenacota** [tldr-pages/tldr#4363]
Hi! The goal of this issue is to discuss one of the inconsistencies I [listed here](https://github.com/tldr-pages/tldr/issues/2509#issuecomment-435521621) a couple of years ago, namely, whether to place quotes `{{"inside"}}` or `"{{outside}}"` a token.

Running a search in the codebase, there are by far more quotes outside than inside. Besides this, I'd argue that putting quotes outside is the best strategy for two other reasons:
1. It removes any ambiguity on what is replaceable and what not within the token - that is, are the quotes necessary or not to preserve?
2. It allows for more appropriate use of the quotes within the token, like for the [gist command](https://github.com/tldr-pages/tldr/blob/master/pages/common/gist.md): `{{echo "hello world"}} | gist`

What do you think? :)

**Comment by owenvoke** [comment]
Hi @glenacota, thanks for flagging this up. I agree that putting quotes outside is the best strategy. 👍🏻

**Comment by glenacota** [comment]
Nice! I can work on this during the week. 
What would be the best way to proceed? I think a bulk update is preferable, with a single, consistent PR. Maybe one could split the changes into several commits by, e.g., localisation.

**Comment by owenvoke** [comment]
I think a single bulk PR makes sense, I guess it depends on how many pages there are that require changes. 🤔

**Comment by sbrl** [comment]
Great spot! A single bulk PR would be preferable. Personally I prefer quotes outside.

We'll need to look closely at it though when reviewing, because it's possible that in some circumstances there will be a reason for the way it has been done. We should also be careful to keep the same type of quotes (e.g. sing vs double), because it's possible they will also have meaning (e.g. single are best when specifying a regular expression, for example).

**Comment by glenacota** [comment]
If you all agree, I can work on this issue in the next days

**Comment by sbrl** [comment]
Yep, I think we can agree that outside quotes are the best approach @glenacota. Thanks for the assistance! :D

**Comment by schneiderl** [comment]
Great find.
I will review the PR you've opened.

**Comment by glenacota** [comment]
Solved with #4431. Thanks, everyone :)
