### ISSUE TITLE
Feature request: Enable individual pages to be displayed with URL slug

### ISSUE THREAD

**Issue by tagawa** [tldr-pages/tldr#440]
For example going to http://www.ostera.io/tldr.js/ping would show the page for the `ping` command.

This way we could create third-party services or browser hacks to link directly to command pages, e.g. a DuckDuckGo bang so that `!tldr [command]` opens that command page.
(Disclaimer: I work for DuckDuckGo)

**Comment by ostera** [comment]
ack. Closing this now. Further discussion can take place over at the https://github.com/ostera/tldr.jsx issues

**Comment by ostera** [comment]
@tagawa :) http://www.ostera.io/tldr.jsx/#/tldr
