### ISSUE TITLE
Coding Projects page does not seem updated

### ISSUE THREAD

**Issue by schneiderl** [tldr-pages/tldr#4414]
As you can see [here](https://github.com/tldr-pages/tldr/wiki/Coding-projects) there is a task **"Implement multi-language support for the node client"**.
I've quickly checked the code and the code seems to be handling multi-languages. 
Can we delete that from the wiki or somehow state that it was completed?
Or there is still something to be done there?

**Comment by sbrl** [comment]
Oh, good point @schneiderl. Yeah, we can probably remove that one now.

**Comment by schneiderl** [comment]
I have removed that section from the wiki and will close this issue. If anybody has any comments on this feel free to contact me via this issue.
