### ISSUE TITLE
Issues with Liberapay

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#4428]
In #3102, we implemented Liberapay, and in #4057 we rolled it out across all our repositories. However, in #4367 @axelson discovered that as it is now, our Liberapay page is non-functional:

![image](https://user-images.githubusercontent.com/9929737/94979127-fdc78f00-0518-11eb-910b-dce456d40d05.png)

I discovered that in my Liberapay account I needed to link my PayPal account (and create a Stripe account) in order to be ready to receive payments, so perhaps this is also the case for other members of the page?

The setting is located here:

![Screenshot_2020-10-03 Payment Processors - sbrl - Liberapay](https://user-images.githubusercontent.com/9929737/94979244-91995b00-0519-11eb-90b2-b620aff0e3df.png)

/cc @agnivade, @waldyrious, @ostera, @owenvoke, @mebeim.

**Comment by agnivade** [comment]
Woops, nice catch. I don't really recieve any payments so I wouldn't know. I think @ostera was from the tldr.sh domain costs.

**Comment by mebeim** [comment]
Hmmm... this is interesting. It looks like each one of us should set up a Payment processor (either PayPal or Stripe). I have PayPal set up now.

**Comment by owenvoke** [comment]
Interesting, mine seems to have already been set up when I created my account before. 👍🏻

**Comment by waldyrious** [comment]
Mine also seems to be set up. I would suspect, as @agnivade suggested, that the issue lies with @ostera's account setup, as he's the only one who is selected to receive funds at the moment (due to maintaining the `tldr.sh` domain).

In any case, it would be nice if this problem was reported in the "income shares" page, rather than only appear when someone actually tries to donate (by the way, thanks so much for the support, @axelson!). Any thoughts about that, @changaco?

**Comment by axelson** [comment]
> In any case, it would be nice if this problem was reported in the "income shares" page, rather than only appear when someone actually tries to donate (by the way, thanks so much for the support, @axelson!)

You're welcome! Thanks for maintaining tldr, I find it extremely helpful in my day-to-day work, and the contribution process is great too.

**Comment by ostera** [comment]
Hej folks! Should be solved now. I had a hiccup setting things up but now my Stripe is fully connected. Sorry for the inconvenience 🙌🏼  🌈

**Comment by axelson** [comment]
Okay, my payment just went through so I think the issue can now be closed :+1:

**Comment by waldyrious** [comment]
Great! Glad we sorted it out :)
