### ISSUE TITLE
Add org member: @navarroaxel

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#4504]
Hi, @navarroaxel! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks.
Thank you for that!
According to [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
You'll now be one of the public faces of the tldr-pages project.

How does that sound? Are you up for it?

**Comment by schneiderl** [comment]
Be welcome @navarroaxel 💯 👍

**Comment by navarroaxel** [comment]
@sbrl yeah that's awesome!

**Comment by sbrl** [comment]
Invite sent :D

**Comment by navarroaxel** [comment]
Accepted!
