### ISSUE TITLE
page request: <chroma>, with added samples

### ISSUE THREAD

**Issue by vtvh** [tldr-pages/tldr#4515]
### Chroma is a general purpose syntax highlighting library and corresponding command
Repo: https://github.com/alecthomas/chroma

### Samples
```sh
# colorize with shell style
chroma -l sh
# Fuzzy search colorized aliases
alias | chroma -l sh | fzf --ansi
```

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
