### ISSUE TITLE
Wikipedia article in the README doesn't exists. 

### ISSUE THREAD

**Issue by seenukarthi** [tldr-pages/tldr#4552]
The Wikipedia link (https://en.wikipedia.org/wiki/TL;DR) in README does not exists.

![image](https://user-images.githubusercontent.com/1208295/95318884-30221500-08a8-11eb-8634-20a24fe039f4.png)

**Comment by endearingyoungcharms** [comment]
I think that it should link to the essay: https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read

**Comment by sbrl** [comment]
Hey, great spot! Thanks for bringing this up. Would you  like to open a pull request to fix it? You can do so through  the GitHub web interface :-)

If there's anything we can do to help you out with the process, let us know :D

**Comment by seenukarthi** [comment]
@sbrl opened a PR #4570
