### ISSUE TITLE
page request: Lynx (web browser)

### ISSUE THREAD

**Issue by endearingyoungcharms** [tldr-pages/tldr#4629]
I think that this is a bit niche, but there are times when other things won't work.

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by annashorthead** [comment]
Hey! I would like to work on this.

**Comment by sbrl** [comment]
You're most welcome to, @annashorthead! Don't forget to include `Fixes #4629` in the description of your pull request to auto-close this issue when it's merged :-)
