### ISSUE TITLE
add clear error message when Ruby is missing

### ISSUE THREAD

**Issue by Permafacture** [tldr-pages/tldr#468]
As someone wanting to contribute some pages, this was confusing:

    me@laptop: ~/code/tldr$ make setup
    Git pre-commit hook installed.
    make: bundle: Command not found
    Makefile:21: recipe for target 'deps' failed
    make: *** [deps] Error 127

In #428 it appears the solution (on Debian) is:

    sudo apt-get install ruby
    gem install bundler

Make setup should say something more clear about what the issue is.

**Comment by waldyrious** [comment]
:+1:
