### ISSUE TITLE
page request: zmv

### ISSUE THREAD

**Issue by hrai** [tldr-pages/tldr#4685]
A page for zsh's utility function - [zmv](http://zsh.sourceforge.net/Doc/Release/User-Contributions.html)

**Comment by navarroaxel** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of CONTRIBUTING.md, which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by waldyrious** [comment]
Fixed in #4705! 🎉
