### ISSUE TITLE
Token inconsistencies: enforce snake_case in token

### ISSUE THREAD

**Issue by glenacota** [tldr-pages/tldr#4746]
The [token syntax guideline](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md#token-syntax) for multi-word tokens is to use the_snake_case_form. However, in some pages, words in tokens are separated by whitespace (e.g., buku, gist, man, [git-send-email](https://github.com/tldr-pages/tldr/pull/4737#discussion_r507013716), ...) and in others dashes (e.g., dexter, git-ls-remote, ...).

I can work on a bulk PR to enforce the snake_case syntax guideline, maybe creating one commit for each wrongful separator.

(this Issue might be linked to [this old one)](https://github.com/tldr-pages/tldr/issues/2509#issuecomment-435521621)

**Comment by glenacota** [comment]
BTW, I'm not sure this is the right place where to ask, but as I'm very fond of this project and lately I've got some more time to contribute to it, I'd like to ask the org owners how does it work to apply for a [regular contributor position](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md)  :)

**Comment by seenukarthi** [comment]
@glenacota there is [gitter room](https://gitter.im/tldr-pages/tldr) I think general discussion can be done there.

**Comment by sbrl** [comment]
Hey there, @glenacota! We'd love to have you onboard. According to our [community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document, you need to have 5 non-trivial PRs merged. From the pull request history, I notice you have the following non-trivial PRs merged: #4364, #4362, #2464, #2458, #2452, and #2440. This qualifies you to become a contributor according to the aforementioned document, so I'll open a new issue about that and @mention you :-)

**Comment by sbrl** [comment]
And to answer the original question in this issue, a PR would be appreciated! Though do be careful to check each one: there may be some instances of concrete examples where the space is essential to the page. And also yes, this does seem related to that issue

**Comment by sbrl** [comment]
Opened #4763

**Comment by glenacota** [comment]
issue solved with https://github.com/tldr-pages/tldr/pull/4788
