### ISSUE TITLE
add contributor: @glenacota

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#4763]
Hi, @glenacota! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#4364, #4362, #2464, #2458, #2452, and #2440)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by glenacota** [comment]
Hi, @sbrl, fantastic Maintainer's guide! Sure, I'd be really happy to be added as a collaborator.

Like most of you, there are periods that I can invest more time on it (like recently) and some period less time, but `tldr` it's a community I've always loved to come back to and support!

**Comment by sbrl** [comment]
Invite sent!

There's a bit of a lead time at the moment on my reading of notifications, because it's both hacktoberfest and I'm busy setting up a new laptop.

**Comment by schneiderl** [comment]
Welcome @glenacota 😄 

Was the invite already accepted? If so, can we close this issue?

**Comment by bl-ue** [comment]
@glenacota are you a collaborator yet?
