### ISSUE TITLE
Are you guys interested in adding a "see also" where it's relevant?

### ISSUE THREAD

**Issue by Parth** [tldr-pages/tldr#481]
For example, the [git.md](https://github.com/tldr-pages/tldr/blob/master/pages/common/git.md) might be one of the first pages a user views, only to see that `git clone`, `git commit`, etc aren't there. It doesn't seem obvious that `tldr git-clone` would show me how to use it. Perhaps if at the foot of pages like that, we could have a bulleted list of _See Also_, and list any other obvious commands. Would this form of a change be welcome?

**Comment by waldyrious** [comment]
Well we already do this in the main description, e.g. in [uname.md](https://github.com/tldr-pages/tldr/blob/master/pages/common/uname.md). Do you think a dedicated section would be better?

**Comment by Parth-Mehrotra** [comment]
Yes, I think it would add more structure if users knew that the if they go to the bottom of the notes they can look at other commands that are closely related, and how they're related. What do you think?

**Comment by Parth-Mehrotra** [comment]
I'd be happy to go through and add this to the ones I know about

**Comment by igorshubovych** [comment]
We were discussing this from time to time.

Actually at the moment any change like this require the changes in the numerous clients. We should very carefully change the format of data and it should be approved by different parties. There are several different propositions to change the format, but this is a drastic change for the project and I'd rather do it very-very carefully.

**Comment by Parth-Mehrotra** [comment]
How about just adding a

# See also
+ git-commit: for blah blah blah
+ git-add: for blah blah blah

On the relevant pages?

**Comment by igorshubovych** [comment]
We have many problems at the moment:
- not enough pages, many even basic commands not covered
- buried by existing pull requests
- better documentation, format description, guidelines
- issues with clients
- organizational issues
and others

Bringing change to the such a basic format will distract us from the main goal.

"See Also" is in our pipeline. One day we will come back discussing it. But it will be not today and not the next week and probably not the next month.

However there is other great open-source project which look at the man problem from different point of view. It might be useful for your case, I mean git example. It is called [cheat](https://github.com/chrisallenlane/cheat).

**Comment by Parth-Mehrotra** [comment]
Okay, I'll go ahead and close this then, and maybe reopen in the distant future, is there a list of missing commands? I'd love to contribute in a meaningful way.

**Comment by igorshubovych** [comment]
There is a [list of missing commands](https://github.com/tldr-pages/tldr/wiki/Pages-plan), but even this one is outdated :)

Now you see how far we are from discussion about format change.

**Comment by igorshubovych** [comment]
Feel free to reopen.

**Comment by waldyrious** [comment]
The issue has been re-raised in #785, so I'll reopen this one for further discussion.

Note also that the node client now renders "see also" sections, per tldr-pages/tldr-node-client#81. We just need to agree on a standard format and add it to CONTRIBUTING.md

**Comment by waldyrious** [comment]
This issue should be addressed once #958 is wrapped up. We also must ensure that clients can process the markup we eventually choose for this (something to keep in mind in #1065).

**Comment by waldyrious** [comment]
Hey @Parth, do you think implementing #784 would solve this issue? If so I'd suggest closing this issue and tracking the implementation there :)
