### ISSUE TITLE
A response when the TLDR page doesn't exist.

### ISSUE THREAD

**Issue by rselwyn** [tldr-pages/tldr#484]
Right now, if 

```
$ tldr foobarbaz
```

is entered, there will literally be nothing.  There will just be a new line in the command-prompt.  I propose having some sort of "catch all" page or an alert to say "this page doesn't exist"

For example, 

```
$ tldr foobar
Unfortunately, the page foobar doesn't exist.  If you expect this to exist, see CONTRIBUTING.md to see how to add it.
```

or

```
$ tldr foobar
```
might bring up some sort of "how-to" page which has information on how to use TLDR.

*Thoughts?*

**Comment by lord63** [comment]
Which client are you using?
Your suggestions make sense. By the way, tldr just offers the markdown pages, you may open an issue in the client repo.

**Comment by ostera** [comment]
Closing this as it's related to a client.
