### ISSUE TITLE
They are not man pages.

### ISSUE THREAD

**Issue by RalphCorderoy** [tldr-pages/tldr#488]
"Simplified and community-driven man pages" is misleading.  They are not man pages in many ways;  they're not roff source, man(1) cannot format them, "man -k" doesn't search them, etc.  bro says their content is a supplement to man pages.  tdlr seem to be usage examples;  perhaps that phrase can be used instead of man pages.

**Comment by sdaitzman** [comment]
I think that phrasing is okay. The project should not undersell itself. It's simpler than manpages (therefore simplified), it's community-driven (accepts PRs) and it's a manual system that lets you learn things (therefore man pages).

**Comment by ostera** [comment]
@sdaitzman I couldn't have said it better. Thanks anyways @RalphCorderoy for taking the time to open this issue!
