### ISSUE TITLE
README: Link to a more relevant article explaining "tl;dr"

### ISSUE THREAD

**Issue by tactlessfish** [tldr-pages/tldr#4885]
The last section of the README (What does "tldr" mean?) links to [Wikipedia's internal essay regarding "Too long; didn't read"](https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read). While the essay does contain some general information about the phrase, its focus is on wordiness in Wikipedia articles:

> This essay examines tl;dr as used in Wikipedia discussions, offering insight into the cause of excessive length, suggestions on how to reduce it, and a reminder to always exercise civility with other editors.

For that reason, it's not the most relevant article to link for readers that want to learn more about the phrase. I suggest linking instead to a more general article, such as [this one from HowToGeek](https://www.howtogeek.com/435266/what-does-tldr-mean-and-how-do-you-use-it/).

**Comment by sbrl** [comment]
Hey, that looks like a good article! Perhaps we could link to that one, but add the existing wikipedia one as a secondary link in brackets next to it or something. Would you like to open a pull request @tactlessfish?

**Comment by tactlessfish** [comment]
Sure, I would love to! I'm just a bit confused though—why should we keep the Wikipedia essay? Its information about article conciseness and advice for editors are specific to Wikipedia, and that may cause confusion for users reading the README.

**Comment by endearingyoungcharms** [comment]
Hello, someone who originally changed the link here.
Originally, the link led to a now-defunct Wikipedia article, which I suggested we should change to the essay. The reason for changing it to the essay was to keep it in Wikipedia and avoid changing the whole thing.
That being said, your article is much better.

**Comment by tactlessfish** [comment]
Ah okay, thanks for the explanation. In that case, @sbrl would it be alright to remove the Wikipedia essay in my PR?

**Comment by sbrl** [comment]
Ah, maybe it would. That sounds like a good plan - let's do that.
