### ISSUE TITLE
page request: electron-packager

### ISSUE THREAD

**Issue by Starkiller645** [tldr-pages/tldr#4891]
A page for the electron-packager tool used to package Electron apps into standalone executables.

https://github.com/electron/electron-packager

**Comment by navarroaxel** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md](CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
