### ISSUE TITLE
Let's document! Android edition 🤖

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#4934]
For those not in the know, the `adb shell` command forward commands to a remote shell on an Android emulator instance or connected Android devices.

Try these:
```
tldr adb shell
adb shell # start an interactive shell on the emulator/device
```

In the case of Android 🤖, it has quite a number of specific platform commands. We should include this pages into the `common/` folder because `tldr` and `adb shell` are used in Windows, Linux and macOS. Let's document them all!

- [x] am → #5481 
- [ ] bugreport → #5743 
- [ ] bugreportz → #5743 
- [x] dumpsys → #5739
- [x] getprop → #5456
- [x] input → #5740
- [x] logcat → #3562, #5737
- [x] pm → #5458
- [x] wm  → #5457

**Comment by Rudloff** [comment]
logcat already has a page since https://github.com/tldr-pages/tldr/pull/3562.

**Comment by navarroaxel** [comment]
Blocked by #5462

**Comment by Rudloff** [comment]
I added some of them in https://github.com/tldr-pages/tldr/pull/5481.

**Comment by marchersimon** [comment]
I couldn't find any documentation for `bugreport`. Only the source code for [bugreport.cpp](https://android.googlesource.com/platform/system/core/+/android-8.1.0_r7/adb/bugreport.cpp), [bugreport.h](https://android.googlesource.com/platform/system/core/+/android-8.1.0_r7/adb/bugreport.h) and [bugreport_test.cpp](https://android.googlesource.com/platform/system/core/+/android-8.1.0_r7/adb/bugreport_test.cpp), from which it seems like `bugreport` doesn't have any command line options.

**Comment by navarroaxel** [comment]
@marchersimon I think `bugreport` just generate the memory stats of each app and display it to stdout (display or `> file), and `bugreportz` is a zipped bugreport.

**Comment by marchersimon** [comment]
And there's just `bugreport` and `bugreportz` to get all bug reports at once? No arguments at all?

**Comment by navarroaxel** [comment]
```
$ bugreportz -h                                                                                                                                            
usage: bugreportz [-h | -v]
  -h: to display this help message
  -p: display progress
  -v: to display the version
  or no arguments to generate a zipped bugreport
```
I think this guy if for OS debugging, no for app's bug report.

**Comment by marchersimon** [comment]
Is there a way to install it natively on Android? I'd like to write the page, but I have no idea how to set up adb shell to test the commands.

**Comment by navarroaxel** [comment]
You just need to install the `adb` command (using Android Studio or alternative ways), turn on USB debugging in the Android device <https://developer.android.com/studio/debug/dev-options>; and with `adb devices` you link the device to your computer. Then you can use `adb shell` to start a remove shell.

**Comment by marchersimon** [comment]
That was actually way easier than expected, thanks.
