### ISSUE TITLE
page request: kjv

### ISSUE THREAD

**Issue by FukurouMakoto** [tldr-pages/tldr#4948]
Hello all, 

Would like to contribute to the project by writing a guide for using the [KJV program ](https://github.com/bontibon/kjv).

Please let me know if it would be okay to go ahead and do this.

**Comment by sbrl** [comment]
Hey there! you're absolutely ok to go ahead - everyone is welcome to contribute to tldr-pages.

Pages are best created by people who understand the command they are about.

If you'd like a starting point, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by bl-ue** [comment]
@FukurouMakoto still working on this?

**Comment by bl-ue** [comment]
Nevermind @FukurouMakoto I see you're done with #4949.  Next time link the issue number in the PR description to auto-close this issue once the PR is merged.
