### ISSUE TITLE
Youtube dl github not avialble

### ISSUE THREAD

**Issue by tminei** [tldr-pages/tldr#4952]
Youtube dl github not avialble. What to do? https://github.com/tldr-pages/tldr/blob/4b06377bad69922dc63d93cf8e9979cb218652ca/pages/common/youtube-dl.md

**Comment by navarroaxel** [comment]
Yeah, we known but the project is not closed, Arch Linux is still upgrading the [youtube-dl](https://www.archlinux.org/packages/community/any/youtube-dl/) package in the official repository and the project itself has made 2 releases after the repository was closed by GitHub. So, I think they will move to another platform sooner. We should wait a little.

In the Arch Linux [PKGBUILD file](https://github.com/archlinux/svntogit-community/blob/packages/youtube-dl/trunk/PKGBUILD) you have the link to the website/source code, I won't paste that here :roll_eyes:

**Comment by sbrl** [comment]
Looks like youtube-dll is back: https://github.com/ytdl-org/youtube-dl
