### ISSUE TITLE
tldr CI failing due to changes with GitHub actions

### ISSUE THREAD

**Issue by sahilister** [tldr-pages/tldr#4963]
As seen [here](https://github.com/tldr-pages/tldr/pull/4962/checks?check_run_id=1417255927), [here](https://github.com/tldr-pages/tldr/pull/4961/checks?check_run_id=1416271461) and [here](https://github.com/tldr-pages/tldr/pull/4960/checks?check_run_id=1412592520), all new CI checks are failing.

The error logs  points towards issue due to `set-env` used during setting up pull request environment for CI. GitHub Actions has recently deprecated `set-env` due a [security vulnerability](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w). Mitigation steps/details are mentioned [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) on GitHub's blog post.

**Comment by einverne** [comment]
I haven't dug into the details. But it seems to work in my branch.
