### ISSUE TITLE
make system-wide install work better

### ISSUE THREAD

**Issue by slel** [tldr-pages/tldr#497]
See this comment by William Stein https://github.com/sagemathinc/smc/issues/346#issuecomment-168028201 after I suggested installing tldr-pages on SageMathCloud.

**Comment by waldyrious** [comment]
Potentially addressed by https://github.com/tldr-pages/tldr-node-client/pull/48

**Comment by igorshubovych** [comment]
Closing this for now, as it is really addressed by https://github.com/tldr-pages/tldr-node-client#48, it is also solved in other clients.
