### ISSUE TITLE
Add version number or date stamp to title page of PDF

### ISSUE THREAD

**Issue by older-pack** [tldr-pages/tldr#4970]
Help easily identify what version of the PDF you have.

**Comment by sbrl** [comment]
Great idea! I'm not sure where the script is that generates the PDF (or even where the PDF itself is located),, but if you can find it, would you like to open a PR to add this?

**Comment by older-pack** [comment]
Link to the PDF in #4969. 
I don't know where the script is.

> would you like to open a PR to add this?

I'd like to but I wouldn't know how :confused:

**Comment by older-pack** [comment]
[This](https://github.com/tldr-pages/tldr/tree/master/scripts/pdf) might be the PDF script?

**Comment by sbrl** [comment]
Open a PR to add this :D

**Comment by older-pack** [comment]
> Open a PR to add this :D

If that's to me I'm not a programmer. I don't know how to do a pull request nor how to do the script and then do the pull request. Sorry. :confused:

**Comment by sbrl** [comment]
No worries, @older-pack! What I meant to say was that I have already opened #4993 to add support for this. As soon as it's merged, as can close this issue :-)

**Comment by older-pack** [comment]
Sorry, my bad.

**Comment by sbrl** [comment]
Support added! :slightly_smiling_face:
