### ISSUE TITLE
tldr error

### ISSUE THREAD

**Issue by ifuchs** [tldr-pages/tldr#4972]
Installed on MacOS (14.6, bash 5)

tldr tar
â  Page not found. Updating cache...Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:208:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by ifuchs** [comment]
Reinstalled with pip and fixed the problem.

**Comment by sbrl** [comment]
Hey! Glad you fixed the problem. I'll close this issue for now, but if you experience any further issues please open  a new issue against the repository for the client you're using.

It looks like you're now using the Python client, so you'd want to open an issue over here if you run into trouble: https://github.com/tldr-pages/tldr-python-client
