### ISSUE TITLE
The clients wiki page does not exist

### ISSUE THREAD

**Issue by SmithJohnTaylor** [tldr-pages/tldr#4973]
The README files references https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients, which directs you to create a new page.

From the readme:

> There is also a comprehensive [list of clients in our Wiki](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients).

**Comment by sbrl** [comment]
Sorted via Gitter. The wiki page for the list of clients was merged into the README, IIRC :-)

(I can't figure out how to get a link out of Gitter, but if anyone else does please paste a link to the conversation here)

**Comment by SmithJohnTaylor** [comment]
https://gitter.im/tldr-pages/tldr?at=5fb6ca4e8d286f2076bcbf05
