### ISSUE TITLE
List the pdf version on the README.md

### ISSUE THREAD

**Issue by older-pack** [tldr-pages/tldr#4975]
I don't think the PDF version is actually listed on the main [README.md](https://github.com/tldr-pages/tldr/blob/master/README.md). It would be good to have it there.

**Comment by sbrl** [comment]
Hey, thanks for opening this! I suggest that we ensure it's auto-updating regularly over in #4969 first before updating the README.

**Comment by bl-ue** [comment]
@sbrl It seems to be auto updating now. https://github.com/tldr-pages/tldr-pages.github.io/blob/master/assets/tldr-book.pdf

**Comment by sbrl** [comment]
Now that the PDF version is auto-updating, I think we can close this issue. Since the PDF version will now always be up-to-date, there's no need to display what the latest version is in the README I don't think.

Feel free to comment though if you think otherwise and I'll reopen this issue.

**Comment by older-pack** [comment]
No, you misunderstood.
I was asking for the PDF version to be listed along with all the other versions on the[ README.md](https://github.com/tldr-pages/tldr/blob/master/README.md).
I didn't mention anything about PDF _version_ to be listed or updated.

**Comment by bl-ue** [comment]
Oh oops!  My fault.  I only understood we wanted it auto-updating :)

I'll take care of that now.

**Comment by bl-ue** [comment]
@older-pack if you have any particular way you're thinking it should be added, will you please do it?

**Comment by bl-ue** [comment]
>I'm not able to use git

Don't worry!  You don't need to use git&mdash;use can use the GitHub UI, which will handle the Git stuff for yout:
1. Click the little pencil icon on the README or click [here](https://github.com/tldr-pages/tldr/edit/master/README.md)
2. Make your changes
3. As the commit message, enter "README: add PDF version to clients list"
4. You can optionally add a longer description in the larger text box
5. Click "Propose changes"
6. Click "Create pull request"
7. Click "Create pull request" (on the next page)

However, if you don't really want to do it right now, I'd be happy to take care of it :)

>The PDF is useful for people who can't or don't want to install a package (especially when they've just come across the project and aren't quite sure about it).

Exactly 👍🏻

**Comment by older-pack** [comment]
Thanks for the step-by-step guide. That wasn't too hard after all. Hope it's ok. Feel free to change or edit or bin it...

**Comment by bl-ue** [comment]
You're welcome!  I left some comments on it.
