### ISSUE TITLE
Add collaborator: @sahilister

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#4994]
Hi, @sahilister! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#4962, #4954, #4511, #4348, #4335, and [many more](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3Asahilister+is%3Aclosed))!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by sbrl** [comment]
Gosh, you must have slipped through the net - that's a lot of PRs - thanks so much!

**Comment by sahilister** [comment]
Thanks @sbrl for the invite. Would be honored to be take more active role in the project.

**Comment by einverne** [comment]
Welcome~~

**Comment by sbrl** [comment]
Invite sent, @sahilister! Sorry it's so late. Welcome to tldr-pages :D
