### ISSUE TITLE
Add kb to the list of similar projects

### ISSUE THREAD

**Issue by sljedeer** [tldr-pages/tldr#5002]
Probably you should add kb to the list of similar projects!
https://github.com/gnebbia/kb (~2.5k stars).

**Comment by sbrl** [comment]
Hey, that looks like a cool project! It seems to have more of a focus on note taking and organising than documenting functionality / creating cheat sheets / etc, but that isn't necessarily a blocking issue. Let's wait to see what others think.

**Comment by bl-ue** [comment]
@sbrl I agree with that, but it _is_ similar, and "similar" doesn't mean "same" :)

**Comment by sljedeer** [comment]
Yeah, at the end it's in line with the other suggested alternatives, plus, having one more suggestion for other users it's always cool imho!

**Comment by sbrl** [comment]
Ok, sounds cool! Want to open a pull request, @sljedeer?

**Comment by sljedeer** [comment]
Ok!

**Comment by bl-ue** [comment]
@sljedeer https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/overview

**Comment by sljedeer** [comment]
@sbrl @bl-ue i should have done it now! Thanks for the references!
It just needs to be merged.
