### ISSUE TITLE
@navarroaxel 's name missing from MAINTAINERS.md

### ISSUE THREAD

**Issue by sahilister** [tldr-pages/tldr#5010]
@navarroaxel has been part of tldr-pages starting with #4291 and later added as Organization member with #4504. Their name needs to be added in [Maintainers List](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md).

**Comment by sbrl** [comment]
Oh, great point! We should totally do that. @navarroaxel, would you like to do the honours?
