### ISSUE TITLE
Rename: pages/{osx => macos}

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5013]
With macOS Big Sur, the major version of macOS has changed from 10 to 11.  Now the `osx` folder is wrong because it's macOS 11, not macOS X.

**Comment by bl-ue** [comment]
[`CLIENT-SPECIFICATION.md`](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md) needs to be updated.

**Comment by bl-ue** [comment]
Theses page need to be updated too:
```
pages/common/spatial.md
pages/osx/bless.md
pages/osx/pkgutil.md
pages/osx/afinfo.md
pages.es/osx/afinfo.md
pages.zh/osx/afinfo.md
```

**Comment by sbrl** [comment]
Hey there, @bl-ue! Thanks for bringing this up. Unfortunately, this is a difficult problem, as a platform rename will result in a breaking change for tldr clients. Updating all of the tldr clients out there is a big task that will take quite a long time. Furthermore, we'll need to figure out a way to do this in a non-breaking fashion, to avoid causing issues for clients during the transition period.

**Comment by bl-ue** [comment]
> all of the tldr clients out there

@sbrl Are there more clients then the [Node.js client](https://github.com/tldr-pages/tldr-node-client), the [Python](https://github.com/tldr-pages/tldr-python-client) client, and the [C client](https://github.com/tldr-pages/tldr-c-client)?

**Comment by sbrl** [comment]
Absolutely! Check out the list here: https://github.com/tldr-pages/tldr/#how-do-i-use-it

**Comment by bl-ue** [comment]
Wow, I can't believe I didn't notice that section.  Hm...we could just merge this issue into #4120, @sbrl?

**Comment by sbrl** [comment]
Ah, no worries!

Yeah, probably. It's a large and complex operation that requires lots of co-ordination. Somehow I don't think it's going to happen anytime soon, I'm afraid.

**Comment by bl-ue** [comment]
I might be able to coordinate it some time :)

**Comment by bl-ue** [comment]
@sbrl
> Furthermore, we'll need to figure out a way to do this in a non-breaking fashion, to avoid causing issues for clients during the transition period.

We could temporarily symlink `osx` -> `macos`.

**Comment by sbrl** [comment]
I believe symlinks are an issue. Check out #787, and also potentially #1966 (but that one is long and complicated).

**Comment by CleanMachine1** [comment]
I think we should close this.

**Comment by bl-ue** [comment]
Done :)
