### ISSUE TITLE
page request: dust

### ISSUE THREAD

**Issue by diohabara** [tldr-pages/tldr#5047]
I haven't seen anything in the current repo for `dust`. If it's the case, I'd like to add a page for it.

Here is the link to dust.
https://github.com/bootandy/dust

**Comment by bl-ue** [comment]
@diohabara Great idea! Add it!

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by bl-ue** [comment]
@diohabara I now use `dust` instead of `du` because of this!  thank you for adding it!! (a lot)
