### ISSUE TITLE
add collaborator: @bl-ue

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#5056]
Hi, @bl-ue! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#5006, #5007, #5008, #5011, #5015)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by bl-ue** [comment]
Hi @sbrl, thank you!  I'm afraid I really won't be able to do very for the project at all, because I'm recently quite busy, and next year I have a lot to do so I probably won't get a lot done. However, I can probably fit things in here and there, so

>Can we add you as a collaborator?

Sure!

**Comment by bl-ue** [comment]
@sbrl...I'd love to be part of tldr.  I'm waiting to get some stuff done while I have time... 😸

**Comment by bl-ue** [comment]
@navarroaxel @sbrl the week is almost over could you please add me??

**Comment by navarroaxel** [comment]
@bl-ue I think only the org owners can add you. I'll ask.

**Comment by sbrl** [comment]
Hey there, @bl-ue! I'll send the invite now. Great to have you onboard! :D

**Comment by sbrl** [comment]
Invite sent!

**Comment by sbrl** [comment]
When you've accepted it, would you like to open a PR to add yourself to the contributors list in MAINTAINERS.md, @bl-ue?

**Comment by bl-ue** [comment]
@sbrl Sure!  I'll open one later today.

**Comment by waldyrious** [comment]
Hey @bl-ue, I think you might like to join the [Gitter chat](https://gitter.im/tldr-pages/tldr), which is where we coordinate in a more informal manner and outside the scope of specific issues / PRs. Come join us! 🙂
