### ISSUE TITLE
Client option to display short options instead of long options

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5092]
I was just about to go through and convert all examples that use short options to long options (if available for each command), when I thought of a cool idea to add a option to all clients to display short options in examples if the user specifies, instead of long options.  In the markdown, we would need some new syntax to store short and long options, I was thinking something like this:
```markdown
- Description:

`cmd {[-l|--long-option]} {{param}}
```

And running `tldr`:

```console
$ tldr cmd
  ...

  cmd -l param

$ tldr cmd -s
  ...

  cmd --long-option param
```

One obviously useful application of this idea would be [`rg`](https://github.com/tldr-pages/tldr/blob/master/pages/common/rg.md).  It has `--no-ignore --hidden --binary` and a short form `-uuu`.  The syntax to store those in the markdown might be `{[-uuu|--no-ignore --hidden --binary]}`.

@tldr-pages What do you think?

**Comment by sbrl** [comment]
Hrm, an interesting thought, but I'm wary of adding additional complexities to custom syntax - especially in the syntax for a command. Generally the rule of thumb at the moment is to use short options on commands a user will be using a lot (e.g. `ls`), and long options for everything else. The `[c]reate` convention is also used in places too. Maybe that would be worth applying to the ripgrep/`rg` page.

**Comment by Managor** [comment]
Closing this in favor of #13556
