### ISSUE TITLE
Pages with bad "More information" link syntax

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5111]
There are some pages with bad "More information" links:

- [`jwt.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/jwt.md)
- [`carbon-now.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/carbon-now.md)
- [`topgrade.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/topgrade.md)

Why were these missed in #5043, #5046, and #5050?

**Comment by schneiderl** [comment]
Why are they bad?

**Comment by schneiderl** [comment]
They do not seem broken and the pages look like the GitHub page from the tool.

**Comment by bl-ue** [comment]
@schneiderl most of the pages have links like this:
```
More information: <...>.
```
But those are link this:
```
For more info: <...>.
```
or
```
More at <...>.
```
I'm not talking about the links themselves, just the syntax.

**Comment by schneiderl** [comment]
Oh, I understand now.
Would you tackle this?

**Comment by bl-ue** [comment]
Absolutely! I was just wondering why `tldr-lint` didn't catch this.  See `TLDR016` "Label for information link should be spelled exactly More information:" at [its README](https://github.com/tldr-pages/tldr-lint).

**Comment by sbrl** [comment]
I think it's a new feature that hasn't been enabled yet? @owenvoke?

**Comment by schneiderl** [comment]
**Off-topic (kind of) -**  I was quickly looking at the code to get this implemented and a question came to my mind: does tldr-lint only works with en pages?

**Comment by bl-ue** [comment]
@schneiderl it appears to: when I make bad changes to a file in a translation other than `en`, it throws the appropriate `TLDRXXX` errors, but I think I see what your getting at: "More information: " isn't going to appear in a Spanish page.

**Comment by owenvoke** [comment]
Yes, we aren't really able to parse other language pages. So we only parse the main `pages` directory.

Regarding the feature, it is currently enabled on v0.0.9 of `tldr-lint`, however it only checks certain formatting of the line. And doesn't check for completely different wording at the moment (just variations of `More info(rmation)`).

**Comment by schneiderl** [comment]
Then shall we enforce the wording "More Information"? 

If so, I would like to tackle this. I've never messed around with the linter but I would like to give it a try 😄.

**Comment by bl-ue** [comment]
@schneiderl definitely enforec "More information". It's what we do 99%+ of the time, it seems.

**Comment by owenvoke** [comment]
@schneiderl, I'd say yes. 👍🏻 Good luck!

**Comment by waldyrious** [comment]
> Then shall we enforce the wording "More Information"?

How will do you plan on doing it, though? We can't test any possible variations of the prefix, can we? An excessively broad matcher would catch false positives. Or would it be OK to force (in the main description section) any line ending with `<http...>` to start with "More information:"?

Here are all the variations I could find in the main (English) pages:

```console
$ rg -I -o '> ?(.+:) ?<http.+>\.?' -r '$1' | sort | uniq
Doc homepage:
For more information:
Home page:
More information:
Tutorial:
```

The culprits are:

- https://github.com/tldr-pages/tldr/blob/713f8f498de8e24f43be2297752173ddec956791/pages/common/valac.md#L3-L5

- https://github.com/tldr-pages/tldr/blob/713f8f498de8e24f43be2297752173ddec956791/pages/common/vala.md#L3-L5

- https://github.com/tldr-pages/tldr/blob/713f8f498de8e24f43be2297752173ddec956791/pages/common/jwt.md#L3-L5

- https://github.com/tldr-pages/tldr/blob/713f8f498de8e24f43be2297752173ddec956791/pages/common/virt-sparsify.md#L3-L5

I suppose we could remove the tutorial links from `vala.md` and `valac.md`, and then all the cases could indeed be fixed with the broad match as I proposed above.

**Comment by waldyrious** [comment]
(By the way, `jwt.md` needs a space after "HS256," in the list of encryption algorithms 😜)

**Comment by bl-ue** [comment]
@waldyrious, `git pull`, because with #5112 and #5120 I fixed some of those 😉

**Comment by bl-ue** [comment]
>How will do you plan on doing it, though? We can't test any possible variations of the prefix, can we? An excessively broad matcher would catch false positives. Or would it be OK to force (in the main description section) any line ending with <http...> to start with "More information:"?

@waldyrious we could just assert that the last line of the descripion MUST start with `More information:`. That way there would always be a link on each page, and we wouldn't have to remove the `Tutorial:` lines in the vala pages.

IMO that's the easiest and most stable way, aka the best way 😄

**Comment by waldyrious** [comment]
I honestly would prefer to have only a single link in the main description, to keep with tldr-pages' spirit of conciseness and visual simplicity, but I'm open to be convinced otherwise.

**Comment by owenvoke** [comment]
I'm not sure forcing a link on every page is a good idea, as a lot of tools don't really have proper docs or information pages (for example most of the old Windows tools).

**Comment by bl-ue** [comment]
>I'd agree with trying to have a single link per page.

👍 

>I'm not sure forcing a link on every page is a good idea, as a lot of tools don't really have proper docs or information pages

Just because there's no official link doesn't mean we can't add the _best_ link available?  For example, the Debian manpages that we seem to refer to aren't official. [`svn-changelist.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/svn-changelist.md), [`git-subtree.md`](https://github.com/tldr-pages/tldr/blob/master/pages/common/git-subtree.md)

**Comment by owenvoke** [comment]
True, I have nothing against adding links from non-official sources (I'm all for adding more links that are useful). I just feel like it might lead to adding links that aren't particularly useful just because that's the only thing available.

**Comment by bl-ue** [comment]
Couldn't the reviewers just recommend a better link?

**Comment by schneiderl** [comment]
I don't think I like forcing to have a link for every page.
In some cases, there is no interesting link to be put on the description. 
Also, in some cases, we might be just repeating ourselves (see #3041). 

I prefer @waldyrious solution: we only have maintain one link per command description. That being, we can check if the syntax is correct as described above.

**Comment by bl-ue** [comment]
You guys all think links should be optional? 👍 I was mainly suggesting it because I think it would make it easier to implement in tldr-lint :)

Perhaps we could check if the last line contains `<http` and then insist it begin with "More information: " ?

**Comment by sbrl** [comment]
Adding links is nice, but it's not suitable for all commands. Take `arch` or `nproc`  for example. I think this is best left out of the linter.

_If_ a link is present, then it should be in the form `> More Information: <URL_HERE>.`, which is what we agreed on.

**Comment by waldyrious** [comment]
> _If_ a link is present, then it should be in the form `> More Information: <URL_HERE>.`, which is what we agreed on.

Just a nit: The "I" in "information" is not to be capitalized.

**Comment by sbrl** [comment]
Oh yeah lol, that's right! Comment updated.

**Comment by marchersimon** [comment]
This issue has already been solved mostly by the `set-more-info-link.py` script. All pages and translations are now completely standardized.
