### ISSUE TITLE
Detecting dead "more information" links

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#5116]
I was inspired by #5111, and I developed another of my bash one-liners to detect broken more information links in tldr pages. Broken links are defined as having a HTTP status code lower than 200, or greater than or equal to 400. Connection issues (e.g. DNS resolution failures, TLS certificate misconfigurations, etc) are also considered dead links

Here's the one-liner:

```bash
find . -type f -iname '*.md' -print0 | xargs -0 cat | awk '/> More information/ { match($0, /<(.*)>/, arr); print(arr[1]); }' | sort | uniq | shuf | xargs -n1 -I{} bash -c 'url="{}"; code="$(curl --user-agent "curl; bash; xargs; tldr-pages-bad-url-checker (+https://github.com/tldr-pages/tldr; implemented by @sbrl)" -sSL -o /dev/null -w "%{http_code}" --fail -I "${url}")"; echo "${code} ${url}" >&2; if [[ "${code}" -lt 200 ]] || [[ "${code}" -ge 400 ]]; then echo "${url}"; fi' >/tmp/bad-urls.txt;
```

`cd` to the root of a previously-cloned version of the tldr-pages repo, and then run the above command. Replace `/tmp/bad-urls.txt` with the path to the file you'd like to populate with the dead links. Sadly it doesn't tell you which page they are on, but this could be rectified with some refactoring.

Requirements:

 - xargs
 - curl
 - find
 - awk
 - bash

Note that while `xargs` is used to (indirectly) drive curl here, I haven't added a `-P "$(nproc)"` because otherwise you'll end up hitting GitHub's rate limit very quickly.

Anyway, here's the current list of dead links I've found with this:

```
https://harding.motd.ca/autossh
https://nixos.org/releases/nix/latest/manual/#sec-nix-collect-garbage
http://www.mysqlfanboy.com/mytop-3
https://nixos.org/releases/nix/latest/manual#sec-nix-build
https://taskwarrior.org/docs/timewarrior
https://docs.microsoft.com/windows-server/administration/windows-commands/reg-flags
https://clementsam.tech/glab/
https://flameshot.js.org
https://httpie.org
https://deluge-torrent.org
https://deemix.app
https://mailutils.org/manual/html_chapter/Programs.html#frm-and-from
https://docs.blender.org/manual/en/latest/render/workflows/command_line.html
https://www.infradead.org/openconnect/manual.html
https://www.clementine-player.org
https://crates.io/
https://jonls.dk/redshift
http://postfix.org
https://help.bitwarden.com/article/cli/
http://supervisord.org
https://redis.io
https://redis.io/topics/rediscli
https://sqlmap.org
```

It seems as though 2 of these are in fact not dead according to Firefox, but it would appear that they have HTTPS misconfigurations that caused curl to fail (i.e. they don't send the intermediate certificate along with the actual certificate). Specifically:

```
https://mailutils.org/manual/html_chapter/Programs.html#frm-and-from
https://deluge-torrent.org/
```

...I've emailed the webmaster for mailutils.org about this, but I can't find a suitable contact address for `deluge-torrent.org`.

The other URLs are a mix of 404s, no route to host, other more serious HTTPS misconfigurations, and DNS resolution errors.

We wouldn't want to run this as a GitHub action as random build failures would be annoying, but I just thought the exercise was interesting / useful to run from time to time :-)

The final list (should be actually dead urls):

```
https://harding.motd.ca/autossh
https://nixos.org/releases/nix/latest/manual/#sec-nix-collect-garbage
http://www.mysqlfanboy.com/mytop-3
https://nixos.org/releases/nix/latest/manual#sec-nix-build
https://taskwarrior.org/docs/timewarrior
https://docs.microsoft.com/windows-server/administration/windows-commands/reg-flags
https://clementsam.tech/glab/
https://flameshot.js.org
https://deluge-torrent.org
https://deemix.app
https://docs.blender.org/manual/en/latest/render/workflows/command_line.html
https://www.infradead.org/openconnect/manual.html
https://jonls.dk/redshift
http://postfix.org
https://sqlmap.org
```

In particular, http://postfix.org/ should be http://www.postfix.org/

**Comment by bl-ue** [comment]
Really cool @sbrl.  I though of this idea just today!

https://mailutils.org/manual/html_chapter/Programs.html#frm-and-from &mdash; @sahilister found this just [27 days ago](https://github.com/tldr-pages/tldr/pull/5011#discussion_r536779415)!

**Comment by bl-ue** [comment]
A lot of those links are false actually, because you have curl's `-I` flag, which sets the method to `HEAD`, and that causes 404s/500s on sites like https://crates.io/ and https://redis.io.

**Comment by sbrl** [comment]
Oh really? That's very unusual. According to the HTTP spec HEAD should return _exactly_ the same HTTP headers as a `GET`, just without the body IIRC.

We can remove links that actually work from the list.

**Comment by sbrl** [comment]
Updated my comment with a revised list

**Comment by bl-ue** [comment]
I see that.  Looks good.

**Comment by bl-ue** [comment]
You say
> Broken links are defined as having a HTTP status code lower than 200, or greater than or equal to 400
```
https://nixos.org/releases/nix/latest/manual/#sec-nix-collect-garbage
https://nixos.org/releases/nix/latest/manual#sec-nix-build
https://docs.microsoft.com/windows-server/administration/windows-commands/reg-flags
```

**Comment by schneiderl** [comment]
That is very cool 👍

**Comment by bl-ue** [comment]
We should add this to `tldr-lint` 🤔

**Comment by sbrl** [comment]
> But these have 3xx (redirect) status codes:

That's odd. I get an error when I load those links:

![Selection_2021-01-16_16:23:31_001_58ccf2c](https://user-images.githubusercontent.com/9929737/104817132-3ca6f980-5817-11eb-8f30-b8656b8f8b25.png)

> That is very cool :+1:

Thanks!

> We should add this to `tldr-lint` :thinking:

That'd be cool, but also annoying when tldr-lint randomly fails because of a link that just went dead. It's best I think if its run periodically.

**Comment by bl-ue** [comment]
>That's odd. I get an error when I load those links:

So do I...I don't know what happened! 🤷

**Comment by bl-ue** [comment]
>That'd be cool, but also annoying when tldr-lint randomly fails because of a link that just went dead. It's best I think if its run periodically.

Just for reference (because I just discovered this): https://github.com/tldr-pages/tldr/pull/2684#pullrequestreview-195338362

**Comment by vladimyr** [comment]
> Here's the one-liner:
> 
> ```shell
> find . -type f -iname '*.md' -print0 | xargs -0 cat | awk '/> More information/ { match($0, /<(.*)>/, arr); print(arr[1]); }' | sort | uniq | shuf | xargs -n1 -I{} bash -c 'url="{}"; code="$(curl --user-agent "curl; bash; xargs; tldr-pages-bad-url-checker (+https://github.com/tldr-pages/tldr; implemented by @sbrl)" -sSL -o /dev/null -w "%{http_code}" --fail -I "${url}")"; echo "${code} ${url}" >&2; if [[ "${code}" -lt 200 ]] || [[ "${code}" -ge 400 ]]; then echo "${url}"; fi' >/tmp/bad-urls.txt;
> ```

@sbrl That's some lovely _one-liner_ :heart: I especially like your user agent :100:

**Comment by vladimyr** [comment]
@sbrl https://gist.github.com/vladimyr/d7bb314b14a59ca5fbefda3498fac81a :wink:

**Comment by vladimyr** [comment]
> A lot of those links are false actually, because you have curl's `-I` flag, which sets the method to `HEAD`, and that causes 404s/500s on sites like [crates.io](https://crates.io/) and [redis.io](https://redis.io).

I don't know for Redis but crates.io won't let you scrape their content. You'll get the same response even with regular 'GET' because they maintain UA allowlist on their end.

**Comment by sbrl** [comment]
@vladimyr Nice one! Don't forget to sleep though in between each call. Many of the links are GitHub, and you'll get rate-limited if you hit GitHub too fast. Alternatively you could group the URLs by domain and do each group of urls in parallel to go real quick, but to do that I'd probably write it in Node.js instead with [phin](https://www.npmjs.com/package/phin) with async/await.

**Comment by bl-ue** [comment]
>I don't know for Redis but crates.io won't let you scrape their content. You'll get the same response even with regular GET because they maintain UA allowlist on their end.

Yeah, @sbrl it would probably be better to use a standard UA like
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```
thought yours is nice, it wouldn't work for some sites like @vladimyr mentioned.

**Comment by vladimyr** [comment]
> @vladimyr Nice one! Don't forget to sleep though in between each call. Many of the links are GitHub, and you'll get rate-limited if you hit GitHub too fast.

I like living on the edge 😂

> Alternatively you could group the URLs by domain and do each group of urls in parallel to go real quick, but to do that I'd probably write it in Node.js instead with [phin](https://www.npmjs.com/package/phin) with async/await.

I was pretty sure that I'm aware of all node http clients but TIL about phin. Thank you!
Yeah, there are many ways how to make it faster, I just wanted to unroll it to proper script as a starting point.

> Edit: Also maybe a HEAD request would reduce remote load too?

Am I not doing that already? First HEAD and then fallback to GET on receiving 405 (method not allowed).

**Comment by sbrl** [comment]
> Yeah, @sbrl it would probably be better to use a standard UA like

Good idea... but that feels a bit dishonest, in declaring that you're someone you're not? It doesn't quite sit right with me.

**Comment by sbrl** [comment]
Added the Bash one-liner to the wiki here: <https://github.com/tldr-pages/tldr/wiki/Useful-scripts-and-programs#detect-broken-more-information-links>

So closing this issue for now, but we can continue the discussion if needed here.
