### ISSUE TITLE
add collaborator: @MasterOdin

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5122]
Hi, @MasterOdin! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#2141, #2278, #2422, #2451, and #5063)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by MasterOdin** [comment]
Sure

**Comment by sbrl** [comment]
Invite sent, @MasterOdin :D

**Comment by MasterOdin** [comment]
Accepted

**Comment by bl-ue** [comment]
:tada:
<img width="294" alt="Screen Shot 2021-01-09 at 10 10 31 AM" src="https://user-images.githubusercontent.com/54780737/104095127-24f1d300-5263-11eb-982c-b40bef54d6db.png">

**Comment by bl-ue** [comment]
@MasterOdin would you like to open a PR adding yourself to [MAINTAINERS.md](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md)?
