### ISSUE TITLE
[Bug] Live demo not working

### ISSUE THREAD

**Issue by VincentTam** [tldr-pages/tldr#5194]
# Steps
1. I opened the official page https://tldr.sh/
2. I clicked on the link "live demo".
3. A new page popped up, saying that the service wasn't available.
# Screenshot
![out](https://user-images.githubusercontent.com/5748535/105997697-31bc5680-60ac-11eb-929d-307eb7222324.gif)
# Technical info
Version:71.0.3770.198
Opera is up to date
Update stream:Stable
System:Ubuntu 20.04.1 LTS (x86_64; ubuntu:GNOME)

**Comment by bl-ue** [comment]
This is likely because @ostera is not maintaining that site anymore 🤷🏻&mdash;@ostera, could you possible please transfer this issue to [ostera/tldr.jsx](https://github.com/ostera/tldr.jsx)?

**Comment by schneiderl** [comment]
Apparently, this is now fixed. https://tldr.ostera.io/ is up and running again.

**Comment by schneiderl** [comment]
I believe this issue can be closed as it is not happening anymore. If the issue comes back, please reopen this incident.

**Comment by ostera** [comment]
Oops! I had a problem with my DNS records. Should be up now!

**Comment by sbrl** [comment]
Thanks, @ostera!

(do you think you could look into #5184 too? thanks :D)

**Comment by VincentTam** [comment]
Thx @ostera for fixing.  It's now working again :v:
