### ISSUE TITLE
Page request: `pueue`

### ISSUE THREAD

**Issue by jakevossen5** [tldr-pages/tldr#5195]
Would love to see a page for [pueue](https://github.com/Nukesor/pueue). I would document it, but I am fairly new to the program myself and am probably not qualified. They have a decent help page already that can probably be pretty easily translated: https://github.com/Nukesor/pueue#how-to-use-it

**Comment by sbrl** [comment]
Thanks for requesting this page!

Pages are best created by people who understand the command they are about, so I'd suggest we wait for someone more qualified to come along and write the page. This may take a considerably long period of time though, so it's possible that once you're more familiar with the command you could attempt to write a page yourself.

Pages don't have to start fully fleshed out - you could always start with contributing a basic page with 2-3 examples, and then when you gain more experience with the command submit a PR to improve it.
