### ISSUE TITLE
Page request: virt-manager

### ISSUE THREAD

**Issue by ThisNekoGuy** [tldr-pages/tldr#5197]
[https://virt-manager.org/documentation/](https://virt-manager.org/documentation/)

Honestly, I don't understand how this virtual machine works at all, which is kind of why I was hoping there was a TLDR for it :/
The website barely explains anything about it at all:
![Screenshot_2021-01-28 Virtual Machine Manager Documentation](https://user-images.githubusercontent.com/28468662/106075220-1df10e80-6105-11eb-9a14-5c9614af184c.png)

And when people recommend it to me over VirtualBox for less-glitchy Windows 10 VMs, it doesn't really help that their website does a terrible job explaining how it works considering that it operates nothing like any traditional VM I've ever seen.

**Comment by sbrl** [comment]
Looks like `virt-manager` is a GUI, rather than a CLI @ThisNekoGuy. Despite this, invoking `virt-manager --help` does yield something useful:

```
$ virt-manager --help
usage: virt-manager [options]

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -c URI, --connect URI
                        Connect to hypervisor at URI
  --debug               Print debug output to stdout (implies --no-fork)
  --no-fork             Don't fork into background on startup
  --show-domain-creator
                        Show 'New VM' wizard
  --show-domain-editor NAME|ID|UUID
                        Show domain details window
  --show-domain-performance NAME|ID|UUID
                        Show domain performance window
  --show-domain-console NAME|ID|UUID
                        Show domain graphical console window
  --show-domain-delete NAME|ID|UUID
                        Show domain delete window
  --show-host-summary   Show connection details window

Also accepts standard GTK arguments like --g-fatal-warnings
```

...though I suspect that you'd get on best just launching `virt-manager` like this:

```
virt-manager
```

...and then using the GUI. Even so, a tldr page for `virt-manager` would be a welcome addition!
