### ISSUE TITLE
donnemartin/saws

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5212]
I found this: https://github.com/donnemartin/saws/blob/master/saws/data/SOURCES.txt, and I fearfully realized that there are about 5293 subcommands??

Can anyone, including @donnemartin, help me to understand what this means?  Are those all AWS command, and if so, are they official?
**Do we need to document them?**
Could we generate examples?

**Comment by sbrl** [comment]
Oof. Hrm, that would be an enormous undertaking. I think it's a case of documenting those that are used most often. I don't think we need to explicitly open an issue about it.

Not using AWS myself, I'm not much help here.

**Comment by bl-ue** [comment]
I agree.  It wouldn't be very useful to 5k commands amidst many much smaller groups...Also that repo gets updated frequently, with more new commands!

**Comment by bl-ue** [comment]
The commands over at https://docs.aws.amazon.com/cli/latest/index.html look more reasonable...I will open a Let's document issue for them if you think so.

**Comment by bl-ue** [comment]
I'll close this for right now.  If we want to take up the aws commands, we can do this in another issue.
