### ISSUE TITLE
Add org member: @bl-ue

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#5219]
Hi, @bl-ue! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks (#5140, #5150, #5152, #5163, #5200).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by bl-ue** [comment]
@navarroaxel I'd love to!  I'd sure appreciate having write access to the other repositories :)

>Additionally, consider subscribing to the notifications from the various repositories under the tldr-pages organization.

I've been watching all of our repos for some time now.

**Comment by sbrl** [comment]
Invite sent, @bl-ue!

> I've been watching all of our repos for some time now.

Great! That is a preset message from our [community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document :slightly_smiling_face:

**Comment by schneiderl** [comment]
I thought @bl-ue already was an org member haha. 

Welcome!

**Comment by bl-ue** [comment]
@sbrl sure!
