### ISSUE TITLE
Add organization owner: @schneiderl

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5224]
Hi, @schneiderl! You've been an active tldr-pages organization member for over 6 months (actually 12 months :smile:).
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by schneiderl** [comment]
Oh, I'm blushing 😊.

I'm very glad about this invite. And I sure do accept it. 
If everyone agrees I'll open the PR updating MAINTAINERS.md.

**Comment by sbrl** [comment]
Role changed, @schneiderl!
