### ISSUE TITLE
netstat: duplicate example for routing table

### ISSUE THREAD

**Issue by dkasak** [tldr-pages/tldr#5251]
It seems that the pages for `netstat` have a duplicated example for printing the routing table, with the order of the flags switched and a slightly different description.

```
  - List routes and do not resolve IP to hostname:
    netstat -rn
```

vs

```
  - Print the routing table:
    netstat -nr
```

**Comment by bl-ue** [comment]
I believe you're correct @dkasak! https://github.com/tldr-pages/tldr/blob/master/pages/linux/netstat.md

Would you like to open a PR to remove one of the examples?

**Comment by dkasak** [comment]
Sorry, I missed the email for this, but thanks for handling it!

**Comment by sbrl** [comment]
No worries, @dkasak :slightly_smiling_face:
