### ISSUE TITLE
New issue label `waiting for linter update`?

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5257]
We occasionally have PRs that can't be merged because they're waiting for a linter update, such as #5205 and #5088, atm.

If we decide to go forward with this, how about some eye-catching new color like: `#9FFC5A`?

**Comment by bl-ue** [comment]
It's not as if we'll have a PR that needs a linter update every week or so, but we have many such labels like that, e.g. "gci" or "invalid".

**Comment by bl-ue** [comment]
The referenced PR's also get poked at by the stale bot every 2 weeks which is annoying because we're not just ignoring them.  I'd like to (if it's possible) configure the stale CI task to ignore issues/PR's with this label.

**Comment by bl-ue** [comment]
I'll update `stale.yml` as soon as the okay is given:
https://github.com/tldr-pages/tldr/blob/0155fb60babf4f1016647e33161c750cfa2b3c47/.github/workflows/stale.yml#L25

**Comment by navarroaxel** [comment]
Maybe we can make more generic label like `blocked`, because we have one PR waiting for the decision in #5036.

**Comment by bl-ue** [comment]
I think it's good for the stale CI to remind of ones like those because there's nothing actually stopping us from taking care of them other than our interest/availability.

**Comment by sbrl** [comment]
This seems too specific for a single purpose. As @ waldyrious suggests on Gitter <https://gitter.im/tldr-pages/tldr?at=6044d7e7d74bbe49e0db5846>, a generic solution would be better.
