### ISSUE TITLE
New web client

### ISSUE THREAD

**Issue by finzzz** [tldr-pages/tldr#5287]
I have made simple web client for tldr-pages, it does not use any analytics. Here is the site, <https://tldr.finzzz.net> and also the source code can be found at <https://git.finzzz.net/tldr/>

**Comment by bl-ue** [comment]
@finzzz cool!  Would you like to open a PR to [add it](https://github.com/tldr-pages/tldr/edit/master/README.md) to the README?  You can also add to the [tldr pages clients wiki page](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients).

**Comment by bl-ue** [comment]
Hmmm, I can't get to your Git repo @ https://git.finzzz.net/tldr:
```
403 Forbidden
```

**Comment by bl-ue** [comment]
@finzzz also, `code` in the example/page descriptions doesn't render well:

<img width="205" alt="Screen Shot 2021-02-20 at 7 59 24 AM" src="https://user-images.githubusercontent.com/54780737/108596272-f1ba5d80-7351-11eb-8072-e4e51e2ccdcd.png">

e.g.
```markdown
> This is some `code`.
```

**Comment by finzzz** [comment]
> Hmmm, I can't get to your Git repo @ https://git.finzzz.net/tldr:
> 
> ```
> 403 Forbidden
> ```
I forgot to add slash at the end. It should be <https://git.finzzz.net/tldr/>

**Comment by finzzz** [comment]
> @finzzz also, `code` in the example/page descriptions doesn't render well:
> 
> <img alt="Screen Shot 2021-02-20 at 7 59 24 AM" width="205" src="https://user-images.githubusercontent.com/54780737/108596272-f1ba5d80-7351-11eb-8072-e4e51e2ccdcd.png">
> 
> i.e.
> 
> ```gfm
> > CLI interface for interacting with `etcd`, a highly-available key-value pair store.
> ```

Uh, I didn't notice that, I'll look into that

**Comment by finzzz** [comment]
Fixed that!

**Comment by sbrl** [comment]
Neat client, @finzzz! Great job. Have you considered implementing the [page resolution algorithm](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#page-resolution)? It might make it more convenient - that way you don't  have to guess which platform it's part of.

**Comment by bl-ue** [comment]
Hmm, @finzzz — https://git.finzzz.net/tldr/ isn't working anymore.  It says "git.finzzz.net’s server IP address could not be found." 🤔

**Comment by finzzz** [comment]
Sorry, it's moved to tldr.finzzz.net
