### ISSUE TITLE
page request: [, [[, (, $, {

### ISSUE THREAD

**Issue by willsheppard** [tldr-pages/tldr#5309]
Usage of brackets in logical expressions in Bash can be challenging. The following all have distinct meanings, sometimes with subtle differences, and they are not necessarily intuitive or easy to remember.

For beginners, even the names are hard to pin down, with people mistakenly using the same word (brackets/braces/parentheses) for all the different types:

* `[` - (square) bracket
* `]`
* `[[`
* `]]`
* `(` - (round) parenthesis
* `)`
* `$` - ?
* `{` - (curly) braces
* `}`

We could start with `[` (and `]`) being added. A google search for "bash logic" turns up a lot of info about how to use these correctly.

**Comment by bl-ue** [comment]
@willsheppard interesting.  We already have a PR adding `[`: #5205.

I think this is a good idea, but tldr-pages may not be the place for it.  tldr-pages is only for _commands_, but all of those tokens (with the exception of `[`, #5205) are shell builtin syntax, not commands.  To demonstrate:

In `zsh`
```console
$ [
[: ']' expected
$ {
cursh> ^C
$ (
subsh> ^C
$ ((
math> ^C
$ [[
cond> ^C
$ $(
cmdsubst> ^C
$
```

In `bash`
```console
$ [
bash: [: missing `]'
$ [[
> ^C
$ (
> ^C
$ $(
> ^C
$ {
> ^C
$
```

**Comment by bl-ue** [comment]
As a matter of fact, `()[]{}$%` are all valid characters for file names on all three major platforms, so technically it's certainly possible.

**Comment by bl-ue** [comment]
I really actually like this idea becuse though as I mentioned earlier they aren't really commands, we _could_ fit them in and have them conform exactly to our style.  I agree with you @willsheppard that there is a lot to learn about them and tldr-pages would do shell uses immense good by summing it up here.

If we go forward, we should also add `%` because it's okay for file names on Windows, an there are many nifty tricks that can be done with it, such as character replacement, substrings, `%~dp0` (for current directory - **d**rive + **p**ath), `%~nx0` (for the name of the current batch script - **n**ame of e**x**ecutable), etc.

**Comment by sbrl** [comment]
Interesting idea! if we did add them, we'd have to be careful that any examples conform to as many different shells as possible, as people use sh, bash, zsh, fish, etc. So unsure as to how that would be handled.

**Comment by bl-ue** [comment]
If you don't mind @willsheppard, I'd like to tackle this.  @sbrl shall we try it?

**Comment by bl-ue** [comment]
@sbrl we could just demo the feature that are common first, then, if there happens to be more room, add shell-specific examples saying `- ... (bash only):`, `- ... (zsh only):`, etc.

**Comment by sbrl** [comment]
Go ahead, @bl-ue! Shell commands are always difficult to document, but we can give this a go for sure.

**Comment by wiwa** [comment]
Could I add a vote for also including `<`? The first result for googling "bash less than meaning" is pretty much "just read the manual".

**Comment by bl-ue** [comment]
Hmm...I don't thing we could do that, because `<` is in the list of characters that aren't valid to be in Window file names: `\ / : * ? " < > |` 😖

**Comment by Managor** [comment]
We now have pages for several of these
https://github.com/tldr-pages/tldr/pull/12091
https://github.com/tldr-pages/tldr/pull/13846
https://github.com/tldr-pages/tldr/pull/10572
https://github.com/tldr-pages/tldr/pull/12341
https://github.com/tldr-pages/tldr/pull/13904
https://github.com/tldr-pages/tldr/pull/7530

**Comment by Managor** [comment]
Closing this in favor of https://github.com/tldr-pages/tldr/issues/10584
