### ISSUE TITLE
Bad linebreak in `ls` page

### ISSUE THREAD

**Issue by mortenfyhn** [tldr-pages/tldr#5312]
Hi all! I'm a big fan of this project. Found a small error:

The slash in one of the `ls` examples creates an unwanted linebreak in the output:

![tldr-ls](https://user-images.githubusercontent.com/6639836/109299456-6b13ed80-7835-11eb-98db-a5ff60c9afa1.png)

---

I could probably try to make a fix, I just haven't taken the time to fix/test yet.

**Comment by bl-ue** [comment]
What version of `tldr` are you using?  You can check by running `tldr --version` (or `tldr -V`).

**Comment by mortenfyhn** [comment]
`0.2.3` on Ubuntu. Very old?

**Comment by bl-ue** [comment]
How did you install it?  It probably is old, because I recall that issue happening only on older clients that didn't support backticks (\`) in the example descriptions.

**Comment by bl-ue** [comment]
[This](https://github.com/tldr-pages/tldr/blame/a57cc14783160e77e20ddfd9f04dcabdb902e8d9/pages/common/ls.md#L13) is the line question that's causing that output.

**Comment by mortenfyhn** [comment]
Aha! I got it through apt on 18.04, so I might be far behind. I didn't realize it could be a problem with the client.

**Comment by bl-ue** [comment]
Yes, unfortunately, this is constantly an issue.  `tldr` on apt is far behind the [latest version, v0.9.0](https://github.com/psibi/tldr-hs/releases/tag/v0.9.0).

**Comment by bl-ue** [comment]
Some solutions:
- :star: You could use the [Node.js client](https://github.com/tldr-pages/tldr-node-client): `npm install --global tldr`
- You could use the [Python client](https://github.com/tldr-pages/tldr-python-client): `sudo apt install tldr-py`

**Comment by mortenfyhn** [comment]
I understand. Trying manual install of tldr-hs no, and it works beautifully! Thanks again for the extremely swift feedback.

**Comment by bl-ue** [comment]
You're welcome! 😊   I just happened to be at GH when I noticed a new notification so I went to take care of it, and since I've _very_ recently dealt with a [similar issue](https://github.com/tldr-pages/tldr/pull/5272), I knew what to do right away.
