### ISSUE TITLE
page request: xcursorgen

### ISSUE THREAD

**Issue by yutyo** [tldr-pages/tldr#5322]
It would be very useful to write possible command variations that can be done by using `xcursorgen`, as its a very capable tool for cursor generation while its [man page](https://linux.die.net/man/1/xcursorgen) is not helping much. I remember searching the entire web to learn how to use it properly for weeks in the past.

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by marchersimon** [comment]
I found <https://wiki.archlinux.org/index.php/Xcursorgen> and <http://manpages.ubuntu.com/manpages/trusty/man1/xcursorgen.1.html>, which both seem very useful. However, the command is mostly about the configuration file you pass, so I'm not really sure how to document it.
