### ISSUE TITLE
Missing: SometypeMono Medium-Small-Caps

### ISSUE THREAD

**Issue by yutyo** [tldr-pages/tldr#5324]
The medium-small-caps variation of SometypeMono is not put in images directory therefore banner files in svg don't display properly.
![image](https://user-images.githubusercontent.com/40173707/109459237-79e5e480-7a6f-11eb-9208-534bc6a17afc.png)

**Comment by bl-ue** [comment]
Hmm...is this something you can fix, @Yutyo?

**Comment by Yutyo** [comment]
> Hmm...is this something you can fix, @Yutyo?

I have made some tweaks in: https://github.com/tldr-pages/tldr/pull/5329
