### ISSUE TITLE
add collaborator: @Yutyo

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5345]
Hi, @Yutyo! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#5341, #5336, #5334, #5333, #5332, and a lot more)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by Yutyo** [comment]
Sure!

**Comment by sbrl** [comment]
Ok, sending invite!

**Comment by bl-ue** [comment]
@Yutyo would you like to open a PR adding yourself to [`MAINTAINERS.md`](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md)?

**Comment by Yutyo** [comment]
> @Yutyo would you like to open a PR adding yourself to [`MAINTAINERS.md`](https://github.com/tldr-pages/tldr/blob/master/MAINTAINERS.md)?

Sure.

**Comment by Yutyo** [comment]
https://github.com/tldr-pages/tldr/pull/5352
