### ISSUE TITLE
idea: creating our own license

### ISSUE THREAD

**Issue by Yutyo** [tldr-pages/tldr#5348]
I think its necessary to make a custom license which will cover both the assets and scripts. That way we can identify both at a single short license.

**Comment by bl-ue** [comment]
Interesting. 👍🏻  We'll see what others have to say.  This will likely take a while, though.

**Comment by Yutyo** [comment]
> Interesting. 👍🏻 We'll see what others have to say. This will likely take a while, though.

I think we can make a license as short as possible while also exactly satisfying free software licensing criteria and call it a "tldr-license", cuz this is a very short license covering everything that others do in tons of complicated lines of words.

**Comment by bl-ue** [comment]
I certainly agree, however, there must be "tons of complicated lines of words" words for a reason.  Anyway, you and I are new members to the team so changes like this definitely need to have input from the more seasoned maintainers, @waldyrious, @sbrl, and @zlatanvasovic in particular.

**Comment by bl-ue** [comment]
Related: https://github.com/tldr-pages/tldr/pull/3687

**Comment by sbrl** [comment]
I'm really not sure that creating a custom licence is a good idea, @Yutyo. Existing licences are well-tested and written by legal experts. I would say it's preferable to use a combination of existing licences than to write our own.

In addition, to make it easy for others to integrate with our content, pre-existing well known licences are preferable to reduce cognitive load.

**Comment by bl-ue** [comment]
I agree those points.  I'll close this issue, for now.
