### ISSUE TITLE
Removing pages.pt_PT

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5370]
I would like to propose to merge `pages.pt_PT` into `pages.pt_BR` and the remove `pages.pt_PT`, and then rename `pages.pt_BR` → `pages.pt` (maybe not rename it though, I'm not sure what effect that might have on clients 🤔).

My reasoning is as follows:

- Notice the difference of `common/xkill.md`, for example:
  ```diff
   > Termina o cliente associado a um elemento gráfico.
   > Utilizado para forçar a terminação de processos que não respondem ou não apresentam botão "fechar".
 
  -- Ativar um cursor para fechar uma janela com o clique do botão esquerdo do rato (pressionar qualquer outro botão para 
  cancelar):
  +- Ativar um cursor para fechar uma janela com o clique do botão esquerdo do mouse (pressionar qualquer outro botão 
  para cancelar):
 
   `xkill`
  ```

- In `touch.md`, for example, every line is different between the two translations, but the only different is that `pt_PT` uses the noun `ficheiro` while `pt_BR` uses `arquivo`.  (`file` vs. `archive`?)

- Besides those seemingly minor differences (which may just be wording usages on the part of the translator, not even necessarily vocabulary differences between the two dialects), there are **151** `pt_BR` pages and **9** `pt_PT` pages.

- There are other such dialectic differences with other languages, e.g. American English vs. British English, but we don't have a `pages.en_US` and `pages.en_GB`.

**Comment by navarroaxel** [comment]
The main difference between Spanish from Spain or LatAm is `fichero` and `archivo`, but I remember to read a comment from @schneiderl saying the `pt_PT` is really different from `pt_BR`.

**Comment by bl-ue** [comment]
Likely #3540.  My only issue though, is that there's only 9 pages for `pt_PT`, and there's no way all 3.8k (and growing) pages are going to be translated into both!

**Comment by schneiderl** [comment]
Hmmm, nice thoughts on this. 

I would say that I, as a `pt_br` native speaker, in the current state of the projects (with way more pages translated to `pt_br`) would not mind to occasionally come across a `pt_pt` page.
I'm not sure I wouldn't mind if that was the other way around, though.

As @navarroaxel mentioned, the two are very different from each other and it might be really confusing if you think you're reading something translated to your language but in reality, it is not your language.

I do understand the argument that there are only 9 pages in `pt_pt` but if we decide to merge these folders and start accepting translations for `pt_pt` and `pt_br` on the same folder it would be impossible to separate them in the future

I'm not a fan of this merge.

**Comment by bl-ue** [comment]
Those are very compelling arguments.  Obviously, this question isn't that important, so I'll close it now, without waiting for others' input.

Thank you @schneiderl!

**Comment by waldyrious** [comment]
As a pt-PT speaker, let me add for future reference that as @mebeim said, there are lots of terminology differences, especially in the tech world (`ficheiro` vs. `arquivo`, `rato` vs. `mouse`, etc.). So not only merging the two variants would be a lossy operation, as @schneiderl rightly points out, but it would also actively make things harder/confusing for speakers of either variant.

I would take this opportunity, however, to suggest that a fallback mechanism for similar languages be added to the client spec as an optional feature for tldr-pages clients. So that a pt-PT user would get the pt-BR page as a fallback if it exists, rather than go straight to the English page.

**Comment by sbrl** [comment]
In theory @waldyrious if you had `LANG` set to `pt_PT` and `LANGUAGE` set to `pt_PT:pt_BR`, it should try `pt_PT` first, then `pt_BR`, and then finally `en` as a fallback according to the [language resolution of the client spec](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#language)
