### ISSUE TITLE
Allow control over example formatting

### ISSUE THREAD

**Issue by bobfoster** [tldr-pages/tldr#539]
tldr on Mac OS X: The example commands are colored with a black background and red and white foreground. The red-on-black is completely unreadable to me. I can only use tldr by suppressing all shell coloring, e.g.,

unset LS_COLORS; export TERM=vt200

It would be much better if there were a way to control or disable coloring, either on install, via a shell variable or a config file.

**Comment by waldyrious** [comment]
@bobfoster what client are you using? Node, python, or something else?

**Comment by waldyrious** [comment]
Closing after several months without feedback from the reporter. Please reopen if you can provide the required info.
