### ISSUE TITLE
Add collaborator: @marchersimon

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5390]
Hi, @marchersimon! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#5368, #5362, #5361, #5357, #5315, #5305, #5294, #5286, and #5282)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by bl-ue** [comment]
Yesterday we discussed raising the minimum PR count for adding new collaborators from 5 to 10, but you already have 9 merged, and you added 2 more, so I think it's fine. 🙂 

@sbrl invite?

**Comment by sbrl** [comment]
Invite sent, @marchersimon! Always a pleasure welcoming someone new onboard :fireworks:

We have a [community roles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document that describes how we grant roles to people :-)

**Comment by bl-ue** [comment]
@marchersimon I see that you've accepted the invitation and that you're already wielding your new powers!  Be careful though, don't merge more complicated PRs until you've got more experience because we generally have unspoken customs, etc. 😄 

Anyway, now that you've accepted, would you like to open a PR adding yourself to [`MAINTAINERS.md`](https://github.com/tldr-pages/tldr/blob/bbbe632af28797181f65556491f561be7c3706d7/MAINTAINERS.md)?

**Comment by marchersimon** [comment]
Sure, thanks for the info. 
I've just looked trough some older PRs and saw that there are many unmerged ones, altough they have enough approvals. Is there a reason for that?

**Comment by bl-ue** [comment]
Maybe, maybe not.  I'd recommend pinging those PRs 👍🏻

**Comment by marchersimon** [comment]
What do you mean by pinging? Re-requesting reviews?

**Comment by bl-ue** [comment]
Sure, or just leave a comment asking what's up, etc.

**Comment by bl-ue** [comment]
Also @marchersimon, how about you join our [Gitter channel](https://gitter.im/tldr-pages/tldr), where we can communicate on these subjects a bit better?

**Comment by bl-ue** [comment]
Again, welcome @marchersimon!
