### ISSUE TITLE
`tar` example in README.md is out of date

### ISSUE THREAD

**Issue by jakevossen5** [tldr-pages/tldr#5400]
If you run `tldr tar`, the result is different than what appears on the README. Obviously not a big deal, but maybe the screenshot should be updated / replaced with text? If you wanted to go all out you could add something to the linter whenever someone changed that file.

**Comment by jakevossen5** [comment]
I like that as well! The only small thing that I would like to see is a plain text version for accessibility - even if it was just a link below to a file that has the exact same text / sequence of commands.

**Comment by lamar-frankie** [comment]
Hey Frank checkin in here

**Comment by sbrl** [comment]
@jakevossen5 that's one of the beauties of SVG, in that the text therein can be highlighted / selected / read :D

Though  don't have a screen reader, so I'm not sure if your average screen reader is aware of this or not though.

**Comment by jakevossen5** [comment]
Alright, who wants to take this up? I should be able to get started on it sometime this week, but if someone who is more familiar with this project wants to take a crack at it I am good with that too. Probably the best thing to do would be open up a PR, then see if someone who uses a screenreader regularly has feedback?

**Comment by bl-ue** [comment]
Yep, go for it.

**Comment by tomadojuice** [comment]
This seems interesting. Can I give it a go?

**Comment by bl-ue** [comment]
Go ahead, @tomadojuice!

**Comment by tomadojuice** [comment]
We could also maybe replace the image on the [sponsor website](https://liberapay.com/tldr-pages) with the new SVG. Is it possible to change this aswell? Should we adress this in a seperate issue?

**Comment by sbrl** [comment]
@tomadojuice yeah, that's absolutely possible - anyone whose part of the Liberapay should be able to edit the statement here: <https://liberapay.com/tldr-pages/edit/statement>

Let's wait until the README PR is closed though before doing that.
