### ISSUE TITLE
Change "tldr tldr" -p option to something that is platform specific?

### ISSUE THREAD

**Issue by jakevossen5** [tldr-pages/tldr#5401]
Currently the `tldr tldr` page has the -p example of `tldr -p {{linux}} {{tar}}`. Maybe there is a rational I don't see, but I feel like the -p option would be better explained if it showed an example of a page specific to linux in this case (the `tar` page is in `common`).

I am not sure of a command that is well known to be different on different platforms (`date` is what first came to mind).

What does everyone think?

**Comment by sbrl** [comment]
Great spot. What about changing it to `tldr -p {{linux}} {{pstree}}` or something?

**Comment by marchersimon** [comment]
Closing, since this example has been rewritten to include all platforms now.
