### ISSUE TITLE
How to change color or change theme

### ISSUE THREAD

**Issue by maonx** [tldr-pages/tldr#542]
TLDR is very helpful for me,but it looks tired.
My system is `Windows7`, I am using a SHELL called `Babun` and ssh to ubuntu server.
![image](https://cloud.githubusercontent.com/assets/272345/12070681/05cdec48-b0bf-11e5-892f-e94fb45978e9.png)

**Comment by igorshubovych** [comment]
Which client are you using?

**Comment by maonx** [comment]
I am using a windows shell called  Babun which base on cygwin
2016年1月2日 上午9:14，"Igor Shubovych" <notifications@github.com>写道：

**Comment by lord63** [comment]
@maonx Not your system environment, but the tldr client, e.g. the python client.

**Comment by maonx** [comment]
There are both python2.7 and python3.4 on ubuntu trusty, buy the command
"python" is run python2.7
2016年1月2日 上午11:01，"lord63" <notifications@github.com>写道：

**Comment by waldyrious** [comment]
He means the tldr client, i.e. one of [these](https://github.com/tldr-pages/tldr#clients)

**Comment by bwh1te** [comment]
Hi there! I'am occuring the similar bug. I've installed `tldr` via `pip install tldr`. OS is Ubuntu 15.04, bash.
![bwh1te bwh1te-peka _003](https://cloud.githubusercontent.com/assets/946520/12074258/817dfbc0-b16a-11e5-831d-eba3043b9baa.png)

**Comment by maonx** [comment]
@lord63 @waldyrious I use `pip3 install tldr`

**Comment by felixonmars** [comment]
I am still waiting for the decision on reference client, and I will update the behavior of python client accordingly afterwards.

**Comment by bwh1te** [comment]
I see that python client is not able to parse `{{token}}` pattern and has no special color option for user-defined parameter now. I could try to fix it. Tell me please, what keyword do you prefer to name parameter color?

**Comment by G570972680893** [comment]
Red

**Comment by searene** [comment]
It would be great if `tldr` only changes the font color instead of the background color, green font under blue background is hard to see.

**Comment by zqqf16** [comment]
If your are using python client, try these env:

```bash
export TLDR_COLOR_BLANK="white"
export TLDR_COLOR_NAME="cyan"
export TLDR_COLOR_DESCRIPTION="white"
export TLDR_COLOR_EXAMPLE="green"
export TLDR_COLOR_COMMAND="white"
```

Preview: (Mac + Terminal.app + Solarized Dark theme)

<img width="654" alt="theme" src="https://cloud.githubusercontent.com/assets/655326/12135212/95a9da4a-b473-11e5-8b05-3ac1aea5b215.png">

**Comment by maonx** [comment]
@zqqf16 Thank you, it work good.

**Comment by bwh1te** [comment]
I guess it is `tldr-python-client` isssue, not `tldr`. And I think @zqqf16 answer should be right in python-client README, because of now it is not obviously that you can change output colors without reading the source code.

**Comment by Cs4r** [comment]
@zqqf16 It worked for me, thanks!

**Comment by waldyrious** [comment]
Since the Python client now has color customization information in the README, I think it's safe to close this issue. If anyone has similar problems, please open issues in the client's own repos, where they're more likely to get attention from the client's authors.
