### ISSUE TITLE
Page request: tldr-lint

### ISSUE THREAD

**Issue by Waples** [tldr-pages/tldr#5444]
```bash
$ tldr tldr-lint
`tldr-lint` documentation is not available. Consider contributing Pull Request to https://github.com/tldr-pages/tldr
```

**Comment by Waples** [comment]
bump @bl-ue

**Comment by bl-ue** [comment]
Good call @Waples—I was thinking of adding this just yesterday! :smile:  I'll do so now.

**Comment by bl-ue** [comment]
@waldyrious / @sbrl, obviously an alias page is needed.  Which would you recommend: link a new `tldr-lint` page to the existing `tldr` page OR rename `tldr` to `tldr-lint` and link new `tldrl` to `tldr-lint`?

**Comment by waldyrious** [comment]
When you write `tldr` above, you mean `tldrl` in all cases, right?

**Comment by bl-ue** [comment]
Yes, my mistake hahaha.

**Comment by waldyrious** [comment]
Both binary names seem to be [equally valid](https://github.com/tldr-pages/tldr-lint/blob/81cf0c8d342d0faa3d329cbc64ec8f7779bb7c76/package.json#L18-L19), so it's arbitrary which one we should pick for the canonical name and which should be the alias. In the spirit of explicitness, I'd vote for making `tldrl` the alias.
