### ISSUE TITLE
Add organization member: @MasterOdin

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5473]
Hi, @MasterOdin! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks.
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by MasterOdin** [comment]
I'd point out that I have not merged 10 PRs or provided 5 non-trivial reviews to PRs within the main tldr-pages/tldr repo which the COMMUNITY-ROLES.md file seems to indicate. I do not have an interest in really reviewing PRs here, having more interest in working on clients and surrounding infrastructure stuff.

**Comment by bl-ue** [comment]
That's a good point, and if you'd like to close I'd be happy to do so. _But_ I have noticed that you contribute a lot the repos such as [tldr-lint](https://github.com/tldr-pages/tldr-lint) and [tldr-node-client](https://github.com/tldr-pages/tldr-node-client), and among other things, being an organization member (to my knowledge) extends your collaborator's permissions to all repositories under the organization.

Also, we should discuss with @waldyrious if the other repos should count at all towards these "promotions."

**Comment by sbrl** [comment]
Yeah, it does extend privileges to all repos. The community roles we have in this repo are really tailored towards the `tldr` repo here, and they don't specifically talk about other repos. With that in mind, I'd suggest that the process for regular contributors of other repos is much more of a case-by-case ad-hoc basis.

If @MasterOdin would like to be an org member to remove barriers in other repos, that's fine by me :-)

**Comment by sbrl** [comment]
I assume that by opening that PR @MasterOdin you're accepting the offer? Sending invite!
