### ISSUE TITLE
Merge the lists of clients on the wiki and the README

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#5512]
> Note: This has been discussed in various places (e.g. [here](https://github.com/tldr-pages/tldr-pages.github.io/pull/30#issuecomment-449832106) and [here](https://github.com/tldr-pages/tldr-pages.github.io/issues/52#issuecomment-752937054)), but apparently we never wrote it down into an actual issue. (The closest we got to that was a mini-project in [our wiki page for Google Season of Docs](https://github.com/tldr-pages/tldr/wiki/Season-of-Docs-projects/f038e98690316dd2ba8ac8d6fbc6974fc8c0369f#project-merge-the-lists-of-clients-on-the-wiki-the-readme-and-the-website), which is where most of the text below comes from.)

There are currently two lists of clients, each maintained independently: one in the [README](https://github.com/tldr-pages/tldr/blob/master/README.md#how-do-i-use-it), and one in a [wiki page](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients). (There actually used to be a _third_ one 😱 in the website, but it was merged a while ago by @20manas in https://github.com/tldr-pages/tldr-pages.github.io/pull/53.)

We want the client lists to live at a single place, so that the lists won't get outdated or out of sync with each other.

The goal is to merge the two lists without losing any relevant information, and keeping the final result readable and easy to consume.

The final list can live at either of the two existing places, or at a new location (e.g. a new `CLIENTS.md` file). The existing locations should either embed or link to the unified list.

Once the lists are merged, we can also discuss the possibility of splitting the list into several sections based on relevant criteria (beyond the current division, which is by platform / language). For example:
- by maintenance status — we don't want to encourage people to use clients that are abandoned, outdated. etc. (see #4044, #1602, #1104)
- by adherence to the client spec (see #1065)
- Eventually, by support for new syntax (see #958, #1082), new directory structure (see #4120 and other [issues under the `architecture` label](https://github.com/tldr-pages/tldr/issues?q=label%3Aarchitecture)), or other features (see #2865, #3269)

For convenience, here are again the links to the existing lists of clients:
  - README: [README.md#how-do-i-use-it](https://github.com/tldr-pages/tldr#how-do-i-use-it)
  - Wiki: [tldr pages clients](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients)

**Comment by MasterOdin** [comment]
My vote would be on having it just be in the wiki, which allows people to self add clients. For most projects I've seen that go this route, I'm not sure I've really seen any instance of spam or whatever on the wiki even though its publicly editable.

**Comment by bl-ue** [comment]
The only part-issue I see with that approach is that maintainers wouldn't know when there's a new client unless they're watching the repository (because GH adds an entry to your feed about users modifiying the wiki of a repo if you watching it), and they take the time to check what the user changed.

**Comment by sbrl** [comment]
Yeah, we really need to tidy this up.

The wiki would be a sensible place to put it, but we would of course need a prominent link to it in the README

**Comment by marchersimon** [comment]
Documentation is actually very important, don't underestimate your work. Thanks for your help!

**Comment by MasterOdin** [comment]
@marchersimon reopening this issue as the primary objective of it:

> We want the client lists to live at a single place, so that the lists won't get outdated or out of sync with each other.

is still not done. We still have two lists (README.md and Wiki), and should consolidate behind one. 

We should open a PR to simplify the README to just point at the wiki, and maybe mention how to install just the official clients.

**Comment by kitarp29** [comment]
@MasterOdin Can I work on it??

**Comment by marchersimon** [comment]
Sure, if you like to

**Comment by kitarp29** [comment]
@MasterOdin https://github.com/tldr-pages/tldr/pull/7381
did the changes and updated README.md

**Comment by sbrl** [comment]
Awesome, @kitarp29! Does this mean we can close this issue now?

**Comment by kitarp29** [comment]
Yes this got merged.
Go ahead and close it.
