### ISSUE TITLE
Let's document: platformio

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5517]
- [x] [`pio`](https://docs.platformio.org/en/latest/core/userguide/index.html) → #5404
- [x] [`pio access`](https://docs.platformio.org/en/latest/core/userguide/access/index.html) → #5518 
- [x] [`pio account`](https://docs.platformio.org/en/latest/core/userguide/account/index.html) → #5410
- [x] [`pio boards`](https://docs.platformio.org/en/latest/core/userguide/cmd_boards.html) → #5409 
- [x] [`pio check`](https://docs.platformio.org/en/latest/core/userguide/cmd_check.html) → #5519 
- [ ] [`pio ci`](https://docs.platformio.org/en/latest/core/userguide/cmd_ci.html) → #6186 
- [x] [`pio debug`](https://docs.platformio.org/en/latest/core/userguide/cmd_debug.html) → #5780 
- [x] [`pio device`](https://docs.platformio.org/en/latest/core/userguide/device/index.html) → #5725
- [x] [`pio home`](https://docs.platformio.org/en/latest/core/userguide/cmd_home.html) → #5406 
- [x] [`pio lib`](https://docs.platformio.org/en/latest/core/userguide/lib/index.html) → #5728
- [x] [`pio org`](https://docs.platformio.org/en/latest/core/userguide/org/index.html) → #5525
- [x] [`pio package`](https://docs.platformio.org/en/latest/core/userguide/package/index.html) → #5713 
- [x] [`pio platform`](https://docs.platformio.org/en/latest/core/userguide/platforms/index.html) → #5727
- [x] [`pio project`](https://docs.platformio.org/en/latest/core/userguide/project/index.html) → #5408 
- [x] `pio init` → #5865
- [x] [`pio remote`](https://docs.platformio.org/en/latest/core/userguide/remote/index.html) → #5902 
- [x] [`pio run`](https://docs.platformio.org/en/latest/core/userguide/cmd_run.html) → #5827
- [x] [`pio settings`](https://docs.platformio.org/en/latest/core/userguide/cmd_settings.html) → #5522
- [x] [`pio system`](https://docs.platformio.org/en/latest/core/userguide/system/index.html) → #5523
- [x] [`pio team`](https://docs.platformio.org/en/latest/core/userguide/team/index.html) → #5524
- [x] [`pio test`](https://docs.platformio.org/en/latest/core/userguide/cmd_test.html) → #5815
- [x] [`pio update`](https://docs.platformio.org/en/latest/core/userguide/cmd_update.html) → #5520
- [x] [`pio upgrade`](https://docs.platformio.org/en/latest/core/userguide/cmd_upgrade.html) → #5521

**Comment by marchersimon** [comment]
I'm having trouble understanding what [`pio ci`](https://docs.platformio.org/en/latest/core/userguide/cmd_ci.html) does. Would be nice if someone could help out with that.

**Comment by CleanMachine1** [comment]
:confetti_ball: :partying_face:
