### ISSUE TITLE
Looks a lot like bro pages...

### ISSUE THREAD

**Issue by michaeleisel** [tldr-pages/tldr#558]
And yet doesn't give any credit. I'm not associated in any way with bro pages, but this is unfair. Why does this repo exist?

**Comment by waldyrious** [comment]
According to the commit history tldr was created earlier ([dec 2013](https://github.com/tldr-pages/tldr/graphs/contributors)) than bropages ([jan 2014](https://github.com/hubsmoke/bro/graphs/contributors)). So if anything, bropages "should" give credit to tldr (by your logic), although I don't believe that's how attribution works -- they seem to have been two [independent inventions](https://en.wikipedia.org/wiki/Multiple_discovery).

In any case, there have been calls for collaboration between the two initiatives (#266), but they have been met with little to no reaction from the bropages side (see https://github.com/hubsmoke/bro/issues/57). So I'd suggest closing this issue, either as misguided/incorrect, or as a duplicate of #266.

**Comment by michaeleisel** [comment]
Eh, fair enough
