### ISSUE TITLE
New tldr client, written in bash

### ISSUE THREAD

**Issue by raylee** [tldr-pages/tldr#569]
Hello! I decided to wile away my Sunday afternoon and write a bash client for tldr, which uses curl to do the heavy lifting. It caches index.json locally, as well as any retrieved pages. The code considers cached copies expired after 14 days and will retrieve new copies after that. If I should change that period to something else, please let me know.

The repository for the client lives at https://github.com/raylee/tldr . If you all like the idea and wish to link to it from your main README.md, I can open a PR or you can toss a link in yourselves.

Thanks for spearheading a fun project. I'm glad to see more things are heading to community maintenance.

**Comment by igorshubovych** [comment]
See #574 regarding the index.

It will be removed sooner or later. Use the version from tldr-pages.github.io/assets/index.json. It is always fresh. As well as pages archive - tldr-pages.github.io/assets/tldr.zip.

**Comment by igorshubovych** [comment]
Overall - great work!

**Comment by waldyrious** [comment]
See also #527. What are your thoughts on that one @igorshubovych, @raylee?

**Comment by igorshubovych** [comment]
@waldyrious that one is super easy.

Actually this client is almost as good for users as node-client. Need some fixes though.

**Comment by raylee** [comment]
@igorshubovych All good pointers, thank you. I'll update the code to rely upon the official asset url for tldr.zip, and pull pages from there. That will simplify the caching on the client side too. I see the zip file contains pages/index.json, is the plan to remove it from there as well?

Regarding caching, are the asset files being rebuilt as needed, or on a schedule? If it's only when there's new content, I can cache the output of `curl -sf --head https://tldr-pages.github.io/assets/tldr.zip | grep ^Last-Modified:` and use that to decide whether to update the whole asset, saving bandwidth.

@waldyrious #527 is nice and simple, I agree with the author that markdown is fine being read by humans (that was one of the design goals after all), so I like it. My goals are slightly different in that I wanted to offer a feature-parity client that could be shipped by a distro with minimum dependencies.

Looking at the node.js client, I can add --random, --random-example, and --render to the bash client easily enough. I'll also look at matching the configuration syntax.

Given all the good comments from you guys above, I'm requesting you hold off on my request to add a link to the bash version :-) Give me a few days to update it for these requests first.

Thanks!

**Comment by igorshubovych** [comment]
@raylee 
> I see the zip file contains pages/index.json, is the plan to remove it from there as well?

No. You can use zip, it has fresh index.json. Or you can use just index.json, if you working on, let's say, web client.

You can see how these assets are generated here:
https://github.com/tldr-pages/tldr/blob/master/scripts/build.sh

**Comment by rubenvereecken** [comment]
["bash is a cursed hammer, when wielded everything looks like a nail, especially your thumb."](http://bjorn.tipling.com/if-programming-languages-were-weapons)

Brave, brave man.

**Comment by igorshubovych** [comment]
Added on README.md. It is already in better state than some of already listed clients.

**Comment by raylee** [comment]
@rubenvereecken <grin> I've worked in more ludicrous languages than bash.
