### ISSUE TITLE
Add organization member: @yutyo

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5702]
Hi, @yutyo! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks (https://github.com/tldr-pages/tldr/pulls/yutyo).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by yutyo** [comment]
Dear @bl-ue,

Thank you for this humble invitation. 

I absolutely accept the role without any concern and take the oath to be a diligent maintainer. I truly hope to satisfy the responsibilities of my new position.

**Comment by sbrl** [comment]
Invite sent,, @yutyo!

**Comment by bl-ue** [comment]
Yep, @yutyo has accepted; I see his comments are marked with the 'Member' badge ✅
