### ISSUE TITLE
Add organization owner: @navarroaxel

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5703]
Hi, @navarroaxel! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by navarroaxel** [comment]
Sure yes! :star_struck:

**Comment by sbrl** [comment]
Role changed, @navarroaxel! Do you want to open a PR to edit MAINTAINERS.md?

**Comment by bl-ue** [comment]
We could use an automation tool that takes an issue number and automatically figures out what's happenening and who it's happening to and update `MAINTAINERS.md` accordingly (locally) 🤔
Sounds like something I'd definitely like to write
