### ISSUE TITLE
Should we add a `tldr <command> {{subcommand}}` example to pages with subcommands?

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5712]
When learning of a command the first time it often isn't obvious that this command has subcommands. And when looking at the tldr page of a command it's impossible to say if there are tldr pages for all the subcommands. What do you think about adding a `tldr <command> {{subcommand}}` example at the bottom? Or maybe put it in the description.

**Comment by bl-ue** [comment]
Related: #5190

**Comment by marchersimon** [comment]
I probably should have checked for existing issues. That one is basically the same.
