### ISSUE TITLE
Add organzation member: @marchersimon

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5722]
Hi, @marchersimon! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks (109 PRs).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by marchersimon** [comment]
That sounds awesome! I'm just not sure if a can meet the expectations of maintaining such a large project. I can't bring much of value, other than creating pages and reviewing PRs.

**Comment by bl-ue** [comment]
Well, there's not much else to do!  It certainly does add a lot of value, though.

**Comment by marchersimon** [comment]
Then I'll try my best.

**Comment by sbrl** [comment]
Haha reviewing PRs is a very valuable task! It's too big a task for 1 person, so the more hands the better!

Thanks for all your stellar work so far, @marchersimon - invite sent!

**Comment by marchersimon** [comment]
Invite accepted!
