### ISSUE TITLE
Remove the index.json

### ISSUE THREAD

**Issue by lord63** [tldr-pages/tldr#574]
In issue #336, we talked about whether we need it or not. Finally, we removed the build. The latest index.json is in https://tldr-pages.github.io/assets/index.json
In issue #487, @ostera [said](https://github.com/tldr-pages/tldr/issues/487#issuecomment-168048513) that we may remove the index.json.

I'm also trying to make [tldr.py](https://github.com/lord63/tldr.py) support rebuilding the index, but one more thing here. The old index.json is still here, when we want to update the pages via `git pull` after we rebuilding the index.json(add some custom new pages, the index.json has changed), it fails because of the uncommited changes.

Since it is out of time and may cause some problems, it's time that we should remove the index.json now?

**Comment by lord63** [comment]
Note there may be some compatible problems for those clients who rely on the `index.json`.

For example, [tldr.py](https://github.com/lord63/tldr.py) use local file and fetch latest pages via `git pull`. If we remove it from the main repo, users who fetch the latest page will can't use `tldr.py` since it can't find the `index.json`. Although I can release a new version to support reindex, some old users that installed it before will run into this problem if they update the pages.

And the update problem for `tlrdr.py` can be resolved by commit the changed `index.json`. But you have to commit it before you run the update command every time.

I still think the `index.json` is a good idea. But I can't come out a good way to solve the problem: make it fresh while easy for collaborating with others.

**Comment by ostera** [comment]
@lord63 we have an up-to-date index located at http://tldr-pages.github.io/assets/index.json

We should remove the index from this repository as soon as the biggest clients migrate over to the new one. 

@igorshubovych perhaps can make a list of the clients here and we can start checking them off as they update, and then use this issue to submit a PR to remove the index.

**Comment by lord63** [comment]
@ostera  Yes, I know, as I've point this out in my comment. And I agree that we should hold on for a while before we make the final decision to remove it. We need discuss more on it.

**Comment by hidroh** [comment]
My client depends on the old `index.json` to discover commands. I'm quite late to the conversation so I may get things wrong, so we should point to http://tldr-pages.github.io/assets/index.json now, or even this `index.json` would soon be removed?

**Comment by ostera** [comment]
@hidroh the new index will be hosted at the tldr-pages URL. You only need to change that url.

**Comment by hidroh** [comment]
Got it thanks.

**Comment by hidroh** [comment]
Do you think it would be useful to have a timestamp on index.json, if we are indeed going to keep it? It may help clients to make more inform decision on whether they should refresh cached commands in local storage.

**Comment by igorshubovych** [comment]
@hidroh 
Interesting idea. I might put some file, let's say meta.json
```json
{
  "lastUpdated": "timestamp-here"
}
```

**Comment by rubenvereecken** [comment]
Power to the client! Power to the populace!

Yeah, fine idea @hidroh.

**Comment by ostera** [comment]
But guys, github already does caching for us at the HTTP level with Varnish, it's only a matter of sending a GET request with the right headers and everything is taken care of for us. 

A typical Github file request has a response with these headers:

```
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Age:134
Cache-Control:max-age=600
Connection:keep-alive
Content-Encoding:gzip
Content-Length:1527
Content-Type:application/json
Date:Tue, 05 Jan 2016 18:10:20 GMT
Expires:Tue, 05 Jan 2016 15:18:14 GMT
Last-Modified:Tue, 05 Jan 2016 15:04:05 GMT
Server:GitHub.com
Vary:Accept-Encoding
Via:1.1 varnish
X-Cache:HIT
X-Cache-Hits:6
X-Fastly-Request-ID:80d81b44bbcc9ff4fc9eca2896a3a6db03024071
X-GitHub-Request-Id:17EB2B2C:448E:38EE69D3:568BDC5D
X-Served-By:cache-ams4126-AMS
X-Timer:S1452017420.456635,VS0,VE0
```

So a simple GET with `If-Modified-Since` set to the right value (`Last-Modified`) will return a 304. At least this is the path I'll be taking to break cache on the index (and pages) for the web client.

Of course you could use any of these values to make local checks before issuing a request, but we don't need a `meta.json`.

**Comment by hidroh** [comment]
I was pondering the HTTP status code as well. Thanks for confirming @ostera.

**Comment by ostera** [comment]
From the record, I'm having trouble with a preflight OPTIONS request when sending `If-Modified-Since` headers to get the index from `tldr-pages.github.io/assets/index.json`. Will ask Github for support.

**Comment by ostera** [comment]
To round up this conversation, GitHub Pages doesn't support OPTIONS requests. So I worked around through the V3 API.
