### ISSUE TITLE
Add collaborator: @Waples

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5774]
Hi, @Waples! You seem to be enjoying contributing to the tldr-pages project.
You now have had six distinct pull requests merged (#5435, #5645, #5694, #5751, #5753, and #5765)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by Waples** [comment]
You already have my answer 😉 ghehe

**Comment by sbrl** [comment]
Invite sent, @Waples :D

**Comment by sbrl** [comment]
Would you like to open a PR to update MAINTAINERS.md?

**Comment by Waples** [comment]
Received and gladly accepted @sbrl ^^

**Comment by Waples** [comment]
> Would you like to open a PR to update MAINTAINERS.md?

I'm happy to do so, but where do I put myself? xD the list is fudged; randomly sorted by date etc.

Shall I also sort it by date or alphabetical then?

**Comment by Waples** [comment]
Ah i see now, the until dates xD PR incoming

**Comment by Waples** [comment]
https://github.com/tldr-pages/tldr/pull/5775
