### ISSUE TITLE
Style question: What about variable number of arguments (varargs)?

### ISSUE THREAD

**Issue by xeruf** [tldr-pages/tldr#5791]
In some cases, one or multiple (or even zero) of an argument can be passed, should we use any specific syntax here? Didn't find anything on https://github.com/tldr-pages/tldr/blob/master/contributing-guides/style-guide.md#token-syntax.

I was thinking of the classical `...` which I started using in a PR already: https://github.com/xerus2000/tldr/commit/ab754537fee0edb609c6b487ef6c009a5532148a
The question then is whether to use singular or plural, i.e. `files...` or `file...`.

**Comment by bl-ue** [comment]
I made a suggestion here: https://github.com/tldr-pages/tldr/pull/5787#discussion_r615845999

As a matter of fact, I very recently brought this question up: https://github.com/tldr-pages/tldr/pull/5768#discussion_r614397719. My preferred style would be like this:

```
command {{path/to/file1 path/to/file2 ...}}
```

Multiple items being inside one token syntax section like that indicates that the position and count of the arguments is variable.

**Comment by Waples** [comment]
I'm siding beside @bl-ue.
just stuff them in there.

**Comment by sbrl** [comment]
Personally I've used `{{thing1}} {{thing2}} {{thingN}}` myself, but I don't think we need a hard and fast rule here as it's dependent on context. `{{thing1 thing2 ...}}` would also be acceptable, as would `{{thing1|thing2|...}}` for a choice of only 1 option.

**Comment by bl-ue** [comment]
I prefer my suggestion because it looks shorted to me than the 1, 2, N approach.

**Comment by xeruf** [comment]
> I prefer my suggestion because it looks shorted to me than the 1, 2, N approach.

I agree - using N might incline some users to ask what the N stands for

**Comment by marchersimon** [comment]
What do yout think about making an issue or a file, where we collect all conventions we decided upon?

**Comment by sbrl** [comment]
@marchersimon Maybe, but I think it's a bit too dependent on context to make a hard and fast rule about it.

**Comment by marchersimon** [comment]
Seems fair. After all it isn't bad to re-discuss some topics from time to time.

**Comment by xeruf** [comment]
y'all know that there already a file for conventions? ;) https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md#token-syntax

**Comment by sbrl** [comment]
Yeah, but we generally speaking try to keep that guide relatively short @xeruf to avoid exhausting new contributors :P

**Comment by xeruf** [comment]
Well, there should be a single point of truth, and I think this file is appropriate for that.
As a new contributor I didn't look at that file right away anyways.
