### ISSUE TITLE
Join Gitcoin

### ISSUE THREAD

**Issue by yutyo** [tldr-pages/tldr#5792]
I suggest opening tldr-pager organization in Gitcoin in order to join their bounty system and boost contributions, which will return in reward to both of us maintainers and contributors. Its not like a sponsorship, propertyizing or adversement. The system is totally based on rewarding git processes, which will encourage people to engage in contributions and us to regularly maintain the project.

For more info about Gitcoin, take a look at https://gitcoin.co/blog/open-source-money-will-buidl-the-open-source-ecosystem/

**Comment by sbrl** [comment]
I'm really not sure that's a good idea @Yutyo.
The thing is that at the moment people contribute because they find tldr-pages useful and they want to donate their time, but if we integrated gitcoin it might change the reasons that people contribute, which I really don't think would be good for anybody involved.

Link to conversation on Gitter about the subject: https://gitter.im/tldr-pages/tldr?at=607d9aafc60826673bb35e47

Some replies from there:

> We don't want to monetize contributions. The discussion in #3102 offers some context on what we consider to be appropriate to be compensated monetarily (basically things that require us to spend money, such as hosting/domain costs, etc.)

--@waldyrious

> idk if the people that comes to contribute in the hacktoberfest use tldr actually lol 

--@navarroaxel

[comment from me here, omitted because @waldyrious explains it better than can]

> @navarroaxel has a good point though, that external motivators can certainly be a factor in bringing new valuable contributions — there's no denying that. However, we must keep in mind that it's not a sustainable model. We are able to cope with that extra activity at that time of the year, but there's no way the project would survive that level of activity and influx of content on a regular basis.
> 
> One of the reasons is definitely one of scaling the support for new contributors. The onboarding of community members is quite a long process, where existing members gradually pass on the project's culture and the nuances of its guidelines through repeated interactions with the newcomers. If we start getting a constant stream of new people, especially drive-by contributors, we will be depleting our limited resources (people, their time, their patience) to onboard them adequately, which may often be a wasted effort if they aren't driven by the project itself but by the chance to get an external reward.
> 
> Then there's the issue of erosion of the intrinsic motivation: even people who start contributing out of passion for the mission of the project, will have their motivation "cannibalized" over time by the external rewards, ending up with less intrinsic drive than initially. This is a well-known psychological effect. There's a great TED talk that explains this: https://www.youtube.com/watch?v=rrkrvAUbU9Y

--@waldyrious

**Comment by Waples** [comment]
Since @yutyo aggreed on Gitter, I'll close this issue now.
