### ISSUE TITLE
What to do with `adb-shell`-only commands for Android?

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5798]
As discussed [here](https://github.com/tldr-pages/tldr/pull/5743#discussion_r612422302), some commands for Android aren't native to Android and can only be executed through `adb-shell`. Therefore they technically aren't Android commands. The current idea is to put them in the Android folder, but mention that they are `adb-shell`-specific. What do you think?

**Comment by navarroaxel** [comment]
Yeah, I think we can add that in the command description (the header).

**Comment by marchersimon** [comment]
Since we have three (including https://github.com/tldr-pages/tldr/pull/5743#discussion_r616199123) approving and no opposing reactions, I'm closing this issue now.
