### ISSUE TITLE
Add collaborator: @aherst

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5810]
Hi, @aherst! You seem to be enjoying contributing to the tldr-pages project.
You now have had 14 distinct pull requests merged (#5800, #5799, #5756, #5755, #5651, #5420, #5328, #5316, #5311, #5307, #5298, #5270, #5052)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by aherst** [comment]
Yes please. 

Thanks,

Adam

**Comment by sbrl** [comment]
Invite sent, @aherst! Welcome to tldr-pages :D
