### ISSUE TITLE
Common pages link to GNU docs, whereas Linux pages do not

### ISSUE THREAD

**Issue by artemislena** [tldr-pages/tldr#5845]
Just something that struck me as weird… E.g. compare `pages/common/cp.md` and `pages/linux/cp.md`. Not all Linux systems use GNU… While I think it would be safe to assume they do, the same isn't true for other systems, such as macOS or BSD, where linking to the GNU version may be questionable. Didn't want to open a PR as this might be intended, so this can be seen more as a question.

**Comment by marchersimon** [comment]
That it isn't there in `linux/cp.md` is my fault, I forgot it when I added the link in #5556.

**Comment by sbrl** [comment]
Oh, great spot there @FantasyCookie17! That's a bit of an awkward one there, since different distros in the same platform have different implementations. Is there a portable POSIX link we could use instead that everyone is compliant with?

**Comment by marchersimon** [comment]
How about <https://manned.org/cp.1posix>?

**Comment by FantasyCookie17** [comment]
> The Linux implementation of this interface may differ (consult the corresponding Linux manual page for details of Linux behavior), or the interface may not be implemented on Linux.

Better than nothing, though, I guess… I suppose we should apply the same to both `common` and `linux`?

**Comment by FantasyCookie17** [comment]
Most other POSIX utilities also seem to link to the GNU page, btw… I checked `ls` and `cat`, for example.

**Comment by marchersimon** [comment]
Would it be a problem if we stick to the GNU documentation? Some special flags may not work on some platforms, but GNU documentations are really good.

**Comment by FantasyCookie17** [comment]
🤷🏻‍♀️ No idea. I guess we *should* be fine, then again, I think I remember having tried something from `tldr` that didn't work on macOS (probably some `sed` thing, however, `sed` is notorious for being poorly standardized).

**Comment by sbrl** [comment]
Yeah, that manned link could be good. I do agree with @marchersimon though that the GNU link is very good.

Yeah, `sed` is a problem - and it does really limit it's crross-platform usefulness when it lacks consistency like that.

I guess the actual examples in the page are portable though? If not, then we'll need to revise them.

**Comment by FantasyCookie17** [comment]
I think it used to be wrong some time ago, but now it seems to work… 🤷🏻‍♀️ Should this issue be closed, then? Or do we want to use the manned.org links?

**Comment by waldyrious** [comment]
> Or do we want to use the manned.org links?

[We do](https://github.com/tldr-pages/tldr/issues/5143) :)

**Comment by FantasyCookie17** [comment]
Alright. Should I look into committing a PR, or does someone else want to work on it?

**Comment by marchersimon** [comment]
@waldyrious the question wasn't if we should use the `manned.org` links at all, but if we should prefer them to the GNU docs in this case. It sounds like that wasn't clear.

**Comment by vitorhcl** [comment]
@kbdharun I believe this was the issue you was referring to in #11956. I think that #9612 already assumed that we should adapt POSIX commands in common. But given this issue is still open, I will give my opinion on this issue:
- In common/, we shouldn't leave GNU commands, only their POSIX equivalents (if any)
- We should leave GNU commands in linux/

**Comment by kbdharun** [comment]
> @kbdharun I believe this was the issue you was referring to in #11956. I think that #9612 already assumed that we should adapt POSIX commands in common. But given this issue is still open, I will give my opinion on this issue:
> 
> * In common/, we shouldn't leave GNU commands, only their POSIX equivalents (if any)
> * We should leave GNU commands in linux/

Yep, that's what we intend to do too (in case there isn't a POSIX equivalent for the GNU command, then IG we can fall back to its link in `common`).

**Comment by vitorhcl** [comment]
So I think we can close this, right?

**Comment by kbdharun** [comment]
> So I think we can close this issue, right? It seems like the issue now is no more a question or decision, but an update of the pages for consistency

Yep, we can track this in the POSIX compliance issue (to update the links too).
