### ISSUE TITLE
Add collaborator: @nicokosi

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5873]
Hi, @nicokosi! You seem to be enjoying contributing to the tldr-pages project.
You now have had 12 distinct pull requests merged (#5841, #5820, #5818, #5805, #5804, #5797, #5764, #5742, #5693, #5675, #5666, #5662)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/master/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/master/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by nicokosi** [comment]
> So, what do you say? Can we add you as a collaborator?

Yes, you can! 👍

**Comment by sbrl** [comment]
Welcome, @nicokosi!

**Comment by marchersimon** [comment]
@nicokosi would you please open a PR to add yourself to [`MAINTAINERS.md`](https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md)?

**Comment by nicokosi** [comment]
> @nicokosi would you please open a PR to add yourself to [`MAINTAINERS.md`](https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md)?

Done: #5882.
