### ISSUE TITLE
Accents in variables

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5924]
As discussed on several recent occasions, we are undecided as to whether or not we should **include accents in variable names**. 

I've linked a few threads where this has been discussed but no conclusion reached.

---

From https://github.com/tldr-pages/tldr/pull/5909#discussion_r628786530:

@navarroaxel [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r628786530):

>I think we should define if we will allow or deny accents (é, ó, ñ) in these variables to enforce the tldr user to read this as a "variable". As a native Spanish speaker I don't like them.

@patricedenis [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r628799965):

>@navarroaxel I agree with you, it should be decided and after that we could follow the rule (this should also be added somewhere in the guidelines for translation at the end).
>For me, it does not matter if we allow or deny the accents in the variables.
>I've put accents here because I was acting as the automatic speller checker I saw which made automatic correction of non accentuated words.
>It seems that your choice of denying them could be seen as reasonable as I'm not sure a variable's name can use these kind of accents in language.
>Can other people give their feedback on these?
>If we choose not to use accents in variable's name, I will happily replace them.

@bl-ue [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r628920535):

>Personally, I see no reason why they should be removed.  Commands work just as well with accented arguments as with plain arguments:
>```console
>$ touch àbçdēfghïjkłmñœpqrßtùvwxÿż
>$ echo 'Hello' > àbçdēfghïjkłmñœpqrßtùvwxÿż
>$ ls | grep àbçdēfghïjkłmñœpqrßtùvwxÿż
>àbçdēfghïjkłmñœpqrßtùvwxÿż
>$ cat ./àbçdēfghïjkłmñœpqrßtùvwxÿż
>Hello
>$ rm $(pwd)/àbçdēfghïjkłmñœpqrßtùvwxÿż
>$ ls | grep àbçdēfghïjkłmñœpqrßtùvwxÿż
>$
>```

@marchersimon [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r628921565):

>I think it's mostly stylistic. In German, we only have three accent letters (üöä) and it's kind of weird to see them in code or commands.

@bl-ue [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r628921721):

>But changing the word (as removing the accents is, is it not?) seems wrong.  We might as well leave the entire variables English then 🤔 

@patricedenis [wrote](https://github.com/tldr-pages/tldr/pull/5909/files#r629367394):

>both of you have points. In French, the accents are linked to the pronounciation and as @bl-ue said there are some words than can have different meaning using accents or not. But we also are used to spelling without the accents because of english-everywhere words used in computer science as quoted by @marchersimon.
>As tldr is more targeted to non technical mates, I personnally would in fact lean towards the usage of accents in variables names (for French ones, I mean).
>But let's discuss that in an Issue as proposed by @marchersimon.

---

From https://github.com/tldr-pages/tldr/pull/5484#discussion_r598283198:

@goznalo-git [wrote](https://github.com/tldr-pages/tldr/pull/5484#discussion_r598286035):

>I do not really see the need for unaccented words in variable names. However, in programming contexts this is good practice, as accents can mess things up. I guess this could be analogous.

@navarroaxel [wrote](https://github.com/tldr-pages/tldr/pull/5484#discussion_r598304585):

>@bl-ue the nouns in German starts with caps and we normalized that to strict `snake_case` recently.

@sbrl [wrote](https://github.com/tldr-pages/tldr/pull/5484#discussion_r598745565):

>I don't think it really matters either way. I guess "variable name" can be somewhat subjective, but l'd suggest it's best to follow convention.
>
>I'm not sure that this is something that could be easily standardised though, because determining what constitutes a variable name would be a somewhat subjective process though.

@schneiderl [wrote](https://github.com/tldr-pages/tldr/pull/5484#discussion_r598890621):

>It is more natural to have variables without accents IMO. But I don't really have a strong opinion nor a big preference.

---

cc @waldyrious @mebeim @zlatanvasovic

**Comment by marchersimon** [comment]
I can only speak for German, but I think we should remove them (at least in German pages). We even have a system, where we replace `ä`/`ö`/`ü` with `ae`/`oe`/`ue` when only using ASCII.

**Comment by zlatanvasovic** [comment]
I haven't followed the discussions so far, but this change may not be needed. Writing words with accent adds to clarity, which helps our userbase understand the commands better. Commands with variables from tldr pages aren't supposed to be copy/pasted anyway, so it shouldn't cause any problems.

**Comment by sbrl** [comment]
I would suggest keeping the accents unless there's a clear stylistic reason in that language.

**Comment by marchersimon** [comment]
I'll close this now, since it seems like we all have agreed on @sbrl's last comment.
