### ISSUE TITLE
Remove organization member: @ivanhercaz

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#5932]
Hi, @ivanhercaz! As you know, our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) defines processes for keeping the list of organization members in sync with the actual maintenance team.
Since you haven't been active in the project [for a while now](https://github.com/tldr-pages/tldr/pulls?q=commenter%3Aivanhercaz), we'll be relieving you from the maintainer responsibilities.

In practice, not much will change on your side, since you'll remain a collaborator in the repos you have been active in.
That means **you will keep the ability to commit, merge PRs, label and close issues, etc.**, whenever you feel so inclined.
If you don't, that's all right too!
Every bit of work you already did for the tldr-pages project was a voluntary gift of your time to this community, which is deeply appreciated.
Your efforts have contributed to a project which helps hundreds of people every day — be proud of it!

And of course, you're welcome back anytime as an active maintainer, if you so choose — in which case, just let us know and we'll re-add you to the organization, in accordance to the principles of our governance guidelines.
In any case, we wish you the best of luck in your new endeavors!

**Comment by sbrl** [comment]
Let's leave this a week before acting. I've set a reminder in my calendar, and I'll come back to this in 4 days time.

**Comment by ivanhercaz** [comment]
Dear tldr pages team, specially @marchersimon (for open the issue) and @sbrl (for the comment),

I really enjoy to participate in this project and being an organization member is a pleasure, but yes, I have not participated in any way in any of the tldr pages repositories. I has been a bit complicated to find time to participate and I decided to use my time for work and learn/participate in specific tools/libraries/languages/etc. that might help me to improve as professional in my field. In addition, I am trying to learn to have free time too to spend with my family and being relaxed (something hard when there is so much to do and so much to learn).

I am agree with the decision and I hope to participate again, maybe not with the same rate, but at least I want to translate more to Spanish in a near future. Of course, I also have pending the improvements I promised to exTldr (Elixir client), although I think I am the only one who use it haha.

Nice moments with all of you discussing in this project! I hope to return!

A huge hug to everyone (or a hand shake, or whatever you prefer!) and please, take care and stay safe.

**Comment by marchersimon** [comment]
You're welcome back any time, @ivanhercaz!
Again, please don't see this as any kind of punishment, it's just to keep the community as dynamic as possible.
Good luck with your future plans and I hope to see you again here sometime.

**Comment by bl-ue** [comment]
>I am trying to learn to have free time too to spend with my family and being relaxed

You should, I'm doing the same :)

>A huge hug to everyone (or a hand shake, or whatever you prefer!)

But what about social distancing? 😂🤣😆

**Comment by navarroaxel** [comment]
Done, you still have the write access to `tldr` and `extldr` repositories to collaborate when you get time for that. Rock on! :guitar:
