### ISSUE TITLE
How to keep pages up to date easily and user friendly

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#5937]
Hi, how can I keep my pages up to date.
Currently my way is to run

cd ./.tldr/tldr
git pull

however I don't feel the average user downloading from an apt repo is going to keep them up to date.

**Comment by marchersimon** [comment]
If you are using the Node.js or Python client, simply use `tldr --update` or `tldr -u`.

**Comment by CleanMachine1** [comment]
Whatever is in the apt repo.

the first longer command seems to fetch while the -u gives this

```
Invalid option `-u'

Did you mean one of these?
    -h
    -v

Usage: tldr [-v|--version] [--update] COMMAND
  tldr Client program
```

**Comment by marchersimon** [comment]
Seems like the client in the apt repo doesn't support `-u`. `--update` should work however.

**Comment by bl-ue** [comment]
I know, you're right about that.  You possibly could — I've never managed any packages on Linux package repositories, but it would probably be easy.  You'd also help a lot of users because I've encountered users that've been tripped up by this problem many a time.

**Comment by CleanMachine1** [comment]
It seems pretty easy, but having access to editing the Ubuntu forums seems out of my reach but I'll look into it

If I do find a solution which version would be used?

Python or _____

**Comment by bl-ue** [comment]
I use the Node.js one.  If it's not too much work, I'd recommend it to you as well.  But the Python one is very easy to install since it's on apt and you don't need `npm` to install it.

**Comment by patricedenis** [comment]
I've left some comments on the referenced issue about Ubuntu and Debian packages.
I'll go checking if there's a repository on salsa.

**Comment by CleanMachine1** [comment]
3 Answer

I completely agree, the apt `tldr` should be focused on since most users will assume to just run sudo apt install tldr

just like I did!

**Comment by patricedenis** [comment]
Thanks for the answer @CleanMachine1

**Comment by sbrl** [comment]
Yeah, we really need the help of a Debian packager there. From my very brief look at the process, there's a *ton* of documentation to read before you're to package something for the official Debian repos. I'd suggest we should open  a dedicated issue about getting the `tldr` package fixed, as it's likely to be quite the ordeal.

**Comment by marchersimon** [comment]
Since the original question is answered and we now have an issue for the Debian package, I'll close this issue.
