### ISSUE TITLE
git-show-branch: bug

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#5945]
- Keep going a given number of commits past the common ancester:

/tldr/pages/common/git-show-branch:34

Spelling error

**Comment by bl-ue** [comment]
Yep, you're right.  That's fixed in #5848, [here](https://github.com/tldr-pages/tldr/pull/5848/files#diff-3a973e69c0939e5dec582a3ef4ae80ae861a10c9c1d9b9ba2e3af20ed470bafeL34).
