### ISSUE TITLE
jq: add key-value search

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#5958]
I find it useful not just to output value by key, but search by key-value pair, ex. `jq 'select(.key=="value")' file.json` 
There's already 8 commands so not sure if there's room

**Comment by sbrl** [comment]
Hey there, @jxu! Unfortunately, `jq` is one of those pages like `awk`, `sed`, and others that has far too much functionality to demonstrate even a small fraction of it in the format of a tldr page, so I'm unsure how we'd be able to fit in such an example.

Perhaps it would be better suited to a `jq` cheat sheet?

**Comment by jxu** [comment]
maybe, I'm not an expert on `jq`. Someone who is should comment

**Comment by sbrl** [comment]
I'm not an expert myself, but I do use it on a daily basis for my PhD. I'm going to close this issue now, but if there's more to discuss we can always re-open.
