### ISSUE TITLE
Add collaborator: @CleanMachine1

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#5961]
Hi, @CleanMachine1! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#5950, #5948, #5947, #5935, #5923)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by CleanMachine1** [comment]
:)

**Comment by CleanMachine1** [comment]
Been hoping for it 😃 

Yes!

**Comment by sbrl** [comment]
Cool, great to have you onboard! Sending invite.

**Comment by sbrl** [comment]
Invite sent!
