### ISSUE TITLE
 getting the tldr Debian package fixed

### ISSUE THREAD

**Issue by patricedenis** [tldr-pages/tldr#5962]
As we discussed in #5937, lots of people are using the `tldr-hs` client that is installed by default when invoking `apt install tldr`.
Unfortunately, the current Debian `tldr` package is not synchronized with the upstream `tldr-hs` client maintained by @psibi.

> More information : <[https://github.com/psibi/tldr-hs](https://github.com/psibi/tldr-hs)>. 

This issue is then here to start a proposal to get this problem fixed.

For information, I'm willing to assign myself to this issue even if I will really like to collaborate with others here as well.
It will be my first attempt to packaging so don't expect this to be fixed in just a day :smiley:

**Comment by navarroaxel** [comment]
Are you thinking about create a bug report into https://bugs.launchpad.net/ubuntu?

I think we should propose to switch to https://github.com/tldr-pages/tldr-python-client like the Arch Linux family uses. Because it is the only client that supports `bash completion` (tab-tab) using the `python-argcomplete` package, as far as I know.

**Comment by psibi** [comment]
> I think we should propose to switch to https://github.com/tldr-pages/tldr-python-client like the Arch Linux family uses. Because it is the only client that supports bash completion (tab-tab) using the python-argcomplete package, as far as I know.

Note that the Haskell one supports bash completion, the steps are here: https://github.com/psibi/tldr-hs/issues/28#issuecomment-686448088 But I'm not sure if the distro's package them.

Also, since it uses optparse-applicative - it supports completion for zsh and fish too IIRC.

**Comment by bl-ue** [comment]
>I think we should propose to switch to https://github.com/tldr-pages/tldr-python-client like the Arch Linux family uses.

What about `tldr-py`?  Should we make it an alias (or the apt equivalent)?  It's currently https://github.com/lord63/tldr.py

https://github.com/tldr-pages/tldr/issues/5937#issuecomment-838880498

**Comment by navarroaxel** [comment]
@psibi why the `completion` is not documented in a more visible place? like the README.md

**Comment by psibi** [comment]
@navarroaxel Yeah, I definitely need to improve the docs. I will see if I can add a mention of it (any PR's welcome!).

**Comment by CleanMachine1** [comment]
Any progress @patricedenis

Looking forward to the day where I see it appear in my apt repo

**Comment by patricedenis** [comment]
I'm trying to implement a container's infrastructure and to understand how to package tldr as it is included in the Haskell team group in salsa. They use specific haskell packaging tools and I'm yet into reading and trying to mimic the construction of examples.

**Comment by sbrl** [comment]
Either updating the existing haskell package (if said client is still maintained), or switching to the Python client would work here.

**Comment by CleanMachine1** [comment]
The python client is also outdated, and seems to be broken on Mint (Ubuntu)

**Comment by sbrl** [comment]
Ah, that's a separate issue then that needs filing against https://github.com/tldr-pages/tldr-python-client to update `tldr-py`.

**Comment by patricedenis** [comment]
Hi, there.
Just to ping here to say that I'm still working on this issue.
I managed to read the debian packaging docs and started to update the tldr debian package.
I still got problems in the building process so I will keep you informed when this will be solved.

**Comment by CleanMachine1** [comment]
Just for anyone wanting to see the issues, heres a link.

https://github.com/psibi/tldr-hs/issues/37#issuecomment-885682110

**Comment by CleanMachine1** [comment]
I think the Debian tldr-py package is different from our tldr-python. Its an unofficial client. Don't quote me that though :) 
Try `pip install tldr` for the official python version which will match our specification and (hopefully) work.

**Comment by matkoniecz** [comment]
I know and I did it, but I initially installed apparently broken and I am curious is there already report to package maintainers that it is apparently broken.

**Comment by doolio** [comment]
@patricedenis any further progress in resolving this? Thanks.

**Comment by patricedenis** [comment]
@doolio 
Yes and as a matter of fact, the official debian `haskell-tldr` package has migrated first to instable and now even to testing since 2022-10-01 (**it is really 4 days ago**) !
Even if it is not from my contribution. In fact, I was not able to cope with the Haskell language as I did not manage to find the time to explore it, and I was stopped by modules dependencies in the compilation process.
The migration is due to the Debian Haskell Group because a regression appeared in `haskell-tldr` package. They fixed it and updated to the last version of `tldr-hs` on the same time.
Next _Debian stable_ version ([Bookworm](https://wiki.debian.org/DebianBookworm)), because it is the actual _Debian testing_ and will then have the `0.9.2-2` version !!
For now, if you are using a _Debian stable_ ([Bulleye](https://wiki.debian.org/DebianBullseye)) version and want to update your haskell-tldr version to `0.9.2-2`, you may alter your `/etc/sources.list` and add the Debian Backport Repos (see process in the two links bellow).


[https://wiki.debian.org/Backports?action=show&redirect=DebianBackports](https://wiki.debian.org/Backports?action=show&redirect=DebianBackports)
[https://backports.debian.org/Instructions/](https://backports.debian.org/Instructions/)

**Comment by doolio** [comment]
Merci Patrice.

**Comment by patricedenis** [comment]
And for those who have a Ubuntu distribution, or any Debian based distribution, it will then have the updated version on next release assuming that this one will be based on Debian Bookworm at least.

**Comment by kbdharun** [comment]
This issue has been fixed and the package was marked as a transitional package and has been moved to `tldr-hs` package name. Checkout https://github.com/tldr-pages/tldr/issues/10533 and https://github.com/tldr-pages/tldr/issues/10198

**Comment by jxu** [comment]
I look forward to the day when Debian/Ubuntu users can use `apt install tldr` like a normal program and not get a weird incompatible "Client program".

**Comment by sbrl** [comment]
Should be in a future release of Debian I think, @jxu! Our trouble is having people with time to contribute towards packaging :P

If there are more packaging systems we're not in and you have time to spare, we'd love the help in packaging a client for it :D
