### ISSUE TITLE
Changing the pinned issues

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#5964]
Maybe the help wanted issues could be pinned, the current ones are somewhat outdated.

Putting the helpwanted ones such as git-extras, may mean more people are encouraged to document things. For example I only documented some of the plain git because I saw the issue at the top and highlighted

**Comment by marchersimon** [comment]
I think we could unpin the `New directory structure` issue, the other two are fine.

**Comment by CleanMachine1** [comment]
Could I get some others opinions, I would like to put git-extras instead of the mentioned one above.
@navarroaxel @patricedenis

**Comment by bl-ue** [comment]
Sure @CleanMachine1.  Unpin #4120 and pin #5137 👍🏻

**Comment by CleanMachine1** [comment]
Done

**Comment by bl-ue** [comment]
@CleanMachine1 I think asking in the Gitter chat is enough for this; it's not important enough for a whole issue, I don't think.

**Comment by CleanMachine1** [comment]
Ok, however I feel the gitter chat is slightly inactive, and not used by anyone other than maintainers, but I don't know

**Comment by bl-ue** [comment]
You're right, it's not that active, but every few days someone starts a new discussion.  It's mostly used by us maintainers, but anyone can and is encouraged to at any time talk in it.  Also there are lots of people (especially the maintainers) that will respond to anything you have to say, usually within 1-180 minutes of your saying it 😉

**Comment by patricedenis** [comment]
I'm not sure on this one. I think I haven't got enough experience to answer here.
