### ISSUE TITLE
Possible duplicate: aria2c and aria2

### ISSUE THREAD

**Issue by gurditsbedi** [tldr-pages/tldr#5978]
I was looking at the tldr pages and found out that there is a possible duplicate:
1. [tldr of aria2c](https://github.com/tldr-pages/tldr/blob/main/pages/common/aria2c.md)
2. [tldr of aria2](https://github.com/tldr-pages/tldr/blob/main/pages/common/aria2.md)

While programs name is `aria2` and terminal command is `aria2c`. 

I have updated [aria2c](https://github.com/tldr-pages/tldr/pull/5914) page a week ago.

Is this duplicate pages intentional?
If Yes, I suggest to create a type of symlink of `aria2` to `aria2c` as `aria2c` is the command name and is more up to date.
If No, I suggest to delete `aria2` page.

**Comment by CleanMachine1** [comment]
https://meta.superuser.com/a/11953

**Comment by CleanMachine1** [comment]
Thank you for the info @gurditsbedi

**Comment by bl-ue** [comment]
@gurditsbedi good catch — `aria2` isn't even on the humongous https://manned.org, so I think we should get rid of it.  I'd suggest replacing `aria2` with an alias page that points to `aria2c`.  See [`mscore`](https://github.com/tldr-pages/tldr/blob/a81bad6485ec5bd7e98fc8a44d0f5e163a152ca2/pages/common/mscore.md) for an example.

**Comment by CleanMachine1** [comment]
I'll make a PR now

**Comment by bl-ue** [comment]
Unfortunately, we'll have to ignore them, unless we can get translations for `This command is an alias of` and `View documentation for the original command` for all languages that we have translations in.

**Comment by sbrl** [comment]
Oh, great catch - we should merge those 2 pages and lease an alias behind. 

(@CleanMachine1: Perhaps next time you could add more than just a link in a comment there?)

**Comment by CleanMachine1** [comment]
The link was just for a quick reference since the poster didn't include any evidence

**Comment by marchersimon** [comment]
We could open an issue with a checklist for all missing translations of the alias page. Then we could somewhere (maybe not in the tldr repo) have a folder with all alias templates.

**Comment by CleanMachine1** [comment]
Could you do it, then we could give i the help wanted and translation tags

**Comment by bl-ue** [comment]
Yeah, that sounds like a great idea!  We should unpin an issue temporarily and pin that one so as to get attention.  Though the project may seem rather sleepy sometimes, people can become aware of random threads quite quickly 🤔

**Comment by CleanMachine1** [comment]
Replace standard git since extras still has easy ones to encourage people

**Comment by marchersimon** [comment]
Already done 😄

**Comment by sbrl** [comment]
> The link was just for a quick reference since the poster didn't include any evidence

They might not have done, but even so it can be seen as a bit rude to just post a link on it's own like that.

**Comment by CleanMachine1** [comment]
Personally I don't see how, I just wanted to highlight the link. I didn't just leave the link and go, that would have been rude. I responded straight after adding a tag thanking the user.
