### ISSUE TITLE
Add collaborator: @SethFalco

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5993]
Hi, @SethFalco! You seem to be enjoying contributing to the tldr-pages project.
You now have had seven distinct pull requests merged (#5864, #5876, #5921, #5922, #5936, #5985, #5991)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by SethFalco** [comment]
Yes, I've love to join as a collaborator! \\(^-^)/

**Comment by SethFalco** [comment]
I hope that's alright. ^-^'
I opted to check out the interactions when other contributors were invited to become collaborators and just copied whatever happened there.

**Comment by navarroaxel** [comment]
Hi @SethFalco, invitation sent!
