### ISSUE TITLE
Replace "sudo" by # before commands that requires root privileges

### ISSUE THREAD

**Issue by ByJumperX4** [tldr-pages/tldr#6073]
It would be better to not mention the "sudo" command in the pages, because all operating systems have sudo. It would be better to use "#" before commands requiring root and "$" before commands that don't require root. For example, the BSDs don't have sudo command by default and I personally use doas instead on all my machines.

**Comment by marchersimon** [comment]
Not a bad idea, especially since `sudo` isn't the only thing you can use. The problem I see however is that tldr is aimed to beginners, which often don't know what `#` means.

**Comment by CleanMachine1** [comment]
Could you give an example as to what you mean?

**Comment by marchersimon** [comment]
For example in `wg.md`:

```markdown
- Check status of currently active interfaces:

`sudo wg`

- Print a new private key:

`wg genkey`
```
to 

```markdown
- Check status of currently active interfaces:

`# wg`

- Print a new private key:

`$ wg genkey`
```

**Comment by CleanMachine1** [comment]
Well in that case, you have to also consider that if it is common, windows users will not have sudo and will be confused when it doesn't work. However what we could do is mention that admin/root is required (sudo) to run this command.

**Comment by bl-ue** [comment]
@sbrl @waldyrious

**Comment by waldyrious** [comment]
I'm with @marchersimon on this one — we have to strike a balance between strict correctness and approachability here, and I'd say a `sudo` would be more recognizable (and more conspicuous) than a change from `$` to `#`. Besides, prompt symbols can be (and often are) customized by systems, shells, or user profiles, so a `#` would not necessarily be a universal signifier of a root prompt.

**Comment by CleanMachine1** [comment]
I like that once I installed tldr, I didn't need to learn a syntax. Having a symbol to indicate confuses.

**Comment by sbrl** [comment]
Interesting suggestion here! However, most of the Linux machines I'm aware of do in fact have `sudo` - and the platforms that don't (e.g. `windows` we don't prefix with `sudo` anyway - this is a Linux-specific convention. Additionally, the Linux distros that don't have `sudo` by default (e.g. Alpine? I'm not actually sure) are generally more for advanced users than beginners, who generally speaking are knowledgeable enough to translate the `sudo` into the equivalent for 

I'd be concerned with `$` and `#` - while intuitive for the intermediate and advanced user - would negatively impact the beginner who would try to copy and paste the command _including_ the `$`/`#`, and then wonder why it doesn't work. This then puts a significant burden on clients to make the `$`/`#` not selectable (which isn't possible in a terminal).

With these points in mind, I do not support this change proposal.

**Comment by marchersimon** [comment]
Since we all seem to agree, should we close the issue?

**Comment by CleanMachine1** [comment]
Yes imo
