### ISSUE TITLE
Add organization member: @CleanMachine1

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#6123]
Hi, @CleanMachine1! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks (#6122, #6101, #6100, #6099, #6097, #6095, #6093, #6092, #6083, #6065, #6064, #6058, #6057, #6047, #6044, #6042, and many more!).
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by CleanMachine1** [comment]
of course!

**Comment by navarroaxel** [comment]
Invitation sent!

**Comment by CleanMachine1** [comment]
Where do I accept? Am I missing something?

**Comment by navarroaxel** [comment]
@CleanMachine1 in your email I guess, maybe notifications.

**Comment by CleanMachine1** [comment]
Ah I found it, it wasn't in my notifications, it was here github.com/orgs/tldr-pages

**Comment by CleanMachine1** [comment]
`member` :smile: 

Im just about start a PR to change the contributor file
