### ISSUE TITLE
Add organization member: @SethFalco

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#6149]
Hi, @SethFalco! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks.
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by SethFalco** [comment]
Accept \\(^-^)/
Glad to be able to help out!

Like last time, I just stalked another issue like this.
I'll just open the PR already. ^-^'

**Comment by sbrl** [comment]
Sending invite :fireworks:
