### ISSUE TITLE
page edit request: nmcli

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#6152]
The current page gives NO help what so ever. 

I would recommend at least a command to edit default DNS server

**Comment by sbrl** [comment]
@CleanMachine1 `nmcli` has many subcommands. For example, we already have a page for `nmcli connection` and `nmcli device`. You can also use `nmcli --help` to show a list of subcommands.

However, I do agree that the description for the `--help` example (`Call general help`) is both grammatically incorrect and not helpful. What about this instead?

```
- Display help, including a list of subcommands:
```

**Comment by CleanMachine1** [comment]
Closing since we have issue for the entire topic of fixing them rather than a request
