### ISSUE TITLE
Token syntax `{{` and `}}` gets confused with more than two closing braces

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#6155]
Take the following document:
```markdown
# example

- Test:

`example --lib {{{fmt}}}`
```
run
```console
$ tldr --render test.md
```
Output:
<img width="195" alt="Screen Shot 2021-06-21 at 1 52 21 PM" src="https://user-images.githubusercontent.com/54780737/122806102-ea6f7600-d297-11eb-81a5-14c6a223549b.png">
Notice that the closing `}` isn't highlighted.

---

The problem code is here:
https://github.com/tldr-pages/tldr-node-client/blob/dcd5daf9fbbd73a9263136a5c64dc018b3e4ab8d/lib/render.js#L17

```console
❯ node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> code = 'example --lib {{{fmt}}}'
'example --lib {{{fmt}}}'
> code.split(/{{(.*?)}}/)
[ 'example --lib ', '{fmt', '}' ]
>
```
🤔 

---

cc @vladimyr @agnivade

**Comment by sbrl** [comment]
Hrm. I've come across this issue before actually. Ideally we need to properly define the behaviour of the `{{token_syntax}}` to avoid the issue.

**Comment by waldyrious** [comment]
(Side note: @bl-ue, please don't make so many comments one after the other. Unlike a chat, a long stream of comments in an issue makes it much harder for a discussion to form and converge.)

**Comment by bl-ue** [comment]
Apologies @waldyrious — I had a burst of fruitful thoughts 🍒💭

**Comment by bl-ue** [comment]
Related reading: https://github.com/tldr-pages/tldr/issues/731

**Comment by bl-ue** [comment]
I think a good solution would be escaping as @sbrl [suggested](https://github.com/tldr-pages/tldr/issues/6155#issuecomment-865339666).  For clients that didn't process the markdown at all and just dumped it to stdout, it would look even more ugly, but that's less of a downside.

So the markdown for this escaping would look like this:
```
`docker inspect --format='\{\{.LogPath\}\}' {{container}}`
```

And for my example in the PR description:
```
`example --lib {{\{fmt}\}}`
```

**Comment by marchersimon** [comment]
@bl-ue you mean `{{\{fmt\}}}`, right?

**Comment by bl-ue** [comment]
Yes, I did, and I updated my comment 😆

**Comment by marchersimon** [comment]
Should we keep this issue open? In the end it's up to every client to implement the rendering correctly and introducing new syntax would only break them.

**Comment by hxzhao527** [comment]
how about two backticks surrounding, like these
```
``docker ps -q | xargs -n 1 docker inspect --format '{{ .Name }} {{range .NetworkSettings.Networks}} {{.IPAddress}}{{end}}' | sed 's#^/##';``
```

display the content in raw mode?
