### ISSUE TITLE
Storing the clients list as JSON (or YAML)

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#6163]
As @MasterOdin [suggested](https://github.com/tldr-pages/tldr/issues/4044#issuecomment-629574467) in #4044, I think the best way to notify client authors of updates to the client spec is by notifying them on GitHub.  I see two choices currently:

1. Open an issue on the main tldr repo, and @-tag the client authors by their usernames, and require that each author tagged reacts to the issue with a 👍
2. Open an issue on all of the client's repos, and require that the issue be closed

Next, we need a way to determine when a client is considered unmaintained.  I was thinking that if the author doesn't respond to the ping (either by reacting to or closing the issue as said above) within a fixed timeframe, e.g. 90 days, we mark them as unmaintained and remove them from the list.  This way, we can ensure that the clients list is accurate and that changes to the spec will be implemented by all the clients in a reasonable amount of time.

---

In order to support such automation, our list of clients needs to be structured and machine-readable.  A JSON or YAML file would be perfect for that.  The pros are:

1. This service for notifying client authors (probably will be tldr-bot) can use the list
2. Any service on the internet with access to https://raw.githubusercontent.com/ can read and parse  the list for their own purposes
3. Currently, we have the README and the [wiki page](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients), which store two unsynchronized lists of clients, and where there is no defined format for a client entry. This proposal would allow for a single source of truth, which could then be used to automatically/scriptedly update the README/wiki page/whatever else in a very clean & consistent way.

I'd prefer the list to be stored as JSON, because JSON feels very structured and with YAML you make subtle mistakes.   YAML is also better for very complex structures with a lot of depth—this would just be an array of objects.

<details>
<summary>The JSON might like something like this (I left of lots of clients).</summary>

```json
[
  {
    "name": "tldr-alfred",
    "group": "Alfred",
    "git_url": "https://github.com/cs1707/tldr-alfred",
    "source_url": "https://github.com/cs1707/tldr-alfred",
    "extra_urls": [],
    "repo_type": "github",
    "maintainers": ["cs1707", "SoMuchRice"],
    "installation_methods": []
  },
  {
    "name": "tldr-alfred",
    "group": "Alfred",
    "git_url": "https://github.com/konoui/alfred-tldr",
    "source_url": "https://github.com/konoui/alfred-tldr",
    "extra_urls": [],
    "repo_type": "github",
    "maintainers": ["konoui"],
    "installation_methods": []
  },
  {
    "name": "tldr-pages Albert Plugin",
    "group": "Albert Plugins",
    "git_url": "https://github.com/bergercookie/awesome-albert-plugins",
    "source_url": "https://github.com/bergercookie/awesome-albert-plugins/tree/master/plugins/tldr_pages",
    "extra_urls": [],
    "repo_type": "github",
    "maintainers": ["bergercookie"],
    "installation_methods": []
  },
  {
    "name": "tldr-flutter",
    "group": "Android",
    "git_url": "https://github.com/Techno-Disaster/tldr-flutter",
    "source_url": "https://github.com/Techno-Disaster/tldr-flutter",
    "extra_urls": [
        "https://play.google.com/store/apps/details?id=wtf.technodisaster.tldr",
        "https://f-droid.org/packages/wtf.technodisaster.tldr/"
    ],
    "repo_type": "github",
    "maintainers": ["Techno-Disaster"],
    "installation_methods": []
  },
  {
    "name": "tldr-python-dash-docset",
    "group": "Dash docset",
    "git_url": "https://github.com/Moddus/tldr-python-dash-docset",
    "source_url": "https://github.com/Moddus/tldr-python-dash-docset",
    "extra_urls": [],
    "repo_type": "github",
    "maintainers": ["Moddus"],
    "installation_methods": [
        "Open Preferences > Downloads > User Contributed and find \"tldr pages\" in the list"
    ]
  },
  {
    "name": "leighmcculloch/tldr",
    "group": "Go",
    "git_url": "https://github.com/Moddus/tldr-python-dash-docset",
    "source_url": "https://github.com/Moddus/tldr-python-dash-docset",
    "extra_urls": [],
    "repo_type": "github",
    "maintainers": ["leighmcculloch"],
    "installation_methods": [
        "`go get 4d63.com/tldr`",
        "`brew install 4d63/tldr/tldr`",
        "Download binaries from https://github.com/leighmcculloch/tldr/releases"
    ]
  },
  {
    "name": "Outfieldr",
    "group": "Zig",
    "git_url": "https://gitlab.com/ve-nt/outfieldr",
    "source_url": "https://gitlab.com/ve-nt/outfieldr",
    "extra_urls": [],
    "repo_type": "gitlab",
    "maintainers": ["ve-nt"],
    "installation_methods": []
  },
  {
    "name": "Outfieldr",
    "group": "Zig",
    "git_url": "https://git.finzzz.net/tldr/",
    "source_url": "https://git.finzzz.net/tldr/",
    "extra_urls": [],
    "repo_type": "other",
    "maintainers": ["finzzz"],
    "installation_methods": []
  }
]

```

</details>

---

Where should we store this file?  I'm thinking it should be called `clients.json`, and should be stored in `/` (top-level).  It might be cool to put it in a new `/data` folder or something similar though, because we might have other such lists of data in the future.  Just a thought.

---

Q/A I've already though of:

> What if a user doesn't have a GitHub account?

They have to in order to submit a PR on GitHub ;)

> What if the author doesn't like reacting to comments?

I doubt this case is common, if it is, we'll discuss it then.

> What if the author wants to take a break from maintenance, but not stop maintaining the client altogether?

We could add an entry like `"pause": true` to the JSON for that client, and the bot would, if it saw that, open an issue _on that client's repository_ with a status of the changes that need to be made to the client.  Every time a spec update was released the bot would go through such issues and add a new comment with the changes perhaps, or something along those lines.  The problem is, what if the repo isn't on GitHub...

> What if the author case a special case for their client, e.g. they want to skip an update?

We'll remove them from this list, because in that case, they're not tldr clients but applications that happen to use our pages.  Which is fine, but they're not tldr clients and shouldn't be advertised on our list as such.

**Comment by sbrl** [comment]
Another alternative: client authors watch releases on this main tldr-pages/tldr repo, and then wee make a release every time  there's a client update. We've been doing this already, actually - but I don't think we've adequately let all client authors know of this.
