### ISSUE TITLE
Switch send-to-bot.py to requests from raw urllib (and do some modifications)

### ISSUE THREAD

**Issue by Stig124** [tldr-pages/tldr#6173]
I propose that the `send-to-bot.py` file should switch from `urllib` to `requests`, which is a wrapper of urllib3, and would be way more understandable/workable than `urllib.requests` (builtin support for dictionary => JSON conversion...). This script has some issues too, mainly with formatting (indentation and spacing).

A PR is underway to try fixing some of those issues and update that script

**Comment by sbrl** [comment]
Sounds like a good idea!

**Comment by Stig124** [comment]
Just lost the job I done for that, will make a PR once I finished to do that

**Comment by Stig124** [comment]
But I'll maybe need some help understanding how this script works, has I don't have any way to test this

**Comment by marchersimon** [comment]
> But I'll maybe need some help understanding how this script works, has I don't have any way to test this

Unfortunatel, @ bl-ue, who wrote the script won't be available for some time.
