### ISSUE TITLE
Call for final formatting convention

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr#622]
I'm talking about command/option descriptions, whether they should be treated as sentences (capitalized, ended with period) or short descriptions without capitalization or periods. This is almost a trivial topic but I feel too much time is wasted on this.

I'm going to write a tool that lints our pages even further so we can minimize our time spent on these issues, given the recent waves of PRs. I'll discuss this tool in a separate issue, but it'd be best if we could settle on a convention so the tool can unambiguously decide when something is off.

The current state is as follows. We are consistent within a page but not among pages. The [contributing guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format) hint at no caps, no periods. Checking the examples section of `man` in its man page, I see full sentences.

I support the latter. We have actual English sentences so we can have actual English sentence decorations. Besides, it's prettier. I'm throwing this out there so others can object if needed and we can finally have this set in stone.

**Comment by waldyrious** [comment]
I agree: full, capitalized, punctuated sentences. And using the infinitive tense, not the present (e.g. "Print x", not "Prints x"). The latter is not enforceable in lint but is suitable for contributing.md.

**Comment by waldyrious** [comment]
Actually, regarding punctuation, maybe we can agree to use colon (:) rather than period (.), since that is what colons are for, and besides it helps clarify that the commands come after the description.

**Comment by igorshubovych** [comment]
What if there are two sentences?

```md
- Sentence 1. Sentence 2

`example 1`
```

**Comment by waldyrious** [comment]
I'd suggest "Sentence 1 (Sentence 2):", but that may not be appropriate in all cases.

**Comment by ostera** [comment]
+1

```md
- List directories:
`ls`

- List directories in a single column:
`ls -1`
```

Also, it's hard for me to think of an example where you would absolutely need two sentences that couldn't be written in a single one.

**Comment by rubenvereecken** [comment]
How about the very first description: a full-fledged sentence as well? We usually have caps but not periods.

**Comment by rubenvereecken** [comment]
I rendered that colon suggestion and I think it looks silly. You get this nice colored relation between description and command which is instinctively obvious, then the colon screams its support. It feels unnecessary because it's already made very clear that they're description/command.

**Comment by ostera** [comment]
@rubenvereecken IMO having a colon is semantically more correct than not having one.

Without one, a command could easily be related to the description below it – whereas with one the relationship is made obvious.

**Comment by rubenvereecken** [comment]
That's indeed so viewed textually, I've actually often mistakenly combined the wrong command and description. Once viewed through my node client though the distinction is made clear because there's no empty line between related description/command.

**Comment by waldyrious** [comment]
My arguments are the same as @ostera's. I'd rather err on the side of being more explicit than necessary (e.g. in the node client) than being less explicit than needed (elsewhere).

Also, regarding the main description, I agree it should be a full sentence, capitalized and punctuated (with a period).

**Comment by rubenvereecken** [comment]
Alright, the linter follows. Glad we got a draft here early on. Eager to hear back from @igorshubovych and maybe another collaborator.

**Comment by rubenvereecken** [comment]
In the meantime, we should have a think about how to get rid of all current inconsistencies. Especially if we're going with the colon. A script could do it, but it's a bit of a pain to write. My parser (in the linter) already has a good foundation.

**Comment by waldyrious** [comment]
Another think that we should define is how to format tokens in the example descriptions. I suggested in https://github.com/tldr-pages/tldr/pull/590#discussion_r48820085 that we could use either \`\` or {{}} to identify them, but @igorshubovych suggested in https://github.com/tldr-pages/tldr/pull/530#discussion_r49004348 that \`\` should only be used for other commands, not tokens. This gave @joelhy conflicting advice and he had to change his PR accordingly. We should have this clearly defined in the contributions guidelines.

**Comment by rubenvereecken** [comment]
Funny that you say that @waldyrious, just now my formatter choked on a command wrapped in backticks in the description. So what would @igorshubovych have for token delimiters instead?

`tldr-format.js` is a fact and runs smoothly on all currently existing pages. Expect a PR soon that cleans up our pages according to the guidelines that we're discussing here, once I'm bothered. @igorshubovych, I'd say now is the time to get your say in about line endings. Currently we're veering towards colons.

**Comment by igorshubovych** [comment]
I agree with colons

**Comment by rubenvereecken** [comment]
This can be closed now since `CONTRIBUTING.md` is adapted.

**Comment by waldyrious** [comment]
So... what do we decide about formatting tokens in the descriptions?

**Comment by rubenvereecken** [comment]
@waldyrious, I pushed a version to a [separate branch](https://github.com/tldr-pages/tldr-lint/tree/lint-verb-tense) of `tldr-lint` that checks for gerunds and present tenses. However, we need some cleaning up first. At the same time we must verify it works. The current regexes are crafted while looking at our current pages; they are covered by tests derived from those. I can't guarantee I haven't missed any weird cases, but it looks complete so far.

**Comment by waldyrious** [comment]
The regexes as I proposed in #677 did catch only valid matches. Any particular reason you tweaked them? Especially the present tense regex needed the "e" before "s" to prevent false positives. It would miss "Displays" in qlmanage.md and "Installs" in bundle.md, which yours catches, but yours also catches "Continuous" in free.md, which is indeed an error, but a different one (and one I don't think we can catch automatically). So at the very least we should add "u" to the exclusion list (negated character class) before the final "s".

Also, in my local tests I have to include the "- " for the regex to work. Does your linter do any pre-processing to remove those?

**Comment by rubenvereecken** [comment]
Thanks for catching that particular case, I missed it as I was sure I'd miss something. Indeed, the linter handles line starting symbols differently so those can be passed on to the compiler part which is a CFG because the latter has more context and can catch some nastier bits. What the linter

**Comment by rubenvereecken** [comment]
By the way, something useful I found out for future breaking lints is that you can install through npm directly from a specific branch. In this case it's `npm install tldr-pages/tldr-lint#lint-verb-tense`

**Comment by waldyrious** [comment]
Thanks for the explanation about the "- ", I expected it would be something like that. But I'm still curious about the other changes (`[A-Z][a-z]{2,}` --> `[A-Za-z]{3,}` and `[A-Z][a-z]+es ` --> `[A-Za-z]{1,}[^s]s `). Are you expecting words to begin with two capital letters? Or want to leave capitalization to be dealt with by another rule?

By the way, `{1,}` is the same as `+` (although to match the original it should be `{2,}` anyway).

**Comment by rubenvereecken** [comment]
Hehe I overlooked that I left a `{1,}` while tweaking. Alright I'll have a look at the differences. Disclaimer though: I wrote the regexes while sleepy.

```[A-Z][a-z]{2,} --> [A-Za-z]{3,}```
It's the same if you stop caring for caps at all, which is what it does. The capital check has already passed before this regex, so we're sure this is the first word of a sentence. It may be badly capitalized, but we should still treat it. That's why I rewrote the linter entirely: focus on recoverability.

```[A-Z][a-z]+es --> [A-Za-z]{1,}[^s]s or [A-Za-z]+[^s]s```
Not quite the same. Allow for one letter less (so 3 or more for the whole word). Why? Don't know, because it doesn't matter between 3 or 4 really. This should still incorporate cases for examples like `continuous`, as you mentioned. I just wanted to cover more than just the `-es` endings, like `ys`, `ts`...

**Comment by waldyrious** [comment]
> The capital check has already passed before this regex, so we're sure this is the first word of a sentence.

Assuming that that check already ensures that only the first letter is uppercase (if it doesn't, it should \*hint hint\*), then we could simply do [a-z] here and make the pattern case insensitive.

> Allow for one letter less

No problem with that. I only had two letters before for the capitalization thing, and only had "es" to prevent false positives like "Continuous". So if we make it case-insensitive, it could be `[a-z]+[^su]s`. What do you think?

**Comment by rubenvereecken** [comment]
> No problem with that. I only had two letters before for the capitalization thing, and only had "es" to prevent false positives like "Continuous". So if we make it case-insensitive, it could be [a-z]+[^su]s. What do you think?

Agreed :+1:, seems to work so far.

> Assuming that that check already ensures that only the first letter is uppercase (if it doesn't, it should *hint hint*), then we could simply do [a-z] here and make the pattern case insensitive.

It ensures that but then doesn't repair it, nor does it stop there because it wants to capture as many errors as possible. Following rules just have to take into account that they're getting 'deteriorated pages'. This is the reason why I completely threw away my beautifully crafted regex that could match any description _as we'd like them_ by `.*`. Devastating really. 

I'll push changes in a sec to aforementioned branch.

**Comment by rubenvereecken** [comment]
Merged, fixed, what have you. It's now active in Travis.
