### ISSUE TITLE
`linux/arch.md` has Chinese translation but no English page

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6232]
In `common` we have both an English and [Chinese](https://github.com/tldr-pages/tldr/blob/main/pages.zh/common/arch.md) page, but in `linux` we only have a [Chinese](https://github.com/tldr-pages/tldr/blob/main/pages.zh/linux/arch.md) page. Since the Chinese pages differ, I don't know if I just should remove the `linux`. (cc @blueskyson @BillLucky)

**Comment by BillLucky** [comment]
My opinion is that you can choose to delete or add the English page, depending on which situation is suitable for us. I personally think that both options are fine. @marchersimon

**Comment by blueskyson** [comment]
`arch` in `common` page seems to be the main version of `arch`, so I think `arch` of `linux` page should be removed.

**Comment by marchersimon** [comment]
So how does the page in `common` differ from the one in `linux`? If they are pretty much the same I think we should delete the Chinese `linux` one, but if they differ we should add the English `linux` one.

**Comment by blueskyson** [comment]
The official site for `linux`: [https://www.gnu.org/software/coreutils/arch](https://www.gnu.org/software/coreutils/arch)
Non official site for `OS X`: [https://www.unix.com/man-page/osx/1/arch/](https://www.unix.com/man-page/osx/1/arch/)
According to above sites, `arch` of `OS X` provides more options than `linux` one. Besides, I didn't find any unix or windows man page of `arch`.

**Comment by marchersimon** [comment]
Aha, thanks. Even tough they differ, both pages only demonstrate the usage of `arch` without any argumetns. So, I think we can either delete the `linux` one or move it to `common` and delete the `common` one. So, basically we keep the better page (in terms of quality). Which one would you pick?

**Comment by blueskyson** [comment]
I prefer to delete the `linux` one.

**Comment by marchersimon** [comment]
Then it shall be done!

**Comment by marchersimon** [comment]
Thanks for your help @blueskyson and @BillLucky
