### ISSUE TITLE
Lint-tldr for conventions

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr#624]
As mentioned in #622, I'm looking to create a tool that lints files according to our conventions: The expected order of name, general description, option descriptions etc. This would speed up our contributing efforts by having Travis do the grunt syntax parsing and nagging when something is not as it should be.

Our current 'stack' is bash and regrettably Ruby (ok and Make). I did not want to expand this at first because users shouldn't have to download a whole language interpreter just to do a quick lint, but looking at Ruby I changed my mind. Since it's mostly Travis executing the script and not contributors, I figured I could just as well write a Python or JS script, languages I _can_ write. Just throwing this out there for now, so people can object if they feel my reasoning is off. Expect the script some day.

EDIT: [tldr-lint](https://github.com/rubenvereecken/tldr-lint)

**Comment by igorshubovych** [comment]
Awesome initiative. Let me know if you need help with it.
If you want to write in JS it is ok too. Travis does not care.

**Comment by rubenvereecken** [comment]
JS it is.

**Comment by rubenvereecken** [comment]
WIP [here](https://github.com/rubenvereecken/tldr-lint). It's a sufficiently big script to be developed separately I figured. Please don't spam it yet, it's still heavily under development.

**Comment by igorshubovych** [comment]
@rubenvereecken should this be closed?

**Comment by rubenvereecken** [comment]
I want some issue to track merging `tldr-lint` in Travis, so I'll keep this and update it.

**Comment by rubenvereecken** [comment]
Let's close this baby for now.
