### ISSUE TITLE
Idea: add indication of short option when possible

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6246]
In the end, this has to be implemented by every client, but I think this should be discussed here.
So, this is my idea:
![Screenshot_20210718_122704](https://user-images.githubusercontent.com/50295997/126063822-30979a53-c65d-4694-bbba-20db06fc7939.png)

When the first character of a long option does match the short option, we could colorize (or maybee underline) that character. The big problem is, that we'd have to introduce new syntax for that, so I don't think it's going to happen, but I think it's worth considering.

(I just now saw that the example above isn't even correct, but I hope you get my point 😄)

**Comment by marchersimon** [comment]
I just realized that this could be done without any additional syntax: By using token syntax. 
Example: `git commit --{{m}}essage "message"`
Freshly rendered by tldr without errors and the need of additional syntax:
![image](https://user-images.githubusercontent.com/50295997/126529119-9e54c034-311d-4583-912d-201a20b87251.png)

**Comment by CleanMachine1** [comment]
Does this apply to other clients?

**Comment by sbrl** [comment]
Long options use a double dash `--` and single ones often use a single dash `-` though? But not always - depends on the tool

**Comment by marchersimon** [comment]
But what if we would just do this for the very common pages where we know they use `-` and `--`?

**Comment by CleanMachine1** [comment]
Some things are inferred, and the only possible solution I can think of is E.G. `command {{--help|-h}}

**Comment by marchersimon** [comment]
I see this doesn't really catch on. (I didn't really expect it to, but it was worth a try).
I'm closing this now.
