### ISSUE TITLE
Idea: Add ISSUE_TEMPLATE forms

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#6257]
The current usage of issues/the standard is the user enters a title and comment, then members add tags and other basic tasks.

This, in return means some issues may get titled wrong, such as instead of what would be the format `page request: {{page_name}}` instead the user may enter `Make a page for {{page_name}}`.

This just creates admin work and could easily be fixed.

If this is to go ahead, we need to discussed following things. 

How many forms would be make, the more there are, the more likely they will use the wrong one. Keeping it minimal such 

1 form for: page request, page edit request, ideas, and clients 

(This wouldn't be enough, since there are others, however maybe complex ideas such as changes to localization could be left alone, and let the user make a completely new issue (there is an option for when creating so that the user can ignore the templates))

Overall, this will make the user experience for contributors a little easier and make admin work less for others.

**Comment by CleanMachine1** [comment]
ps, feel free to change the label if it is wrong.

**Comment by marchersimon** [comment]
How would that work? Are these templates just some text, which the user can then edit or is it possible that a template automatically sets the correct title and labels?

**Comment by CleanMachine1** [comment]
I only have 1 repo that I know uses them.

However, what happens is the user goes to create a new issue then is greeted by this.

![https://ibb.co/9r1vDq2](https://ibb.co/9r1vDq2)

This allows the user to select from premade issue templates, where they can just fill the gaps, like how our PR template is.

**Comment by marchersimon** [comment]
Looks amazing. But this doesn't exist for PRs right? That's where we would need it the most.

**Comment by CleanMachine1** [comment]
This has since been added via this PR

#7743
