### ISSUE TITLE
page request: openscad

### ISSUE THREAD

**Issue by chrissxYT** [tldr-pages/tldr#6268]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment

**Comment by marchersimon** [comment]
Hey @chrissxYT, thanks for the request. Would you like to add that page yourself? It's not hard at all, just have a look at https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md and https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md.
