### ISSUE TITLE
page request: auditctl

### ISSUE THREAD

**Issue by d33tah** [tldr-pages/tldr#6280]
*Most issues on this repo are requests for new commands. If it's the case, make sure to use the standard title ("page request: <command name>"), and include a link to a web page about the command, and if possible, to an existing source of example-style documentation.*

https://linux.die.net/man/8/auditctl

**Comment by CleanMachine1** [comment]
Heres a better man page we will use.

https://manned.org/auditctl

**Comment by spageektti** [comment]
I opened a PR adding page for this command.
