### ISSUE TITLE
Possible duplicate: http and httpie

### ISSUE THREAD

**Issue by nyameteor** [tldr-pages/tldr#6287]
I was looking at `http` in tldr pages and found out that there are two pages for this command:

- [httpie in linux page](https://github.com/tldr-pages/tldr/blob/main/pages/linux/httpie.md)
- [http in common page](https://github.com/tldr-pages/tldr/blob/main/pages/common/http.md)

I took a cursory look at [HTTPie documentation](https://httpie.io/), it seems like this command is cross platform now. 
Are these two pages separated intentionally, or maybe they could be merged?

**Comment by marchersimon** [comment]
In this case they should definitively be merged and put in the `common` platform. Thanks for bringing that to our attention.
I'm just a bit confused about why there are two names for this command (`httpie` and `http`). Is one an alias for the other?

If you'd like you can open a PR to merge those two pages and also update it a bit if you want.

**Comment by nyameteor** [comment]
OK, I understand. I think `http` is not an alias for `httpie`. `httpie` is the package name, while `http` is the command name of this package, so `httpie` need to be merged to `http`.

Because there are different examples in these two pages, could you contact the contributor of `http` page to decide what example should be merged? I think the contributor will do it better than me.

**Comment by marchersimon** [comment]
Alright. The `httpie` page shold've been called `http` from the start.
I think we could do this on our own, but it can't hurt to involve a developer. @bobotig (seems to be the most active at the moment):
If you'd like to, it woud be great if you could take a look at our `http` page and give your opinion.

**Comment by nyameteor** [comment]
Oh, maybe I didn't express correctly, I meant to let the contributor of `tldr` `http` page to decide what examples should be kept, but if the developer of `httpie` software could give suggestions, it will be nice.

And, OK, I will look at `http` page and try to give my opinion :)
