### ISSUE TITLE
page request: pacman-key

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#6294]

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by CleanMachine1** [comment]
I haven't got an idea how to use it! Was hoping someone would see it and know immediately what to write
