### ISSUE TITLE
Should the style guide be translated?

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6303]
After fixing our Chinese punctuation, we try to document that in our style guide. @noarchwastaken translated the whole style guide into Chinese and added those rules in #5952. Since we can't review that, @blueskyson added those rules to our style guide in #6285. The question is now if we should even merge #5952, since that would be our only translation of the style guide.

The pros and cons I thought abouts
```diff
+ More translations means more people to contribute to the project
- But it also means more efforts for maintainers to keep them all up to date
```

**Comment by CleanMachine1** [comment]
I don't see why not. The more people that can actually access information about how to make a page, the more there will be that actually decide to contribute

**Comment by blueskyson** [comment]
I personally approve to have style guide in other languages as I commented in [#6825](https://github.com/tldr-pages/tldr/pull/6285#issuecomment-891976110): "better than nothing".

**Comment by sbrl** [comment]
Seems like a good idea to have translated style guides. It seems like people are stepping up to translate them, so it shouldn't be too much of an issue. We could perhaps suggest in the translated version that the English version is most up to date or something like that perhaps.

**Comment by marchersimon** [comment]
Closing, since we all seem to agree to have translations.
