### ISSUE TITLE
page request: hcitool

### ISSUE THREAD

**Issue by sreekesari-vangeepuram** [tldr-pages/tldr#6315]
# Tool: hcitool
`hcitool` basically `configure Bluetooth connections`

# Description
> hcitool is used to configure Bluetooth connections and send some special command to Bluetooth devices. If no command is given, or if the option -h is used, hcitool prints some usage information and exits.

Documentation on `hcitool` can be found [here](https://wiki.tizen.org/Bluetooth).

# Reason (to add this page)
I recently got the need to use this tool and when I tried to `tldr` it. It was unavailable and gave the output as below:
```console
$ tldr hcitool
`hcitool` documentation is not available. Consider contributing Pull Request to https://github.com/tldr-pages/tldr
```
So after seeing this, I thought of opening a new pull request to add a page on this tool.
I think it would be helpful for the people those who want to work with
`hcitool` on the go, while solving there problem(s) or for learning purposes.

#### Thank You

**Comment by CleanMachine1** [comment]
https://github.com/tldr-pages/tldr/pull/6310 whats wrong with this PR?

**Comment by CleanMachine1** [comment]
PS, consider upgrading your python TLDR

pip3 install --upgrade tldr

**Comment by sreekesari-vangeepuram** [comment]
> #6310 whats wrong with this PR?

This is about PR #6311

**Comment by CleanMachine1** [comment]
Yes but why were a duplicate PR made

**Comment by sreekesari-vangeepuram** [comment]
I actually reforked the repo. So I made a new PR.

**Comment by CleanMachine1** [comment]
Ah, OK. I see.

We have no objection to user created pages, its actually what is meant to happen. TLDR is made by a community of random people who found a missing page and wanted to contribute it.

No request has to be made, and users can make whenever they feel for us (the maintainers) to fix/review.

**Comment by sreekesari-vangeepuram** [comment]
Awesome!

**Comment by sreekesari-vangeepuram** [comment]
@CleanMachine1 I hope the page is ready now.
