### ISSUE TITLE
move pkg-config to common

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6317]
https://www.freedesktop.org/wiki/Software/pkg-config/, https://gitlab.freedesktop.org/pkg-config/pkg-config/-/blob/master/pkg-config.1 or https://gitlab.freedesktop.org/pkg-config/pkg-config (let's let the author of the page decide)

**Comment by CleanMachine1** [comment]
Can we not just link to here instead for the entire repo view? https://gitlab.freedesktop.org/pkg-config/pkg-config

Although the link you have provided is more specific to help rather than information, and still to this day, I don't know whether one or the other should be used.

**Comment by marchersimon** [comment]
@pixelcmtd this page does already exist. It has been added in #4045

**Comment by pixelcmtd** [comment]
@marchersimon oh thats interesting so much code review and nobody thought of putting it in the right platform
