### ISSUE TITLE
page request: lerna

### ISSUE THREAD

**Issue by dwy6626** [tldr-pages/tldr#6325]
A tool for managing JavaScript projects with multiple packages: https://github.com/lerna/lerna / https://lerna.js.org

**Comment by npalladium** [comment]
Interested in taking this up. Will do it over the weekend. Any concerns/tips before I start?

**Comment by navarroaxel** [comment]
Hi @npalladium, try to base your example descriptions in examples already merged from similar commands if possible. Good luck.

**Comment by npalladium** [comment]
I'm going to cover five commonly used commands: `lerna {init, run, exec,bootstrap,publish}` and the `--concurrency` and the `--scope` flags. These are what I commonly use. Feedback on what to cover to be useful is appreciated.

Please expect a draft PR sometime this weekend. Cheers!
