### ISSUE TITLE
page request: xcodebuild

### ISSUE THREAD

**Issue by xiaoyu2006** [tldr-pages/tldr#6339]
xcodebuild: https://www.manpagez.com/man/1/xcodebuild/

**Comment by marchersimon** [comment]
@xiaoyu2006 we already have a [xcodebuild](https://github.com/tldr-pages/tldr/blob/main/pages/osx/xcodebuild.md) page 🤔 
But it could need some improvement.

**Comment by xiaoyu2006** [comment]
@marchersimon Oh sorry I didn’t find it. Maybe I can work on this page.

**Comment by marchersimon** [comment]
Sure, that would be great
