### ISSUE TITLE
page request: mk

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6345]
http://doc.cat-v.org/plan_9/4th_edition/papers/mk, maybe https://manned.org/mk
you can derive it in part from `make`

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
