### ISSUE TITLE
page request: vi, r2, ex, cola

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6346]
all of these are aliases.

- [x] `vi`: `vim` → #6435 
- [x] `r2`: `radare2` → #6436 
- [ ] `ex`: `vim` (or maybe it's own page) → #6595
- [x] `cola`: `git-cola` → #6472

**Comment by sbrl** [comment]
Hey there! Thanks for requesting this page. As you've noted, we already have a page for `vim`. This sounds like a good candidate for an [Alias Page](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/alias-pages.md#alias-pages). Would you like to contribute an alias page for `vi`?
