### ISSUE TITLE
page request: pfetch

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6352]
https://github.com/dylanaraps/pfetch

we just need 1 example, cause it doesnt have any arguments

**Comment by Gitleptune** [comment]
I could do it, I also know the creator on Discord so I can ask them if it's correct afterwards.

**Comment by iuliandita** [comment]
I'm not sure what the tldr page for pfetch would look like, as it's literally just one command, but I guess we can show the ENV options to limit or manipulate output:

`USER="user" HOSTNAME="hostname" XDG_CURRENT_DESKTOP="desktop_environment" PF_INFO="ascii title os host kernel uptime pkgs memory editor shell de palette" pfetch`

**Comment by sbrl** [comment]
Great idea, @iuliandita!
