### ISSUE TITLE
page request: lb, sup, zm

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6353]
- [x] [lb](https://github.com/LukeSmithxyz/lb) → https://github.com/tldr-pages/tldr/pull/6354
- [ ] [sup](https://github.com/LukeSmithxyz/lb) → #6531
- [x] [zm](https://github.com/ZERMZeitung/zm2) → https://github.com/tldr-pages/tldr/pull/6355

**Comment by sbrl** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
