### ISSUE TITLE
Let's document: XML starlet

### ISSUE THREAD

**Issue by daniel-birket** [tldr-pages/tldr#6368]
XML starlet is a toolkit with subcommands to query, edit, check, transform and perform other operations on XML documents.
See <http://xmlstar.sourceforge.net> and <http://xmlstar.sourceforge.net/doc/xmlstarlet.pdf>.

I've already started work on this. It has a main `xml` entry and twelve subcommands. I'm creating this issue to serve notice that it's a work in progress (instead of annoying you with an incomplete pull-request). The draft main entry is below:

-----
# xml

> XMLStarlet toolkit: Query, edit, check, and transform XML documents.
> Subcommands: `canonic`, `edit`, `elements`, `escape`, `format`, `list`, `pyx`, `p2x`, `select`, `transform`, `unescape`, or `validate`.
> More information: <http://xmlstar.sourceforge.net/doc/xmlstarlet.pdf>.

- Execute a subcommand with input from a file or URI and using standard output:

`xml {{subcommand}} {{options}} {{path/to/input.xml|URI}}`

- Execute a subcommand using standard input and standard output:

`xml {{subcommand}} {{options}}`

- Execute a subcommand with input from a file or URI and output to a file:

`xml {{subcommand}} {{options}} {{path/to/input.xml|URI}} >{{path/to/output}}`

- Display help for a subcommand:

`xml {{subcommand}} --help`

- Display general help:

`xml --help`

- Display version:

`xml --version`

**Comment by blueskyson** [comment]
Wow, it looks great. Thank you in advance!

**Comment by marchersimon** [comment]
If the subcommand pages aren't very similar, I think it would be easier to review, if we have one PR per new page.

**Comment by daniel-birket** [comment]
> If the subcommand pages aren't very similar, I think it would be easier to review, if we have one PR per new page.

I saw this suggestion after sending the PR. Note that I think it's easier to manage writing it as one PR instead of 13. I'm not in a hurry to have some of the pages accepted before others. I'll finish the tough 3 when I can and request a review then. Question: what exactly does a "draft pull request" do? Would that have been more appropriate for this incomplete PR?

**Comment by marchersimon** [comment]
It just tells everyone that it's work in progress and prevents it from being merged. Basically, if it's not ready to be reviewed it should be a draft PR.
