### ISSUE TITLE
Refering to sub-command pages of a command

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6369]
We've lately had some PRs to add examples to a page, which were already covered by it's subcommand-pages. And that's no surprise, because we don't mention those in any of the pages. If you're new to `tldr` and you're searching `tldr git`, how should you know that there's also a page for `git-commit`, `git-push`, etc.?

That's my ideas:
* Add a ``See also: git-`subcommand` `` note in every page
* Add an example ``Show tldr documentation for subcommands:  `tldr git-{{subcommand}}` `` (But often there isn't any space for that.)
* Maybe some other note like `This command also has documentation about its subcommands`

That could be a problem if we don't have documented every single subcommand, but if we don't have one users find out pretty quickly.

**Comment by CleanMachine1** [comment]
I like the last suggestion, in multiple instances I have tried to run a command for tldr and I get a terrible page with just _command {{subcommand}}

Then since I understand the layout of our pages I find the subcommand page.

I agree that a simple note should be made about our documentation of subcommands.

**Comment by blueskyson** [comment]
I prefer to the second idea and I think it would be clearer to display a concrete subcommand rather than `tldr git-{{subcommand}}`.

> Show tldr documentation for subcommands, e.g. `tldr git-push`.

**Comment by sbrl** [comment]
Adding to the description  of a page probably makes the most sense. @blueskyson's suggestion is a good idea (though `tldr git-push` would be `tldr git push`).

**Comment by marchersimon** [comment]
I personally prefer to write `git-push`, because it looks a bit cleaner to me.

**Comment by marchersimon** [comment]
I just realized that we need this phrase in every language. That translation platform we once talked again would come quite handy here.
Should we maybe have one big file where we keep all common phrases in all languages, like `alias-pages.md`? Or a directory with one file per phrase?

**Comment by sbrl** [comment]
@marchersimon true, but that's not the command that the user will actually end up executing, so I suggested `tldr git push` to avoid confusion

> I just realized that we need this phrase in every language.

Good point. 1 big file doesn't sound like a bad idea
