### ISSUE TITLE
page request: egrep, rgrep, bzgrep, bzegrep, bzfgrep, zgrep, zegrep, zfgrep, ptargrep, zipgrep

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6382]
- [x] [egrep](https://manned.org/egrep) → #6737
- [x] [rgrep](https://manned.org/rgrep) → #7021 
- [x] [bzgrep](https://manned.org/bzgrep) → #7145
- [x] [bzegrep](https://manned.org/bzegrep) → #7199
- [x] [bzfgrep](https://manned.org/bzfgrep) → #7211
- [x] [zgrep](https://manned.org/zgrep) → #4131
- [x] [zegrep](https://www.unix.com/man-page/freebsd/1/zegrep/) → #7233
- [ ] [zfgrep](https://www.unix.com/man-page/freebsd/1/zfgrep/)→#8708
- [x] [ptargrep](https://manned.org/ptargrep) → #7050
- [x] [zipgrep](https://manned.org/zipgrep) → #7004

**Comment by antoine-amara** [comment]
Hello, I'm working on `egrep` command, I will open a PR soon. I can open an other PR with a french translation too.

**Comment by CleanMachine1** [comment]
Thanks @morevi for the notice, we must have missed it with the flood of hacktoberfest :smile: 

fixed now.

**Comment by dz-at-tc** [comment]
Looking at the task list above, I think:

bzfgrep is complete via PR #7211

zegrep is complete via PR #7233

zfgrep is in progress via my new PR #8708 

So assuming my latest submission gets merged eventually, this issue will finally be complete, yay!
