### ISSUE TITLE
Request: add option to `set-more-info-link.py` to sync translations.

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6385]
It's really hard to ensure all translations have the same more information link as the English page, especially when reviewing PRs which add the links. It would be awesome it there was a `--sync` option, which makes sure every translated page has the same link. I tried to add that myself, but my Python skills weren't good enough. So, I'm leaving this here for somebody who wants to implement this. (Maybe @blueskyson)

**Comment by blueskyson** [comment]
OK, I'll work on it.
