### ISSUE TITLE
page request: ebuild

### ISSUE THREAD

**Issue by pshirshov** [tldr-pages/tldr#646]
What about small ebuild for gentoo?

**Comment by igorshubovych** [comment]
What do you mean? Page for ebuild? You are free to add it.

**Comment by igorshubovych** [comment]
Feel free to add this page.
You should start with [Contributing guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md).

**Comment by pshirshov** [comment]
Eh, actually I meant an ebuild available to use but this is fine too, lol.

**Comment by sbrl** [comment]
What do you mean "an ebuild available to use", @pshirshov?

**Comment by pshirshov** [comment]
Ah, an ebuild in overlay or in the main tree, ehm.

**Comment by sbrl** [comment]
Ah, I think I see. I've done some research, and ebuild appears to be a bit like Arch's AUR I think?

To that end, are you asking for a tldr client available via ebuild, @pshirshov?

**Comment by pshirshov** [comment]
Yup for both questions. Yes, it's similar to aur, yes I've been asking exactly for that :)

**Comment by sbrl** [comment]
Ah, ok! This is the repo for just the pages. If you'd like an ebuild package for tldr-pages, you should probably ask in the repository for one of the clients listed in the readme.
