### ISSUE TITLE
md5sum: change token filename1 to filename

### ISSUE THREAD

**Issue by arunisaac** [tldr-pages/tldr#6460]
In the first example of `pages/common/md5sum.md`, it would be better if the token `filename1` is `filename` instead.

Cheers!

**Comment by marchersimon** [comment]
Definitevely! Would you like to open a PR for that?

**Comment by marchersimon** [comment]
Also, I think we sholud change all `filename` to `path/to/file`, since that's the syntax we're currently using

**Comment by glapa-grossklag** [comment]
> Also, I think we sholud change all `filename` to `path/to/file`, since that's the syntax we're currently using

It looks like all the `${HASH}sum` pages (i.e., `sha256sum`, `sha512sum`, `b2sum`, etc.) also need to be updated.
