### ISSUE TITLE
Simple Jquery client

### ISSUE THREAD

**Issue by TheAshwanik** [tldr-pages/tldr#647]
Hi @felixonmars   

I have created a Simple Jquery client using the Github APIs.
I did not want to install nodejs at work..

https://github.com/TheAshwanik/tldr-Jquery-client

**Comment by felixonmars** [comment]
Calling @ostera and @igorshubovych :P

**Comment by igorshubovych** [comment]
So what do you want?
You want it to be listed in README.md?

**Comment by TheAshwanik** [comment]
Really its upto you,I just wanted to inform. If you could include in the README, it will be great.

**Comment by igorshubovych** [comment]
For now I added it on Wiki page [TLDR clients](https://github.com/tldr-pages/tldr/wiki/TLDR-clients).
We plan to have all related projects there and remain only a few on README.md.

Question: would it be difficult for you to host it somewhere? Let's say on Github pages.

**Comment by TheAshwanik** [comment]
Thanks a lot.

I am working on moving it to Github-Pages. Sure will let you know.

**Comment by ostera** [comment]
Closing as there's nothing else for us to do here. Thanks for contributing!
