### ISSUE TITLE
Duplicate pages from `linux` and `osx`

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6489]
I've noticed that there are many duplicate files in `linux` and `osx` which should be moved to common. Sometimes the same page has two different translations, which makes it hard to decide which one to keep.

Here's a list of all pages which are (probably) duplicates:

- [x] compgen.md → #6508
- [x] eval.md → #6508
- [x] export.md → #6508
- [x] fc.md → #6487 
- [x] feh.md → #6487 
- [x] file.md → #6508
- [x] hexdump.md → #6549
- [x] hostname.md → #6487 
- [x] logger.md → #6549
- [x] netstat.md → #6549
- [x] n.md → #6549
- [x] nm.md → #6549
- [x] pdfgrep.md → #6549
- [x] pwgen.md → #6551
- [x] ssh-add.md → #6487 
- [x] sshuttle.md → #6551
- [x] trap.md → #6551
- [x] tree.md → #6551
- [x] whereis.md → #6552
- [x] xar.md → #6552
- [x] yank.md → #6552

**Comment by Suletta-Majo** [comment]
I'm trying to use this awesome library from my own application  
So, I felt the same question, and when I searched for the `pages` directory with the find command,  
it seems that there are duplicate files such as `cat, du, ed, tail, etc`  
As you can see, there are still duplicate items in the OSX directory that are duplicates.  
it reason such as the description is for OSX?  Is this the right state?

**Comment by kbdharun** [comment]
> I'm trying to use this awesome library from my own application  
> So, I felt the same question, and when I searched for the `pages` directory with the find command,  
> it seems that there are duplicate files such as `cat, du, ed, tail, etc`  
> As you can see, there are still duplicate items in the OSX directory that are duplicates.  
> it reason such as the description is for OSX?  Is this the right state?  
> 
> I'm reading here right now, oh This was a project that started for OSX, so there's an OSX directory here
> https://github.com/tldr-pages/tldr/issues/1966

Hi,

Most the UNIX commands like these have a lot of additional or unsupported options we document the Opengroup's POSIX variant of the command (standardized options same across multiple directories) in `pages/common` and we document the platform specific commands/additional flags under the respective directories.

This is done to avoid situations where the tldr page documents an option but it doesn't work/exist for your platform.

**Comment by Suletta-Majo** [comment]
Thanks for the explanation Since I am a beginner in programming,  
I made a program that simply searches and displays the search command name +.md  
The search destination path is currently for `common` and `linux`,   
i'm trying add osx so I was a little troubled when I noticed this problem :D  
I'll either review the structure of the program, or avoid searching the osx directory because it's not necessary, thank you
