### ISSUE TITLE
Period char at the end of links

### ISSUE THREAD

**Issue by fgionghi** [tldr-pages/tldr#6500]
I'm on linux and for every command I search I get a link, but at the end of the link there is a period and with CTRL-click it goes to a page that doesn't exist (because of the period).
Can't we just remove the period from all the markdown files?

My workaroud using awk is:
`tldr --theme ocean --random-example | awk '{if ($0 ~ /More information/) {gsub(/.$/,""); print} else {print}}'`
and it does the job but I'm loosing the color theme (and not understanding why, maybe when the output is not redirected to stout it does not use colors?). 

Thank you.

**Comment by CleanMachine1** [comment]
I personally agree however its our syntax. Maybe a space between the link> . So it can be copied easier

**Comment by CleanMachine1** [comment]
You might find it better to just remove all the periods from your list of pages since most tldr clients are just markdown renders + some extras

**Comment by navarroaxel** [comment]
@fgionghi I don't have the `.` issue with `Ctrl + click`, maybe your client has a bug, because the link in closed between `<>` to avoid this situation.

Which client and version you are using? I use the `tldr-python-client` tag `2.0.0`.

**Comment by sbrl** [comment]
The space at  the end of the more information link is required as part of out linter syntax. However, it does sound like the client you are using has a bug, as the angle brackets `<>` are markdown's autolinking syntax - which clearly defines which part is the URL and which part is not - so the ctrl+click should work as expected.

Which client are you using? Said client probably doesn't correctly implement [URLs in terminal emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda).

**Comment by fgionghi** [comment]
>Which client are you using? Said client probably doesn't correctly implement Hyperlinks (a.k.a. HTML-like anchors) in terminal emulators.`

Understood, I'm using tilix (on ubuntu 20, using bash-pages), which seems to support the feature. Don't know what to try, in the settings of tilix I'm not finding anything about that.

**Comment by sbrl** [comment]
I see. I don't get any useful search results when I search for that, do you have a link to your client? I recommend opening an issue against it.

**Comment by marchersimon** [comment]
The issue isn't the client. I know this because in my own client I didn't implement anything to support links and it still works. So the terminal emulator takes care of this. @fgionghi which terminal emulator are you using?

**Comment by marchersimon** [comment]
I tried to replicate the issue to maybe open an issue for `tilix`, but it works for me. Maybe it is indeed an issue with the tldr client. Could you tell us which one you're using or from where you installed it?

**Comment by fgionghi** [comment]
I'm using tldr bash client, installed with npm as described [here](https://tldr.sh/#installation).

**Comment by fgionghi** [comment]
Ok I think it is my fault. I now installed tldr as described [here](https://gitlab.com/pepa65/tldr-bash-client#installation) and it is working. What I was installing with npm?

**Comment by marchersimon** [comment]
When you installed it with `npm` it's the Node.js client.

But I tested this with the Node.js client in Tilix and found no issues. Could it maybe be an issue in your Tilix configuration? Could you try another terminal emulator?

**Comment by fgionghi** [comment]
Ahh thank you now I understand. The problem is I'm using fish shell! 
With bash, node.js client and tilix is working.

**Comment by fgionghi** [comment]
Ok can it be that some link are formatted well and others not?
For example `tldr vue` is working, but `tldr dumpe2fs` is not.

**Comment by marchersimon** [comment]
If you're talking about the hyperlink, then that's probably because the link in `vue` ends with `.org` and the link in `dumpe2fs` ends with a word. That really sounds like a configuration issue of Tilix.
