### ISSUE TITLE
The Chinese translation of mention sub-command string

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#6525]
I noticed that the description of mention sub-command has been slightly changed. Should the Chinese one be update as well? I personally think current translation is fine.

Outdated one (current one in Chinese):

```
en: This command also has documentation about its subcommands, e.g. `example command`.
id: Kami mempunyai dokumentasi terpisah untuk menggunakan subperintah seperti `example command`.
zh: 此命令也有关于其子命令的文件，例如：`example command`.
zh_TW: 此命令也有關於其子命令的文件，例如：`example command`.
```

Latest one:

```
en: Some subcommands such as `example command` have their own usage documentation.
id:
zh: 一些子命令如 `example command` 也有独立的文件。
zh_TW: 一些子命令如 `example command` 也有獨立的文件。
```

**Comment by marchersimon** [comment]
The main reason I changed it is because (in my opinion) it sounded better. If in Chinese the old one sounds better that we should keep it. If you can come up with something even better, we should take that.

**Comment by blueskyson** [comment]
OK, I think the original one is more understandable in Chinese. Keep the original one is fine.
