### ISSUE TITLE
page request: adb-backup

### ISSUE THREAD

**Issue by 1-John** [tldr-pages/tldr#6553]

**Comment by marchersimon** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)

**Comment by s4ik4t** [comment]
```
WARNING: adb backup is deprecated and may be removed in a future release
```

**Comment by marchersimon** [comment]
We should definitively add this to the page, but this doesn't prevent us from documenting it

**Comment by Managor** [comment]
Closing this in favor of https://github.com/tldr-pages/tldr/issues/13997
