### ISSUE TITLE
vlc: link to more useful information

### ISSUE THREAD

**Issue by tactlessfish** [tldr-pages/tldr#6569]
Currently, the tldr page for `vlc` links to its [homepage](https://www.videolan.org/vlc/), which does not provide much useful information for someone wanting to learn more about the command. The homepage only advertises its features and links to downloads.

I suggest that we instead link to `vlc`'s [documentation homepage](https://wiki.videolan.org/Documentation:Documentation/) or its [documentation page for the CLI](https://wiki.videolan.org/Documentation:Command_line/).

**Comment by marchersimon** [comment]
The second link looks great. I think we can change it. Would you like to open a PR?

**Comment by tactlessfish** [comment]
I would love to! Just to clarify, you want the specific page for the CLI, right?

**Comment by marchersimon** [comment]
I'm not really understanding what you mean. The `vlc` page is at `pages/common/vlc.md` if that's what you're asking.

**Comment by tactlessfish** [comment]
Ah, my question was to clarify which webpage we should link to, since either webpage I suggested could be the second link depending on which link we start counting from.

But now that you mention it, `vlc` has other tldr pages, in `pages.zh/` and `pages.it/`. Should I change those in my PR as well?

**Comment by marchersimon** [comment]
I was talking about this one -> [documentation page for the CLI](https://wiki.videolan.org/Documentation:Command_line/).

For the link you could use our `set-more-info-link.py` script. It handles translations automatically. Just run `python scripts/set-more-info-link.py -p common/vlc "link"` from the tldr repository root. But we could also do that for you if you only add the link in the English page.

**Comment by tactlessfish** [comment]
In general, should I prefer CLI documentation pages to documentation homepages, if the pages are separate?
