### ISSUE TITLE
Let's document: cups

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#6597]
- [x] [cancel](https://www.cups.org/doc/man-cancel.html) → #11843
- [x] [cups-config](https://www.cups.org/doc/man-cups-config.html) → #6623
- [x] [cupsaccept](https://www.cups.org/doc/man-cupsaccept.html) → #11826
- [x] [cupsctl](https://www.cups.org/doc/man-cupsctl.html) → #11745
- [x] [cupsd](https://www.cups.org/doc/man-cupsd.html) → #6623
- [x] [cupsdisable](https://www.cups.org/doc/man-cupsenable.html) → #11826
- [x] [cupsenable](https://www.cups.org/doc/man-cupsenable.html) → #11826
- ~[ ] [cupsfilter](https://www.cups.org/doc/man-cupsfilter.html)~ DEPRECATED
- [x] [cupsreject](https://www.cups.org/doc/man-cupsaccept.html) → #11826
- [ ] [cupstestppd](https://www.cups.org/doc/man-cupstestppd.html) → #11898
- [x] [ippevepcl](https://www.cups.org/doc/man-ippevepcl.html) → #11846
- [x] [ippeveprinter](https://www.cups.org/doc/man-ippeveprinter.html) → #11846
- [x] [ippeveps](https://www.cups.org/doc/man-ippevepcl.html) → #11846
- [ ] [ippfind](https://www.cups.org/doc/man-ippfind.html) →
- [ ] [ipptool](https://www.cups.org/doc/man-ipptool.html) →
- [x] [lpadmin](https://www.cups.org/doc/man-lpadmin.html) → #11745
- [x] [lpinfo](https://www.cups.org/doc/man-lpinfo.html) → #6623
- [x] [lpmove](https://www.cups.org/doc/man-lpmove.html) → #11843
- [x] [lpoptions](https://cups.org/doc/man-lpoptions.html) → #11745
- [x] [lpq](https://cups.org/doc/man-lpq.html) → #11745
- [x] [lprm](https://www.cups.org/doc/man-lprm.html) → #11745

This list is not complete at all. Look at the [official documentation](https://www.cups.org/documentation.html) for more.

**Comment by marchersimon** [comment]
We usually use `page request` only for single or a few unrelated pages.

**Comment by reinhart1010** [comment]
I might want to do `cups-config` and 
`cupsd`

**Comment by vitorhcl** [comment]
@kbdharun @sebastiaanspeck cupsfilter and some more commands that I haven't added to the list are deprecated. We don't need to document these commands, right?
