### ISSUE TITLE
Sample screenshot text not matching conventions

### ISSUE THREAD

**Issue by Cvetomird91** [tldr-pages/tldr#667]
I just noticed that the example on the screenshot most probably will not pass all the CI checks due to the following reasons:

- the options descriptions start with a lower case letter
- the colon at the end is missing.

**Comment by igorshubovych** [comment]
Ha! We need new screenshot.
I knew the day would have come!

**Comment by igorshubovych** [comment]
Do you like these screenshots? (cc @waldyrious)

![tldr_sort](https://cloud.githubusercontent.com/assets/93907/13513012/d29bd826-e1a6-11e5-833d-73ae9b98b20d.png)

![tldr_mkdir](https://cloud.githubusercontent.com/assets/93907/13513017/d77165b4-e1a6-11e5-8ac3-d92f595f4771.png)

**Comment by igorshubovych** [comment]
`tar` is too long for small screenshot

**Comment by waldyrious** [comment]
A bit hard to read tbh (especially the red text), and maybe a plain black background would be better.

I'd prefer something without the text highlight:
![](https://cloud.githubusercontent.com/assets/946520/12338139/ffc056ee-bb2f-11e5-8180-b586cfb439b2.png)
([src](https://github.com/tldr-pages/tldr-python-client/pull/25#issue-126752630))

<img src="https://cloud.githubusercontent.com/assets/526284/12036275/6c58eb70-ae12-11e5-8902-325d14407e4b.png" width="600">
([src](https://github.com/tldr-pages/tldr-node-client/issues/39#issuecomment-167804268))

![](https://monosnap.com/file/CtFXlQ4LBXRwMmSxopd0e9zrVeFNdQ.png)
([src](https://github.com/tldr-pages/tldr-node-client/pull/61#issue-125503279))

...or even better, without much coloring at all, like here:

![theme: bw](http://i.imgur.com/f2mmKL8.png?1)
([src](https://github.com/tldr-pages/tldr-node-client/pull/61#issue-125503279))

**Comment by ostera** [comment]
I'd use `tar`. It's more characteristic thanks to the XKCD comic :P

**Comment by jedahan** [comment]
![screen shot 2016-03-04 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/32407/13538703/1282eac4-e21a-11e5-8304-0aefae9272df.png)

**Comment by agnivade** [comment]
So what's the word on this ? As far as I understand, we just need to update the screenshot, and @jedahan's screenshot looks good to me. 

If there's nothing else pending, I will go ahead and make a PR and get this done.

**Comment by waldyrious** [comment]
@agnivade eventually we ought to change the client's default colors, but for now this screenshot ought to work, yes :)

**Comment by waldyrious** [comment]
Fixed in #957
