### ISSUE TITLE
Should we stop using the non-breaking space in French pages?

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#6815]
Until recently we enforced a non-breaking space in front of colons in every French page, because that's apparently the correct syntax. But this [comment](https://github.com/tldr-pages/tldr/pull/6673#discussion_r720878900) from @noraj mentioned an interesting point.

> Outside of WYSIWYG editor like MS Word nobody uses them because there is no easy way to insert them from keyboard.

Almost everyone is viewing tldr-pages in the terminal, so you can't even tell the difference between the two spaces. So should we just stop using them? It would also simplify all this a bit.

Ping @noraj, @Nico385412, @patricedenis, @nicokosi

**Comment by sbrl** [comment]
This would be inline with other stylistic choices made in the English pages. For example, we only allow straight double quotes `"` in descriptions, because you can't type smart ones with the keyboard.

**Comment by Nico385412** [comment]
Totally agree with @noraj
That would be great to stop using non-breaking spaces for french pages 👍

**Comment by marchersimon** [comment]
Great. So should we just put a regular space in front of a colon or none at all?

**Comment by noraj** [comment]
> Great. So should we just put a regular space in front of a colon or none at all?

In english there is no space but in french there is one, so let's keep a regular space.

**Comment by patricedenis** [comment]
Hi there, long time no see!
Just to say that I totally agree with the decision that has been made.
In fact, it was clearly more difficult to add those non-breaking spaces. Generally we couldn't even see if we had included them in a proper war without a bot to tell and check for us.
