### ISSUE TITLE
Pages with multiple commands per example

### ISSUE THREAD

**Issue by rubenvereecken** [tldr-pages/tldr#687]
Related to tldr-pages/tldr-node-client#64 and somewhat to #685. 

The current linter at `tldr-pages/tldr-lint#multiple-examples` (npm install path) detects multiple commands per example. It also comes with a tabular output formatter. That enabled me to do the following: 

`tldrl pages/ -t 2>&1 | cut -f1 | uniq | grep "pages.*" -o`

Resulting in this beauty.
```
pages/common/cal.md
pages/common/ls.md
pages/common/redis-cli.md
pages/common/rename.md
pages/common/salt-key.md
pages/common/scp.md
pages/common/srm.md
pages/common/touch.md
pages/common/which.md
pages/common/zpool.md
pages/linux/md5sum.md
pages/linux/sha1sum.md
pages/linux/sha224sum.md
pages/linux/sha256sum.md
pages/linux/sha384sum.md
pages/linux/sha512sum.md
pages/linux/ss.md
pages/linux/wpa_cli.md
pages/osx/md5.md
pages/osx/sysctl.md
pages/osx/systemsetup.md
pages/osx/xed.md
```

These are all files with multiple commands per example. 

EDIT: @notpeter had a go at them, we're almost through.

- [x] pages/common/scp.md
- [x] pages/common/zpool.md
- [x] pages/linux/ss.md
- [x] pages/linux/wpa_cli.md

**Comment by igorshubovych** [comment]
cc @rprieto

**Comment by notpeter** [comment]
I already have PRs waiting for:
pages/common/zpool.md (#684)
pages/common/scp.md (#681)

I think I got all the rest except two, because I'm not familiar.
pages/linux/ss.md
pages/linux/wpa_cli.md

**Comment by rubenvereecken** [comment]
Now merged in tldr-lint's master branch.
