### ISSUE TITLE
Git subcommand confusion

### ISSUE THREAD

**Issue by cmoel** [tldr-pages/tldr#689]
Hello! I've showed a few folks `tldr` and they found using it for `git` subcommands a bit confusing (as did I until I remembered how `git` does subcommands).

Would you be open to a PR describing how to access `git` subcommands on the `git` page? If yes, how would you want me to format it? The section on [markdown format](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format) in the contributing guide doesn't describe this kind of data (i.e., getting more information about related commands).

**Comment by ostera** [comment]
@cmoel I think we can do better. Structurally we want those sub commands to be there, but from an UX point of view, all clients should push to find `git-add` if the person is typing `git add`.

For the group of maintainers, I've supported this as [tldr.jsx/#/git add](http://ostera.io/tldr.jsx/#/git add) for a bit now and I think it'd be good to have it in the other clients too.

**Comment by cmoel** [comment]
@ostera Good point. The responsibility does seem to be more on the client than on the something that should be part of the document
