### ISSUE TITLE
Possible duplicate : base64 ?

### ISSUE THREAD

**Issue by gd-codes** [tldr-pages/tldr#6892]
I noticed that there are 2 entries for the base64 command : `pages/common/base64.md` and `pages/osx/base64.md`. They're nearly identical in content, except for the man page links and other minor wording.

I'm not sure if this is intentional, but I thought I'd mention it. (I've only used it on MacOS, so i'm not sure if there are differences in other versions, if any). I'm willing to make a PR with any changes if required !

Using the tldr python3 client (with pip3 install ...) on MacOS, the osx/ version of the file is displayed.

**Comment by navarroaxel** [comment]
Just checking the pages I see the `osx` version a `--input` argument that it's not available in `linux`.

**Comment by gd-codes** [comment]
Oh, yes that is different ! I guess I missed that 😅...
