### ISSUE TITLE
Client spec: `osx` and `macos`

### ISSUE THREAD

**Issue by niklasmohrin** [tldr-pages/tldr#7076]
Hi everyone!

Over at [tealdeer](https://github.com/dbrgn/tealdeer) we wanted to allow users to specify `macos` as a platform for filtering pages (see https://github.com/dbrgn/tealdeer/pull/108#discussion_r730431290 and https://github.com/dbrgn/tealdeer/pull/215).

It would of course be great if we could get confirmation from you guys that you won't add a "macos" platform any time soon - or a hard "no" if you _are_ planning to do so. Maybe this alias could even manifest itself in the client spec as a recommendation or option. After all, [the operating system is not called "osx" anymore](https://en.wikipedia.org/wiki/Macintosh_operating_systems#Mac_OS_X_/_OS_X_/_macOS).

Is this alias something the client spec authors would approve or are we shooting ourselves in the foot here? I would love to hear your thoughts on this! 

Slightly related: #5013

**Comment by CleanMachine1** [comment]
As mentioned in one of the issues, changing will break a lot of clients or functionality. Some clients are actively used by people however no longer maintained.

Until we make the entire switch which doesn't look likely yet, I feel tealdeer using an "alias" of some kind in its code would be the best solution.

**Comment by pixelcmtd** [comment]
The best solution for all clients would be to have a check like

```
if "pages/macos" exists:
    alias "osx" to "macos"
else:
    alias "macos" to "osx"
```

as getting that into 90% of the clients allows for a very smooth transition.

**Comment by sbrl** [comment]
Hmmmmm, this is a great point. Ideally, we should move `osx` to `macos`, but as you say it would unfortunately break clients. Aside from assessing the various clients to see which ones would actually break, an alias would be a great thing to add in the meantime to the spec. Would you like to open a pull request for that?
