### ISSUE TITLE
[Feature Request] pre-download all requeired command help resourses

### ISSUE THREAD

**Issue by eval-exec** [tldr-pages/tldr#7084]
The tldr need network connection, but sometime we donn't have network, or bad network. so pre-download all command's help resourses can solve the problem.

**Comment by MasterOdin** [comment]
The node client downloads the entire cached zip whenever it updates, while the python client grabs pages one by one.

**Comment by eval-exec** [comment]
> The node client downloads the entire cached zip whenever it updates, while the python client grabs pages one by one. Both do try to use the local cache though before utilizing network.
> 
> @eval-exec it would be good to know what client you are using?

i am using `tldr` python client
![image](https://user-images.githubusercontent.com/46400566/138192579-d070b442-6a78-40b1-b1ba-b46f17f72714.png)

thank you, this helped me alot
