### ISSUE TITLE
Improve contributing guides

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#7094]
We should explain how to deal with common issues that the contributors face when they send pull requests.

- [x] Explain that it's bad practice to send PRs from the `main` branch of their forked repository.
- [x] Explain how to explain suggestions in their pull requests from the web, because it's the easier way to accept suggestions in the pull requests. https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request
- [x] Explain that, only for translations, they can translate several pages in one PR. Maybe this is explained somewhere but should be more visible.
- [x] Enforce the **don´t** `push --force` to the PRs.

**Comment by shermanhui** [comment]
Hi, I'm a new contributor to this repository, I'll take a shot at updating the `CONTRIBUTING.md` with the bullet points you've outlined in the issue description!
