### ISSUE TITLE
Issues with EditorConfig option and line endings on Windows

### ISSUE THREAD

**Issue by trolzen** [tldr-pages/tldr#7097]
I am using Sublime Text with the EditorConfig plugin on my Windows-machine. When I clone the repository all the files get `CRLF` line endings, because of the `* text=auto` in the `.gitattributes`. Then, when I edit the file, or just save it without any modifications all line endings convert to `LF`, because my editor honors the `end_of_line = lf` setting in the `.editorconfig`. Which gives me some inconvenience getting `warning: LF will be replaced by CRLF in...` and making `git  status` tell the file have changed when it's not.

Is there any way to make some changes to repository config files to cover this use-case?

**Comment by marchersimon** [comment]
I think `git config core.autocrlf input` ([docs](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace)) should do the trick. I'm just not sure how to push such a setting to GitHub, since you can't commit changes inside of `.git/`.
