### ISSUE TITLE
index.json schema change

### ISSUE THREAD

**Issue by hidroh** [tldr-pages/tldr#717]
Hey guys,
Look like #697 changed schema for `index.json` from
```json
{
    "commands": [
        {...},
        {...},
        ...
    ]
}
```
to
```json
[
    {...},
    {...},
    ...
]
```
My client depends on this file for indexing of commands, and I totally missed this (I do watch the repo for important changes like this). Maybe we should version this file if we plan to have such breaking changes in the future, or at least clearly announce it way in advance so clients can do proper upgrade?

For the change itself, can I confirm that this is intentional and not a mistake?

**Comment by hidroh** [comment]
This is the relevant travis commit that changes `index.json` Github pages: tldr-pages/tldr-pages.github.io@7f6172c10613dd7d5c7b3c04a9aa2c4a854e7e7a

**Comment by igorshubovych** [comment]
Ooops. I will fix it soon. Thank you for quick reaction.

**Comment by igorshubovych** [comment]
Could you plz try again?

**Comment by hidroh** [comment]
Shoot. I just updated my client to follow the wrong schema. Gotta revert it now :(

**Comment by hidroh** [comment]
@igorshubovych it's working now. Thanks.
