### ISSUE TITLE
Does the "index.json" file format occasionally change?

### ISSUE THREAD

**Issue by mflint** [tldr-pages/tldr#718]
Forgive me, I think I'm going mad.

I'm getting the `index.json` file from inside `https://tldr-pages.github.io/assets/tldr.zip`, and my app occasionally fails to parse the file.

Last week, I was converting the JSON to the Swift type `Dictionary<String, Array<Dictionary<String, AnyObject>>>`, which implied that the file format was something like this:

    {"commands":[{"name":"7za","platform":["common"]}]}

But then it stopped working. I needed to change it to `Array<Dictionary<String, AnyObject>>` because it was getting this JSON inside the zip:

    [{"name":"7za","platform":["common"]}]

And this morning (sometime around 9am UTC) it changed back.

Is this an expected thing? Seems strange to me.

(Confirmation: I've been testing the app on several iOS simulators, and each one has a separate directory for storing documents. Sure enough, the ones I tested last night have an array as the root object. This morning I'm seeing a dictionary/map as the top level object, with a "commands" key.)

**Comment by mflint** [comment]
(Edited to correct a typo - I'm downloading the tldr zip from `https://tldr-pages.github.io/assets/tldr.zip`)

**Comment by igorshubovych** [comment]
@mflint 
It was fixed already. Sorry for inconvenience. See #717.

**Comment by rubenvereecken** [comment]
I believe @igorshubovych just fixed this one. Might be worth having a test for.

**Comment by mflint** [comment]
@igorshubovych No apologies necessary!

So the correct format is `{"commands":[{"name":"7za","platform":["common"]}]}`.

**Comment by rubenvereecken** [comment]
Yeap.
