### ISSUE TITLE
Snap package is not available anymore

### ISSUE THREAD

**Issue by olbrew** [tldr-pages/tldr#7193]
I love tldr and would like to install it to some smaller servers without having to install the whole NPM client or some other language’s package manager.
I saw there was a Snap package available on the [Clients page](https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients) but it it seems to be gone now:

```bash
$ sudo snap install tldr
> error: snap "tldr" not found
```

The [Snap page](https://snapcraft.io/tldr) also gives a 404.

I prefer installing packages this way, since it mostly doesn’t need additional programs to be installed and Snap is now available on a lot of Linux distro’s. Could the package be reinstated?

**Comment by marchersimon** [comment]
I removed it from the wiki. Does this resolve your issue @olbrew?

**Comment by olbrew** [comment]
Yes it does. A better option would've been to fix the snap package but this closes the issue as well ;).

**Comment by marchersimon** [comment]
Well, as @navarroaxel already said, we don't control that. We could however try to send a request to Snapcraft to re-add the package.

**Comment by sbrl** [comment]
Hrm, that's weird. I think we need someone experienced with packaging to help out here to sort out and maintain the various os-level tldr packages. Other package managers also have issues - I think we have an issue open about those too.

**Comment by marchersimon** [comment]
I started a [new thread](https://forum.snapcraft.io/t/is-there-a-record-of-previously-removed-snaps/27391) at the Snapcraft forum to find out why it was removed. Creating snaps doesn't seem very complicated, but it has to be done on Ubuntu.

**Comment by chrysle** [comment]
> I see a snap from @luk3yx. Did you try it?

This has been removed now, too.

**Comment by kbdharun** [comment]
> > I see a snap from @luk3yx. Did you try it?
> 
> This has been removed now, too.
> 

Yes, we are aware of it.

Offtopic: Maintaining an official snap isn't hard, I will consult with a friend who is experienced with snaps regarding this and get back. 

If we are creating one it would probably be for our Python client.

**Comment by kbdharun** [comment]
> Offtopic: Maintaining an official snap isn't hard, I will consult with a friend who is experienced with snaps regarding this and get back.

An Update on this, with the help of my friend, I have recreated the [Snap package](https://snapcraft.io/tldr) for tldr now based on the [Python client](https://github.com/tldr-pages/tldr-python-client/blob/main/snap/snapcraft.yaml) instead of the old one which was based on the Node client.

You can install it with the following command:

```shell
sudo snap install tldr
```

**Note**: For the time being, there isn't support for tab completion and man page support in the Snap package we are planning to add it in future.

**Comment by pixelcmtd** [comment]
> I started a [new thread](https://forum.snapcraft.io/t/is-there-a-record-of-previously-removed-snaps/27391) at the Snapcraft forum to find out why it was removed.

Not-so-Fun fact: That thread 404s and isn't in the Internet Archive. (I also did like a minute of precision quacking and wasn't able to find it) ...email logs anyone?

**Comment by kbdharun** [comment]
> > I started a [new thread](https://forum.snapcraft.io/t/is-there-a-record-of-previously-removed-snaps/27391) at the Snapcraft forum to find out why it was removed.
> 
> Not-so-Fun fact: That thread 404s and isn't in the Internet Archive. (I also did like a minute of precision quacking and wasn't able to find it) ...email logs anyone?

Yeah, I can't find any reference to it in both the Google Cache or the Wayback machine. Which is interesting.
