### ISSUE TITLE
Merge windows/powershell with common/pwsh?

### ISSUE THREAD

**Issue by reinhart1010** [tldr-pages/tldr#7194]
As in #6621 I've stated that PowerShell is now available on macOS and Linux, and after the unification of PowerShell Core and the legacy Windows PowerShell (now referred by Microsoft by its latest version, **PowerShell 5.1**), a majority of parameters and options for the `windows/powershell` command are available on other platforms as well, making `common/pwsh` more like an alias of it.

I'm planning a PR with massive changes to:

1. merge all the current options from `common/pwsh` into `windows/powershell`,
2. then move the documentation of `powershell` from `windows/` into `common/`,
3. and finally create a new documentation for `common/pwsh` stating that it's an alias of `common/powershell`. 

This will not affect PowerShell commands and cmdlets which have already been documented (again, see #6621 for examples), since the goal of this is to merge the documentation for the **intepreter** of PowerShell, which is now also accessible on macOS and Linux.

**Comment by sbrl** [comment]
Sounds interesting. I think we agreed recently though to document PowerShell commands under `windows` rather than `common` since it's on Windows that PowerShell is usually used though?

The other changes here sound good though. Thanks!

**Comment by reinhart1010** [comment]
Partially fixed in #7984
