### ISSUE TITLE
purpose of {{ and }} in output of tldr

### ISSUE THREAD

**Issue by sigmonsays** [tldr-pages/tldr#731]
What is the purpose of the excess of {{ and }} in the output of the pages?

This doesn't seem like a practical format and is only ugly to read. Shouldn't some sort of symbol be used that isn't so ugly?

**Comment by rubenvereecken** [comment]
Depends on the client you're using. The raw pages will include the double curly braces whereas clients will interpret them and are able to color them for example, dropping the curly braces.

**Comment by waldyrious** [comment]
By the way, it would be great if we (sometime in the future) could change this markup to the more standard cli notation `<...>`, as described e.g. in the [docopt](http://docopt.org/) standard, but that's probably something to be considered in the long term.

**Comment by rprieto** [comment]
One reason `{{foo}}` was chosen over others (including `<foo>`) is that it makes parsing easier, especially for the more complex examples. E.g.

```bash
cat <input.txt >/dev/null
```

**Comment by waldyrious** [comment]
@rprieto is that up for revisiting? It would be really neat if we could adopt the standard CLI syntax, and that would also be a concrete requirement for clients, along the lines of what we've discussed in #679 and elsewhere. I realize this would put a burden on all existing clients, so I'm not suggesting a change overnight, just putting that proposal under discussion if you guys agree it may make sense.

**Comment by waldyrious** [comment]
(That said, I don't feel too strongly about this, so an explicit, publicly recorded decision to stick to `{{...}}` instead of `<...>` would be a positive outcome for this issue as well, IMO.)

**Comment by rubenvereecken** [comment]
I vote for sticking anytime. Don't feel like there's a real advantage to either since neither is valid markdown, so the one that's easier for clients to parse sticks out. `< >` is prettier but users should never have to suffer the symbols, just a client rendering.

**Comment by bwh1te** [comment]
@sigmonsays look how it works in python TLDR client: https://github.com/tldr-pages/tldr-python-client/pull/20

**Comment by sjackman** [comment]
Is there a web client for TLDR that interprets `{{foo}}`? Both tldr.sh and https://tldr.ostera.io/cut display the raw `{{foo}}`.

**Comment by waldyrious** [comment]
@sjackman those are the same client, by the way. @ostera's client is embedded in tldr.sh. The only other web client I know of is [DistroWatch's](https://distrowatch.com/dwres.php?resource=man-pages), as indicated in the [README](https://github.com/tldr-pages/tldr#clients). It does consume the `{{}}`.

**Comment by sjackman** [comment]
I've opened a feature request at https://github.com/ostera/tldr.jsx/issues/97

**Comment by sbrl** [comment]
I assume that this issue is resolved now?

**Comment by agnivade** [comment]
Yes. I believe so.

**Comment by bl-ue** [comment]
>Is there a web client for TLDR that interprets `{{foo}}`? Both http://tldr.sh and https://tldr.ostera.io/cut display the raw `{{foo}}`.

@sjackman Finally, yes! But it's in progress ;) https://github.com/bl-ue/tldr-pwa

Subscribe to https://github.com/bl-ue/tldr-pwa/issues/1 to receive updates.

**Comment by kshensovato** [comment]
Why is this closed? I'm still seeing double braces in Ubuntu 22.04 terminals.

**Comment by kbdharun** [comment]
> Why is this closed? I'm still seeing double braces in Ubuntu 22.04 terminals.

Double braces are used to highlight placeholders across most of our clients and all our official clients. If you installed tldr from Ubuntu 22.04 repositories you are using the tldr-hs Haskel client which isn't official and inactive. I would suggest switching to our official client packaged as Snap (`snap install tldr`).
