### ISSUE TITLE
Automate application of labels for PRs

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr#7325]
I feel like it would be worth considering automating label application to PRs. In the past two weeks, there's been two new labels added to the organization. Scanning through, there is 24 labels that can be applied to a given PR. Each of these labels are applied manually, which just does not seem tenable to me, and that label application would be missed, especially for newcomers into the tldr organization.

As low hanging fruit, I think the following PRs could be automated without much debate on when to apply them:

- `new command` - PR is for creating a new page
- `page edit` - PR affects only one existing page
- `translation` - PR is for a page not in `pages/` directory

Maybe `mass changes` could be applied as well if there was some agreement on what "multiple pages" means (2+, 10+, etc.).

Once we've automated application of these simple ones, follow-up work could be applied for:

- `review needed` - PR does not yet have 2 reviews (could be applied after X days like stalebot posts)
- `waiting` - PR review requested changes?

An ideal example of this level of label automation would be the https://github.com/DefinitelyTyped/DefinitelyTyped repository.

**Comment by navarroaxel** [comment]
You can add `documentation` for `*.md` files outside `pages*/`. And, `tooling` for `*.js` and `*.py` files.

**Comment by CleanMachine1** [comment]
Agreed.

Lots of other repos have auto labeling bots and for a project like this, its needed.

I like the idea of the review needed after X days, maybe 4?

**Comment by CleanMachine1** [comment]
mass changes to me indicates more than 1 change to 2 or more pages.
