### ISSUE TITLE
README.md is too long.

### ISSUE THREAD

**Issue by kindraywind** [tldr-pages/tldr#736]
Could you add the TL;DR section at the top that only have a short description, one screenshot and the quickest way to install (e.g., `npm install -g tldr`)

:D

**Comment by igorshubovych** [comment]
cc @waldyrious :)

**Comment by waldyrious** [comment]
@kindraywind has a good point. It's not that the Readme is too long, but poorly organized. In honor of the spirit of tldr, we should definitely make the changes suggested here. I'll take a stab at this soon (hopefully this weekend).

**Comment by ostera** [comment]
I think we can close this now since the #765 was merged
