### ISSUE TITLE
page request: tldr entry for pip

### ISSUE THREAD

**Issue by sisrfeng** [tldr-pages/tldr#7360]
Since I use `pip install XXX` a lot and some commands are not frequently used, I  am used to type `tldr XXXX`, but feel sad to find nothing.
Will there be support for pip packages?
Thx

**Comment by marchersimon** [comment]
I'm not really understanding your question. Does `XXXX` stand for any arbitrary command installable via `pip`?

**Comment by sbrl** [comment]
If installing a command via `pip` it results in a command being available on the user's system (e.g. `youtube-dl`) then it's definitely eligible to be documented here @sisrfeng!

tldr-pages is a community-run effort, so please do contribute pages that you find are missing :smiley:

**Comment by CleanMachine1** [comment]
Hi, I am closing this issue since it has been solved.

Yes commands installed using pip can be documented here
