### ISSUE TITLE
Adding teams to request review from multiple people 

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#7365]
In case you've never used teams here's the official [GitHub docs](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams).

I thought about adding some teams with each a few people in it to better request review from the right people. We could for example create a `German` team with me and @pixelcmtd in it and if there's a German PR you'd just have to request a review from the German team. We also could make other teams for Linux-specific commands or everything concerning our organization.

I now we already have labels for that but at least to me they're mostly useless, because I always work through my [notifications](https://github.com/notifications) where I don't even see them. But there's an own tab for `Team mentioned` there (I'm not sure if this includes `Team review requested` however).

I'm not sure if this is really useful, but it wouldn't be much work to set up one team and test it.

**Comment by deadpyxel** [comment]
Not in my place to say, but I believe that it could smooth out the PR review and probably allow for further automation using GitHub Actions (some actions work really well with GitHub Teams).

**Comment by marchersimon** [comment]
Do you have anything specific in mind? I can imagine this works awesome with more maintainers, where you have multiple teams with a few people each, but for our case, the `German` team is the only which makes sense in my opinion.

**Comment by marchersimon** [comment]
Small update: While you can't see labels in your notifications, you can still create a filter to get PRs with a specific label, so my original issue basically has been resolved. But I'm still waiting what others think.

**Comment by deadpyxel** [comment]
I was thinking maybe of something like this: https://github.com/marketplace/actions/review-assign-action but like you said, maybe this is not really that useful.

My idea would be that you could send a notification given some kind of tag or specific comment (like `tl:German`) to potential reviewers.

**Comment by CleanMachine1** [comment]
French is also worth creating a team.

I will create the teams now, and if people like it then we will keep it, else it was worth a trial :shrug:

**Comment by CleanMachine1** [comment]
Hmm, I can't leave a team after I make it, @marchersimon would you like to?

**Comment by marchersimon** [comment]
Well, I just created @tldr-pages/german and saw that you can only add org members to a team. From what I have read, you have to restrict this team to specific repositories, where all team members have access to. So in our case, we would have to restrict the access to tldr-pages/tldr, because collaborators only have access to this one. But to do that I need to be an org owner. @navarroaxel could you please try that [here](https://github.com/orgs/tldr-pages/teams/german/repositories)?

**Comment by navarroaxel** [comment]
Done @marchersimon

**Comment by marchersimon** [comment]
Great, it actually worked. Now we have to come up with a useful list of teams we could create. Some ideas:

* `german` (already exists)
* `review` (just general review, this could replace the `review-needed` label)
* `maintaining` (for general stuff like documentation of scripts)
* `python` or `tldr-python-client`
* `js` or `node` or `tldr-node-client`
* `c` or `tldr-c-client`

Depending what we currently want to do, we could kind of "subscribe" or "unsubscribe" from a team and we just have to request review from a whole team.

**Comment by reinhart1010** [comment]
Maybe platform-specific teams (e.g. `linux` or `powershell`) would also be great?

**Comment by CleanMachine1** [comment]
I think we can close this issue, due to the fact that other reviewers need to be part of the organization to be added to a team, it makes it difficult to use this feature and the teams have _currently_ 1 member each. 

I can say that they haven't really had usage within the org.
IMO they should say regardless if they don't do a lot and are never really used.

Anyone have any other opinions or can we close this?

**Comment by marchersimon** [comment]
You're right, I'll close it.
Our org is a little too small to really make use of teams.
