### ISSUE TITLE
Python client for tldr pages

### ISSUE THREAD

**Issue by iamgodot** [tldr-pages/tldr#7382]
I've implemented a new Python client for tldr pages [here](https://github.com/iamgodot/py-tldr), now I'm wondering where should I list it for everyone to use. Should I just update the wiki page?

BTW, I checked on [tldr.py](https://github.com/lord63/tldr.py) but cannot be able to use it. The code seems broken and I got no response from the author. I'm not sure if it should be removed from the client list while new users may waste more time on it.

**Comment by marchersimon** [comment]
Looks great. Just add it to the Wiki.
Regarding tldr.py, I'm not sure. We have a lot of client's which don't work anymore, but we haven't got to decide what to do with them yet.

**Comment by iamgodot** [comment]
> Looks great. Just add it to the Wiki. Regarding tldr.py, I'm not sure. We have a lot of client's which don't work anymore, but we haven't got to decide what to do with them yet.

Cool, I just did. Hopefully you'll make a decision soon, maybe assign someone for a particular language to manage stuff.

**Comment by CleanMachine1** [comment]
Since the client has been added to our wiki of clients, I am going to close this issue, since the topic of the issue has been solved!
