### ISSUE TITLE
Add collaborator: @reinhart1010

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr#7404]
Hi, @reinhart1010! You seem to be enjoying contributing to the tldr-pages project.
You now have had 17 distinct pull requests merged (#7192 #7089 #7087 #7086 #6623 ...)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by marchersimon** [comment]
@reinhart1010?

**Comment by reinhart1010** [comment]
Sorry for late reply, but after some consideration I'm willing to do so. Thanks!

**Comment by navarroaxel** [comment]
@reinhart1010 Invitation sent, please accept and close this issue sending a PR adding you to the MAINTAINERS.md.
