### ISSUE TITLE
Standardize shell tldr pages

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7416]
I think shell tldr pages should be more standardized to simplify their reading for people. For instance shell commands can be ordered as:

- Start an interactive shell session
- Start an interactive shell session without loading startup configs
- Execute commands
- Execute a script
- Check a script for syntax errors
- any other examples

In all examples long options should be preferred (if available) because they are easier to remember than short ones. And the following assumptions can take a place:

- non-interactive command exits immediately by default after execution

I want to close this issue myself. ;)

**Comment by CleanMachine1** [comment]
Different pages have different topics they should focus on, so having a universal syntax for pages starts to make them manuals and less helpful.

I'm not completely satisfied with this idea.

**Comment by marchersimon** [comment]
> In all examples short options should be preferred (if available) because they are harder to remember than long ones.

I'm confused. Did you mean `easier to remember`? If so, I don't agree with that, remembering a word with a meaning is definitively easier than remembering a single letter.

**Comment by EmilySeville7cfg** [comment]
I think that tldr pages can help use and remember short options faster because they are less user friendly than long ones. That's why I prefer to use short options in pages. But the benefit of short options is less typing. ;)

**Comment by marchersimon** [comment]
The problem with short options often is, that you don't understand what they do. When you read `--command`, you know exactly what it does, but when you read `-c` it can be anything (it's often implied by the context, but not always).

**Comment by EmilySeville7cfg** [comment]
On the other hand we can prefer long options always when they exist.🤔

**Comment by marchersimon** [comment]
We settled on faster memorizing (and especially understanding) some time ago. When you're working a lot with a command you probably already had a look at the man page where you can find the short options.

**Comment by EmilySeville7cfg** [comment]
Ok. Got it. I wanna to write about it in CONTRIBUTING.md after a while.

**Comment by marchersimon** [comment]
I was sure we already covered that somewhere, but apparently not. But it should go in `contributing-guides/style-guide`, and not `CONTRIBUTING.md`.

**Comment by EmilySeville7cfg** [comment]
There is a new #8018 issue that has a goal to standardize everything.
