### ISSUE TITLE
page request: octave

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7419]
[Here](https://octave.org/doc/v4.4.0/Command-Line-Options.html) command line options can be found.

**Comment by EmilySeville7cfg** [comment]
I [leave](https://octave.discourse.group/t/tl-dr-page-for-octave/1792) here link for my topic with octave developers here.

**Comment by saikatsgupta** [comment]
https://docs.octave.org/latest/

**Comment by EmilySeville7cfg** [comment]
Issue is already closes: `octave` page is created.
