### ISSUE TITLE
page request: `semanage-fcontext` & `restorecon`

### ISSUE THREAD

**Issue by cyqsimon** [tldr-pages/tldr#7479]
`semanage fcontext`, and `restorecon` are frequently used commands when working with SELinux.

## `semanage fcontext`

Edits the persistent SELinux rules for file context.
https://man7.org/linux/man-pages/man8/semanage-fcontext.8.html
https://wiki.gentoo.org/wiki/SELinux/Tutorials/Controlling_file_contexts_yourself

## `restorecon`

Resets the SELinux context for the selected files according to persistent rules.
https://linux.die.net/man/8/restorecon
https://www.thegeekstuff.com/2017/05/restorecon-examples

## Related commands with existing pages
[chcon](https://github.com/tldr-pages/tldr/blob/main/pages/common/chcon.md)
[semanage](https://github.com/tldr-pages/tldr/blob/main/pages/linux/semanage.md)

**Comment by cyqsimon** [comment]
Also just out of curiosity, why is `chcon` under /pages/common instead of /pages/linux?

**Comment by CleanMachine1** [comment]
Might it be available on a platform like MacOS?

**Comment by cyqsimon** [comment]
> Might it be available on a platform like MacOS?

AFAIK, no.

`man chcon`

```man
─────────────────────────────────────────────────────────────────────────────────────────
CHCON(1)                             User Commands                            CHCON(1)

NAME
       chcon - change file security context

SYNOPSIS
       chcon [OPTION]... CONTEXT FILE...
       chcon [OPTION]... [-u USER] [-r ROLE] [-l RANGE] [-t TYPE] FILE...
       chcon [OPTION]... --reference=RFILE FILE...

DESCRIPTION
       Change the SELinux security context of each FILE to CONTEXT.  With --reference,
       change the security context of each FILE to that of RFILE.
```

Unless MacOS has an equivalence to SELinux and also uses the same `chcon` (which I don't believe is the case). Even then the usage is certainly not the same.
