### ISSUE TITLE
page request: csvkit (for common args)

### ISSUE THREAD

**Issue by oxguy3** [tldr-pages/tldr#749]
I recently contributed tldr pages for a lot of the tools in [csvkit](https://csvkit.readthedocs.org/en/0.9.1/cli.html), a command-line utility belt for dealing with CSV files. Since the pages got merged and I've actually been using them in practice, I'm noticing that I really wish I had more information.

Every tool in csvkit has its own set of arguments and options, but there's also [a lot of options common to all commands](https://csvkit.readthedocs.org/en/0.9.1/common_arguments.html). Many of these options tend to be very useful very often, but there wasn't really space to cover them on each individual tldr page.

So here's my idea: There's no "csvkit" command, but we could make a "csvkit.md" tldr page. This page could be used exclusively for documenting the shared arguments. On the pages for each individual command, the note "Included in csvkit." could be replaced with "See `tldr csvkit` for further information."

This would allow these very useful arguments to be documented without overfilling any one tldr page. But it'd be a bit of a deviation from normal tldr-pages operating procedures, so I figured I'd ask before making a PR. What do you guys think?

**Comment by oxguy3** [comment]
The arguments I'd probably want to include in csvkit.md would be `-d` (specify weird delimiter), `-t` (specify delimiter is tab character, overrides `-d`), `-q` (specify weird quote character), and `-H` (denote that there is no header row)

**Comment by waldyrious** [comment]
I agree with your thinking :+1:

**Comment by waldyrious** [comment]
Fixed by @GuilhermeJSilva in #3386! 🎉
