### ISSUE TITLE
Sysctl for Linux section

### ISSUE THREAD

**Issue by Cvetomird91** [tldr-pages/tldr#750]
I noticed that there's a sysctl page for MacOS, but the Linux section is lacking one. 

I am taking in consideration that these are two different types of operating systems and kernels, so the sysctl command is most probably operating in a different manner in those systems.

I can create a PR for the Linux specific sysctl utility.

Or should the content of the MacOS page be moved into pages/other and extended with Linux specific options. 

Please advise.

**Comment by rubenvereecken** [comment]
Hi @Cvetomird91, we just need a linux-specific copy in `pages/linux`, that'll be sufficient. You can copy the MacOS page to get you started.

**Comment by rubenvereecken** [comment]
PR at #750.
