### ISSUE TITLE
Group commands by shells

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7503]
There are now some tldr pages related to shell builtins. I suggest group such pages by shell not to be limited by naming conflicts in the same folder. Grouping only by OS is not always enough.

Maybe the following strategy would be enough:

- If command is __not OS specific and is external__ then it goes to `pages/general/general` folder.
- Else if command is __OS specific and is external__ then it goes to `pages/<os_name>/general` folder.
- Else if command is __not OS specific and is shell specific__ then it goes to `pages/general/<shell_name>` folder.
- Else it goes to `pages/<os_name>/<shell_name>` folder.

**Comment by CleanMachine1** [comment]
This makes the structure of tldr a lot more complex.

I can't tell if I like it but this will break a **lot** of clients.

**Comment by EmilySeville7cfg** [comment]
Maybe it's better to have less clients but more robust. ;) Having too many clients is not very convenient - not all of them are up to date for now and moreover not all of them have the same features.

The way we can solve this problem - list tldr clients we want to support officially and try change them so they will support suggested directory structure (maybe not by default but via some flag). I can make PRs for console clients because I don't have much experience in writing GUI apps. ;)

**Comment by sbrl** [comment]
I'm not sure I follow your proposed solution, @EmilySeville7cfg.

While I agree that shell builtins are a sticking point, note that part of what makes tldr-pages really useful and easy to contribute to is it's simplicity - I'm wary of the additional complexity this would introduce.

Perhaps documenting such shell builtins is best left for a cheatsheet-style project rather than tldr-pages itself?

**Comment by EmilySeville7cfg** [comment]
Another solution: describe short list of builtins what can be described here, and accept only them to reduce naming conflicts with external commands similarly named.  For example we accept only POSIX-compatible shell builtins for:

- setting/unsetting variables
- if conditions
- for/while/do-while/until loops
- case patterns

**Comment by sbrl** [comment]
Something like that makes sense, yeah. It's interesting you've brought up POSIX compatibility - this could be a good standard to decide on what can be included in a page about a shell builtin that is present in multiple shells.

Of course, I'm some shells have their own unique builtins that are not found in other shells, and these could be treated as regular commands with a note what shell they are from.

**Comment by marchersimon** [comment]
I'm closing this now, since the original proposal would need a new directory structure.

**Comment by EmilySeville7cfg** [comment]
Okay ;)
