### ISSUE TITLE
Describe quoting rules

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7521]
I suggest to write quoting rules to standardize where we use them or not. They may be as follows:

- Prefer double quotes everywhere until they are nested. In such case use single quotes not to complicate code snippets with quote escaping when possible. Motivation: allow user insert variable names/command substitutions/etc in some command without worrying about quoting.
- Do not use quotes only when some shell/tool requires number. If any arbitrary string is accepted then double quotes must be used.

At my glance it's better to be slightly more verbose than allow user do unintended mistakes because of relatively complex quoting rules in shells.

**Comment by sbrl** [comment]
Using doublle quotes *everywhere* could significantly confuse pages. I think it's probably best to only use them:

1. When they are required for a command to function correctly
2. When an argument will always contain spaces.

Remember that the point of tldr pages is to describe a specific command - not basic functionality of your shell. Quotes and such in pages are simply suggestions - just like the `sudo` prefix is also just a suggestion that `root` privilages are required.

**Comment by EmilySeville7cfg** [comment]
> When they are required for a command to function correctly

In other words: when command fails to handle string with space-separated words. But what means "fails" in this case? Returning non-zero status, some error message in stderr or unexpected/undefined behaviour?

**Comment by EmilySeville7cfg** [comment]
What about simply use quotes for an argument only when command permits spaces in argument?

**Comment by sbrl** [comment]
That sounds good, but it's really situationally specific. While conventions exist, there are always exceptions to those conventions - and even then such conventions aren't implemented equally by everyone.

**Comment by EmilySeville7cfg** [comment]
I will use the following rule for PRs:

> Use double quotes for an non-path argument only when command permits spaces in argument or any character outside of `[0-9A-Za-z]`.

**Comment by EmilySeville7cfg** [comment]
This issue is no longer needed.
