### ISSUE TITLE
Add collaborator: @258204

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#7522]
Hi, @258204! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#6131, #6132, #6133, #6134, #6137, #6145, #6547, #7484)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by 258204** [comment]
Thank you! I accept.

**Comment by navarroaxel** [comment]
Invitation sent, please accept it and send a PR adding you to https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md to close this issue.

**Comment by sbrl** [comment]
Welcome, @258204 :tada:
