### ISSUE TITLE
ble.sh pages request

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7533]
I want to create [ble.sh](https://github.com/akinomyoga/ble.sh) tldr pages.

**Comment by CleanMachine1** [comment]
there is no need to request pages, do you mean you want someone else to see this and make one?

If you plan on doing them, please close this issue!

**Comment by EmilySeville7cfg** [comment]
> there is no need to request pages, do you mean you want someone else to see this and make one?

No, I mean myself. ;)

**Comment by CleanMachine1** [comment]
Thanks for the clarification!
