### ISSUE TITLE
Add organization owner: @marchersimon

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#7540]
Hi, @marchersimon! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by marchersimon** [comment]
Unfortunately I currently don't really have time for tldr and that probably won't change in the near future. 
But I'd love to take that position, once I can come back to tldr.
I'll just reopen this issue then.

**Comment by marchersimon** [comment]
Totally forgot about this one.
