### ISSUE TITLE
Add organization owner: @CleanMachine1

### ISSUE THREAD

**Issue by navarroaxel** [tldr-pages/tldr#7541]
Hi, @CleanMachine1! You've been an active tldr-pages organization member for over 6 months.
Thanks for sticking around this far and helping out!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you're now eligible for becoming an owner in the organization.

That means you will, from now on, be part of the team responsible for performing role changes (like this one!) in the community.
When performing such role transitions, make sure to follow the process described in the [COMMUNITY-ROLES.md](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md) document.

Is that OK with you? Let us know!

Either way, thanks so much for all the work you've done so far. You rock!

**Comment by CleanMachine1** [comment]
Of course! I'll make the PR!

**Comment by 258204** [comment]
Congratulations! You've certainly earned it.

**Comment by bl-ue** [comment]
Belated, but, **congratulations @CleanMachine1!!** 😄
