### ISSUE TITLE
Regarding Databricks issue

### ISSUE THREAD

**Issue by ssvm12ptps** [tldr-pages/tldr#7552]
I have completed this part:- First copy the token somewhere safe, then select Configure SSO and Authorize to allow the token to access the M&S Digital Innovation organisation 

Now I am looking for this part but not finding:-
 Open Databricks and go to Settings followed by User Settings

After that I will perform this:-
Under the Git Integration tab chose GitHub as the Git provider, input your Marks and Spencer email that you’ve used for your GitHub account then paste in the newly generated access token

**Comment by MasterOdin** [comment]
This repository is not for providing support for using Databricks. Your best bet is to consult their [Help Center](https://help.databricks.com/s/) and the associated resources like their community or dedicated support team.
