### ISSUE TITLE
page request: ip-route-show

### ISSUE THREAD

**Issue by kamalmost** [tldr-pages/tldr#7568]

**Comment by d4n3sh** [comment]
@kamalmost 

The page is available at [ip-route.md](https://github.com/tldr-pages/tldr/blob/main/pages/linux/ip-route.md)

**Comment by patricedenis** [comment]
Hi, as said by @d4n3sh the issue is already been addressed by #5696.
Would you like some other examples?

**Comment by marchersimon** [comment]
The current `ip route` page does however not really document `ip route show`, which itself has a lot of subsubsubcommands.

**Comment by patricedenis** [comment]
Yes, that's right.
I will see if I can add some extra details on this one.
