### ISSUE TITLE
TLDR -u homebrew Error: Unable to update cache

### ISSUE THREAD

**Issue by gmkey** [tldr-pages/tldr#7569]
When I perform `tldr -u` I get the following error `Error: Unable to update cache from https://tldr-pages.github.io/assets/tldr.zip`

I've checked what whould happen if I were to request the update using wget. This is the output (in dutch, but the meaning should be clear:

`FOUT: kan certificaat van tldr-pages.github.io (uitgegeven door ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’) niet controleren: 
Kan de autoriteit van de uitgever niet lokaal verifiëren.
Gebruik '--no-check-certificate' om een onbeveiligde verbinding met tldr-pages.github.io te maken.`

Free translation: 
```
Error: can't verify the cerficate belonging to ldr-pages.github.io (issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’):
can't locally verify the authority of the issuer. 
Use '--no-check-certificate' to setup an insecure connection with tldr-pages.github.io.```

I have checked what could be at the root of this issue on this site:
https://support.apple.com/en-us/HT212773

It seems that Macos  12.1 no longer supports DigiCert SHA2 High Assurance Server CA.

Or at least the redirection to tldr.sh yields a similar result.
```
❯ wget https://tldr.sh/assets/tldr.zip
--2021-12-23 14:40:16--  https://tldr.sh/assets/tldr.zip
Herleiden van tldr.sh (tldr.sh)... 104.21.44.67, 172.67.196.115
Verbinding maken met tldr.sh (tldr.sh)|104.21.44.67|:443... verbonden.
FOUT: kan certificaat van tldr.sh (uitgegeven door ‘CN=Cloudflare Inc ECC CA-3,O=Cloudflare\\, Inc.,C=US’) niet controleren:
  Kan de autoriteit van de uitgever niet lokaal verifiëren.
Gebruik '--no-check-certificate' om een onbeveiligde verbinding met tldr.sh te maken.
```

**Comment by sbrl** [comment]
Hmmm, the certificate seems fine for me. have you made sure your system root CA certificates are up to date?
