### ISSUE TITLE
page request: netperf

### ISSUE THREAD

**Issue by Dentrax** [tldr-pages/tldr#7570]
[Netperf](https://github.com/HewlettPackard/netperf) is a benchmark that can be used to measure the performance of many different types of networking. It provides tests for both unidirectional throughput, and end-to-end latency.

**Comment by navarroaxel** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
