### ISSUE TITLE
Automate applying "review-needed" label

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr#7582]
From Gitter, would be useful to apply the review-needed label automatically as new maintainers might not know it exists, and rules to apply it are generally static.

Quoting the relevant thread below as could not find a way to link to it.

> Starbeamrainbowlabs @sbrl Dec 24 18:07
> Don't forget to attach the review needed label to PRs that need a second review to allow for rapid identification & handling
> 
> Matthew Peveler @MasterOdin Dec 25 16:12
> Do we want to automatically apply review needed to PRs that are X days old and have less than two reviews? Or just apply it any new PR? Feel like we could automate that tag...
> 
> Starbeamrainbowlabs @sbrl Dec 26 17:14
> Sounds like a good idea, @MasterOdin!
> 
> Starbeamrainbowlabs @sbrl Dec 26 17:14
> how do we automate tagging PRs already?
> 
> Matthew Peveler @MasterOdin Dec 26 17:45
> A GH action (https://github.com/tldr-pages/tldr/blob/main/.github/workflows/labeler.yml) runs anytime someone writes to a PR which triggers https://github.com/tldr-pages/tldr-labeler-action
> 
> Matthew Peveler @MasterOdin Dec 26 17:46
> For this proposal, could automate it to run when a PR is submitted, PR review is submitted, or just a nightly cron job depending on what criteria you'd want to have to apply that label
> 
> Starbeamrainbowlabs @sbrl Dec 26 18:03
> Hmmmm, for now when a PR review is submitted seems like the best option
> Then we can check if the PR has 1 approval + no request changes, and then auto-label it with review-needed

**Comment by CleanMachine1** [comment]
I think if possible, it should be added 24 hours after 0 or only 1 reviews

**Comment by sbrl** [comment]
@CleanMachine1's suggestion sounds good. I therefore propose the following conditions:

1. The PR has only 1 approval AND no request changes AND has been open for more than 24 hours
2. The PR has no reviews AND is open for more than 24 hours

**Comment by MasterOdin** [comment]
Should there be a new label created named "Revision Needed" or something for the case where there's a comment by @tldr-bot or the PR request changes?

**Comment by CleanMachine1** [comment]
> Should there be a new label created named "Revision Needed" or something for the case where there's a comment by @tldr-bot or the PR request changes?

We kind of already have this in the form of the waiting tag. However I see no harm in adding it.

**Comment by MasterOdin** [comment]
Ah, I missed the "waiting" label, yeah, that works.
