### ISSUE TITLE
page request: bazel

### ISSUE THREAD

**Issue by uhthomas** [tldr-pages/tldr#7586]
Bazel is a tool that automates software builds and tests.

https://bazel.build/

It doesn't look like there are any man pages (beside https://github.com/bazelbuild/bazel/issues/10519), or great examples of tldr-eqsue content.

**Comment by navarroaxel** [comment]
Thanks for requesting this page! Do you want to have a go yourself?

Pages are best created by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
