### ISSUE TITLE
page request: interfaces

### ISSUE THREAD

**Issue by Dygear** [tldr-pages/tldr#7607]
Current man pages can be found here: [HE Man Pages: `INTERFACES(5)`](http://man.he.net/?topic=interfaces&section=all).

I admit this is a big topic. I don't think it would be possible to do a true TLDR for this because it's so huge with so many options. My problem is that it's not very well documented from what I can find on the internet right now. Would this project be suitable for such a large undertaking? I think it would be about a chapter of writing for this to actually be useful for anyone. I would remove references to older standards such as IPX, and focus more on the WiFi / Ethernet options with IPv4 and IPv6. A strict TLDR might be possible, 6 short examples that would get an interface up and running, but I'm not entirely sure if that would be actually useful with so many possible options.

We could focus on getting an ethernet connection up or a WiFi connection up for examples one and two. For examples three and four setting a static IP address in the verbose (Gateway, Netmask) and then concise way (CIDR notation). For five and six, setting predicate with the pre-up and then termination with post-down.

**Comment by Managor** [comment]
What are the commands that this would document?

**Comment by Dygear** [comment]
It’s been so long since I’ve even thought about this. I think it was the ip command. If I recall this was when I was setting up my Debian server and was trying to get all of the interfaces to play nice.

**Comment by Managor** [comment]
In that case I'll close this issue for now. The pages might exist by now or they might have a Let's document issue opened.
