### ISSUE TITLE
replace current rename page with the contents of file-rename, remove file-rename

### ISSUE THREAD

**Issue by IniasP** [tldr-pages/tldr#7616]
Currently, the page for `rename` contains the following:
```
NOTE: this page refers to the command from the util-linux package.
For the Perl version, see file-rename or perl-rename.
```
However, `rename` is no longer being installed by `util-linux` (as I observe on my system running Ubuntu 21.10, but see also [this commit](https://salsa.debian.org/debian/util-linux/-/commit/1c7dc9a26c6e7e273b87b374e72f64261f52348f)).

Additionally, the `file-rename` page mentions:
```
NOTE: this page refers to the command from the file-rename Debian package.
```
But [there is no file-rename Debian package](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=file-rename). Both `file-rename` and `rename` are installed by the [rename package](https://packages.debian.org/bullseye/rename).
These commands are the same in terms of tldr support, because their man pages [rename(1)](https://manpages.debian.org/testing/rename/rename.1.en.html) and [file-rename(1p)](https://manpages.debian.org/testing/rename/file-rename.1p.en.html) contain only one difference, which is the `-u` option added by `rename`.
There is also [prename(1p)](https://manpages.debian.org/testing/rename/prename.1p.en.html), equivalent to `file-rename`.

I would propose to just get rid of the current `rename` page for the `util-linux` version and make the page for `rename` about the more relevant version, namely the perl version from the rename package, currently documented as `file-rename` for Debian (and `perl-rename` for Arch, but that looks right).
If that's not something we want, then at least the `file-rename` page should be updated to say its Debian package is named `rename`, not `file-rename`.

**Comment by navarroaxel** [comment]
But, you are checking the specific repo for Debian. The official Linux repo is https://github.com/util-linux/util-linux and the releases are being published here: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/

I still have the command in Arch Linux.

**Comment by IniasP** [comment]
You're right, in that case it's probably a bad idea to simply get rid of the `util-linux` version. Do you agree that the package name should be changed to `rename` on the `file-rename` page?

**Comment by sbrl** [comment]
Oh wow, this was the command I was thinking of the other day when things got complicated with command names. Does anyone have a link to the issue/PR where this was last discussed? I believe it got significantly complicated.

**Comment by IniasP** [comment]
> a

I think you mean https://github.com/tldr-pages/tldr/issues/3125. I hadn't noticed it when searching for similar issues/prs, looks very complicated indeed. I trust that they resolved their mess properly, but Debian does not seem to have a `file-rename` package. On Debian, the package installing `file-rename`, `prename`, `rename` (since the Debian version of `util-linux` doesn't install its `rename` anymore as established above) is simply called `rename`.

Anyway, I think just changing that package name is fine for this issue, since I was tunnel-visioned on Debian when proposing to throw out the `util-linux` version.
