### ISSUE TITLE
CLA signing not working 

### ISSUE THREAD

**Issue by n14s** [tldr-pages/tldr#7627]
I [added a page](https://github.com/tldr-pages/tldr/pull/7604) around a week ago.
Throughout the week I signed the CLA of the pull request. There was no error thrown. It doesn't change its status though and is still blocking the pr.

Any ideas?

**Comment by navarroaxel** [comment]
The issue is with this commit (it doesn't have your avatar)
![image](https://user-images.githubusercontent.com/1536740/148600177-915e4e56-7c69-469a-bd75-f636e36e1eb6.png)
If you use `git log` you can see that <email-provider> email address is not associated with your GitHub account.
