### ISSUE TITLE
Suggestion: Add link to ArchWiki's Rosetta page in pages for Linux package managers

### ISSUE THREAD

**Issue by cyqsimon** [tldr-pages/tldr#7637]
When it comes to commonly used package managers like `apt`, `dnf`, `pacman`, etc, [Archwiki's Rosetta page](https://wiki.archlinux.org/title/Pacman/Rosetta) is an excellent middle ground between a tldr page and a full-on manpage. I think a link to it would be helpful for many Linux users looking up an unfamiliar package manager.

The justification is that most Linux users would have some experience with at least one package manager. So if they are on a different distro with a different package manager, the best way to help them could very well be to show them a translation table if the tldr page does not suffice.

Personally I had prior experience in `dnf` and `apt` prior to using `pacman` on Manjaro, so this Rosetta page became my goto-resource before reading any manpage. I feel like this is a relatable experience to many other Linux users too, whether they are distro-hopping, working on a server over SSH, or testing software compatibility. I think it would be nice if tldr simply informs its users of this resource via a link.

And finally as a disclaimer - I'm not financially associated with ArchLinux or Archwiki. I am promoting their Rosetta page simply because it's the best resource of its kind, in my opinion, as far as I know. Please don't hesitate to suggest an alternative if you think it's better.

**Comment by cyqsimon** [comment]
This is what it would look like, using the tealdeer client on Alacritty:
![image](https://user-images.githubusercontent.com/28627918/148789289-e3a3e285-dc8d-4d57-ba82-5d445e02c4cf.png)

**Comment by sbrl** [comment]
Hmmmmm. This isn't a bad idea - and it doesn't break the client spec either. The question I suppose is whether the linter would like it. I wonder what others think fo this. /cc @navarroaxel, @258204, @CleanMachine1.

**Comment by 258204** [comment]
This is an excellent idea.

**Comment by CleanMachine1** [comment]
LGTM

**Comment by cyqsimon** [comment]
Great. If so I will go ahead and open a PR. Before that though, any ideas on how to shorten this line a bit without sacrificing clarity?

```
For a translation table between different package managers, see: <https://wiki.archlinux.org/title/Pacman/Rosetta>.
```
