### ISSUE TITLE
Escaping placeholders via backslash

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7673]
It is not possible to write smth like this now:

```md
`awk '{{\{ print gensub("apple", "mango", "g") \}}}'`
```

to underline that awk accepts an arbitrary correct command not just this one.

**Comment by blueskyson** [comment]
If you want to display `{ ... }`, You can see the 6th example of `jq.md`:
```
`cat {{file.json}} | jq '{{{my_new_key}}: .{{key_name}}, {{my_other_key}}: .{{other_key_name}}}'`
```

If you want to display `\{ ... \}`, You can see the 5th example of `fakedata.md`:
```
`echo "{{\{\{Generator\}\}}}" | fakedata`
```

**Comment by EmilySeville7cfg** [comment]
Thanks. ;)

**Comment by EmilySeville7cfg** [comment]
![image](https://user-images.githubusercontent.com/42812113/150630428-4f10fbdd-0564-463c-9cb8-b33c54fd14ad.png)

Coloring is broken... It is a tldr client problem.
