### ISSUE TITLE
Add collaborator: @EmilySeville7cfg

### ISSUE THREAD

**Issue by blueskyson** [tldr-pages/tldr#7677]
Hi, @EmilySeville7cfg ! You seem to be enjoying contributing to the tldr-pages project.
You now have had nineteen distinct pull requests merged (between #7409 to #7675 from [here](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3AEmilySeville7cfg+is%3Aclosed))!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by EmilySeville7cfg** [comment]
Yes, you can me as a collaborator. :)

**Comment by navarroaxel** [comment]
@EmilySeville7cfg invited.

**Comment by mfrw** [comment]
Welcome :)

**Comment by CleanMachine1** [comment]
Thanks for all of your current, past and (hopefully) future commits!
