### ISSUE TITLE
alias ripgrep to rg?

### ISSUE THREAD

**Issue by uhthomas** [tldr-pages/tldr#7686]
The package [ripgrep](https://github.com/BurntSushi/ripgrep)'s tool is `rg`. TLDR pages for `rg` exist, but tldr for `ripgrep` doesn't. Does it make sense to alias this? (if possible)

**Comment by navarroaxel** [comment]
We document commands, not packages. Is this executable named `ripgrep` in some OS? or is it always just `rg`?

**Comment by git-em** [comment]
>  Is this executable named `ripgrep` in some OS?

I don't think so. [The binary name for ripgrep is `rg`](https://github.com/BurntSushi/ripgrep/blame/master/README.md#L192).

**Comment by marchersimon** [comment]
While not really the purpose of tldr, I think it couldn't hurt to have a `ripgrep` page, which states, that `ripgrep` is just the common name for `rg`. I can imagine that some people are trying to run `tldr ripgrep`.
