### ISSUE TITLE
Lookup aliases

### ISSUE THREAD

**Issue by uhthomas** [tldr-pages/tldr#7692]
Some users may be used to using aliases which come out of the box with popular terminal frameworks like [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh). It may be useful to lookup the alias if the function cannot be found. For example, `gsw` is an alias for `git switch`. It would be nice for `tldr gsw` to transparently become `tldr git switch`. This can be achieved with `tldr $(alias gsw | choose -f \' 1)`.

What are your thoughts? Would this be useful or is it just bloat?

**Comment by sbrl** [comment]
Hrm. This is a client-specific feature I think. We have alias pages already in tldr-pages, but they are not transparent as you describe here - instead they are regular pages. See `mscore` for example.

**Comment by blueskyson** [comment]
Currently we can provide an alias page like:
```
# gsw

> This command is an alias of `git switch`.

- View documentation for the original command:

`tldr git switch`
```

**Comment by marchersimon** [comment]
As @sbrl mentioned this would have to be client specific. There's not a lot we can do about that.
