### ISSUE TITLE
page request: duc

### ISSUE THREAD

**Issue by AngelODeath** [tldr-pages/tldr#7770]
https://duc.zevv.nl/ - collection of tools for inspecting and visualizing disk usage

**Comment by AngelODeath** [comment]
I have prepared a md file I would like to contribute

**Comment by CleanMachine1** [comment]
There is no need to request a page, this type of "issue" is for when the requester doesn't know how to use the command for example.

Feel free to open a PR whenever!

**Comment by AngelODeath** [comment]
It seems I am unable to open a PR, as I am ubable to create a branch pages/duc

**Comment by AngelODeath** [comment]
I created a PR using Github UI

**Comment by CleanMachine1** [comment]
Did you open a branch on a fork or did you try to push straight to the repo? 

If you tried to push here then since you aren't an admin of the repo, it will be rejected
