### ISSUE TITLE
page request: lci

### ISSUE THREAD

**Issue by nebulaa44** [tldr-pages/tldr#7786]
LCI refers to the LolCode Interpreter. Decided I'd mention because there's barely any related results for googling "LCI".

**Comment by centaurii44** [comment]
I might put up a PR for this once I get home.

**Comment by saikatsgupta** [comment]
https://github.com/justinmeza/lci

**Comment by nath1as** [comment]
pr open https://github.com/tldr-pages/tldr/pull/9033
