### ISSUE TITLE
page request: startx

### ISSUE THREAD

**Issue by nebulaa44** [tldr-pages/tldr#7793]
A manpage can be found [here.](https://linux.die.net/man/1/startx)

**Comment by lknows** [comment]
> A manpage (for startx)can be found [here.](https://linux.die.net/man/1/startx)

And here's a manpage for [xinit here.](https://linux.die.net/man/1/xinit)

The startx script is a front-end for xinit. -- [xinit ArchWiki](https://wiki.archlinux.org/title/xinit)

The xinit program allows a user to manually start an X display server. -- [xinit Wikipedia](https://en.wikipedia.org/wiki/Xinit)

By default, xinit and startx start an X display server pointing to a display device that is enumerated as `:0` and then start an xterm on it. When the xterm terminates, xinit and startx kill the X display server. In general, xinit and startx can start an arbitrary server and run an arbitrary script. Typically, this script runs a number of programs and a window manager.

**Comment by nath1as** [comment]
added with https://github.com/tldr-pages/tldr/pull/8752
