### ISSUE TITLE
page request: ld

### ISSUE THREAD

**Issue by centaurii44** [tldr-pages/tldr#7794]
A manpage for ld can be found [here.](https://linux.die.net/man/1/ld)

**Comment by maniyar1** [comment]
Hello, I'm planning on going through and trying to PR this in soon, I was wondering if the llvm (`lld`) and gnu (`ld`) `ld`s should be done separately or if they're seen as "close enough" to do one PR for both? The second seems to be implied by #6367 and that's what I'm going forward with right now, but let me know? Thank you.

**Comment by pixelcmtd** [comment]
`lld` is not one program (there is a binary called `lld`, but nobody's supposed to use it that way), but rather like other parts of LLVM a set of clones. `ld.lld` emulates `ld`, `lld-link` emulates `link`, like `clang` and `clang-cl` emulate `gcc` and `cl`. Therefore I think that `ld` should be based on GNU `ld` and `gold` documentation, and `ld.lld` an alias of `ld`.

**Comment by maniyar1** [comment]
This is fair - one of my examples is working on `ld` but not `ld.lld` which is odd, im away from home for a few days but I'll look when I get back. I know `ld.lld` has the stated goal of being a complete drop in replacement for `ld` so if im doing things right this might be something to bring up with them.
