### ISSUE TITLE
Cannot create directory after aborting first tldr run

### ISSUE THREAD

**Issue by yassinecc** [tldr-pages/tldr#7798]
#### Platform
- Ubuntu 20.04.3

#### Observed behaviour
When I install tldr and run it for the first time with e.g. `tldr tar`, if I exit during initialization, subsequent tldr runs will fail with the following message:
```bash
mkdir: cannot create directory ‘/home/yassine/.tldr’: File exists
tldr: Received ExitFailure 1 when running
Raw command: mkdir /home/yassine/.tldr
```

#### Expected behaviour
It's possible to delete the ~/.tldr folder to avoid the issue but subsequent runs could gracefully recover from the first exit

#### Ideas
I would attempt to clean up the .tldr folder on abortion or on next runs. Any other ideas or suggestions?

**Comment by navarroaxel** [comment]
How did you install the client? via `npm` or `apt`? which client version?

**Comment by MaJiu** [comment]
> How did you install the client? via `npm` or `apt`? which client version?

Hi，navarroaxel. I ran into this problem too. I installed it via `apt`  on Ubuntu 20.04 LTS

**Comment by navarroaxel** [comment]
@MaJiu the client installed via `apt` is a really old version of the Node.js client. I recommend that you install it via `npm install -g tldr` or the https://github.com/dbrgn/tealdeer client.

**Comment by MaJiu** [comment]
> @MaJiu the client installed via `apt` is a really old version of the Node.js client. I recommend that you install it via `npm install -g tldr` or the https://github.com/dbrgn/tealdeer client.

Got it! Thank You! I run it successfully via `npm`.

**Comment by CleanMachine1** [comment]
@yassinecc could you please confirm that this solution works for you. 

Personally I would recommend using our official python client, `pip install tldr`

**Comment by yassinecc** [comment]
I installed `tldr` through `apt` indeed. Installing through `npm` or `pip` does solve the issue indeed @CleanMachine1 , thanks :+1:
