### ISSUE TITLE
linux/ac: command also available on osx

### ISSUE THREAD

**Issue by git-em** [tldr-pages/tldr#7859]
Osx have a limited but somewhat linux-compatible version of [`ac`](https://www.unix.com/man-page/freebsd/8/ac/). As usual it doesn't support long options, but it does have all of the same functionalities, except for: https://github.com/tldr-pages/tldr/blob/c12a5c84333fb51372ee3a2e466c1150817c6078/pages/linux/ac.md?plain=1#L22-L24

Should it be trimmed and moved to [common](https://github.com/tldr-pages/tldr/tree/c12a5c84333fb51372ee3a2e466c1150817c6078/pages/common)?

**Comment by CleanMachine1** [comment]
Create a new page for just the mac without that option.

**Comment by pixelcmtd** [comment]
> Create a new page for just the mac without that option.

Shouldn't that be in common since it's also in FreeBSD, as you can see in that manpage?
