### ISSUE TITLE
tldr-book.pdf, inconsistent visibility of entries

### ISSUE THREAD

**Issue by nbehrnd** [tldr-pages/tldr#7870]
Though I don't intend to print the [the book](https://tldr.sh/assets/tldr-book.pdf), I noticed the sort of entries in the .pdf restarts more than once by letter «a»:

![2022-03-09_tldr_sort](https://user-images.githubusercontent.com/19709084/157434378-713a9b73-6fe2-4592-8750-a02b730ef950.png)

(outline mode, qpdfview)

I would welcome if these entries (except for `tldr pages`, of course) were sorted consistently by a -> z, without discern if the entry starts with in lower case (most entries), or upper case (e.g., `AdGuardHome`).

**Comment by navarroaxel** [comment]
That's because after the list of Linux pages, the PDF starts with the pages in the `osx/` folder. That's why after `zypper`, it continues with `afinfo`.

**Comment by nbehrnd** [comment]
I now recognize that the document consists of multiple sections (e.g., Android, p. 2 [though the later entry about gimp, p. 597, or inkscape, p. 934 may be seen cross-platform]; or Linux, p. 2038; or Osx, p. 2816).

However then, the cross-links of _these_ section titles in the index should not be nested as an entry of the previous software described (e.g., Linux as last entry of zsteg, p. 2037; and Osx as last entry of zypper, p. 2815) which are visible only if the index entries are unfolded:

![2022-03-09_nested_Linux](https://user-images.githubusercontent.com/19709084/157538942-37cb5d68-4487-47b3-a6e7-085d391c09e3.png)

![2022-03-09_nested_Osx](https://user-images.githubusercontent.com/19709084/157538995-f4dd1d0c-eda3-4a3a-9fd0-797cdcf72ef3.png)

Instead, these should be as prominent (i.e. at hierarchy equal to) `tldr pages`.  Entries like e.g., `am`, `bugreport` etc., dependent children of the former then should subsequently move to lower hierarchy (similar to `Simplified and community-driven man pages`):

![2022-03-09_unest_Android](https://user-images.githubusercontent.com/19709084/157540181-4e436ccb-7538-44df-b420-4fccc5ea68aa.png)

**Comment by navarroaxel** [comment]
@MasterOdin could you please check if we can fix this issue in the Python code?
