### ISSUE TITLE
Separate pages with language syntax examples

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7944]
For instance we have `sed.md` which mainly describes `sed` options. I suggest create `sed.syntax.md` (and others similar)  pages to write about sed commands. It is hard to demonstrate everything in just 8 examples.

What do you think about it?

**Comment by blueskyson** [comment]
I'm not a fan of this. I think brief, useful examples is good for tldr. You should find a projext that accepts detailed cheat sheet. Or maybe we can open a new repository for detailed this? @CleanMachine1 @navarroaxel

**Comment by CleanMachine1** [comment]
Yeah, I agree with @blueskyson this doesn't fit the scheme of tldr

**Comment by sbrl** [comment]
I agree with @blueskyson and @CleanMachine1 - this falls outside the scope of tldr-pages, as it sounds more like a cheat sheet then a tldr page. Perhaps it would be better served being contributed to a collection of cheat sheets instead?
