### ISSUE TITLE
page request: hcloud

### ISSUE THREAD

**Issue by pixelcmtd** [tldr-pages/tldr#7950]
https://github.com/hetznercloud/cli

- [ ] hcloud (#8147)
- [ ] hcloud-certificate
- [ ] hcloud-completion
- [ ] hcloud-context
- [ ] hcloud-datacenter
- [ ] hcloud-firewall
- [ ] hcloud-floating-ip
- [ ] hcloud-help
- [ ] hcloud-image
- [ ] hcloud-iso
- [ ] hcloud-load-balancer
- [ ] hcloud-load-balancer-type
- [ ] hcloud-location
- [ ] hcloud-network
- [ ] hcloud-placement-group
- [ ] hcloud-server
- [ ] hcloud-server-type
- [ ] hcloud-ssh-key
- [ ] hcloud-version
- [ ] hcloud-volume

**Comment by i8abyte** [comment]
Hi @pixelcmtd, I'd like to work on this issue.

**Comment by pixelcmtd** [comment]
@i8abyte I appreciate that, feel free to ask me in case you have any questions that the Style Guide can't answer for you.

**Comment by i8abyte** [comment]
Hi @pixelcmtd, I have opened a PR:
[hcloud: add page #8147](https://github.com/tldr-pages/tldr/pull/8147)
