### ISSUE TITLE
Standardize arbitrary number argument syntax for placeholders

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#7969]
## First decision

I suggest the following syntax to be used when any number of arguments are required:

- 0..1: `command_name {{""|argument_name}}`
- 0..more: `command_name {{""|argument_name1 ...}}`
- 1..more: `command_name {{argument_name1}} {{""|argument2 ...}}`

Examples:

- 0..1: `command_name {{""|path/to/source_file}}`
- 0..more: `command_name {{""|path/to/source_file1 ...}}`
- 1..more: `command_name {{path/to/source_file1}} {{""|path/to/source_file2 ...}}`

## Second decision

Use one syntax for everything:

- 0..1, 0..more, 1..more: `command_name {{argument_name1 ...}}`

Examples:

- 0..1, 0..more, 1..more: `command_name {{path/to/source_file1 ...}}`

**Comment by CleanMachine1** [comment]
https://gitter.im/tldr-pages/tldr?at=6258f24d8db2b95f0ab84570
