### ISSUE TITLE
Travis CI doesn'e isn't triggered consistently for all PRs

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#803]
See e.g. #783.

**Comment by rindeal** [comment]
Have you seen any other example? Because if not it's quite possible that you simply hit a time-limited failure on GH/Travis side.

GH status for 2016/02/22:
```
05:12 UTC
We've identified an issue with an upstream peering provider. Connectivity is restored and we continue to monitor the situation.
04:49 UTC
We're investigating connectivity issues affecting some users. 
```

**Comment by waldyrious** [comment]
At the time I had seen quite a few, but I don't recall seeing the issue lately -- thanks for the heads-up; I'll close this for the time being, we can reopen later if we see it happening again.
