### ISSUE TITLE
Add @EmilySeville7cfg as org member

### ISSUE THREAD

**Issue by mfrw** [tldr-pages/tldr#8053]
Hi, @EmilySeville7cfg! After joining as a collaborator in the repository, you have been regularly performing maintenance tasks ().
Thank you for that!
According to our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md), you've now met the thresholds to be effectively considered an active maintainer of the project.
To publicly acknowledge that fact, we'd like to add you to the tldr-pages organization.

If you accept the invitation, we ask you to make your membership public, and (in case you don't already) start hanging out in our Gitter chat room.
Additionally, consider subscribing to the notifications from the various repositories under the [tldr-pages organization](https://github.com/tldr-pages).
As one of the public faces of the tldr-pages project, it's also especially important that you follow and encourage the [project
governance principles](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

How does that sound? Are you up for it?

**Comment by EmilySeville7cfg** [comment]
Sounds great! 😊 I am going to accept this invitation

**Comment by navarroaxel** [comment]
Invitation sent.

**Comment by mfrw** [comment]
@EmilySeville7cfg could you please create a PR where you add yourself in the [Maintainers](https://github.com/tldr-pages/tldr/blob/main/MAINTAINERS.md) file

**Comment by EmilySeville7cfg** [comment]
Yes, I can. 😁

**Comment by mfrw** [comment]
Closed by PR:
- #8062
