### ISSUE TITLE
Imperative mood in command descriptions

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#8056]
When we have to use imperative mood in the top level command descriptions and when not? Contribution guide doesn't mention what to do with command descriptions:

> **Example descriptions** have to be phrased in imperative mood.
For example, use List all files, instead of Listing all files or File listing.
This also applies to all translations by default, unless this is not possible for some reason.

What about to require imperative mood everywhere?

**Comment by marchersimon** [comment]
A sentence in imperative mood is often rather specific. Describing a whole command in imperative mood can often make it unclear what it actually does. Also, for many commands, we use the official command description, which isn't imperative mood either.

I don't really see, where this would help us.

**Comment by sbrl** [comment]
This isn't something I think we should enforce. As @marchersimon says, it's rather situationally specific as to what should be used. Rather, when I'm reviewing I look at the overall tone and voice of the text, and correct it if it seems out of place - though unfortunately I can't offer much more advice here as my native language is English, so I don't think about it much when I'm reviewing haha - for me it's just about what sounds "right".

**Comment by marchersimon** [comment]
@EmilySeville7cfg if you agree, can we close this issue?
