### ISSUE TITLE
page request: free

### ISSUE THREAD

**Issue by dimitris1ps** [tldr-pages/tldr#8117]
### Command description

Let's document [free](https://www.geeksforgeeks.org/free-command-linux-examples/)

### Command details

The free command gives you a summary of the memory usage

### OS

Linux

**Comment by nbehrnd** [comment]
Observation: Preparing a backup, I frequently use `df -h` to check if there is enough capacity available; this seems to overlap with the information collected by `free`.

My question reading the request to add an entry about `free`: is it within the scope of the tldr project to hint the user (e.g., by a cross link to an already existing entry) that there is a command of similar intent?  (A similar pair could be `pdf2ps` and `pdftops` as offered e.g., in Linux Debian.)

**Comment by navarroaxel** [comment]
@nbehrnd but `df` is for filesystem usage, `free` is for memory (RAM) usage.

**Comment by nbehrnd** [comment]
@navarroaxel True, I see that I erred. Sorry.

**Comment by CleanMachine1** [comment]
I am going to close this now, since there is already a preexisting `free` page, and if you would like to add to it, feel free to send a pull request
