### ISSUE TITLE
[rewrite/incorrect] cgroups

### ISSUE THREAD

**Issue by lakhininenina** [tldr-pages/tldr#8123]
https://github.com/tldr-pages/tldr/blob/main/pages/linux/cgroups.md contains commands which seem to be completely wrong.

for example: `Show the tldr page for cgclassify: tldr cgclassify`

**Comment by navarroaxel** [comment]
Based on #6766 the `cgroups` doesn't have any command.

**Comment by lakhininenina** [comment]
@navarroaxel are you aware of other similar man pages? if my commit looks good enough, i will edit other man pages also. thanks for bringing to my attention.

**Comment by CleanMachine1** [comment]
Can we close this issue?

**Comment by lakhininenina** [comment]
@CleanMachine1 thank you. my english is rudimentary. if i come across, i will copy. closing ...
