### ISSUE TITLE
page request: git subcommand

### ISSUE THREAD

**Issue by diegovrocha** [tldr-pages/tldr#8137]
### Command description

Please, let's document **git subcommands**

### OS

General

**Comment by mfrw** [comment]
Hi @diegovrocha, do you have any specific subcommands in mind that do not have a page yet & are not covered by:
- https://github.com/tldr-pages/tldr/issues/3953

Please feel free to use the above tracking issue instead of creating a new one :)

Thank you.

Closing this issue as a duplicate of #3953
