### ISSUE TITLE
page modification: caffeine, caffeinate

### ISSUE THREAD

**Issue by Jonta** [tldr-pages/tldr#8138]
Currently says "Prevent macOS from sleeping"

But is also available for GNU/Linux

Perhaps it should be moved from pages/osx to pages/common, or given its own entry in pages/linux. :)

**Comment by mfrw** [comment]
I think it would make sense to add a new entry for `linux`.

Refrerence:

- [caffeine](https://manned.org/caffeine)
- [caffeinate](https://manned.org/caffeinate)

**Comment by franzqat** [comment]
Added as new entry for linux with PR#8769

**Comment by nicokosi** [comment]
I think this issue can be closed: 
```
$ head -1 /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
$ tldr caffeine

caffeine

Prevent desktop idleness in full-screen mode.
More information: <https://manned.org/caffeine>.

- Start a caffeine server:
    caffeine

- Display help:
    caffeine --help

- Display version:
    caffeine --version

$ tldr caffeinate

caffeinate

Prevent desktop from sleeping.
More information: <https://manned.org/caffeinate>.

- Prevent desktop from sleeping (use `Ctrl + C` to exit):
    caffeinate
```
