### ISSUE TITLE
page request: fuser

### ISSUE THREAD

**Issue by k12ish** [tldr-pages/tldr#8160]
### Command description

Here's a rough summary:

`fuser` displays the PIDs of processes using the specified files or file systems.

Kill the process with a TCP connection on port 8080:

    fuser 8080/tcp -k

### OS

Linux

**Comment by mfrw** [comment]
I think we have a page for [fuser](https://github.com/tldr-pages/tldr/blob/main/pages/linux/fuser.md)
Is there any other specific example that we are missing apart from the `8080/tcp` ?

**Comment by k12ish** [comment]
The TLDR specifications states:

> If a page is not available for either the host platform or the common platform, then clients SHOULD search other platforms and display a page from there - along with a warning message.

I shall take up this gripe with [tealdeer](https://github.com/dbrgn/tealdeer)
