### ISSUE TITLE
Cacheless clients most likely to take 2 requests

### ISSUE THREAD

**Issue by emivespa** [tldr-pages/tldr#8167]
[CLIENT-SPECIFICATION.md 1.5 > Terminology > Platform](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#platform):
>Pages are grouped by platform, i.e. operating systems — for example, `windows`, `linux`, `osx`.
>The special platform `common` contains pages for commands that work identically across more than one platform.
>
>If a page is common across multiple platforms, but slightly differently on a given platform, then the page is still stored in `common`, but a copy tailored for the differing platform is placed in that platform's specific folder.

[CLIENT-SPECIFICATION.md 1.5 > Page resolution > Platform](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#platform-1):
>If a page is not available for the host platform, clients MUST fallback to the special `common` platform.

`linux` and `osx` share most commands, so for those I'd go so far as to guess fetching most pages require a first attempt to fail, only to then fall back to `common`. (Not sure whether this applies to `android` or `sunos`.)

**Comment by emivespa** [comment]
One solution could be to create platform "joins" for cacheless clients by automating some flavor of  this:
        cd pages
        mkdir linux+common
        cp common/* linux+common
        cp linux/* linux+common # Overwriting repeat pages.

**Comment by emivespa** [comment]
Just read up on a couple of issues concerning overhauling the page directory hierarchy (latest #4120). Would making cacheless clients take a single request be considered relevant or are they more of an afterthought?

**Comment by sbrl** [comment]
Indeed, linux and osx do share some commands, as does windows (eg inkscape). However, there are a significant number of differences, so unfortunately we can't merge those platforms, as it would be unclear as to which version of a page should be used.

Platform joins like that might make a simple cacheless client simpler, but it would mean we no longer have a single source of truth on the matter, which would significantly complicate our git history and maintenance.

Generally, we expect that clients will cache locally, as this reduces network load and enables them to work offline. Can you give us an example of a situation in which a cacheless client would be preferable?

**Comment by emivespa** [comment]
Oh, I never meant to suggest doing anything to the source-of-truth pages. The joins were just meant as an example.

>Can you give us an example of a situation in which a cacheless client would be preferable?
Not really? I made a toy client, without a cache at first, and it seemed weird to me that lots of calls would make a "wasteful" request. Since a cache is supposed to be optional, I thought I'd point it out. To be clear, it's not really a pain point and might be best left unfixed (sorry if this was somewhat superfluous).

**Comment by marchersimon** [comment]
If the number of requests is important in a situation, a cached client would be better suited anyways. I'll close this issue now.

**Comment by marchersimon** [comment]
And if you finish your client don't forget to tell us, so we can add it to the list :)
