### ISSUE TITLE
page request: docsify-cli

### ISSUE THREAD

**Issue by boldandbrad** [tldr-pages/tldr#8184]
### Command description

`docsify` initializes and serves docsify markdown documentation locally

https://cli.docsifyjs.org/#/
https://docsify.js.org/#/quickstart?id=quick-start

I plan on submitting a PR for this, but I figured I'd formally submit an issue to link first!

### Command details

v4.x

### OS

General

**Comment by CleanMachine1** [comment]
Hey, just for future reference, you do not need to open a page request issue before submitting a PR, feel free to just submit the PR!
