### ISSUE TITLE
Add collaborator: @Nico385412

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#8224]
Hi, @Nico385412! You seem to be enjoying contributing to the tldr-pages project.

You have [23 PRs merged](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+author%3ANico385412+is%3Amerged), congrats! 👍🏻 

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by CleanMachine1** [comment]
The invite has been sent so you can join if you wish

**Comment by Nico385412** [comment]
Hi everyone !

Why not ! as collaborator i will be able to review french translations as well 😆
I just received the invite in my inbox and accepted it.

**Comment by navarroaxel** [comment]
@Nico385412 you should send a PR adding you in `MAINTAINERS.md` as collaborator to resolve this issue, similar the following: https://github.com/tldr-pages/tldr/pull/6341
