### ISSUE TITLE
Pages for gulp and bower

### ISSUE THREAD

**Issue by emileber** [tldr-pages/tldr#823]
I want to contribute by adding pages for gulp and bower but I'm not sure if it's a good fit since tldr is mostly about UNIX / Linux / OSX / SunOS. I searched the issues (both open and closed) and PRs and have not found any either positive nor negative about gulp or bower.

I want to add pages for those because I found myself trying `tldr bower` with no avail.

**Comment by igorshubovych** [comment]
Do it! Create `common/gulp.md` and start editing.

**Comment by emileber** [comment]
Both commands have been merged. I'm closing this.
