### ISSUE TITLE
add collaborator: @kbdharun 

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#8309]
Hi, @kbdharun ! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#8293 #8295 #8282 #8292 #8294 and others)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by kbdharun** [comment]
Sure, I would love to join as a collaborator.  Thank you so much.

**Comment by CleanMachine1** [comment]
Ok, the invite has been sent, please open a PR for adding yourself to the maintainers.md file

**Comment by CleanMachine1** [comment]
welcome to tldr!
