### ISSUE TITLE
Add the quota command

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#832]
We currently have at least one command per letter of the alphabet in the common folder, except for Q. I figured a good candidate would be `quota`, but it seems to have different incarnations depending on the system. If anyone's familiar with it, please start a page so we can cover the whole alphabet!

Also, check out this list: https://github.com/tldr-pages/tldr/wiki/Pages-plan

**Comment by ostera** [comment]
Don't we have `quit` ? D:

**Comment by waldyrious** [comment]
@ostera is that an actual command? I can't seem to find any reference to it. Or am I missing a joke somewhere?

**Comment by agnivade** [comment]
Oh we have a pages plan ! Gosh .. didn't realise so many commands were left out. Brace yourselves, PRs are coming !
