### ISSUE TITLE
add collaborator: @adrienthebo

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#8321]
Hi, @adrienthebo! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#8249, #8250, #8230, #8081 and #8078)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by adrienthebo** [comment]
Hey! I've been a bit low on bandwidth for the last week so sorry for the delay - but yes, I'd love to be a collaborator! tldr-pages have been incredibly helpful for the last several years of my working life, I'd be delighted to contribute back more.

 I'll review the maintainer's guide shortly. Cheers! 🍻

**Comment by CleanMachine1** [comment]
No problem, thanks for all of your current contributions, hope to review some more.

The invite has been sent!
