### ISSUE TITLE
gcc: Use more common output flag -o instead of --output

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8379]
I know the guidelines say we should prefer full names, but -o is so widespread and standardized that I think it's more appropriate going for -o. Curiously I can't even find --output in the man page. Worth mentioning the g++ tldr and the other options are all abbreviated.

**Comment by sbrl** [comment]
Thanks for the comment! tldr pages should document the most useful form of arguments, and not just default to the long options regardless of what is actually used day-to-day. Have you considered opening a pull request to correct this?
