### ISSUE TITLE
gcc: Specify -std for C standards 

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8380]
This is already given in tldr page of g++, so for page parity 

Available standards include GCC extensions like gnu99
 https://gcc.gnu.org/onlinedocs/gcc/Standards.html 

https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#C-Dialect-Options

**Comment by sbrl** [comment]
Thanks for requesting this edit! Do you want to have a go at implementing it yourself?

Pages are best created or edited by people who understand the command they are about.

If you do, take a quick read of [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md), which guides you through the process of creating a new page here. Then, just simply send a pull request to this repository - and if you need any assistance, just ask :-)
