### ISSUE TITLE
gcc/g++: clarify -Wall flag

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8388]
The current g++ guide says 

>  - Display (almost) all errors and warnings:
> g++ {{path/to/source.cpp}} -Wall -o {{path/to/output_executable}}

AFAIK -Wall has nothing to do with errors and enables all common warnings ("common" is my opinion, as a bunch more are in -Wextra, and there are still more warnings like -Wconversion). 

The current gcc guide says 

>  - Allow warnings, debug symbols in output:
>   gcc {{path/to/source.c}} -Wall -Og --output {{path/to/output_executable}}

This shows two flags at once which might be confusing and doesn't specify which warnings are turned on.

**Comment by trolzen** [comment]
This can be closed as resolved.
