### ISSUE TITLE
Try decine PRs with `Co-authored by` lines by CI

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#8399]
This is a continuation of [this](https://github.com/tldr-pages/tldr/pull/8391#issuecomment-1225909897) comment.

**Comment by navarroaxel** [comment]
You can't manage this with CI, it's the auto generated commit message when you click on the `Squash & merge` green button.

**Comment by EmilySeville7cfg** [comment]
Got it ;)

**Comment by kbdharun** [comment]
> You can't manage this with CI, it's the auto-generated commit message when you click on the `Squash & merge` green button.

I have a doubt, can a coauthor be automatically removed from the commit message by default using Github's new [default commit message feature.](https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request) even when clicking on `Squash & merge button`.

**Comment by navarroaxel** [comment]
@kbdharun I've checked it quickly but the `Co-authored by` is always present in the auto generated text in the textarea for the commit message body

**Comment by kbdharun** [comment]
> @kbdharun I've checked it quickly but the `Co-authored by` is always present in the auto generated text in the textarea for the commit message body 

Oh ok, Thanks for info.
