### ISSUE TITLE
tldr book readability

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8405]
I read the README and discovered that tldr apparently has a 3200 page PDF version. I'm not sure if anyone has used this, in print or as a PDF, but for readability: 

- Enable syntax highlighting and/or pure black and white version (like manpages) 
- Tan background and gray font is actually a little hard to read and imo not visually appealing. I propose darkening the font and getting rid of the tan background, which would also make it appear in physical print better

**Comment by blueskyson** [comment]
Checkout [https://github.com/tldr-pages/tldr/tree/main/scripts/pdf](https://github.com/tldr-pages/tldr/tree/main/scripts/pdf). You can render a black and white version by executing `python3 render.py ../../pages --color basic`.
