### ISSUE TITLE
7z: guess archive format from file extension

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8414]
I'm not sure where this is documented but apparently 7z will guess the archive format from the file extension so `-t` is not strictly necessary in most cases.

The current tldr page says
```
 - [a]rchive using a specific archive type:
   7z a -t{{7z|bzip2|gzip|lzip|tar|zip}} {{path/to/archive.7z}} {{path/to/file_or_directory}}
```

but it is enough to use for example 

    7z a archive.zip data/

Should this be mentioned in the tldr page?

**Comment by navarroaxel** [comment]
You can send an edit to the first example to say the archive type is defined by the archive extension.

**Comment by jxu** [comment]
also I don't know which 7z versions support it (I have version 16.02)

**Comment by kbdharun** [comment]
> also I don't know which 7z versions support it (I have version 16.02)

I too have `7z` version 16.02 in Fedora (Linux). When I archive a 7z file without the `-t` flag it converts 7z to zip [See Ref IMG 1]. But there is no change when I try to convert zip. I will further look into it to check whether the flag is required or not.

**Comment by jxu** [comment]
> When I archive a 7z file without the `-t` flag it converts 7z to zip [See Ref IMG's].

What do you mean converts 7z to zip?

The usual invokation is like `7z a archive.zip input`. Since you didn't specify input I assume it does current directory? That is not .7z format.

**Comment by kbdharun** [comment]
> > When I archive a 7z file without the `-t` flag it converts 7z to zip [See Ref IMG's].
> 
> What do you mean converts 7z to zip?
> 
> The usual invokation is like `7z a archive.zip input`. Since you didn't specify input I assume it does current directory? That is not .7z format.

Oops, my bad 😄 , I tried it, and it works example in `7z a test.zip test `, a `test.zip` file is created from the test directory. Using `-t` flags works too for example in `7z a -ttar tar test` a `tar.tar` archive file is created from the test directory, and I don't need to specify file extension separately. I think the current example in the tldr 7z page is itself good enough maybe we can just remove `.7z` alone in the command on the main page.
```
- [a]rchive using a specific archive type:
   7z a -t{{7z|bzip2|gzip|lzip|tar|zip}} {{path/to/archive}} {{path/to/file_or_directory}}
```

**Comment by jxu** [comment]
So 7z will add its own appropriate extension in that case? I'm not sure if I like that behavior

**Comment by kbdharun** [comment]
> So 7z will add its own appropriate extension in that case? I'm not sure if I like that behavior

Yes, For `-t` flag you don't need to specify it separately because we are already specifying the file extension along with it.
For example, `7z a -tzip {{path/to/archive}} {{path/to/file_or_directory}}` and `7z a -tzip {{path/to/archive.zip}} {{path/to/file_or_directory}}` both works but since this page deals with multiple file types I think we don't need to specify a particular file extension alone in commands.

**Comment by jxu** [comment]
I think it's easier for the user to just write `7z a archive.zip data` than `7z a -tzip archive data`, although there are merits to both.

**Comment by gutjuri** [comment]
So, should we go ahead and change this example

https://github.com/tldr-pages/tldr/blob/a95bc099de6815edef72d05435549afca091042c/pages/common/7z.md?plain=1#L26-L28

to 
```
 - [a]rchive using a specific archive type: 
  
 `7z a -t{{7z|bzip2|gzip|lzip|tar|zip}} {{path/to/archive}} {{path/to/file_or_directory}}` 
```

(removing `.7z` from the archive file name)?

**Comment by jxu** [comment]
> > So, should we go ahead and change this example (removing .7z from the archive file name)?
> 
> Yep, feel free to create a PR to close this issue.

I forgot about this issue but my issue was about usually not needing -t flag, not about 7z extension.

**Comment by kbdharun** [comment]
> > > So, should we go ahead and change this example (removing .7z from the archive file name)?
> > 
> > Yep, feel free to create a PR to close this issue.
> 
> I forgot about this issue but my issue was about usually not needing -t flag, not about 7z extension.

In that case, we could add a note for this at the page description.

**Comment by gutjuri** [comment]
> > > So, should we go ahead and change this example (removing .7z from the archive file name)?
> > 
> > 
> > Yep, feel free to create a PR to close this issue.
> 
> I forgot about this issue but my issue was about usually not needing -t flag, not about 7z extension.

But we already have examples showcasing this.
