### ISSUE TITLE
Why can't some commands be displayed. Is it because of the network?

### ISSUE THREAD

**Issue by feijiang00** [tldr-pages/tldr#8427]
### Command description

不能够显示出一些命令，比如mv，但是可以显示tar，仅可以显示tar
在输出 tldr mv后等待了一段时间后出现:
Error fetching from tldr: <urlopen error EOF occurred in violation of protocol (_ssl.c:877)>

Translation:
It can't display some commands, such as `mv`. However it can only display `tar`.
Afer executing `tldr mv` and waiting for a while, the terminal shows:
Error fetching from tldr: <urlopen error EOF occurred in violation of protocol (_ssl.c:877)>

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by navarroaxel** [comment]
Which client and version are you using?

**Comment by feijiang00** [comment]
the tldr is tldr 3.1.0 (Client Specification 1.5)
the linux is  centOS  3.10.0-1160.11.1.el7.x86_64
@blueskyson

**Comment by blueskyson** [comment]
@feijiang00
1. Can your computer access `https://tldr-pages.github.io/assets/tldr.zip`? 
2. Checkout `openssl version` and make sure it's new enough.
3. Try to update `requests` version by `pip install requests --upgrade`.
4. Checkout if your proxy or vpn blocks the openssl connection.

I have no other idea if the above approaches don't work...

**Comment by feijiang00** [comment]
ok,thanks,maybe is the `**openssl version**` 's question, I'm trying to update it

**Comment by jxu** [comment]
Does curl or git fetch work?

**Comment by fatCatGm** [comment]
I also encountered the same error, and I tried the above methods. Have you solved it

**Comment by fatCatGm** [comment]
[root@localhost network-scripts]# tldr mv
Error fetching from tldr: <urlopen error [Errno 111] Connection refused>

**Comment by jxu** [comment]
> Does curl or git fetch work?

**Comment by fatCatGm** [comment]
thanks，I set DNS（ 185.199.108.133 raw.githubusercontent.com）, and it can run successfully。

**Comment by EltonAlvess** [comment]
should this issue be closed?

**Comment by navarroaxel** [comment]
I think we can close, if someone needs more help we can reopen this.

**Comment by qq516249940** [comment]
> 185.199.108.133 raw.githubusercontent.com

can't not work in china
