### ISSUE TITLE
add collaborator: @CairnThePerson

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr#8438]
Hi, @CairnThePerson! You seem to be enjoying contributing to the tldr-pages project.
You now have had five distinct pull requests merged (#8413 #8412 #8411 #8404 #8403)!
That qualifies you to become a collaborator in this repository, as explained in our [community roles documentation](https://github.com/tldr-pages/tldr/blob/main/COMMUNITY-ROLES.md).

As a collaborator, you will have commit access to the repository.
That means you can merge pull requests, label and close issues, and perform various other maintenance tasks that are needed here and there.
Of course, all of this is voluntary — you're welcome to contribute to the project in whatever ways suit your liking.

If you do decide to start performing maintenance tasks, though, we only ask you to get familiar with the [maintainer's guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/maintainers-guide.md).

So, what do you say? Can we add you as a collaborator?

Either way, thanks for all your work so far!

**Comment by CairnThePerson** [comment]
Hey, absolutely! I've got some more ideas about what to add, but I'm happy to gradually build up to maintaining as well.

When I'm adding new pages, can I still submit PRs? I'd like to continue to get feedback on my work, even though it wouldn't be strictly necessary.

**Comment by CleanMachine1** [comment]
Yes, PRs are actually a must for any page and for anyone.

I've sent the invitation now.

Thanks for all of your current contributions, hope to see some more!

**Comment by CleanMachine1** [comment]
Make sure to make a PR to change the MAINTAINERS.md file, and add your name there.

**Comment by CairnThePerson** [comment]
> Make sure to make a PR to change the MAINTAINERS.md file, and add your name there.

Will do. :+1:

**Comment by CleanMachine1** [comment]
Could you check your Gitter notifications @CairnThePerson
