### ISSUE TITLE
7z: fix explanation of a

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8442]
TIL a does not stand for [a]rchive but [a]dd. it can be used to add files to an existing archive 

https://sevenzip.osdn.jp/chm/cmdline/commands/add.htm

**Comment by pixelcmtd** [comment]
Could you make a PR for that?

btw: something like [the manpage](https://manned.org/7z.1) would be a more credible looking source to me (i'm not familiar with osdn.jp)

**Comment by jxu** [comment]
Teah I can when I remember to later.

The reason I link that page is because 7z's manpage says to "see /usr/share/doc/p7zip/DOC/MANUAL/cmdline/switches/method.htm" which is presumably what's hosted at osdn.jp (I didn't check if it was up to date)
