### ISSUE TITLE
magick: clean up current commands

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8454]
>   - Convert file type:
>    magick {{image.png}} {{image.jpg}}

Maybe it should say "with default quality options" and specify which is the source and target. PNG to JPEG is not lossless.

>  - Resize an image, making a new copy:
>   magick convert -resize {{100x100}} {{image.jpg}} {{image.jpg}}

Does this really make a new copy? As it's written it just overwrites the old image which is destructive

>  - Create a GIF using images:
>   magick {{*.jpg}} {{images.gif}}

This seems to lack detail. Animated GIF? What resolution and framerate?

>  - Create checkerboard pattern:
>   magick -size {{640x480}} pattern:checkerboard {{checkerboard.png}}

I'm not opposed to this but is this a common command? I would rather have a command like `-resize 50%`. Also it should be noted `-resize 100x100` will NOT make an image exactly 100x100, just one that would FIT into a box that size. Use `!` to force changing aspect ratio https://legacy.imagemagick.org/Usage/resize/#noaspect

**Comment by sbrl** [comment]
Great ideas! This page was probably written a while ago, hence the difference in quality. Have you considered opening a PR to correct these issues? See https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md for more info.

> ...and specify which is the source and target. PNG to JPEG is not lossless.

Maybe `source.png` and `target.png` instead of `image.png` and `image.png`?

**Comment by acuteenvy** [comment]
The page has recently been updated (#10764, #10850).
