### ISSUE TITLE
page request: flite

### ISSUE THREAD

**Issue by maniyar1** [tldr-pages/tldr#8461]
### Command description

flite - A small simple speech synthesizer

man page: https://manpages.ubuntu.com/manpages/trusty/man1/flite.1.html

Pretty simple for the most part, see the espeak tldr page for what general use case might look like. 

### Command details

Version: 2.2 

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by khairnarsaurabh23** [comment]
Can I work on this issue?

**Comment by pixelcmtd** [comment]
@khairnarsaurabh23 Nobody can stop you.
