### ISSUE TITLE
page request: certutil

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#8502]
### Command description

Note: From what I found there seems to be some differences for commands in every platform. But this tool seems to be from Microsoft.

## Windows

> Certutil.exe is a command-line program, installed as part of Certificate Services. You can use certutil.exe to dump and display certification authority (CA) configuration information, configure Certificate Services, backup and restore CA components, and verify certificates, key pairs, and certificate chains.

- Docs link for Windows: <https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil>.

## Linux

> certutil - Manage keys and certificate in both NSS databases and other NSS tokens.

- Ubuntu Docs Link: <https://manpages.ubuntu.com/manpages/xenial/man1/certutil.1.html>.
- Ref cheatsheet: <https://akasurde.github.io/certutil-cheat-sheet.html>.

## Mac

- I found this repo, but I can't find any more information about this, <https://github.com/suolapeikko/certutil>.

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by pixelcmtd** [comment]
About that Mac thing: `certutil` doesn't have a man page on my system, but it's installed from the Homebrew package `nss`.

```
$ ll /opt/homebrew/bin/certutil
lrwxr-xr-x 1 pixel admin 31 Sep 17 00:56 /opt/homebrew/bin/certutil -> ../Cellar/nss/3.83/bin/certutil
```
