### ISSUE TITLE
page request: mumble

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#8525]
### Command description

Mumble is a software for voice-chatting.

I think it would be great to document the subcommand `mumble rpc`.

### OS

- [ ] Android
- [X] Linux
- [x] macOS
- [ ] sunOS
- [X] Windows

**Comment by EltonAlvess** [comment]
i notice that doesn't have any references to a documentation.

The request is about server or client side?

**Comment by gutjuri** [comment]
This request is about the client side

**Comment by burned42** [comment]
I opened https://github.com/tldr-pages/tldr/pull/8750 documenting the mumble client for linux :)

**Comment by pixelcmtd** [comment]
@burned42 Is there any reason you created the page under `linux`? (other than maybe not being familiar with `common` 😁)

**Comment by burned42** [comment]
@pixelcmtd not really, no. I just use the linux version, so that's the only one I'm familiar with and which I was confident enough documenting. If it works identical on other platforms, it could of course also be put into `common`.
