### ISSUE TITLE
page request: HandBrakeCLI

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#8526]
### Command description

The HandBrakeCLI command allows to run HandBrake (https://handbrake.fr/) without a GUI. This is useful for automation of repetitive rendering tasks.

Unfortunately, I have no experience using HandBrakeCLI, so I cannot do this myself.

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [X] Windows

**Comment by kbdharun** [comment]
This would be a very good addition to tldr, But I noticed that there are a lot of commands for HandBrakeCLI. Link:<https://handbrake.fr/docs/en/latest/cli/command-line-reference.html>. Let me ask somebody how a page for this command can be created.

@navarroaxel, @CleanMachine1, @EmilySeville7cfg, there seem to be a lot of flags for this program. Should we create multiple pages or should we create a page with essential options?

**Comment by navarroaxel** [comment]
If the command has arguments like `pacman -S`, that it's similar to a pacman subcommand we can create pages for them. otherwise tldr are for basic examples, like `jq` or `grep` we can't create pages for all the universe of examples.

**Comment by yuriskinfo** [comment]
Actually, there is already a page https://github.com/tldr-pages/tldr/blob/main/pages/common/handbrakecli.md, just saying. 
And yes, tools like Handbrake/ffmpeg/ImageMagick/Gimp, in my view, can only be covered with lots of subcommand pages, like lots of pages )). A one-page entry does disservice to them more than helps.

**Comment by gutjuri** [comment]
> Actually, there is already a page https://github.com/tldr-pages/tldr/blob/main/pages/common/handbrakecli.md, just saying. And yes, tools like Handbrake/ffmpeg/ImageMagick/Gimp, in my view, can only be covered with lots of subcommand pages, like lots of pages )). A one-page entry does disservice to them more than helps.

Good to know, turns out my tldr client is case-sensitive. Closing this issue for now as the existence of the tldr page in question solves my problem.
