### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by hosiet** [tldr-pages/tldr#853]
The content of pages have increased greatly since last tag (release). Would it be better if we make another release as a milestone (e.g., v0.0.2)?

Thanks.

**Comment by igorshubovych** [comment]
We do not release it that way anymore.

We are releasing clients which downloads the latest archive. Read more about it here:
https://github.com/tldr-pages/tldr/wiki/Minimum-specifications-for-TLDR-command-line-clients

**Comment by hosiet** [comment]
Thans for your explanation.
