### ISSUE TITLE
find: mention maxdepth 1

### ISSUE THREAD

**Issue by jxu** [tldr-pages/tldr#8540]
Very useful option

**Comment by saikatsgupta** [comment]
Hi, @jxu and @navarroaxel! There are already 8 examples on the `find` page. Are we trying to fit this in the existing ones or create a 9th example?

**Comment by kbdharun** [comment]
> Hi, @jxu and @navarroaxel! There are already 8 examples on the `find` page. Are we trying to fit this in the existing ones or create a 9th example?

The 9th example can't be added as our current clients and linter only support a maximum of 8 examples. So if required we can fit this example with an existing one.

**Comment by navarroaxel** [comment]
A page can't have more than 8 examples. `find` is a complex command, maybe some example could be edited the the 3rd or the 5th.

**Comment by kbdharun** [comment]
> A page can't have more than 8 examples. `find` is a complex command, maybe some example could be edited the the 3rd or the 5th.

Agreed, But the page already looks so cluttered.

**Comment by fallenpixel** [comment]
Submitted a PR, I don't think this edit adds too much clutter considering the added value of documenting maxdepth.
