### ISSUE TITLE
Offline TL;DR Pages

### ISSUE THREAD

**Issue by popey456963** [tldr-pages/tldr#856]
For those of us that sometimes enter environments that prohibit us from having any form of custom programs or internet access, it is often nice to have paper versions of commands and things.

It would be nice to have some very simple PDF booklet with all of the commands on.

**Comment by maxbeier** [comment]
Gave it a shot – is #861 kind of what you wanted?

**Comment by popey456963** [comment]
Exactly what I wanted and so much more!  You even got syntax highlighting and a contents page :+1:
