### ISSUE TITLE
Misleading information about 'test'

### ISSUE THREAD

**Issue by PackmanDude** [tldr-pages/tldr#8581]
By executing
```
tldr test
```
you will get output, which includes:
```
- If-else statement:
  test condition && echo "true" || echo "false"
```
but you must notice, that `A && B || C is not if-then-else. C may run when A is true.`

**Comment by CleanMachine1** [comment]
Would you like a PR changing this?

**Comment by PackmanDude** [comment]
Sure, I think.

**Comment by CleanMachine1** [comment]
Sorry, I mean would you like to make one.

**Comment by gwo0d** [comment]
I will look into this and submit a PR.

**Comment by PackmanDude** [comment]
Huh, it doesn't referenced it. Here, it is #8594.
