### ISSUE TITLE
[, [[, test: -z and -n are very similar

### ISSUE THREAD

**Issue by fallenpixel** [tldr-pages/tldr#8722]
The behavior of -z and -n are very similar, condensing them down to a single example still looks highly readable. I know I tend to get them confused, being able to look at one line and see the difference sounds like a good improvement. 

While editing the common/test.md I noticed a bit of awkward wording around the && and || operators. I'm not sure I like what I have, but I believe it's an improvement. 

#8721

**Comment by Managor** [comment]
Is this still an issue for you?
