### ISSUE TITLE
Consider merging brew-cask into brew

### ISSUE THREAD

**Issue by SnowComfortable6726** [tldr-pages/tldr#8741]
`brew cask` has been removed from upstream, the equivalent command now is `brew --cask`. With this in mind, I don't think that we need a separate page for `brew cask` anymore.

**Comment by saikatsgupta** [comment]
Locations for the `brew cask` command:
- [ ] pages/common/brew-cask.md
- [ ] pages.de/common/brew-cask.md
- [ ] pages.it/common/brew-cask.md
- [ ] pages.zh/common/brew-cask.md

**Comment by saikatsgupta** [comment]
If we remove the existing `brew cask` command pages then respective `brew` command should accommodate the changes with the `--cask` option. Since the main `brew` page already has 8 examples we need to see how to best fit this.

**Comment by kbdharun** [comment]
> `brew cask` has been removed from upstream, the equivalent command now is `brew --cask`. With this in mind, I don't think that we need a separate page for `brew cask` anymore.

> If we remove the existing `brew cask` command pages then the respective `brew` command should accommodate the changes with the `--cask` option. Since the main `brew` page already has 8 examples we need to see how to best fit this.

I think the best thing to do is to mention that the separate command is depreciated and is replaced by the flag in the `brew-cask` page and then update all commands on this page instead of `brew`.

In the `brew` page we can add `See more:` in the main command description.

What do you think @navarroaxel @CleanMachine1 @mfrw?

**Comment by navarroaxel** [comment]
I think change the `brew-cask` page to use the `--cask` argument is better

**Comment by kbdharun** [comment]
> I think change the `brew-cask` page to use the `--cask` argument is better

Agreed, I will open a PR regarding this soon.
