### ISSUE TITLE
Request: conform to XDG basedir spec

### ISSUE THREAD

**Issue by jasonkarns** [tldr-pages/tldr#876]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Presently, it is writing to `~/.tldrc` and is not respecting `XDG_CONFIG_HOME` or `XDG_CACHE_HOME` or `XDG_DATA_HOME`. I'm not sure how much of the directory is config vs cache vs data, so I don't know which xdg directories it should be written to. But none of it should be in `~`.

**Comment by SShrike** [comment]
You can use [tealdeer](https://github.com/dbrgn/tealdeer), which adheres to the XDG BaseDir spec.

Disclaimer, I'm a contributor to the project.

**Comment by waldyrious** [comment]
@SShrike and @jasonkarns, this is something we might include in the client spec that is being defined at #1065. Please comment there if you think it should be enforced for all clients, or not.

**Comment by marchersimon** [comment]
@SebDanielsson do you mean the tldr cache where the pages are stored? If so, you can open an issue about this at your client's repository or use another client.

**Comment by SebDanielsson** [comment]
Looks like this issue belongs to this repo:
https://github.com/tldr-pages/tldr-c-client.

There's already an issue for it:
https://github.com/tldr-pages/tldr-c-client/issues/49

Sorry for the inconvenience.

**Comment by noraj** [comment]
## Before

- Python client no config file but reads some custom environment variables https://github.com/tldr-pages/tldr-python-client?tab=readme-ov-file#configuration
- Node.js client reads a config file `.tldrrc` in a non-standard location https://github.com/tldr-pages/tldr-node-client?tab=readme-ov-file#configuration
- C client has no global configuration support
- Elixir client has no global configuration support

## After

The specification should define a standard file format and location for a user configuration file.

As the official clients are cross-platforms, they should read from the standard configuration folder for each platform:

- Unix / Linux: `$XDG_CONFIG_HOME/tldr/`
- macOS: `~/Library/Application Support/tldr/`
- Windows: ` %APPDATA%\tldr\`

## Reference

- [discussion](https://github.com/orgs/tldr-pages/discussions/10796#discussioncomment-7162817)
- [Apple - File System Overview](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFileSystem/Articles/WhereToPutFiles.html)
- [macOS Library Directory Details](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1)
- [XDG base directory](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- [XDG user directory](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/)
- [Windows - Known Folder](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776911(v=vs.85).aspx)
- [macOs Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6)

## Examples

Examples of project doing that:

- [poetry](https://python-poetry.org/docs/configuration/)
- [Zim](https://zim-wiki.org/manual/Help/Config_Files.html)
- [Rust](https://docs.rs/dirs/latest/src/dirs/lib.rs.html)

**Comment by niklasmohrin** [comment]
I am not sure I am convinced about having a unified configuration file that is detailed in the client spec. Different programming languages tend to use their own file format (Javascript would probably use JSON, Rust programs tend to prefer toml), so there isn't really one format that fits all. Allowing different formats and having clients check multiple files seems overly complicated to me. Additionally, if some clients have more options than others, all clients would have to explicitly ignore options they don't understand, which in turn makes it harder to debug a faulty config (for example a typo `language` vs `langauge`, one of which would be ignored).

I think that recommending something like "stick to XDG or similar convention" sounds good, but a unified `.config/tldr/tldr.toml` does not.

**Comment by noraj** [comment]
There are 3 different things about the config:

1. **Unifying the path/location**, I personally think it should be important in the spec
2. **Unifying the file format** (JSON, YAML, TOML), that may not be enforced, each client could choose it's own, for example to avoid having to include additional external dependencies (for example Ruby has a native JSON and YAML parser bot not a TOML one)
3. **Unifying a minimal set of keys**, the spec could require a minimal set of keys to mandatory supported by the clients (eg. languages) and tell in the spec explicitly that other clients could support more options and so ignore them. By the way the node under which the official keys and client custom keys are could be different for that purpose. Eg. the spec could ask to put the custom keys under a client node: `client.<client_name>.<custom_key>` so it would be easy to ignore all `client.<client_name>` sub-nodes that are not `client.<my_client>. A bit like some SSG does for extension where extensions should not modify or add keys under the root of the config file but under a dedicated `extensions` node.

**Comment by niklasmohrin** [comment]
Hm, I must say, I don't think I agree with "Unifying a minimal set of keys". Some options have natural derivations from the CLI specification, but I wouldn't force anyone to implement a mapping to a config file in any particular way. I think the most that could be required from clients is to document how CLI args are mapped to configuration file options, for example by recommending that this can be found from `my-tldr --help` or `man my-tldr` (or a separate `man my-tldr.toml`). However, this recommendation then seems somewhat excessive to me, because it's just recommending good practices and I feel the spec should focus on tldr-specific topics.

**Comment by noraj** [comment]
I understand your point, however if there is not a _minimal set of keys_ supported by all clients and a standard config file location, then it means the clients are not much interoperable and a user need to re-write a specific conf file when he change of tldr flavor.
But that's not specific to config only, the same occurs for the data location (cache folder), for example tealdeer save the data in a custom path so you need to redownload all the pages even if you already have tldr-python. While all spec-compliants tldr clients could all use `$XDG_CACHE_HOME` and the same file structure.

**Comment by sbrl** [comment]
The client spec tries to be accepting of all kinds of client, regardless of whether they are CLI-based or not.

Perhaps some wording like it's RECOMMENDED to follow the appropriate per-platform standards for storing any configuration files.

> then clients are not really inter-operable outside being able to use the same pages and having the same CLI option naming.

It was never the goal to have clients be interoperable. I would argue that this is out-of-scope. If all clients do exactly the same thing, then why do we have multiple clients?

The point of an ecosystem of clients is to allow every possible platform and combination to be supported. Not just CLI clients, but also Android, web, etc......

Ref XDG, does this even make sense on all platforms (e.g. Windows, Android, etc)?
