### ISSUE TITLE
 dolt-merge: add page

### ISSUE THREAD

**Issue by Torfab** [tldr-pages/tldr#8799]
* [x]  The page(s) are in the correct platform directories: `common`, `linux`, `osx`, `windows`, `sunos`, `android`, etc.
* [x]  The page(s) have at most 8 examples.
* [x]  The page description(s) have links to documentation or a homepage.
* [x]  The page(s) follow the [content guidelines](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#guidelines).
* [x]  The PR title conforms to the recommended [templates](/tldr-pages/tldr/blob/main/CONTRIBUTING.md#commit-message).

**Comment by navarroaxel** [comment]
I don't understand this issue.

**Comment by Torfab** [comment]
It was a sub issue of #5471 
But i see i could directly do a pull request, we can close this issue and handle it directly, sorry
