### ISSUE TITLE
page request: emerge

### ISSUE THREAD

**Issue by monomycelium** [tldr-pages/tldr#8810]
### Command description

`emerge` is basically a package manager in Gentoo Linux that does not give a damn about binaries, only building by parsing `ebuild` instructions.

`man` page: https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by pg99696** [comment]
@monomycelium, can you please add 'hacktoberfest' label to this issue?

**Comment by pg99696** [comment]
I have gone through the docs and found emerge command is already present in the docs.

**Comment by kbdharun** [comment]
Emerge is already present in <https://github.com/tldr-pages/tldr/blob/main/pages/linux/emerge.md>. I am closing the issue. Thanks for your contribution.
