### ISSUE TITLE
Let's Document: xz utils

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#8859]
### Command description

xz utils is a suite of tool for handling .xz and .lzma files. Documentation can be found on the following page: https://tukaani.org/xz/

It consists of the following commands:

* [x] xz → #740
* [x] unxz → #9091
* [x] xzcat → #9091
* [x] xzdiff → #8923
* [x] xzcmp → #9704
* [x] xzgrep → #9983
* [x] xzegrep → #10185
* [x] xzfgrep → #10185
* [x] xzless → #9059, #10179
* [x] xzmore → #10186
* [x] lzma → #9091
* [x] unlzma → #9091
* [x] lzcat → #9091
* [x] lzgrep →  #10171, #10185
* [x] lzegrep → #10185
* [x] lzfgrep → #10185
* [x] lzless →  #10172, #10185
* [x] lzmore → #10185

I think some of these are aliases, this however needs further investigation.

### OS

- Linux
- macOS
- sunOS
- Windows

**Comment by Nikhil-Samant** [comment]
@gutjuri , I will do further investigation and add the page

**Comment by asdsyd** [comment]
Is this issue fixed?

**Comment by gutjuri** [comment]
> Is this issue fixed?

No, the commands that have not been marked as completed in the original post are still missing in tldr.

**Comment by navarroaxel** [comment]
> How do I work on this issue ? thanks

Same I answered here: https://github.com/tldr-pages/tldr/issues/7923#issuecomment-1275262574

**Comment by acuteenvy** [comment]
> lzfegrep

There's a typo. It should be `lzfgrep`.

**Comment by acuteenvy** [comment]
I created PRs for all missing pages.
