### ISSUE TITLE
page request: yplan

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#8860]
### Command description

yplan is a command to generate daily planners in LaTeX. Documentation can be found on this page: https://www.ctan.org/tex-archive/macros/latex/contrib/yplan

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by DEBADRIBASAK** [comment]
@gutjuri Please assign this task to me. I would like to contribute.
