### ISSUE TITLE
Let's document: Info-ZIP tools

### ISSUE THREAD

**Issue by gutjuri** [tldr-pages/tldr#8861]
### Command description

Info-ZIP is a workgroup that provides tools for dealing with .zip files. This is their website (with documentation): https://infozip.sourceforge.net/

I found the following tools that are not yet documented in tldr:

* [X] zipinfo→#6918
* [X] zipgrep →#7004
* [x] zipnote → #8908
* [x] zipcloak → #8914
* [x] zipsplit → #8871
* [x] funzip → #8937,#9236
* [ ] unzipsfx →#9225

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by pg99696** [comment]
@gutjuri , can you please add label 'hacktoberfest' to this issue?

I'm going to add page for _zipsplit_.

**Comment by gutjuri** [comment]
> @gutjuri , can you please add label 'hacktoberfest' to this issue?
> 
> I'm going to add page for _zipsplit_.

The repo already has the topic "hacktoberfest", so any PR will count (as long as it gets accepted)

**Comment by pg99696** [comment]
@gutjuri, I have sent a PR for review for zipsplit command. 

Do I need to mention anyone to review the PR?

Please guide me as this is my first PR for any open source project.

**Comment by kbdharun** [comment]
> @ gutjuri, I have sent a PR for review for `zipsplit` command.

Great 

> Do I need to mention anyone to review the PR?

We will review your PR soon, You don't need to mention anyone for reviewing in most cases except sometimes when you require someone's expertise.

> Please guide me as this is my first PR for any open-source project.

The best place to start would be to look around the repository and you can use our guides such as [CONTRIBUTING.md](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md), [Style Guide](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/style-guide.md) and [Translation templates](https://github.com/tldr-pages/tldr/tree/main/contributing-guides/translation-templates) as a reference for your PR.
