### ISSUE TITLE
page request: treetime

### ISSUE THREAD

**Issue by anna-parker** [tldr-pages/tldr#8966]
### Command description

Makes timetrees of phylogenetic trees, used in genomic epidemiology of e.g. SARS-CoV-2, monkeypox, flu etc.

### Command details

0.9.4

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [X] Windows

**Comment by kbdharun** [comment]
Adding Links for reference <https://manned.org/treetime> , <https://github.com/neherlab/treetime>. 

@anna-parker; Feel free to create a PR for this page if you want to add it yourself.

**Comment by vatana7** [comment]
I've created a PR for this. Please check
