### ISSUE TITLE
page request: ldd

### ISSUE THREAD

**Issue by saikatsgupta** [tldr-pages/tldr#8998]
### Command description

`ldd` prints the shared objects (shared libraries) required by each program or shared object specified on the command line. More details: https://manned.org/ldd.1

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by pixelcmtd** [comment]
https://github.com/tldr-pages/tldr/blob/main/pages/linux/ldd.md 🤔

**Comment by saikatsgupta** [comment]
Whoops! I made a mistake by searching the command here - https://tldr.ostera.io/ldd. Closing issue.

**Comment by saikatsgupta** [comment]
Whoops! I made a mistake by searching the command here - https://tldr.ostera.io/ldd. Closing issue.
