### ISSUE TITLE
page request: uuidgen

### ISSUE THREAD

**Issue by saikatsgupta** [tldr-pages/tldr#9000]
### Command description

Creates a new UUID value - https://manned.org/uuidgen.1

### OS

- [ ] Android
- [X] Linux
- [X] macOS
- [ ] sunOS
- [ ] Windows

**Comment by saikatsgupta** [comment]
#9000 🎉 🎉 🎉

**Comment by navarroaxel** [comment]
The pages already exist https://github.com/tldr-pages/tldr/blob/main/pages/osx/uuidgen.md and https://github.com/tldr-pages/tldr/blob/main/pages/linux/uuidgen.md

**Comment by kbdharun** [comment]
As @navarroaxel mentioned this page exists on both the platforms mentioned in this issue. So I am closing this issue, Thanks for your contribution.

- Linux Page: https://github.com/tldr-pages/tldr/blob/main/pages/linux/uuidgen.md
-  macOs Page: https://github.com/tldr-pages/tldr/blob/main/pages/osx/uuidgen.md

**Comment by saikatsgupta** [comment]
My bad I missed this due to over-excitement 😛
