### ISSUE TITLE
page request: loadkeys

### ISSUE THREAD

**Issue by saikatsgupta** [tldr-pages/tldr#9003]
### Command description

Loads keyboard translation tables - https://manned.org/loadkeys.1

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by DEBADRIBASAK** [comment]
@saikatsgupta Is anyone working on this? I would like to work on this issue.

**Comment by saikatsgupta** [comment]
Go ahead @DEBADRIBASAK 👍🏼

**Comment by DEBADRIBASAK** [comment]
I made a PR. Can someone please approve it?
