### ISSUE TITLE
page request: fixfiles

### ISSUE THREAD

**Issue by saikatsgupta** [tldr-pages/tldr#9006]
### Command description

`fixfiles` - fix file SELinux security contexts.
Details: https://manned.org/fixfiles.8

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by vatana7** [comment]
I'll take a look at this

**Comment by vatana7** [comment]
I've created a PR for this. Please check
