### ISSUE TITLE
cron

### ISSUE THREAD

**Issue by SanketDG** [tldr-pages/tldr#904]
There is no tldr for cron

**Comment by waldyrious** [comment]
@SanketDG as always, feel free to propose one :)

**Comment by waldyrious** [comment]
@SanketDG I will close this as covered by `crontab`, which was introduced in #770. If you (or anyone else) think a separate `cron` page is warranted, please comment to that effect.

**Comment by SanketDG** [comment]
Is aliasing possible, most people would search for cron IMHO

**Comment by waldyrious** [comment]
Ok, understood. This is tracked in #787.

**Comment by waldyrious** [comment]
Reopening so we can close this for real with #9388. :smiley:
