### ISSUE TITLE
page request: caffeinate 

### ISSUE THREAD

**Issue by MengsokunVeng** [tldr-pages/tldr#9167]
### Command description

Add new key option - https://ss64.com/osx/caffeinate.html

### OS

- [ ] Android
- [ ] Linux
- [X] macOS
- [ ] sunOS
- [ ] Windows

**Comment by rajatmohan22** [comment]
Can you elaborate a little more? Which key do you want to add ?

**Comment by rajatmohan22** [comment]
Can you elaborate a little more? Which key do you want to add ?

**Comment by MengsokunVeng** [comment]
`caffeinate -m` to prevent disk from idle sleeping until you press Ctrl-C

**Comment by saikatsgupta** [comment]
The command pages exist: 
https://github.com/tldr-pages/tldr/blob/main/pages/linux/caffeinate.md
https://github.com/tldr-pages/tldr/blob/main/pages/osx/caffeinate.md
You can update the same.
