### ISSUE TITLE
Suggest: Add a link to tldr-alfred in README

### ISSUE THREAD

**Issue by onesuper** [tldr-pages/tldr#931]
As a Mac OS user, I find @cs1707's tldr plugin for Alfred workflow is very easy and cool to use: https://github.com/cs1707/tldr-alfred

Could you mention this project in README?

**Comment by waldyrious** [comment]
We sure could (feel free to submit a PR). But I feel it would be only fair for the tldr project to be linked to from their README as well.

**Comment by waldyrious** [comment]
Closed in #932
