### ISSUE TITLE
page request: java_home

### ISSUE THREAD

**Issue by Mikaa404** [tldr-pages/tldr#9321]
### Command description

`java_home` - return a value for $JAVA_HOME

### Command details

Executable in `/usr/libexec/`.

### OS

- [ ] Android
- [ ] Linux
- [X] macOS
- [ ] sunOS
- [ ] Windows

**Comment by saikatsgupta** [comment]
Hi @MikaaTT, could you share the man page or any reference for this command?

**Comment by MikaaTT** [comment]
Ok @saikatsgupta, [Here](https://gist.github.com/MikaaTT/9dddc5b7f95a53ff2f1eb3813c4cf46a) is the man page.
