### ISSUE TITLE
read: backslash is still missing

### ISSUE THREAD

**Issue by Saevyn** [tldr-pages/tldr#9322]
Several months ago, I opened [a pull request](https://github.com/tldr-pages/tldr/pull/7731) to fix a missing backslash for the `read` page. The fix was rashly declined and mistakenly recognised as a Node client issue, [even though it wasn't](https://github.com/tldr-pages/tldr/pull/7731#issuecomment-1074564213). Recently, I needed to check the `read` command again and noticed the missing backslash is still there, so I thought I'd open an issue for it.

**Comment by SethFalco** [comment]
Checking the background of this issue, yeah it shouldn't have been closed.

It seems everyone forgot that the pages are _Markdown_, so `\)` should be an escaped closed bracket, clients shouldn't be rendering the slash. Clients that currently render it are the ones with that needs to be fixed, not the node client imo.

```md
(\)
```

This is how `(\)` is supposed to look: (\)

**Comment by Saevyn** [comment]
So, uh... Can we do anything about it?

**Comment by SethFalco** [comment]
If no one else does, I'll make a PR next week.
Meanwhile, if you have time, feel free to make your PR again and I'll approve it.

Sorry for the shoddy experience with your previous PR, though.

**Comment by Saevyn** [comment]
Alright, thanks a lot for the help! 😄
