### ISSUE TITLE
page request: dbus-daemon

### ISSUE THREAD

**Issue by williamkida** [tldr-pages/tldr#937]
dbus-daemon man page request

**Comment by williamkida** [comment]
dbus-daemon man page request

**Comment by ostera** [comment]
@williamkida We welcome and encourage PR's with proposals, so if you find a minute to write one, we'l very happily make sure it gets merged! :)

**Comment by agnivade** [comment]
@williamkida - Why was this closed ?

**Comment by waldyrious** [comment]
I'll reopen for now. If @williamkida presents arguments for closing, we can always reconsider.

**Comment by williamkida** [comment]
Woops, sorry.
