### ISSUE TITLE
Proposal: Create seperate PDFs for translation pages

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#9432]
**I have a proposal how about creating independent PDFs for separate language pages?** 

I observed the [current PDF](https://tldr.sh/assets/tldr-book.pdf) only contains English pages. Creating separate PDFs for each language will make it easy to read for native readers. What do you guys think about this proposal?

>  (But we need to figure out fonts for it I guess)

**Comment by yutyo** [comment]
I think it makes sense.

**Comment by public-rant** [comment]
I would be interested in working on this. Would I be correct in assuming this change would require modifying [`render.py`](https://github.com/tldr-pages/tldr/blob/main/scripts/pdf/render.py)?

**Comment by kbdharun** [comment]
> I would be interested in working on this. Would I be correct in assuming this change would require modifying [`render.py`](https://github.com/tldr-pages/tldr/blob/main/scripts/pdf/render.py)?
> 
> assuming @kbdharun hasn't already made a start?

Sure, you can work on it. I haven't made a start lol, as I am not that good with scripts.

**Comment by kbdharun** [comment]
@public-rant Any updates on this?

**Comment by public-rant** [comment]
Negative @kbdharun
