### ISSUE TITLE
Cross reference all pages related to `vim`

### ISSUE THREAD

**Issue by richardsavio** [tldr-pages/tldr#9472]
Currently all the `vim` related pages (`vim`, `vimdiff`, `nvim`, `vimtutor`) do not cross reference each other. The pages could be updated to rectify that.

I did not realize that there was a `vimdiff` page until recently. I expected to find something (at least a link to `vimdiff`) on the main `vim` page.

**Comment by CleanMachine1** [comment]
Would you like to add this your self in a PR?
