### ISSUE TITLE
chrome extension

### ISSUE THREAD

**Issue by sdvdxl** [tldr-pages/tldr#948]
It's useful,and would you like to develop a chrome extension?

**Comment by ostera** [comment]
I'd be up for that.

Some options in my head right now are:

0. clickable on-hover tooltip with definition, linking to command in the web client.
1. `Right Click -> tldr`, opens selection in the web client

We'd want something unobtrusive, either lightweight or aggressively cached.

**Comment by waldyrious** [comment]
I think the tooltip provides nicer UX, but I wonder if it would require too much processing to scour every page for potential command names (and what about false positives?), so perhaps the select > right click could work better.

**Comment by rubenvereecken** [comment]
Ah man the tooltip would be awesome. A first version could err on the side of caution and only really selectively search inside `pre`s and `code` tags and the like, that should immediately cover all of StackOverflow.

Then the right click covers all the other cases and could even send us the data (would love to set up a little server for this) so we can derive rulesets from these.

I've played with similar crowd-sourced ideas when working on the clickbait detector (though it never reached completion).

**Comment by ostera** [comment]
Seems like I have a weekend project then :)

**Comment by rubenvereecken** [comment]
That `decision` label is so ominous.

**Comment by waldyrious** [comment]
> That decision label is so ominous.

Thought so too xD I normally reserve that to when there's some contention that needs consensus to be reached.

**Comment by ostera** [comment]
Haha sorry, feel free to take it out :P

**Comment by agnivade** [comment]
I really love the idea of gathering data for the commands searched. That way, we can focus more on improving the most frequently searched pages.

**Comment by ostera** [comment]
I might have something...

<img width="881" alt="screen shot 2016-07-14 at 12 16 09 pm" src="https://cloud.githubusercontent.com/assets/854222/16836247/e88e2de0-49bc-11e6-966f-2b37832e134f.png">

**Comment by waldyrious** [comment]
I look up `ln` religiously almost every time I use that command 😅

**Comment by waldyrious** [comment]
I think @agnivade was referring to commands that people are searching for but not finding, though.

**Comment by ostera** [comment]
Ah! Well, rather than tracking pages, I could hookup Mixpanel to gather the data nicely.

Then a small bot could poll the data and create issues if a not-found page has been searched more than N times.

**Comment by rubenvereecken** [comment]
I offered collecting data mostly so we could improve the detection of a command by the plugin, but sure we can go around collecting popular 404s :)

**Comment by agnivade** [comment]
Ah no .. I wanted exactly what @ostera shown. :smile:  But tracking not-found pages is a great idea too !

**Comment by hill** [comment]
Hey there, is anyone working on this, and if not, would you like me to have a go???

(this is such a cool project by the way!!)

**Comment by hill** [comment]
Thinking something like this for selection tooltip:

![mockup-dark](https://user-images.githubusercontent.com/5620045/34076496-b188d274-e31b-11e7-9eee-b3f459adedfd.png)

**Comment by agnivade** [comment]
AFAIK, nobody is working on it. So you are most welcome to have a go :smile:

**Comment by hill** [comment]
Hey - just letting you that I have something working here: [https://github.com/hill/tldr-chrome](https://github.com/hill/tldr-chrome) that works on right-click select to open a tooltip ... still needs a bit of work though haha

**Comment by agnivade** [comment]
Great stuff. I see that you are using `XMLHttpRequest`. Any specific reason for not using `fetch()` ?

**Comment by hill** [comment]
Didn't even know fetch existed until right now. Will certainly look into replacing my current implementation! Thanks @agnivade 😁

**Comment by sbrl** [comment]
What's `fetch()`, @agnivade? Haven't heard of that before, and devdocs.io doesn't appear to have it listed.

**Comment by agnivade** [comment]
It is essentially a big improvement over `XMLHttpRequest`. Any modern codebase should use `fetch` instead of `XMLHttpRequest`. 
MDN - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
Here it is in devdocs - http://devdocs.io/dom/fetch_api/using_fetch

**Comment by sbrl** [comment]
My.... wow. That's really powerful! Gone are the days of using a `Promise` wrapper for `XMLHttpRequest`....! I must have been looking under the wrong section of devdocs then.
