### ISSUE TITLE
page request: mogrify

### ISSUE THREAD

**Issue by MarAvFe** [tldr-pages/tldr#9531]
### Command description

[mogrify](https://manned.org/mogrify) is an awesome image manipulator cli software:

> mogrify - resize an image, blur, crop, despeckle, dither, draw on, flip, join, re-sample, and much more. Mogrify overwrites the original image file, whereas, [convert](https://manned.org/convert) writes to a different image file.

### Command details

executable in /usr/bin

### OS

- [ ] Android
- [X] Linux
- [ ] macOS
- [ ] sunOS
- [ ] Windows

**Comment by ohyahgit** [comment]
Has this already been completed?

**Comment by jxu** [comment]
Mogrify is part of ImageMagick btw.

**Comment by pixelcmtd** [comment]
https://github.com/tldr-pages/tldr/blob/main/pages/common/mogrify.md
