### ISSUE TITLE
add perl command

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#955]

**Comment by ostera** [comment]
Thanks for reporting! Feel free to start a PR to add this page -- take a look at CONTRIBUTING.md for some guidelines :)

**Comment by waldyrious** [comment]
Unfortunately I don't have experience with the command - I only came across it in the context of a sed Alternative that can handle newlines in the search pattern. I could start the page with just that example, but in not sure that's much better than nothing. What do you think?

**Comment by ostera** [comment]
Oh I was just making a joke, I even copied one of your replies from another issue 😝

**Comment by waldyrious** [comment]
Hahaha i did think you said that tongue in cheek, but didn't recognize my own words xD

**Comment by assemusr** [comment]
Working on this..
