### ISSUE TITLE
Rendered emails become URL-encoded

### ISSUE THREAD

**Issue by Bauke** [tldr-pages/tldr#9560]
For example, with `tldr gpg`:

```
  - Export public key for mailto:&#97;&#108;&#x69;&#99;&#x65;&#x40;&#101;&#120;&#x61;&#x6d;&#x70;&#108;&#101;&#x2e;&#x63;&#111;&#109; (output to stdout):
    gpg --export --armor alice@example.com
```

**Comment by Bauke** [comment]
Oh I just realized this may not be the correct repo for this issue. I'm using the Node client.

**Comment by EmilySeville7cfg** [comment]
@Bauke, so I am closing this issue. Please provide a link to an issue in the correct repo. Thanks!
