### ISSUE TITLE
Automatically warn contributors via CI in PRs when possibly broken generic placeholders were detected

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [tldr-pages/tldr#9580]
The following possibly broken placeholder's patterns should be considered:

- `{{file}}`, `{{file_*name}}`, `{{directory}}`, `{{directory_*name}}` - invalid path format, correct: `{{path/to/file}}`, `{{path/to/directory}}`. Description: one path format should be used.
- `{{content_+1}}` - invalid placeholder number format, correct: `{{content1}}`. Description: one numbering format should be used.
- `{{content0}}` - invalid first index: correct `{{correct1}}`. Description: one numbering format should be used.
- `{{content1}} +{{content2}}` - possibly invalid placeholder sequence, possibly correct: `{{content1 content2 ...}}`. Description: one placeholder repetition format should be used.
- `{{content1}} {{content2}} {{...}}` - possibly invalid placeholder sequence, possibly correct: `{{content1 content2 ...}}`. Description: one placeholder repetition format should be used.
- `{{content{1,2}}}` - possibly invalid placeholder sequence, possibly correct: `{{content1 content2 ...}}`. Description: one placeholder repetition format should be used.

PR merge will **not** be blocked by such warnings as false positives can occur.

Such warning's ideas are based on [my script](https://github.com/tldr-pages/tldr/issues/9579) working results. I'll try replace some parts of my reviews via scripts.

**Comment by gutjuri** [comment]
As you correctly state that the placeholder patterns you mentioned are not necessarily indicators of malformatting, we should at most provide a warning in such cases, not an error.

**Comment by gutjuri** [comment]
Okay, in this case I'd close this issue.
