### ISSUE TITLE
How to display in different languages ​​on the command line？

### ISSUE THREAD

**Issue by Buliet** [tldr-pages/tldr#9588]
I tried as follows but it didn't work
<img width="727" alt="image" src="https://user-images.githubusercontent.com/32899664/205477204-d9a78394-0672-4ec7-8ad3-28f1a44e6bdd.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/32899664/205477207-a7370d5e-4297-4dd5-8795-f689847192f5.png">

**Comment by EmilySeville7cfg** [comment]
Which client do u use? Official Python client supports `-L` option.

**Comment by Buliet** [comment]
Thank you so much.
`pip3 install tldr` 
ps: don't forget to add it to your PATH

you can also choose
`npm install tldr`
