### ISSUE TITLE
Use mnemonics for all options 

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#9598]
There is no written rule restricting them to short options only. So maintainers can't mandate follow their preferences in this way. And I guess I was wrong while suggesting optional fixes to remove mnemonics for long options. 

I am going to create such rule to explicitly permit mnemonics for everything later.

My idea is to permit mnemonics for everything until mnemonic name is the same as full option name.

[This](https://github.com/tldr-pages/tldr/pull/9594#discussion_r1040544510) PR was triggered this issue creation.

**Comment by jxu** [comment]
Is mnemonics things like writing `e[x]tract` to indicate `-x` is the short option?

**Comment by EmilySeville7cfg** [comment]
Yes, you are right, in this particular case.
