### ISSUE TITLE
Announcing intent: Creating Fediverse/Mastodon account

### ISSUE THREAD

**Issue by sbrl** [tldr-pages/tldr#9705]
It's been floated before (though I'm unsure where), but I'm making an issue to centralise the discussion on creating a Fediverse/Mastodon account on fosstodon.social.

I'm happy to create the account, but I notice in the rules for accounts on fosstodon.social the following item:

> 6. Do not use automated tools to toot without participating in the community. It is fine to post with an automated tool so long as you are an active member of the Fosstodon community and respond to replies you receive here. Unmonitored accounts that post automatically are not acceptable.

...so we'd need to ensure the account is monitored by at least 1 person.

I suggest the following account name:

```
@tldr_pages@fosstodon.social
```

...as our Twitter account's name  is `@tldr_pages`.

**Comment by kbdharun** [comment]
As I told before in Gitter, I agree with this change. It will be nice if we have an account on Mastodon/Fediverse.

**Comment by sbrl** [comment]
Now that I've given this some time for people to comment, I have officially requested the account `@tldr_pages@fosstodon.org`.

Once the application is approved, I'll set the account up with automated posting of tweets, and also add a reference to it on our main Twitter account.

**Comment by EmilySeville7cfg** [comment]
Congratulations. 🚀

**Comment by sbrl** [comment]
We now have a Fediverse / Mastodon account!

https://fosstodon.org/@tldr_pages

Posts from twitter are automatically reposted to this Mastodon account via https://moa.party/ , but not the other way around (though this is an easy setting to change).

If any maintainers wish to have the credentials for this account, please get in touch and I'll share.

If any maintainers have accounts on the fediverse, please message @tldr_pages@fosstodon.org and I'll follow you back on this new account.

**Comment by sbrl** [comment]
account created!

Find it here: https://fosstodon.org/@tldr_pages

If any maintainer wants access to the account, just let me know and I'll share the credentials via secure means.
