### ISSUE TITLE
add heroku command

### ISSUE THREAD

**Issue by rafaelcastrocouto** [tldr-pages/tldr#972]
https://devcenter.heroku.com/categories/command-line

**Comment by ostera** [comment]
Thanks for reporting! Feel free to [send a PR](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to propose this page — if in doubt, take a look at [CONTRIBUTING.md]
(https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) for some guidalines, and let us know if you need any help :)

**Comment by yasharmaster** [comment]
Hey I would like to add heroku commands if no one else id working on it.

**Comment by agnivade** [comment]
Absolutely, please go ahead and send a PR !

**Comment by yasharmaster** [comment]
should I create another directory named "heroku" in the pages directory and put man pages in there?

**Comment by agnivade** [comment]
No need to create a directory. Create a page for `heroku` in the `common` directory under `pages`. Take a look at [CONTRUBUTING.md](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) to guide you in the process.

**Comment by yasharmaster** [comment]
@agnivade I have just submitted a PR #1111. Please review it.

**Comment by yasharmaster** [comment]
@agnivade Just sent a PR. Please review it #1112

**Comment by mflint** [comment]
PR #1112 was merged - can we close this issue?

**Comment by agnivade** [comment]
Yep ! Maybe the auto-close text wasn't correct somehow.

**Comment by rafaelcastrocouto** [comment]
Thanks a lot everybody!
