### ISSUE TITLE
add `fc-list` for  font list search

### ISSUE THREAD

**Issue by leoluyi** [tldr-pages/tldr#978]
`fc-list | grep {{font_name}} `

**Comment by ostera** [comment]
Thanks for reporting! Feel free to [send a PR](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#submitting-a-pull-request) to propose this page — if in doubt, take a look at [CONTRIBUTING.md]
(https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md) for some guidalines, and let us know if you need any help :)

**Comment by mkoppmann** [comment]
I think we can close this issue.

**Comment by waldyrious** [comment]
indeed @mkoppmann 👍
