### ISSUE TITLE
Replace ".md" with ".tldr" extension

### ISSUE THREAD

**Issue by EmilySeville7cfg** [tldr-pages/tldr#9788]
This allow me to write syntax highlighting and LSP specifically for TlDr pages and not to confuse those with Markdown files. We are not using Markdown, we using a Markdown based language for describing pages.

**Comment by CleanMachine1** [comment]
This will break almost every client.

**Comment by EmilySeville7cfg** [comment]
Yes, it will. But we can make an announcement that we are going to make this breaking change in some time and then update official clients. We can't control all clients anyway but we can enhance our official ones.

**Comment by CleanMachine1** [comment]
Think of all the future issue reports, even from people that have installed the python client for example, since pip packages aren't as regularly updated and also the client which is in the Debian repos would break and it is likely one of the most popular clients, and because of it being Debian, it could take a couple of years to update to a version that works.

I just can't see any good pros.

Why not work around the problem by only highlighting pages which are in a pages/ directory.

**Comment by EmilySeville7cfg** [comment]
> Why not work around the problem by only highlighting pages which are in a pages/ directory.

So u suggest that highlighter should just recognize `pages/*` pages? Am I correctly understood u? I think it's not a solution as highlighter should not depend on specific directory, as user can write independent pages outside of this directory.

**Comment by CleanMachine1** [comment]
Regarding translations, you could just do pages*/*

Its a better quick fix compared to breaking probably about 50% of all users tldr client. I just don't see why we break so much for so little gain for syntax highlighting and scripting purposes.

**Comment by EmilySeville7cfg** [comment]
> Its a better quick fix compared to breaking probably about 50% of all users tldr client. I just don't see why we break so much for so little gain for syntax highlighting and scripting purposes.

Maybe it's better to continue developing my own TlDr replacement suitable for scripting proposes then. 🤔 Because maybe it's too late fix some basic things now.

**Comment by CleanMachine1** [comment]
Perhaps, IMO some of these ideas are not really possible without consequences to the user experience.

**Comment by SethFalco** [comment]
One potential solution for this worth exploring would be using the `.tldr.md` file extension instead. Would have to investigate how clients are handling this, but I suspect they're library to get the base name or just splitting by `.` anyway and getting the first index anyway, so might actually work with little impact to clients. :thinking: 

I think dropping `.md` might be a bit much, but changing the file extension isn't a bad call.
