### ISSUE TITLE
CLA Assistant doesn't register agreement correctly

### ISSUE THREAD

**Issue by blueglyph** [tldr-pages/tldr#9821]
As part of a pull request, I agreed to the CLA mentioned in the [contributing](https://github.com/tldr-pages/tldr/blob/main/CONTRIBUTING.md) page.

I did it first before opening the [pull request](https://github.com/tldr-pages/tldr/pull/9749). Then I saw that it was shown a blocking step:

![image](https://user-images.githubusercontent.com/31706195/216318089-7f5cf509-106c-48eb-8955-60497caa9a77.png)

So I signed ... again. Actually if some time has passed, I can sign it again, otherwise it says that I have agreed - sometimes the information is blank, sometimes not (see screenshots below).

But despite that, it's never taken into account by the flow, as you can see by following the link of the pull request.

![image](https://user-images.githubusercontent.com/31706195/216318465-8e00db6a-e28a-4839-be7d-e4399eb98af2.png)

![image](https://user-images.githubusercontent.com/31706195/216318538-350c56bc-0cb0-405c-ab02-d63fd2217d9a.png)

**Comment by kbdharun** [comment]
This issue is related to CLA assistant and not with tldr. I will transfer this issue over there.

**Comment by blueglyph** [comment]
@kbdharun Well, you are using this feature and I don't know how. But I'll make a post with a link here; if there are questions on how it's used, I won't be able to answer though.

**Comment by blueglyph** [comment]
https://github.com/cla-assistant/cla-assistant/issues/959

**Comment by blueglyph** [comment]
Can't be fixed.

**Comment by kbdharun** [comment]
An alternative for you would be to sign the commits using `--signoff` but it requires email too. If you are privacy conscious then you can set up a git email from privacy-respecting providers like Proton and configure CLA Assistant.

**Comment by blueglyph** [comment]
> An alternative for you would be to sign the commits using `--signoff` but it requires email too. If you are privacy conscious then you can set up a git email from privacy-respecting providers like Proton and configure CLA Assistant.

I simply changed my git config to set a real email, though I won't be reading it.

Protonmail will not help regarding privacy in that regard, an email address is an identifier and a potential spam target, no matter where it's hosted. I know that they offer a way to add suffixes to email addresses but it's not robust against that. What is good regarding privacy with them is how their server respect the users' privacy, but that's not what I meant here.
