### ISSUE TITLE
add unar command

### ISSUE THREAD

**Issue by ivo-wang** [tldr-pages/tldr#997]
unar command

**Comment by yasharmaster** [comment]
@waldyrious This page already seems to be there.
https://github.com/tldr-pages/tldr/blob/master/pages/common/unrar.md

**Comment by agnivade** [comment]
That is `unrar`, this issue is about `unar` (unarchiver). :)

**Comment by yasharmaster** [comment]
ohh my bad

**Comment by assemusr** [comment]
Working on this..
